/* eslint-disable sonarjs/no-duplicated-branches */
import endsWith from 'lodash/endsWith';
import includes from 'lodash/includes';
import some from 'lodash/some';
import startsWith from 'lodash/startsWith';

const BLACKLISTED_TAGS = [
  '<3',
  '00s',
  "00's",
  '10 out of 10',
  '100 gecs',
  '1001 albums you must hear before you die',
  '10cc',
  '10s',
  '13 reasons why',
  '1950s',
  '1960s',
  '1970s',
  '1980s',
  '1990s',
  '19th century',
  '2 s34rch',
  '200 great albums owned by sideflower',
  "2000's",
  '2000s',
  '2010s',
  '2017 listen',
  '2020s',
  '20s',
  '20th c',
  '20th century',
  '21st century',
  '2cd',
  '2dl',
  '2edgy4me',
  '2pac',
  '3-5',
  '30 seconds to mars',
  '4',
  '4 star',
  '4-25',
  '4-5',
  '40s',
  '4ad',
  '4chan',
  '4nas',
  '50 cent',
  '50s',
  '60s',
  '70s',
  '718 metal',
  '8 kbps',
  '8 soothing songs for rut',
  "80's",
  '80s',
  "90's",
  '90s',
  'a',
  'a cappella',
  'a distant fire burning',
  'a mental attack',
  'a8',
  'a9',
  'abba',
  'abc',
  'abstract',
  'abstract electronica',
  'accordeon',
  'acerbic',
  'achingly intelligent',
  'acid',
  'acoustic groove',
  'acquire',
  'addictive',
  'adele',
  'adolf hitler',
  'adrien wayne',
  'adsfghjklmn',
  'adult alternative',
  'aerosmith',
  'after hours',
  'ageofaquarius63',
  'agitada',
  'aggressive',
  'aggroschlager',
  'aids',
  'air',
  'air supply',
  'airplane',
  'akb48',
  'akiko shikata',
  'akiko shikata is ugly',
  'akiko shikata sucks',
  'akrazia',
  'al-hizan',
  'alben',
  'album',
  'album collection',
  'album fav',
  'albums',
  'albumsiown',
  'aleister',
  'aleister crowley',
  'aleyster',
  'aleyster crowley',
  'aleyster crowley bernardo de andrade',
  'aleystercrowley',
  'aleystercrowleype',
  'alien',
  'all',
  'all aboard the failboat',
  'all things annoying in the world put together into one stupid bitch',
  'all time fav',
  'all-time favorite',
  'all-time-favorite',
  'allboutguitar karlsruhe',
  'allbout guitar lessons karlsruhe',
  'allboutguitar',
  'allboutguitar lesson',
  'allboutguitar lessons - blues workshops',
  'allboutguitarcom',
  'allison mack',
  'allmusicm',
  'alt',
  'alt rock',
  'alt-rock',
  'alt-cr',
  'alt-folk',
  'alter',
  'alternative',
  'alternative lounge',
  'alternative media',
  'amatue',
  'amazing',
  'ambiance',
  'ambient dildocore',
  'ambient drone',
  'ambient piano',
  'ambitious',
  'american dream',
  'american life',
  'amidio junior',
  'amn 2006',
  'amo',
  'analog',
  'analogue',
  'anarchy',
  'anatomy',
  'anches',
  'and',
  'andrew',
  'andy',
  'angelina jolie',
  'angelina valentine',
  'angry',
  'angst-ridden',
  'angstwave',
  'animal cruelty',
  'anime',
  'anison',
  'anita blond',
  'anita dark',
  'anjunabeats',
  'anjunadeep',
  'annoying',
  'annymix',
  'ant-zen',
  'anti-semitic',
  'anticon',
  'antifa',
  'antonin dvorak',
  'antonio vivaldi',
  'anxious',
  'anyzio rocha',
  'aor',
  'aoty',
  'ap',
  'aphex twin',
  'apocalyptic',
  'approved',
  'approximately 1000 times less pleasant than extreme anal caving',
  'april',
  'arcane',
  'ariana grande',
  'arion-music',
  'armoured skeptic',
  'art',
  'arturo toscanini',
  'aryan',
  'as awesome has having testicles in your face when you wake up',
  'asap rocky',
  'asot',
  'asscore',
  'at work',
  'atb',
  'atmosphere',
  'atmospheric',
  'atrocious',
  'attention whore',
  'august',
  'aural vomit',
  'austrian kabarett',
  'auteur-compositeur-interprete',
  'autism',
  'auto-tagged',
  'autumn',
  'autumnal',
  'av',
  'ava addams',
  'availableonemusic',
  'avant',
  'avant garde',
  'avant-garde',
  'avant-jazz',
  'avantgarde',
  'avril lavigne',
  'awesome',
  'awesomeness',
  'awful',
  'b powell',
  'b-sides',
  'babe',
  'babybabybaby',
  'babyfacepatsy',
  'bach',
  'backstreets',
  'bacteria',
  'bad',
  'bad music',
  'bad taste',
  'badass',
  'balada',
  'ballads',
  'bananas',
  'band',
  'banda metamorphosis',
  'bandcamp',
  'barneycore',
  'baroque or early',
  'bartok',
  'barturismooth',
  'based',
  'basically bass',
  'bat for lashes',
  'batcave',
  'batman',
  'bats',
  'bbc new generation',
  'bbk',
  'bdsm',
  'beach',
  'bearl3a1e5da4n15l1',
  'beatdown',
  'beatles',
  'beatles cover',
  'beatles covers',
  'beatport',
  'beats',
  'beats for days',
  'beautiful',
  'beautiful album covers',
  'beautiful killing machine',
  'beauty',
  'beck',
  'beef',
  'beer',
  'belgian',
  'bella topolina',
  'bella union',
  'beneficial',
  'berliner',
  'bernardo montador de moveis em recife',
  'bernstein',
  'beshine',
  'best',
  'best album',
  'best album ever',
  'best albums ever',
  'beto juara',
  'better die than listen to this',
  'better on vinyl',
  'better than radiohead',
  'beyondwithin',
  'beyonce',
  'big sean',
  'bilititas',
  'bill clinton',
  'bill evans',
  'billie eilish',
  'billie holiday',
  'biology',
  'bittersweet',
  'bizarre',
  'bjork',
  'black',
  'black doom',
  'black sabbath',
  'black veil brides',
  'blackpink',
  'blandband',
  'bleak',
  'blogs',
  'blondie',
  'blue',
  'blue note',
  'blue october',
  'blues bar',
  'blues rock club radio karlsruhe',
  'blues rock radio deutschland',
  'blues rock radio germany',
  'blues rock radio germany deutschland',
  'blues und rockclub karlsruhe',
  'blues-rockclub',
  'bluezzz',
  'bluk glub',
  'bmtribute',
  'boards of canada',
  'boastful',
  'bob dylan',
  'bob marley',
  'bois',
  'boisterous',
  'bollocks',
  'bolsonaro',
  'bom sambinha',
  'bon jovi',
  'boner rock',
  'boogie on down',
  'boomkat',
  'bootleg',
  'bop',
  'bore',
  'boring',
  'bossa',
  'bossy cow',
  'bots',
  'bought',
  'boughtlast3years',
  'bovine',
  'bowie',
  'boy with luv',
  'brahms',
  'brap',
  'brash',
  'brasil',
  'brasil es robertitus',
  'bravado',
  'brayden',
  'brc blues band',
  'breakingbluesnews',
  'breakup',
  'breasts',
  'bresil',
  'brian eno',
  'briana banks',
  'bridge nine',
  'bright',
  'brilliant',
  'brilliant record',
  'brisk sound',
  'britney spears',
  'britrock',
  'britten',
  'brooding',
  'brooklyn decker',
  'brown music for pink people',
  'bruce springsteen',
  'bruno',
  'brutal',
  'brutal death',
  'brutal electronic deathmosh',
  'brutal fagcore',
  'brutal nazi scumcore with fascist influence and guest vocalist adolf hitler',
  'brutal power metal',
  'bts',
  'bubblegum',
  'bums bums',
  'burger',
  'buryblue',
  'buy',
  'c mingus',
  'c parker',
  'cafe',
  'cafe del mar',
  'cafe del mar music',
  'california coast',
  'california dreaming',
  'california local',
  'california rock clube',
  'california seixas',
  'california sunshine',
  'california usa',
  'calm',
  'calming',
  'cameron diaz',
  'camisa de venus',
  'can',
  'canadian',
  'cant sing',
  'carefree',
  'carpet crawler',
  'carson lueders',
  'cartoon',
  'cartoons',
  'cash',
  'cassette',
  'cat',
  'catchy',
  'cathartic',
  'cc',
  'cd',
  'cd-sammlung',
  'cds',
  'cdsiwanttoown',
  'celebratory',
  'cello',
  'cerebral',
  'ch3ck 74',
  'chainsaw',
  'chameleon',
  'channel13',
  'chanson française',
  'chaos',
  'chaotic',
  'charles mingus',
  'chasey lain',
  'check',
  'check later',
  'check out - friends',
  'check out',
  'check the wordplay',
  'check this out',
  'checkout',
  'cheerful',
  'cheese',
  'cheesy',
  'chick corea',
  'child abuse',
  'child molester',
  'childhood',
  'children',
  'childrens',
  'chill',
  'chill chill',
  'chillair',
  'chilled',
  'chillosophy',
  'chillounge1',
  'chilllounge1',
  'chopin',
  'chosen',
  'chris brown',
  'christina aguilera',
  'christmas',
  'christopher lee',
  'chromatica',
  'cinema',
  'cinematic',
  'city lounge',
  'civil war',
  'clanddi jinkcego',
  'clara morgane',
  'clasica',
  'clasicram',
  'class struggle',
  'classic',
  'classic best of',
  'classic horror',
  'classic synthpop',
  'classica',
  'classiclelet',
  'classicpurp1e',
  'classics',
  'classique',
  'claude debussy',
  'claudia schiffer',
  'clinically romantic',
  'close harmony',
  'club',
  'cocaine',
  'cold',
  'cold meat industry',
  'coldplay',
  'coleman hawkins',
  'collaboration',
  'collected',
  'collection',
  'colors',
  'colossal faggot',
  'colours',
  'colt ford',
  'coltrane',
  'columbia',
  'comedy central',
  'comfort',
  'coming summer melancholy',
  'compilation',
  'compilations',
  'complex',
  'con artist',
  'concept',
  'conceptual',
  'concerto',
  'confident',
  'confrontational',
  'conny plank',
  'conscious',
  'conservative',
  'conspiracy',
  'contempor',
  'contemporary',
  'contemporary praise and worship',
  'cool',
  'cool score',
  'coolest album art',
  'coolwench',
  'coprogrind',
  'coprophagia',
  'copyleft',
  'core',
  'cosmic',
  'cover',
  'covers',
  'cowhat superalbums',
  'cracked',
  'crap',
  'crappy',
  'crappy english versions of german stuff',
  'crates of vinyl',
  'crazy',
  'cream of the crop',
  'creamed my pants',
  'creative',
  'creative commons',
  'creed',
  'creed taylor',
  'creepy',
  'crime',
  'crimes against humanity',
  'cronowish power',
  'crossover',
  'cuivre',
  'cult',
  'cultura',
  'cuneiform',
  'cunning',
  'curso de armonica',
  'cute',
  'cybertrash',
  'czalbums',
  'daddy',
  'daft punk',
  'dake',
  'dake-bonoism',
  'daniel',
  'danzig',
  'daphne rosen',
  'dark',
  'dark age',
  'dark dark',
  'dark sky',
  'darklight',
  'darkness',
  'dave',
  'dave brubeck',
  'david',
  'david bowie',
  'david orton',
  'day',
  'day driving',
  'daya',
  'days',
  'de',
  'de todo mio favoritos',
  'dead',
  'dead kennedys',
  'dead rockstars',
  'death',
  'death cab for cutie',
  'death row',
  'debbie harry',
  'debut',
  'decades',
  'december',
  'decent',
  'deek',
  'deekles',
  'deep',
  'deep purple',
  'definition of fantabulous',
  'delicate',
  'demi lovato',
  'demo',
  'demos',
  'denon essentials',
  'dense',
  'depeche mode',
  'depressing',
  'depression',
  'depressive',
  'der moment',
  'der ring des nibelungen',
  'deranged 9 year old bedroom pop',
  'derivative',
  'desert island discs',
  'desiigner',
  'desperate',
  'destaque',
  'det snurrar i min skalle',
  'detached',
  'deutsch',
  'deutscher schlager',
  'deviliscious432',
  'dgillespie',
  'diarrhea',
  'dicky',
  'die kranken schwestern',
  'different',
  'digital',
  'dildocore',
  'dirty',
  'disaster',
  'dischord',
  'discover',
  'discoverockult',
  'disease',
  'disgrace to society',
  'disney',
  'diva',
  'dj mix',
  'django reinhardt',
  'django sphere',
  'dk',
  'dkdkdk',
  'dnb',
  'do nagrania',
  'doc watson and co',
  'doctor who',
  'domenico scarlatti',
  'domino',
  'don kalifa',
  'donald trump',
  'done',
  'donkalifa',
  'donna',
  'donne',
  'dont have',
  'doom',
  'dope',
  'dope shit ouwe',
  'doucefrance',
  'douchebag',
  'download',
  'downloadable',
  'downloadable tracks',
  'dr gay and his gang of faggots',
  'dr small jukebox',
  'draghixa',
  'drake',
  'dramatic',
  'dream',
  'dream theater',
  'dreamy',
  'drill',
  'drinking',
  'driving',
  'drone doom',
  'drone doom metal',
  'druggy',
  'drugs',
  'drum & bass',
  'drum n bass',
  "drum'n'bass",
  'drums',
  'drunk tank singalong tune',
  'dub-u',
  'dubtech',
  'duets',
  'duke dumont',
  'duke ellington',
  'dukedukeduke',
  'dull',
  'dulukk',
  'dulukkcore',
  'dumb',
  'dustin lynch',
  'dusty',
  'duyster',
  'dylan',
  'dynamic',
  'e fitzgerald',
  'eargasm',
  'early music performer',
  'earnest',
  'earth',
  'earthy',
  'easter',
  'easy',
  'eccentric',
  'eclectic',
  'ecm',
  'ecm globalmusic',
  'ecstasy',
  'ed sheeran',
  'edgy',
  'educate yourself',
  'edvard grieg',
  'eerie',
  'ego',
  'eighties',
  'electric',
  'electro rock',
  'electro-rock',
  'electrocool',
  'electronic breakbeat',
  'electronic music',
  'electronic superhighway',
  'electronic-lounge',
  'electropcool',
  'electropearls',
  'elegant',
  'elektro',
  'elektro target',
  'elektronic beats',
  'eletronic',
  'elettronica',
  'ella fitzgerald',
  'elton john',
  'elvis',
  'elvis presley',
  'emi',
  'eminem',
  'emoe',
  'emogaycore',
  'emotional',
  'empowerment',
  'emusic',
  'emusic download',
  'en',
  'encontro dos famosos',
  'endless listening',
  'energetic',
  'energy',
  'enigma',
  'enigmatic',
  'enjoy your stay isaac',
  'eno',
  'enoque gomes',
  'enya',
  'ep',
  'epic',
  'epic album covers',
  'epic bitch',
  'epic fail',
  'epic lounge',
  'epitaph',
  'eponymous',
  'epstein',
  'eric clapton',
  'ernandes dantas',
  'erotic',
  'esc',
  'esoteric',
  'espagne',
  'essential',
  'ethnic fusion robertitus',
  'eva karera',
  'evanescence',
  'eventos',
  'everything',
  'everytime you listen to this crap a truck hits a granny',
  'evil',
  'evil dnb',
  'evocative',
  'exciting',
  'exclamations',
  'exfandessixties',
  'exodus',
  'exotic',
  'experimental',
  'experimental jazz',
  'experimentalism',
  'exploitation',
  'extended play',
  'extreme',
  'extreme goregrind',
  'exuberant',
  'f schubert',
  'f singer-songwriter',
  'f-w-f-label',
  'fabrykamagazine',
  'faggot',
  'failure',
  'fajne motywy',
  'familia',
  'familia santos',
  'family',
  'fancy album covers',
  'fantastic',
  'fantasy',
  'fap',
  'fascinating',
  'fashioncore',
  'fast',
  'fat',
  'fat mike',
  'fat wreck chords',
  'fats domino',
  'fav',
  'fav album',
  'faves',
  'faves of the year',
  'favo',
  'favorit',
  'favs',
  'favs - eng',
  'favs of nocci',
  'fear of music',
  'february',
  'fecal',
  'fecalgrind',
  'feel good',
  'feelgood',
  'feeling',
  'feeling blue',
  'fellating the bottom of a bottle of wine',
  'female',
  'female artists',
  'female fronted',
  'female singer',
  'female singers',
  'female vocal',
  'female vocalist',
  'female vocals',
  'female voice',
  'female voices',
  'femmina',
  'femmine',
  'ferri',
  'fettttttttttttttt',
  'fierce',
  'film',
  'filter',
  'filtered',
  'fiendgood blends club',
  'fiery',
  'film score',
  'filmes',
  'finely tailored',
  'finished',
  'fip',
  'fire',
  'first',
  'fisco',
  'fish',
  'flac',
  'flakes',
  'flap',
  'flashback alternatives',
  'flat-out amazing records that everyone should have in their cd collection',
  'flatulence',
  'flawless',
  'fleetwood mac',
  'flop',
  'florida georgia line',
  'flowmotion',
  'fluffy',
  'folklore',
  'folklore intellectuel',
  'follow me',
  'foo fighters',
  'forro',
  'fortuneseed',
  'four',
  'fox',
  'frank ocean',
  'frank sinatra',
  'franz joseph haydn',
  'franz liszt',
  'franz schubert',
  'freak out',
  'frederic chopin',
  'free',
  'freedom',
  'freeformfreakout',
  'freepurp1e',
  'freewheeling',
  'fresh',
  'friday',
  'fuck',
  'fugly',
  'full',
  'full tracks',
  'fully streamable album',
  'fully streamable track',
  'fully streamable tracks',
  'fun',
  'fun to skateboard to',
  'funky',
  'funny',
  'future',
  'future jazz',
  'futuristic',
  'fuzz',
  'g mulligan',
  'gaga',
  'game',
  'gammarec',
  'gangsta',
  'garage hop',
  'garbage',
  'garten punk',
  'gary glitter',
  'gay',
  'gay black metal',
  'gay metal',
  'gay nigger black metal',
  'gaycore',
  'gaygrind',
  'gen z',
  'generic',
  'genesis',
  'genius',
  'genre',
  'gentle',
  'georg friedrich handel',
  'german cars vs american homes',
  'german underground',
  'ghislaine maxwell',
  'ghostly international',
  'gioacchino rossini',
  'girl',
  'girl power',
  'girls',
  'girls girls girls',
  'girly',
  'gitarre karlsruhe',
  'gitarrenunterricht',
  'gitarrenunterricht karlsruhe',
  'glam',
  'glee',
  'glee cast',
  'glo-fi',
  'gloomy',
  'gloomy crust metal',
  'glorify my drug usage',
  'glorious vocals',
  'goatse',
  'god',
  'god tier',
  'god-like',
  'god-tier guitar',
  'godlike drumming',
  'gold',
  'golden age',
  'gomorrans',
  'good',
  'gorgeous',
  'gorillaz',
  'gossip',
  'got it on 8 track',
  'gotanygoodmusic',
  'goth',
  'goth music for pussies',
  'gothic',
  'gothic doom',
  'grade a',
  'grady',
  'grammy nominated',
  'gramusels bluesrock',
  'granka',
  'great',
  'great album',
  'great album artwork',
  'great album covers',
  'great compilation',
  'great cover art',
  'great groove',
  'great jazz',
  'great live band go see them',
  'great lyricists',
  'great name',
  'great voice',
  'greatest hits',
  'greatness',
  'greatrockers',
  'green',
  'green day',
  'grim',
  'grind',
  'gritty',
  'groove',
  'groovy',
  'grumpy still skin',
  'gucci mane',
  'guilty',
  'guilty pleasure',
  'guilty pleasures',
  'guitar',
  'guitar hero',
  'guitar karlsruhe',
  'guitars',
  'gusic',
  'gustav mahler',
  'gutsy',
  'guys night out',
  'gvbwv',
  'haendel',
  'hair chest',
  'hairy chest',
  'halftime',
  'halftoned singles club',
  'halle berry',
  'halloween',
  'halsey',
  'handel',
  'handleliste',
  'hands up',
  'hanging out',
  'hanzo main',
  'haohmaru',
  'happy',
  'happy music for happy people',
  'hard',
  'hardbopiano',
  'harmolodics',
  'harmonia mundi',
  'harmonies',
  'harmony',
  'harmony bliss',
  'harry styles',
  'haruka',
  'harsh',
  'has',
  'hate my nation',
  'haunting',
  'have',
  'have on vinyl',
  'haydn',
  'he',
  'headbangers ball',
  'healing',
  'heart',
  'heartache',
  'heavy',
  'heavy bottom end',
  'heavy psych',
  'heavy rock',
  'heavy rotation',
  'hed kandi',
  'hedonistic',
  'heil hitler',
  'hell',
  'hello project',
  'hells pit',
  'herbie hancock',
  'hick-hop',
  'high school',
  'higher octave',
  'hilarious',
  'hillary clinton',
  'hinder',
  'hino',
  'hiphopfrlab',
  'hipster',
  'hipster garabe',
  'hipster garbage',
  'hit',
  'hitler',
  'hitler was right',
  'hits',
  'hiv positive',
  'hoeralbum',
  'holiday',
  'hollow monkey',
  'home recording',
  'homeland',
  'homeless on the streets giving handjobs for crack',
  'homicide',
  'homocore',
  'homoerotic',
  'homoerotic wet dream nostalgia metal',
  'homophobia is so gay',
  'homosexual intifada',
  'horrible',
  'horror',
  'horstaxe',
  'hostile',
  'hot',
  'hotline miami',
  'hughes63',
  'humor',
  'humorous',
  'hunks',
  'hupin',
  'hypnotic',
  'icp',
  'ian watkins',
  'idiot',
  'idioten',
  'idiotic',
  'idk',
  'idols',
  'illegal',
  'illuminate',
  'imaginary girlfriend',
  'imagination',
  'impossible for liberals to deal with',
  'improv',
  'in love',
  'in my collection',
  'in queue no tracks',
  'in queue',
  'in the end',
  'in the red',
  'incel',
  'independent',
  'index',
  'indie',
  'indie stadium',
  'indietronic',
  'infernal',
  'inlove',
  'innocent',
  'insane',
  'insane clown posse',
  'insanity',
  'inspirational',
  'inspiring',
  'intelligent',
  'intense',
  'interesting',
  'interesting title',
  'international christmas',
  'internet',
  'intimate',
  'introspection',
  'introspective',
  'investigate',
  'irack',
  'iron maiden',
  'ironic',
  'irreverent',
  'isolationism',
  'it girl',
  'itunes',
  'itunes store',
  'its not indie assholes',
  'ive',
  'iveldie bar',
  'j smith',
  'j4zz13',
  'jaarlijstje 2007',
  'jack johnson',
  'jacob sartorius',
  'jair bolsonaro',
  'jamendo',
  'james bond',
  'james brown',
  'james call',
  'jamiroquai',
  'january',
  'jason aldean',
  'javajustice',
  'jay-z',
  'jayden',
  'jazz club verve',
  'jazz instrumental',
  'jazz vocal',
  'jazz-soul-funk',
  'jazz-trip',
  'jazzdrums',
  'jazzy',
  'jazzy female vocal',
  'jazzy trip',
  'je devrais avoir mon enfer de la caresse',
  'je dirai quelque jour vos naissances latentes',
  'jebemtimaterupichku-tojepank',
  'jebenica',
  'jecks',
  'jeff young',
  'jeffrey epstein',
  'jello biafra',
  'jenna jameson',
  'jerry goldsmith',
  'jesus',
  'jihad',
  'jimi hendrix',
  'jimmy savile',
  'jj',
  'jj lawhorn',
  'jlunare',
  'joe biden',
  'johann sebastian bach',
  'johannes brahms',
  'john coltrane',
  'john eliot gardiner',
  'john lennon',
  'john mayer',
  'john oliver',
  'john peel',
  'johnny cash',
  'johnny orlando',
  'jonas brothers',
  'jonasmusik',
  'jordi savall',
  'journey',
  'joy',
  'joy division',
  'joyous',
  'jpoptrasher',
  'js bach',
  'jubei yagyu',
  'juggalo',
  'july',
  'juma',
  'june',
  'just another folk singer',
  'justin',
  'justin bieber',
  'justin bieber my worlds',
  'justin timberlake',
  'k1r7m',
  'kacke',
  'kanye west',
  'kappe alb',
  'karajan',
  'karen lancaume',
  'kategorische elative',
  'katy perry',
  'kayden',
  'kayfovo',
  'keith jarrett',
  'kendrick lamar',
  'kept in freezer to be served as dinner',
  'khh',
  'kick ass track',
  'kid rock',
  'kids',
  'killforpeace',
  'kim kardashian',
  'kin',
  'kinder',
  'king',
  'kings',
  'kitsch',
  'kittycow',
  'kkk',
  'klassik',
  'kolob',
  'kompakt',
  'korean pop',
  'kraftwerk',
  'krica morena',
  'krica morena bela',
  'kricamorena',
  'kult',
  'kurt cobain',
  'kvelertak',
  'kvlt',
  'l beethoven',
  'l3a1e5da4n15l1',
  'la',
  'ladies',
  'lady gaga',
  'laetitia casta',
  'laid back',
  'laika',
  'lame',
  'lana del rey',
  'laptop',
  'lashgo98',
  'late night',
  'latin diva',
  'latin grammy nominated',
  'latin queen',
  'latino',
  'latino americain',
  'latinoamerica',
  'latinx',
  'lauraann163',
  'laure sainclair',
  'laurens fave',
  'lautfm bluesclub',
  'lautfm bluesclub koeln',
  'lautfmbluesclub',
  'lbm',
  'leadbelly and co',
  'led zeppelin',
  'leftfield',
  'legend',
  'legendary',
  'legendary night music for chads',
  'legends',
  'leonard cohen',
  'lesbian',
  'lethargic',
  'liblistened',
  'library',
  'liebe',
  'life',
  'light',
  'like',
  'lil nas x',
  'lil wayne',
  'lil xan',
  'limited edition',
  'linkin park',
  'lion',
  'lisa crawford',
  'lisa lipps',
  'list',
  'listen',
  'listen again',
  'listen carefully',
  'listen16',
  'liszt',
  'literate',
  'little st james',
  'little star',
  'live',
  'live punk',
  'lively',
  'lixo',
  'llll',
  'lmao',
  'lml',
  'lo-fi beat',
  'lol',
  'lolcow',
  'lolfest',
  'lolicore',
  'lonely',
  'longing',
  'look into',
  'lost',
  'lostprophets',
  'lou reed',
  'loud',
  'louis armstrong',
  'lounge chill',
  'lounge electronic',
  'lounge-tech',
  'love',
  'love at first listen',
  'love it',
  'love kasia',
  'love this albem',
  'loved',
  'loved album',
  'lovely',
  'low-fi',
  'lp',
  'lucy dacus',
  'ludwig van beethoven',
  'lugubrious',
  'luke bryan',
  'lush',
  'luvassa vaihtelevaa',
  'lvb piano sonatas',
  'lyrical',
  'lyrics',
  'm callas',
  'm davis',
  'm singer-songwriter',
  'ma pomme',
  'maarts',
  'madonna',
  'maga',
  'magic',
  'mainstream',
  'maison des cultures du monde',
  'make america great again',
  'male',
  'male vocal',
  'male vocalist',
  'male vocals',
  'mam',
  'mamao com acucar',
  'man in the pickle suit tricked me again',
  'mandatory',
  'manic',
  'manowar',
  'mantric acoustic',
  'marcelo nova e a envergadura moral',
  'march',
  'mariah carey',
  'marijuana',
  'marilyn manson',
  'maroon 5',
  'mars',
  'marshmello',
  'marvel',
  'maschi',
  'maschio',
  'massive attack',
  'master piano',
  'master saxo',
  'masterpiece',
  'masturbation fodder',
  'matador',
  'math',
  'mattyb',
  'matty braps',
  'mattybraps',
  'maverick',
  'maxi lista',
  'may',
  'me',
  'meat loaf',
  'melancholism',
  'media',
  'medieval',
  'mediocore',
  'mediocre',
  'meditative',
  'megadeth',
  'mein house',
  'mein virtuelles musikregal',
  'meine party',
  'meine privat-cd-sammlung',
  'melancholic',
  'melancholy',
  'mellow',
  'melodic',
  'melodic death',
  'melodic dildocore',
  'melodic noise',
  'meme',
  'memories',
  'menacing',
  'mendelssohn',
  'mendigao thrash',
  'merkliste',
  'mes chansons',
  'metal for teletubbies',
  'metal of god',
  'metallica',
  'metropolis',
  'miaou',
  'micha maat',
  'michael jackson',
  'micropenis',
  'midi',
  'mike patton',
  'miles davis',
  'milestones',
  'miley cyrus',
  'milla jovovich',
  'mine',
  'minhas musicas',
  'minimal',
  'minimalist',
  'minimalistic',
  'minutes',
  'misanthropic gay romance nostalgia metal',
  'misc',
  'miscellaneous',
  'misery',
  'mishap crew',
  'misogyny',
  'mistagged',
  'mitch mcconnell',
  'mittelalter',
  'mix',
  'mixed',
  'mixes',
  'mixtape',
  'mlx',
  'mmfwcl',
  'mmpps',
  'mmt rs 500',
  'moby',
  'mod',
  'modern',
  'modern classical',
  'modern composition',
  'modern country',
  'modernjazz',
  'modtoday',
  'modus',
  'moist butt kittens',
  'moisture',
  'mojo 1000',
  'mojo 1000 rock',
  'monakitty432',
  'monday',
  'mondiovision',
  'mongo',
  'monk',
  'montador de moveis em recife',
  'moody',
  'moog',
  'more gay than a san fransisco man in a hawaiian shirt sniffing some liquid gold and watching sex in the city',
  'morning',
  'moronic',
  'mosca navarro',
  'moses',
  'moskalyaku na gillyaku',
  'most amazing bands in the fucking world',
  'most loved',
  'motivation',
  'movie',
  'movie soundtracks',
  'movies',
  'mozart',
  'mp3',
  'mtv',
  'mtv trash',
  'muddy',
  'muka muka',
  'multiple copies',
  'murder',
  'muse',
  'music',
  'musica',
  'musicas no plural',
  'musicals',
  'musiikkia autiolle saarelle',
  'musik',
  'musik karlsruhe',
  'musique contemporaine',
  'musique de fou',
  'musique sacree',
  'must have',
  'my',
  'my-love',
  'mycds',
  'myfavo',
  'mylist',
  'mysterious',
  'mystic',
  'mystical',
  'nacional',
  'nadh',
  'nakoruru',
  'name',
  'names of people',
  'natasha khan',
  'national socialist black metal',
  'nature',
  'navidad',
  'naxos',
  'nazi',
  'nebenbei',
  'necropsy seal of brutality',
  'need to check out',
  'need to check this out',
  'negocios',
  'neil young',
  'nelson',
  'nemesea',
  'neoclassic',
  'netaudio',
  'netlabel',
  'netlabels',
  'neu',
  'new',
  'new age groovin',
  'new age rythm',
  'new milkmaid',
  'new music',
  'new new age',
  'new one',
  'new sound',
  'new to listen',
  'new wave of british heavy metal',
  'new world fair',
  'news',
  'nice',
  'nice album art',
  'nicenoise',
  'nichopoulooza',
  'nickelback',
  'nickelodeon',
  'nicki minaj',
  'nicolas gombert',
  'night',
  'nightwish',
  'nigga',
  'niggacore',
  'nihilistic',
  'nine inch nails',
  'ninja tune',
  'nintendo',
  'nirvana',
  'no',
  'no cure',
  'no cure band',
  'no cure1',
  'no gum on monday',
  'no pubic hair',
  'no talent',
  'no thanks',
  'nocturnal',
  'noir',
  'noisy',
  'noize',
  'non-music',
  'nordisk',
  'norleans',
  'normani',
  'northwest',
  'nostalgia',
  'nostalgic',
  'not',
  'not art',
  'not available on last-fm radio yet',
  'not experimental',
  'not on my computer anymore',
  'not sexy',
  'nouvelle scène française',
  'nova california seixas',
  'november',
  'now',
  'now available on last-fm radio 07q3',
  'nox-aeternus',
  'nu-bluz funky grooves in the e-lounge',
  'nuggets',
  'nul',
  'numbers',
  'numckeith',
  'nur mit dir',
  'nxivm',
  'ny',
  'nyc',
  'o peregrino da musica',
  'oasis',
  'objectum-sexualis',
  'obscure',
  'occhi a cuoricino',
  'occult',
  'october',
  'of',
  'officially retarded',
  'offspring',
  'oh so naughty',
  'old school',
  'olivia del rio',
  'ollas leiwaund',
  'oma',
  'ominous',
  'omni new age',
  'on cd',
  'on repeat',
  'on vinyl',
  'one',
  'one eye sign',
  'one hit wonder',
  'one of the greatest album i ever heard',
  'one world',
  'one-man-band',
  'onision',
  'opelmelange',
  'open',
  'optimistic',
  'orange',
  'organic',
  'orgel',
  'orgue',
  'original',
  'originales',
  'ornette coleman',
  'os karetas',
  'os putos brothers',
  'oscar peterson',
  'osho',
  'ost',
  'ot-free listening',
  'other',
  'ouahhhhh',
  'ouest africa',
  'out',
  'outsider',
  'ouvir depois',
  'over twenty minutes',
  'overrated',
  'ovo',
  'own',
  'own cd',
  'own it',
  'own on cd',
  'own on vinyl',
  'owned',
  'owsla',
  'p-funk',
  'paedo',
  'pain',
  'palco',
  'pants off',
  'paramore',
  'paranoid',
  'paredes de coura 2007',
  'part of my vinyl collection',
  'partial',
  'parts',
  'party',
  'partying',
  'passing',
  'passionate',
  'pat metheny',
  'pathetic',
  'paul chambers',
  'paul mccartney',
  'paved wiener',
  'peace',
  'peacedogman',
  'peaceful',
  'pedagogie',
  'pederastcore',
  'pedo',
  'pedophile',
  'pee pee',
  'peel sessions',
  'pendientes',
  'penelope pumpkins',
  'penis',
  'penisbird',
  'pennywise',
  'people i dont want to have sex with',
  'people who have no talent',
  'peter scully',
  'physical cds i actually own',
  'pile of plastic',
  'pink',
  'pink floyd',
  'pirates',
  'piss',
  'pissgore',
  'pitchfork best new music',
  'pixies palace',
  'pixies palace basement',
  'place',
  'placebo',
  'plaintive',
  'planet kolob',
  'planet mu',
  'playful',
  'pleasant',
  'please assassinate',
  'pleasing',
  'pligaa',
  'plinio01',
  'plop',
  'plopper',
  'pmbdiscovery',
  'poetic',
  'poignant',
  'political',
  'politically correct',
  'politics',
  'polydor',
  'polyphony',
  'pooptron',
  'poopy',
  'poopy-man',
  'pop lament',
  'pork',
  'porn',
  'porngore',
  'pornogore',
  'portishead',
  'poser',
  'posers',
  'positive',
  'posluchac',
  'post',
  'post anal experience',
  'post malone',
  'post-anal experience',
  'post-classical',
  'post-nerdcore',
  'posteverything',
  'pottery wordz',
  'power',
  'powerful',
  'praise',
  'praise & worship',
  'praise and worship',
  'prda',
  'precious',
  'pretentious',
  'pretentious music for undersexed nerds',
  'pretty',
  'primary',
  'prince',
  'prince andrew',
  'pro sun and no fear',
  'producer',
  'prog',
  'prog metal',
  'prog rock',
  'progressive',
  'progressive buttsecks metal',
  'progressive dreamfunk',
  'propaganda',
  'property',
  'proud to be gay',
  'proverbs',
  'provocative',
  'psy',
  'psych',
  'psych folk',
  'psych rock',
  'psychedelia',
  'psychadelic',
  'psychedelic',
  'psychedelic trance',
  'psycho',
  'psychodelic',
  'psychopathic',
  'punk',
  'pura ranchera',
  'puro ranchero',
  'purple',
  'pussycore',
  'pwr bttm',
  'pyschochick',
  'quatuor',
  'québec',
  'queen',
  'queen of flop',
  'queen of pop',
  'queer',
  'quiet',
  'quiet storm',
  'quinten painter',
  'quirky',
  'r&b',
  'r and b',
  'r kelly',
  'rachmaninov',
  'racism',
  'racism in music rules',
  'racism in music sucks',
  'racist',
  'radio',
  'radio13',
  'radiohead',
  'rain',
  'rainbow',
  'rainy day',
  'rambunctious',
  'rammstein',
  'ramones',
  'random',
  'rape',
  'raped in public by barney',
  'rapes my ears',
  'rapist',
  'rare',
  'raster-noton',
  'rather good stuff',
  'raucous',
  'raul seixas',
  'ravel',
  'raw',
  'real life rhymes',
  'real oi is rac',
  'rebellious',
  'recent music heroes',
  'reckless',
  'recommendations and such',
  'recommended',
  'records',
  'recos',
  'recoverworld',
  'red',
  'red city pt2',
  'red hot chili peppers',
  'redditcore',
  'redhot',
  'refined',
  'reflection',
  'reflective',
  'reggae celebration',
  'regine-disc',
  'registret',
  'regressive buttrock',
  'rei do pop',
  'reincarnation of hitler',
  'relationships',
  'relax',
  'relaxation',
  'relaxed',
  'relaxing',
  'religious',
  'remember70',
  'remix',
  'renaissance',
  'repetitive',
  'repoff',
  'restrained',
  'retarded',
  'retro',
  'review on schwermetall-ch',
  'reviewed',
  'reviewed in the guardian',
  'revolution',
  'rhythmic',
  'rich',
  'rich new age and chill',
  'richard',
  'richard strauss',
  'richard wagner',
  'richie hawtin',
  'ridiculous',
  'rihanna',
  'ripped',
  'rive gauche',
  'road trip',
  'robbie williams',
  'robert allen zimmerman',
  'robert schumann',
  'robertitus global',
  'rock & roll',
  'rock and roll',
  'rock en español',
  'rock latino',
  'rock pop',
  'rock progressif',
  'rock top',
  'rock-protopunk',
  'rocked reviews',
  'rockin party',
  'rockmusik',
  'rockstars',
  'rodrigo otarola',
  'rojun suomalaiset suosikit',
  'rolf harris',
  'rollicking',
  'rolling stones',
  'rollins',
  'romantic',
  'romanticism',
  'rough trade',
  'rousing',
  'rowdy',
  'roxette',
  'rs500album',
  'rs500best',
  'rsyniklaced',
  'run when you hear this you halfbreed filth',
  'russell98',
  'russian roulette',
  'rx',
  's richter',
  's y s l o v o',
  'sacred bones',
  'sad',
  'sampledelic',
  'sampler',
  'samples',
  'sarcastic',
  'sassy gals',
  'satan',
  'satanic',
  'satanic dildocore',
  'satanic garbage',
  'satire',
  'saturday',
  'save to itunes',
  'sax',
  'saxo',
  'saxomania',
  'saxophone',
  'scandinavian',
  'scary',
  'scat goregrind',
  'scatgore',
  'scatgrind',
  'scheisse',
  'schlageroldies',
  'schoene musik',
  'schubert',
  'schumann',
  'sci-fi',
  'scifi',
  'score',
  'scott',
  'scree123',
  'scryed edward tracks power',
  'seacocks',
  'seadawgg',
  'seahawks',
  'searching',
  'second',
  'seen live',
  'seiyuu',
  'sekalaisia suosikkeja',
  'selbst',
  'selena gomez',
  'self-released',
  'self-titled',
  'seligalex',
  'sellout',
  'sensual',
  'sentences',
  'sentimental',
  'september',
  'serve chilled',
  'served chilled',
  'seventies',
  'sex',
  'sexual',
  'sexy',
  'sexy album covers',
  'shady',
  'shady grady',
  'shakira',
  'shame',
  'she sings so sweetly',
  'ships ahoy',
  'shit being pumped into my head through a fire hose',
  'shit only a fag would listen to',
  'shit only a retard would listen to',
  'shit to check out',
  'shitcore',
  'shite',
  'shitty',
  'shoe0nhead',
  'shoegazer',
  'shoegazing',
  'shoegazing goodness',
  'shopping-list',
  'short and sweet',
  'shostakovich',
  'shows',
  'sibelius',
  'sick',
  'sickness',
  'sicmusic',
  'sieg heil',
  'sieg heil hakenkreuz',
  'silly',
  'silva alhandra',
  'silvio passos',
  'simone',
  'simplesdemais',
  'simply amazing',
  'sinatra',
  'sincerely yours',
  'sing',
  'singer',
  'singing songwriters',
  'single',
  'singles',
  'sjass',
  'skram',
  'skrillex',
  'sky',
  'slayer',
  'sleaze',
  'sleep',
  'sleepless',
  'slick',
  'slodkie',
  'slow',
  'slut',
  'slut pop',
  'smart',
  'smash mouth',
  'smooth',
  'so bad its good',
  'so fucking sexy',
  'so sexy',
  'so zorry',
  'soft',
  'soft and moist',
  'solo',
  'solitude',
  'solo project',
  'somber',
  'sombre',
  'son',
  'sonate',
  'song',
  'song noir',
  'songs',
  'songs i absolutely love',
  'songs i never get sick of',
  'songs played obsessively on repeat at some point',
  'songs to play after you sit for an hour waiting for a bus',
  'songwriter',
  'sonic fetish',
  'sonic youth',
  'soothing',
  'sophisticated',
  'sotto suolo',
  'sought',
  'soul rnb',
  'soulful',
  'sound',
  'sound art',
  'sounds',
  'sounds like a woman driving a vehicle with a manual transmission',
  'sounds66till77',
  'soundtracks',
  'sour',
  'southern',
  'spacecow',
  'space',
  'spacey',
  'spam',
  'spamcore',
  'spammer',
  'spammers',
  'sparkbums',
  'special',
  'speech',
  'speed',
  'spelling lobotomy correctly',
  'spermgrind',
  'spirit',
  'split',
  'spokojne',
  'spooky',
  'spoolme',
  'spotify',
  'sprawling',
  'spring',
  'ss',
  'sst',
  'staff',
  'standards',
  'standup comedy',
  'star fucking hipsters',
  'star wars',
  'starship',
  'starship entertainment',
  'stax',
  'stereo',
  'stimmung',
  'sting',
  'stonedbeat',
  'stoner',
  'stones throw',
  'stormy byrd',
  'strange',
  'street-smart',
  'strung out on violins',
  'stuff i need',
  'stupid',
  'stylish',
  'stza',
  'suavesfabio power',
  'sub pop',
  'sublime',
  'sucks',
  'suicide',
  'summer',
  'summery',
  'sun',
  'sun and moon and stars and outer space',
  'sunday',
  'sunday afternoon',
  'sundaymix',
  'sunny leone',
  'super',
  'superb song to drive to',
  'superhero',
  'superr',
  'superstar gods',
  'surreal',
  'survive',
  'svenskprov',
  'swag',
  'swaggering',
  'swazz',
  'sweet',
  'sweet and neato sounds',
  'sweet downtempo',
  'swissbear top 10',
  'sympathy68',
  'symphonic',
  'synth',
  'tag',
  'tagged',
  'tags',
  'tape',
  'talentless',
  'tangerine dream',
  'tanzen',
  'tatum',
  'taylor swift',
  'tchaikovsky',
  'tdhassociation',
  'technical',
  'technical perfection',
  'ted bundy',
  'teeheecore',
  'teh typos',
  'telemann',
  'television',
  'tenderness',
  'tenoxsax radio mix',
  'terrascopic',
  'terrible',
  'test',
  'testament',
  'tgif',
  'the',
  'the absolute finest piece of music which has ever stroken my ears and soul',
  'the andrews sisters',
  'the beatles',
  'the beatles cover',
  'the best',
  'the black keys',
  'the chainsmokers',
  'the cure',
  'the dc - 00s',
  'the devil and the deep blue sea',
  'the doors',
  'the fray',
  'the gayest thing ever to happen to music',
  'the good stuff',
  'the greatest album',
  'the harrisburg family band',
  'the killers',
  'the merch grrls',
  'the music maker society',
  'the noise inside my head',
  'the offspring',
  'the only true metal of steel',
  'the poets',
  'the really loved',
  'the rolling stones',
  'the rough guide to series',
  'the smiths',
  'the victims of chernobyl',
  'the vitamin b12',
  'the way you look',
  'the weeknd',
  'the who',
  'the worst thing ever to happen to music',
  'theasoul',
  'theatrical',
  'thelonious monk',
  'they look like serial prostitutes with fake dildos to scare little kids',
  'this album is pretty neat though',
  'this gave me cancer',
  'this heat worship',
  'this is garbage and you know it',
  'though',
  'thoughts',
  'thrash',
  'three',
  'thrill jockey',
  'thriller',
  'thursday',
  'tits',
  'to be someone',
  'to buy',
  'to check',
  'to check out',
  'to discover',
  'to download',
  'to explore',
  'to get',
  'to listen',
  'toilet sickness',
  'tom waits',
  'tony visconti',
  'tool',
  'top',
  'topper',
  'torture for my ears',
  'touch',
  'touhou',
  'traci lords',
  'tracks',
  'tragic',
  'trannies',
  'tranny',
  'transphobe',
  'transphobes',
  'transphobic',
  'transym',
  'trap rap',
  'trash',
  'trash metal',
  'trashbag filled with vomit',
  'treble',
  'tremendous noise',
  'trepidants',
  'trevor daniel',
  'tribute',
  'trilha sonora',
  'trippy',
  'trite',
  'troll',
  'trolling',
  'tropcool',
  'tropical',
  'troy',
  'true metal of steel',
  'trump',
  'trumpet',
  'trumpetmania',
  'truth',
  'try before i buy',
  'trying too hard',
  'tuesday',
  'tugs at me heart strings',
  'tv',
  'twee',
  'twinkle daddies',
  'twinkling starry skies',
  'two',
  'two thousand six',
  'tyra banks',
  'tzadik',
  'u2',
  'udoblues',
  'ugly',
  'uglycore',
  'uk bass',
  'uk top 40',
  'ultrapop',
  'un',
  'uncle kracker',
  'uncompromising',
  'uncreative',
  'under 100 listeners',
  'under 2000 listeners',
  'under 87665009756551896889899987854287765479831234470946568933668823144561 listeners',
  'underground',
  'underrated',
  'underrated and overlooked',
  'unfff',
  'unforgettable songs from when i was a teenager',
  'unglaublich',
  'unimaginative',
  'uninteresting',
  'unique',
  'united kingdom',
  'united states',
  'universal music enterprises',
  'unlistenable',
  'unoriginal',
  'unsexy',
  'unsigned',
  'untalented',
  'until we-re dead',
  'upbeat',
  'upcoming',
  'uplifting',
  'urban',
  'urgent',
  'us',
  'us-american',
  'usa underground',
  'used at guantanamo bay',
  'utter crap',
  'uuta jazzia',
  'uutta jazziz',
  'va',
  'vagina',
  'valley of the bees radio',
  'vangelis',
  'vanilla deville',
  'variete anglo-saxonne',
  'variete francaise',
  'various',
  'vemu',
  'very good',
  'very popular among the gay community',
  'vgm',
  'vibes',
  'vibesmania',
  'vibrafon',
  'vibraphon',
  'video game',
  'video games',
  'video killed the radio star',
  'vintage',
  'vinyl',
  'vinyl dont scrobble',
  'violates the geneva convention',
  'violence',
  'violin',
  'violon',
  'viralbraindeath',
  'virally yours',
  'virtuoso',
  'visceral',
  'visions',
  'visual',
  'visual gay',
  'vive la france',
  'vivaldi',
  'vocal',
  'vocal downtempo',
  'vocal-band',
  'vocal-lounge',
  'vocalist',
  'vocalistas femeninas',
  'vocalistas masculinos',
  'vocals',
  'voce femminile',
  'voce maschile',
  'voci femminili',
  'voci maschili',
  'voice',
  'voice actress',
  'volatile',
  'volvofh12',
  'vulgar',
  'w mozart',
  'waahh i love it',
  'wagner',
  'wagnerian arrangements',
  'walter buddy freter',
  'walter mojo freter',
  'wanking and crying while running a marathon',
  'want',
  'wanted',
  'wantlist',
  'wants',
  'war',
  'warm',
  'warner bros',
  'warp',
  'was officially brilliant live',
  'waste of valuable human sperm',
  'watzmann',
  'wave',
  'we miss you normani',
  'weallgetold',
  'web release',
  'webaudio',
  'weblabel',
  'weblabels',
  'weeaboo',
  'weed',
  'weezer',
  'weihnachten',
  'weird',
  'welcome',
  'western ny',
  'what',
  'what a voice',
  'what a waste of site resources',
  'what should i listen to next',
  'when i listen to them i dont have to buy peptobysmol anymore',
  'where are my headphones',
  'where gods began',
  'where is my bong',
  'whimsical',
  'white music for white people',
  'white powder',
  'white power',
  'white power rock',
  'white pride',
  'whore',
  'why',
  'wicked',
  'wie alles begann',
  'wiener',
  'will you tell me the secret of flop',
  'wilson seixas',
  'winamp',
  'wind and rain and ice and snow',
  'winter',
  'wish list',
  'wishlist',
  'wistful',
  'witty',
  'wny',
  'wolfgang amadeus mozart',
  'women',
  'wonderful',
  'wonderful women',
  'wonky',
  'wont play',
  'work',
  'worldmusic',
  'worn-out from overplay',
  'worst',
  'worst ever',
  'worthless',
  'wow',
  'wp',
  'wry',
  'wtf',
  'wu-tang',
  'wwafawdwg',
  'wwwlautfmbluesclub',
  'xap',
  'xgrottox',
  'xmas',
  'xmiyx',
  'xyz',
  'ye',
  'yeah',
  'yearning',
  'years',
  'yellow',
  'yes',
  'yolala nofx',
  'you',
  'you candle sniffing fuck fence go climb a wall of dicks you double nigger',
  'you cant illustrate while you suffocate',
  'you need to own this',
  'you too',
  'youngstar',
  'your ears will bleed',
  'youtube',
  'yoyoyo',
  'zappa',
  'zero',
  'zombie',
  'zywe',
];

const BLACKLISTED_TAG_STARTS = [
  ' ',
  '-',
  '00s ',
  '10s ',
  '1st ',
  '2010s ',
  '2015 ',
  '2016 ',
  '2017 ',
  '20s ',
  '30s ',
  '40s ',
  '50s ',
  '60s ',
  '70s ',
  '80s ',
  '90s ',
  'album of ',
  'albums ',
  'albuns ',
  'all time favorite ',
  'altar of the metal gods',
  'anal ',
  'approved by',
  'argeu',
  'awesome ',
  'bbc ',
  'best ',
  'better than ',
  'brc blues band ',
  'c20 ',
  'cd ',
  'cds ',
  'conforms to ',
  'excellent',
  'exists ',
  'fart',
  'favorite',
  'favourite',
  'for ',
  'free ',
  'from ',
  'fuck ',
  'fuckin ',
  'fucking ',
  'general ',
  'good',
  'harukaex',
  'i ',
  'incest',
  'intrumental',
  'jpoptrasher',
  'killer ',
  'listen to ',
  'lounge at ',
  'lyrics ',
  'meine ',
  'music from ',
  'music i ',
  'music to ',
  'musica ',
  'my ',
  'nice ',
  'not ',
  'perfect',
  'playlist',
  'post-post-',
  'purchased',
  'radio ',
  'records ',
  'shit ',
  'sick ',
  'similar to ',
  'stand out ',
  'streamable',
  'the best ',
  'thebest',
  'title is ',
  'to jest ',
  'too much',
  'top ',
  'ugly ',
  'under the radar',
  'valkyeriex',
  'valkyreiex',
  'valkyriex',
  'wiz khalifa',
  'worse than ',
  'worst ',
  'you can listen ',
];

const BLACKLISTED_TAG_ENDS = [
  ' 2016',
  ' 2020',
  ' aesthetics',
  ' af',
  ' album',
  ' album cover',
  ' album covers',
  ' albums',
  ' artist',
  ' artists',
  ' as fuck',
  ' brilliance',
  ' collection',
  ' concerto',
  ' does not approve',
  ' etc',
  ' fathers',
  ' favorites',
  ' favourites',
  ' flavoured',
  ' gods',
  ' group',
  ' groups',
  ' i own',
  ' influences',
  ' like this',
  ' likes this album',
  ' lovers',
  ' lyrics',
  ' minutes',
  ' music',
  ' musician',
  ' musicians',
  ' my ass',
  ' of the 21st century',
  ' on cover',
  ' owns',
  ' owns this',
  ' performance',
  ' productions',
  ' ram',
  ' radiostation',
  ' rare',
  ' recommends',
  ' records',
  ' releases',
  ' selection',
  ' song',
  ' songs',
  ' soundtrack',
  ' stars',
  ' streamable',
  ' tag',
  ' to hear before you die',
  ' vibe',
  ' vibes',
  '-esque',
  '-inch',
  'buttcore',
  'cunt',
  'fanatics',
  'fecalomatateus',
  'fm',
  'genius',
  'kircore',
  'owner',
  'peniscore',
  'radio',
  'recs',
  'rpm',
  'scum',
  'scumcore',
  'sexy sounding',
  'shit',
];

const BLACKLISTED_SUBSTRINGS = ['/', ' - ', ':'];

const MIN_TAG_NAME_LENGTH = 2;
const MAX_TAG_NAME_LENGTH = 40;
const NUMERIC_RE = /^\d+$/;

export default function isTagBlacklisted(tagName: string): boolean {
  let result = false;

  if (includes(tagName, '.')) {
    // logger.debug(`isTagBlacklisted(${tagName}) => ${result}: dot`);
    return true;
  }
  if (tagName.length < MIN_TAG_NAME_LENGTH) {
    result = true;
    // logger.debug(`isTagBlacklisted(${tagName}) => ${result}: length`);
  } else if (tagName.length > MAX_TAG_NAME_LENGTH) {
    result = true;
    // logger.debug(`isTagBlacklisted(${tagName}) => ${result}: length`);
  } else if (includes(BLACKLISTED_TAGS, tagName)) {
    result = true;
    // logger.debug(`isTagBlacklisted(${tagName}) => ${result}: explicitly`);
  } else if (NUMERIC_RE.test(tagName)) {
    result = true;
    // logger.debug(`isTagBlacklisted(${tagName}) => ${result}: numeric`);
  } else if (
    some(BLACKLISTED_TAG_STARTS, (blacklistedTagStart) =>
      startsWith(tagName, blacklistedTagStart),
    )
  ) {
    result = true;
    // logger.debug(`isTagBlacklisted(${tagName}) => ${result}: start`);
  } else if (
    some(BLACKLISTED_TAG_ENDS, (blacklistedTagEnd) =>
      endsWith(tagName, blacklistedTagEnd),
    )
  ) {
    result = true;
    // logger.debug(`isTagBlacklisted(${tagName}) => ${result}: end`);
  } else if (
    some(BLACKLISTED_SUBSTRINGS, (blacklistedSubstring) =>
      includes(tagName, blacklistedSubstring),
    )
  ) {
    result = true;
  }

  // logger.debug(`isTagBlacklisted(${tagName}) => ${result}`);
  return result;
}
/* eslint-enable sonarjs/no-duplicated-branches */
