export const { AMQP_HOSTNAME = 'localhost' } = process.env;
export const { AMQP_PASSWORD } = process.env;
export const { AMQP_PORT } = process.env;
export const { AMQP_USER } = process.env;
export const { AMQP_VHOST = 'v1' } = process.env;
export const { APP_NAME = 'app' } = process.env;
export const { DISCOGS_ACCESS_TOKEN } = process.env;
export const { LASTFM_API_KEY } = process.env;
export const { MONGODB_DATABASE } = process.env;
export const { MONGODB_URI } = process.env;
