/* eslint-disable sonarjs/no-duplicated-branches */
import endsWith from 'lodash/endsWith';
import includes from 'lodash/includes';
import some from 'lodash/some';
import startsWith from 'lodash/startsWith';

import logger from './logger';

const BLACKLISTED_TAGS = [
  '<3',
  '1001 albums you must hear before you die',
  '2 s34rch',
  '200 great albums owned by sideflower',
  '2cd',
  '3-5',
  '4',
  '4 star',
  '4-5',
  '4chan',
  '4nas',
  '8 soothing songs for rut',
  '718 metal',
  'a',
  'a8',
  'a9',
  'abc',
  'abstract',
  'achingly intelligent',
  'acquire',
  'agitada',
  'aggressive',
  'akb48',
  'alben',
  'album',
  'album collection',
  'album fav',
  'albums',
  'albumsiown',
  'aleystercrowleype',
  'all',
  'all aboard the failboat',
  'all things annoying in the world put together into one stupid bitch',
  'all time favourites',
  'all-time-favorite',
  'allboutguitar',
  'allboutguitar lessons - blues workshops',
  'allboutguitarcom',
  'amazing',
  'ambient dildocore',
  'ambitious',
  'angry',
  'anison',
  'annoying',
  'annymix',
  'anyzio rocha',
  'ap',
  'apocalyptic',
  'approved',
  'approximately 1000 times less pleasant than extreme anal caving',
  'as awesome has having testicles in your face when you wake up',
  'asscore',
  'atmosphere',
  'atmospheric',
  'atrocious',
  'attention whore',
  'august',
  'autumn',
  'autumnal',
  'availableonemusic',
  'awesome',
  'awesomeness',
  'awful',
  'bad',
  'bad music',
  'bad taste',
  'bananas',
  'band',
  'band records',
  'barneycore',
  'barturismooth',
  'based',
  'bearl3a1e5da4n15l1',
  'beautiful',
  'beautiful album covers',
  'beauty',
  'bella topolina',
  'bernardo montador de moveis em recife',
  'best',
  'best album',
  'best album ever',
  'best albums ever',
  'better die than listen to this',
  'better than radiohead',
  'beyondwithin',
  'bilititas',
  'bittersweet',
  'bizarre',
  'blue',
  'blues rock club radio karlsruhe',
  'blues rock radio deutschland',
  'blues rock radio germany',
  'blues rock radio germany deutschland',
  'blues-rockclub',
  'bluk glub',
  'boisterous',
  'bollocks',
  'bom sambinha',
  'bore',
  'boring',
  'bossy cow',
  'brc blues band',
  'bright',
  'brilliant',
  'brilliant record',
  'brooding',
  'brutal',
  'brutal fagcore',
  'brutal nazi scumcore with fascist influence and guest vocalist adolf hitler',
  'buryblue',
  'buy',
  'cant sing',
  'carefree',
  'carpet crawler',
  'cat',
  'catchy',
  'cd-sammlung',
  'check',
  'check later',
  'check out - friends',
  'check out',
  'checkout',
  'cheerful',
  'child molester',
  'children',
  'chill',
  'chilllounge1',
  'classic',
  'classica',
  'classics',
  'clinically romantic',
  'collected',
  'collection',
  'colors',
  'colossal faggot',
  'comfort',
  'coming summer melancholy',
  'complex',
  'con artist',
  'cool',
  'coolest album art',
  'coolwench',
  'cosmic',
  'crap',
  'crappy',
  'crappy english versions of german stuff',
  'cream of the crop',
  'creamed my pants',
  'creepy',
  'cronowish power',
  'cute',
  'darkness',
  'darkwave my ass',
  'dave',
  'day',
  'december',
  'decent',
  'deep',
  'depressive',
  'derivative',
  'det snurrar i min skalle',
  'detached',
  'deviliscious432',
  'dicky',
  'dildocore',
  'discover',
  'discoverockult',
  'disgrace to society',
  'donald trump',
  'dont have',
  'dope',
  'dope shit ouwe',
  'douchebag',
  'download',
  'downloadable tracks',
  'dr gay and his gang of faggots',
  'dr small jukebox',
  'dream',
  'drugs',
  'dull',
  'dumb',
  'eargasm',
  'ecstasy',
  'edgy',
  'educate yourself',
  'ego',
  'elegant',
  'emogaycore',
  'emusic',
  'emusic download',
  'ep',
  'epic',
  'epic bitch',
  'epic fail',
  'epitaph',
  'erotic',
  'essential',
  'everything',
  'everytime you listen to this crap a truck hits a granny',
  'exciting',
  'experimental my ass',
  'exuberant',
  'faggot',
  'failure',
  'fantastic',
  'fap',
  'fart machine',
  'fat',
  'fav',
  'fav album',
  'faves',
  'faves of the year',
  'favorit',
  'favs',
  'favs of nocci',
  'february',
  'fellating the bottom of a bottle of wine',
  'filter',
  'fiery',
  'fip',
  'flat-out amazing records that everyone should have in their cd collection',
  'flatulence',
  'flawless',
  'flop',
  'for howisya to hear',
  'for rainy days',
  'free',
  'freedom',
  'freepurp1e',
  'freewheeling',
  'friday',
  'fully streamable',
  'fully streamable album',
  'fully streamable track',
  'fully streamable tracks',
  'fun',
  'fun to skateboard to',
  'funky',
  'funny',
  'garbage',
  'gay',
  'gay metal',
  'gay nigger black metal',
  'gaycore',
  'generic',
  'genius',
  'gentle',
  'glorify my drug usage',
  'glorious vocals',
  'goatse',
  'god-like',
  'god-tier guitar',
  'godlike drumming',
  'good',
  'gossip',
  'goth music for pussies',
  'gothic my ass',
  'grade a',
  'grady',
  'great',
  'great album',
  'great album covers',
  'great groove',
  'great live band go see them',
  'great lyricists',
  'great name',
  'greatest hits',
  'greatrockers',
  'gritty',
  'groovy',
  'guilty',
  'guilty pleasure',
  'hairy chest',
  'handleliste',
  'hanging out',
  'hard',
  'has',
  'hate my nation',
  'have',
  'have on vinyl',
  'he',
  'heartache',
  'heil hitler',
  'hilarious',
  'hipster garabe',
  'hipster garbage',
  'hitler was right',
  'hits',
  'hiv positive',
  'holiday',
  'homeless on the streets giving handjobs for crack',
  'homocore',
  'homoerotic wet dream nostalgia metal',
  'homosexual intifada',
  'horrible',
  'hot',
  'idiot',
  'idioten',
  'idiotic',
  'impossible for liberals to deal with',
  'in my collection',
  'in queue no tracks',
  'in queue',
  'innocent',
  'insane',
  'inspirational',
  'inspiring',
  'intelligent',
  'intense',
  'interesting',
  'internet',
  'irack',
  'ironic',
  'itunes',
  'itunes store',
  'its not indie assholes',
  'january',
  'javajustice',
  'jazz favorites ram',
  'je devrais avoir mon enfer de la caresse',
  'je dirai quelque jour vos naissances latentes',
  'jesus',
  'jonasmusik',
  'jubei yagyu',
  'juma',
  'june',
  'k1r7m',
  'kacke',
  'kategorische elative',
  'kayfovo',
  'kept in freezer to be served as dinner',
  'killforpeace',
  'kitsch',
  'kvlt',
  'l3a1e5da4n15l1',
  'la',
  'lame',
  'laptop',
  'lautfm bluesclub',
  'leather daddy rape soundtrack',
  'legend',
  'legendary',
  'legendary night music for chads',
  'library',
  'life',
  'like',
  'list',
  'listen',
  'listen16',
  'literate',
  'lively',
  'lmao',
  'lol',
  'lolfest',
  'lolicore',
  'lost',
  'love',
  'love at first listen',
  'love it',
  'loved',
  'lovely',
  'lush',
  'lyrical',
  'mainstream',
  'mandatory',
  'march',
  'masterpiece',
  'me',
  'media',
  'mediocore',
  'mediocre',
  'megadeth',
  'mein house',
  'mein virtuelles musikregal',
  'meine party',
  'meine privat-cd-sammlung',
  'melodic',
  'melodic dildocore',
  'memories',
  'menacing',
  'metal for teletubbies',
  'metal of god',
  'micropenis',
  'milestones',
  'misanthropic gay romance nostalgia metal',
  'misc',
  'miscellaneous',
  'mlx',
  'mmfwcl',
  'mod',
  'modern',
  'mojo 1000 rock',
  'monakitty432',
  'monday',
  'moody',
  'more gay than a san fransisco man in a hawaiian shirt sniffing some liquid gold and watching sex in the city',
  'moronic',
  'moskalyaku na gillyaku',
  'most amazing bands in the fucking world',
  'most loved',
  'mtv trash',
  'music',
  'must have',
  'my-love',
  'name',
  'need to check this out',
  'netaudio',
  'new',
  'new milkmaid',
  'new music',
  'new one',
  'new to listen',
  'news',
  'nice',
  'nice album art',
  'nicenoise',
  'no',
  'no talent',
  'no thanks',
  'not art',
  'not available on last-fm radio yet',
  'not on my computer anymore',
  'november',
  'now available on last-fm radio 07q3',
  'nuggets',
  'numbers',
  'objectum-sexualis',
  'occhi a cuoricino',
  'of',
  'officially retarded',
  'on repeat',
  'one of the greatest album i ever heard',
  'organic',
  'original',
  'ot-free listening',
  'ouahhhhh',
  'out',
  'ouvir depois',
  'overrated',
  'own',
  'own it',
  'own on cd',
  'own on vinyl',
  'owned',
  'part of my vinyl collection',
  'pathetic',
  'peacedogman',
  'peaceful',
  'pederastcore',
  'pee pee',
  'people i dont want to have sex with',
  'people who have no talent',
  'pile of plastic',
  'piss',
  'pitchfork best new music',
  'pitchfork: best new music',
  'place',
  'playlist',
  'please assassinate',
  'plop',
  'pooptron',
  'poser',
  'posers',
  'posluchac',
  'post anal experience',
  'post-anal experience',
  'powerful',
  'prda',
  'pretentious',
  'pretentious music for undersexed nerds',
  'pretty',
  'primary',
  'property',
  'psycho',
  'purple',
  'pussycore',
  'puuma85 musicians',
  'qlencja jazz selection',
  'queen of flop',
  'quiet storm',
  'quirky',
  'racism in music rules',
  'racism in music sucks',
  'radio',
  'rainy day',
  'rambunctious',
  'random',
  'raped in public by barney',
  'rapes my ears',
  'rather good stuff',
  'real oi is rac',
  'recent music heroes',
  'reckless',
  'recommendations and such',
  'recommended',
  'redditcore',
  'redhot',
  'refined',
  'registret',
  'regressive buttrock',
  'reincarnation of hitler',
  'relaxation',
  'relaxed',
  'retarded',
  'review on schwermetall-ch',
  'reviewed',
  'reviewed in the guardian',
  'ridiculous',
  'ripped',
  'rock top',
  'rousing',
  'rsyniklaced',
  'run when you hear this you halfbreed filth',
  'rx',
  'sad',
  'satanic dildocore',
  'satanic garbage',
  'saturday',
  'scheisse',
  'schoene musik',
  'scree123',
  'scryed edward tracks power',
  'searching',
  'second',
  'seen live',
  'selbst',
  'seligalex',
  'sellout',
  'sensual',
  'sentimental',
  'september',
  'serve chilled',
  'served chilled',
  'sex',
  'sexy',
  'sexy album covers',
  'shady',
  'shady grady',
  'shame',
  'ships ahoy',
  'shit being pumped into my head through a fire hose',
  'shit only a fag would listen to',
  'shit only a retard would listen to',
  'shit to check out',
  'shitcore',
  'shite',
  'shitty',
  'shoegazing goodness',
  'sick',
  'sieg heil hakenkreuz',
  'sincerely yours',
  'sjass',
  'sleepless',
  'slut',
  'slut pop',
  'smart',
  'so bad its good',
  'so zorry',
  'song',
  'songs i never get sick of',
  'songs played obsessively on repeat at some point',
  'songs to play after you sit for an hour waiting for a bus',
  'sonic fetish',
  'sought',
  'soulful',
  'sound',
  'sounds',
  'sounds like a woman driving a vehicle with a manual transmission',
  'spacecow',
  'spacey',
  'spam',
  'spammer',
  'spammers',
  'sparkbums',
  'special',
  'spermgrind',
  'spooky',
  'sprawling',
  'staff',
  'standards',
  'strange',
  'streamable',
  'stuff i need',
  'stupid',
  'stylish',
  'suavesfabio power',
  'sucks',
  'summer',
  'sunday',
  'sunday afternoon',
  'sundaymix',
  'super',
  'superb song to drive to',
  'superr',
  'superstar gods',
  'tag',
  'tagged',
  'tags',
  'talentless',
  'technical perfection',
  'teh typos',
  'television',
  'terrible',
  'test',
  'the',
  'the absolute finest piece of music which has ever stroken my ears and soul',
  'the best',
  'the gayest thing ever to happen to music',
  'the only true metal of steel',
  'the really loved',
  'the victims of chernobyl',
  'the way you look',
  'the worst thing ever to happen to music',
  'they look like serial prostitutes with fake dildos to scare little kids',
  'this album is pretty neat though',
  'this is garbage and you know it',
  'though',
  'three',
  'thursday',
  'to buy',
  'to check out',
  'to discover',
  'to download',
  'to explore',
  'to listen',
  'top',
  'torture for my ears',
  'tracks',
  'transym',
  'trap',
  'trash',
  'trashbag filled with vomit',
  'trippy',
  'trite',
  'troll',
  'trolling',
  'true metal of steel',
  'truth',
  'try before i buy',
  'trying too hard',
  'tv',
  'ugly',
  'uglycore',
  'uk top 40',
  'uncompromising',
  'uncreative',
  'under 2000 listeners',
  'under 87665009756551896889899987854287765479831234470946568933668823144561 listeners',
  'underrated',
  'underrated and overlooked',
  'unforgettable songs from when i was a teenager',
  'unimaginative',
  'uninteresting',
  'unique',
  'unlistenable',
  'unoriginal',
  'untalented',
  'upcoming',
  'urgent',
  'used at guantanamo bay',
  'valley of the bees radio',
  'very good',
  'vibes',
  'vinyl',
  'violates the geneva convention',
  'viralbraindeath',
  'virally yours',
  'visceral',
  'visual gay',
  'volatile',
  'volvofh12',
  'waahh i love it',
  'wanking and crying while running a marathon',
  'want',
  'wanted',
  'wants',
  'warm',
  'warp',
  'waste of valuable human sperm',
  'weallgetold',
  'weird',
  'what',
  'what a waste of site resources',
  'what should i listen to next',
  'when i listen to them i dont have to buy peptobysmol anymore',
  'where are my headphones',
  'where is my bong',
  'whimsical',
  'white powder',
  'whore',
  'why',
  'wie alles begann',
  'will you tell me the secret of flop',
  'winamp',
  'winter',
  'wish list',
  'wishlist',
  'wistful',
  'witty',
  'wonderful',
  'wonderful women',
  'wonky',
  'work',
  'worst',
  'worst ever',
  'worthless',
  'wow',
  'wry',
  'wtf',
  'wwwlautfmbluesclub',
  'xap',
  'yearning',
  'years',
  'yellow',
  'yes',
  'you candle sniffing fuck fence go climb a wall of dicks you double nigger',
  'your ears will bleed',
  'zero',
];

const BLACKLISTED_TAG_STARTS = [
  ' ',
  '1st ',
  'album of ',
  'albums ',
  'albuns ',
  'all time favorite ',
  'altar of the metal gods',
  'anal ',
  'argeu',
  'awesome ',
  'best ',
  'better than ',
  'brc blues band ',
  'cd ',
  'cds ',
  'excellent',
  'favorite',
  'favourite',
  'free ',
  'fuck ',
  'fucking ',
  'genre:',
  'good',
  'harukaex',
  'i ',
  'lounge at ',
  'lyrics ',
  'music i ',
  'music to ',
  'my ',
  'nice ',
  'perfect',
  'purchased',
  'records ',
  'the best ',
  'thebest',
  'top ',
  'ugly ',
  'under the radar',
  'valkyeriex',
  'valkyreiex',
  'valkyriex',
  'worse than ',
  'worst ',
];
const BLACKLISTED_TAG_ENDS = [
  ' albums',
  ' collection',
  ' does not approve',
  ' favorites',
  ' i own',
  ' like this',
  ' likes this album',
  ' lyrics',
  ' owns',
  ' owns this',
  ' radio',
  ' releases',
  ' stars',
  ' vibe',
  'buttcore',
  'cunt',
  'fecalomatateus',
  'fm',
  'genius',
  'kircore',
  'peniscore',
  'scum',
  'scumcore',
  'sexy sounding',
  'shit',
];

const MIN_TAG_NAME_LENGTH = 2;
const MAX_TAG_NAME_LENGTH = 40;
const NUMERIC_RE = /^\d+$/;

export default function isTagBlacklisted(tagName: string): boolean {
  let result = false;
  if (includes(tagName, '.')) {
    logger.debug(`isTagBlacklisted(${tagName}) => ${result}: dot`);
    return true;
  }
  if (tagName.length < MIN_TAG_NAME_LENGTH) {
    result = true;
    logger.debug(`isTagBlacklisted(${tagName}) => ${result}: length`);
  } else if (tagName.length > MAX_TAG_NAME_LENGTH) {
    result = true;
    logger.debug(`isTagBlacklisted(${tagName}) => ${result}: length`);
  } else if (includes(BLACKLISTED_TAGS, tagName)) {
    result = true;
    logger.debug(`isTagBlacklisted(${tagName}) => ${result}: explicitly`);
  } else if (NUMERIC_RE.test(tagName)) {
    result = true;
    logger.debug(`isTagBlacklisted(${tagName}) => ${result}: numeric`);
  } else if (
    some(BLACKLISTED_TAG_STARTS, (blacklistedTagStart) =>
      startsWith(tagName, blacklistedTagStart),
    )
  ) {
    result = true;
    logger.debug(`isTagBlacklisted(${tagName}) => ${result}: start`);
  } else if (
    some(BLACKLISTED_TAG_ENDS, (blacklistedTagEnd) =>
      endsWith(tagName, blacklistedTagEnd),
    )
  ) {
    result = true;
    logger.debug(`isTagBlacklisted(${tagName}) => ${result}: end`);
  }
  return result;
}
/* eslint-enable sonarjs/no-duplicated-branches */
