import includes from 'lodash/includes';
import startsWith from 'lodash/startsWith';

const BLACKLISTED_TAGS = [
  '<3',
  '1001 albums you must hear before you die',
  '4',
  'agitada',
  'album i own',
  'albums',
  'albums i love',
  'albums i own',
  'albums i own on vinyl',
  'albums i want',
  'all time great albums',
  'amazing',
  'annoying',
  'approved',
  'attention whore',
  'availableonemusic',
  'awesome',
  'awful',
  'bad',
  'bad music',
  'bad taste',
  'beautiful',
  'beauty',
  'best',
  'best album',
  'best album ever',
  'best albums',
  'best albums ever',
  'better than radiohead',
  'bizarre',
  'boring',
  'brilliant',
  'bullshit',
  'cant sing',
  'check',
  'cd collection',
  'cds i own',
  'check out',
  'cool',
  'crap',
  'crappy english versions of german stuff',
  'creamed my pants',
  'cronowish power',
  'darksky fm',
  'decent',
  'deep',
  'derivative',
  'deviliscious432',
  'dicky',
  'discover',
  'disgrace to society',
  'download',
  'dumb',
  'epic fail',
  'excellent streamability',
  'exciting',
  'fat',
  'fav',
  'fav album',
  'fav albums',
  'favorite album',
  'favorite albums',
  'favorite bm',
  'favorite instrumentals',
  'favorite songs',
  'favorite tracks',
  'favorites',
  'favourite',
  'favourite album',
  'favourite albums',
  'favourite tracks',
  'favourites',
  'favs of nocci',
  'flop',
  'free complete album to check out',
  'free tracks',
  'fully streamable',
  'fully streamable albums',
  'garbage',
  'gay',
  'generic',
  'genius',
  'god-tier guitar',
  'godlike drumming',
  'good',
  'gossip',
  'great',
  'great albums',
  'great lyricists',
  'great lyrics',
  'handleliste',
  'has',
  'hilarious',
  'hipster garabe',
  'hipster garbage',
  'horrible',
  'i have this album',
  'i own this cd',
  'idiot',
  'idiotic',
  'in my collection',
  'internet',
  'ironic',
  'kacke',
  'kitsch',
  'known albums',
  'lame',
  'legend',
  'legendary night music for chads',
  'life',
  'love',
  'love at first listen',
  'love it',
  'masterpiece',
  'me',
  'mein house',
  'mein virtuelles musikregal',
  'meine party',
  'milestones',
  'monakitty432',
  'most amazing bands in the fucking world',
  'my albums',
  'my favorite albums',
  'my favourite albums',
  'nancykitten all time favourite albums',
  'nazi shit',
  'no talent',
  'of',
  'officially shit',
  'on repeat',
  'ot-free listening',
  'overrated',
  'own',
  'own on vinyl',
  'owned',
  'pathetic',
  'people who have no talent',
  'perfect',
  'perfect albums',
  'playlist',
  'posluchac',
  'pretentious',
  'queen of flop',
  'rather good stuff',
  'recent music heroes',
  'review on schwermetall ch',
  'ridiculous',
  'rolling stone 500 greatest albums',
  'rsyniklaced',
  'satanic garbage',
  'satanic shit',
  'scheisse',
  'scryed edward tracks power',
  'seen live',
  'sellout',
  'sexy',
  'shit',
  'shitcore',
  'slut',
  'so zorry',
  'songs to play after you sit for an hour waiting for a bus',
  'streamable',
  'stupid',
  'suavesfabio power',
  'superr',
  'talentless',
  'technical perfection',
  'terrible',
  'test',
  'the best',
  'this albums is pretty neat though',
  'to check out',
  'totally fully albums',
  'trash',
  'trite',
  'trying too hard',
  'ugly',
  'ugly vocalists',
  'uncreative',
  'under 2000 listeners',
  'under 87665009756551896889899987854287765479831234470946568933668823144561 listeners',
  'underrated',
  'unforgettable songs from when i was a teenager',
  'unlistenable',
  'untalented',
  'vinyls i own',
  'waahh i love it',
  'what should i listen to next',
  'whore',
  'will you tell me the secret of flop',
  'winamp',
  'wishlist',
  'worst',
  'worst ever',
  'wow',
  'wtf',
];

export default function isTagBlacklisted(tagName: string): boolean {
  if (includes(BLACKLISTED_TAGS, tagName)) {
    return true;
  }
  if (startsWith(tagName, 'best ')) {
    return true;
  }
  if (startsWith(tagName, 'perfect ')) {
    return true;
  }
  if (startsWith(tagName, 'valkyriex')) {
    return true;
  }
  if (startsWith(tagName, 'valkyeriex')) {
    return true;
  }
  if (startsWith(tagName, 'harukaex')) {
    return true;
  }
  if (startsWith(tagName, 'valkyreiex')) {
    return true;
  }
  if (startsWith(tagName, 'top 10 of ')) {
    return true;
  }
  if (startsWith(tagName, 'worst of ')) {
    return true;
  }
  if (startsWith(tagName, 'worse than ')) {
    return true;
  }
  return false;
}
