UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2015' WHERE artist = 'Iron Maiden' AND "name" = 'Somewhere in Time (2015 - Remaster)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Iron Maiden' AND "name" = 'Ed Hunter CD 2 (CDA)';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1981-10-05' WHERE artist = 'Saxon' AND "name" = 'Denim And Leather';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1981-04-20' WHERE artist = 'Girlschool' AND "name" = 'Hit and Run';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1981-01' WHERE artist = 'Raven' AND "name" = 'Rock Until You Drop';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1981-05' WHERE artist = 'Samson' AND "name" = 'Shock Tactics';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1981-04' WHERE artist = 'Tygers of Pan Tang' AND "name" = 'Spellbound';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1981-11' WHERE artist = 'Tygers of Pan Tang' AND "name" = 'Crazy Nights';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-08-09' WHERE artist = 'Slander' AND "name" = 'Kneel Before Me';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Motörhead' AND "name" = 'Everything Louder Than Everyone Else (disc 2)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Judas Priest' AND "name" = 'Metal Works ''73-''93 Disc 1';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2009-03-13' WHERE artist = 'Metalucifer' AND "name" = 'Heavy Metal Bulldozer';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1982-03-12' WHERE artist = 'Diamond Head' AND "name" = 'Borrowed Time';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1982-03' WHERE artist = 'Tank' AND "name" = 'Filth Hounds of Hades';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1982-07-03' WHERE artist = 'Demon' AND "name" = 'The Unexpected Guest';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1983-11' WHERE artist = 'Tokyo Blade' AND "name" = 'Tokyo Blade';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1983-03' WHERE artist = 'Jaguar' AND "name" = 'Power Games';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1983-08' WHERE artist = 'Raven' AND "name" = 'All for One';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1985-05' WHERE artist = 'Grim Reaper' AND "name" = 'Fear No Evil';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Def Leppard' AND "name" = 'First Strike';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2008-05-12' WHERE artist = 'Iron Maiden' AND "name" = 'Somewhere Back In Time';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1986-04-09' WHERE artist = 'Angel Witch' AND "name" = 'Frontal Assault';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1987-09-05' WHERE artist = 'Grim Reaper' AND "name" = 'Rock You to Hell';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1998' WHERE artist = 'Iron Maiden' AND "name" = 'Seventh Son Of A Seventh Son (1998 Remastered Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1988-07' WHERE artist = 'Cloven Hoof' AND "name" = 'Dominator';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1998' WHERE artist = 'Iron Maiden' AND "name" = 'The Number of The Beast (1998 Remastered Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1998' WHERE artist = 'Iron Maiden' AND "name" = 'No Prayer For The Dying (1998 Remastered Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1998' WHERE artist = 'Iron Maiden' AND "name" = 'Powerslave (1998 Remastered Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1998' WHERE artist = 'Iron Maiden' AND "name" = 'Piece Of Mind (1998 Remastered Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 24, "date" = '1991-12' WHERE artist = 'Girlschool' AND "name" = 'The Collection';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '1999-07-25' WHERE artist = 'Iron Maiden' AND "name" = 'Ed Hunter';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1982-06-03' WHERE artist = 'Raven' AND "name" = 'Wiped Out';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2004-05-23' WHERE artist = 'Pagan Altar' AND "name" = 'The Time Lord';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007-08-10' WHERE artist = 'Blitzkrieg' AND "name" = 'Theatre Of The Damned';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2021' WHERE artist = 'Raven' AND "name" = 'All For One (Bonus Track Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1980-12' WHERE artist = 'Angel Witch' AND "name" = 'Angel Witch';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1980-02' WHERE artist = 'Witchfynde' AND "name" = 'Give ''Em Hell';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1981' WHERE artist = 'Praying Mantis' AND "name" = 'Time Tells No Lies';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2011-05-13' WHERE artist = 'Hell' AND "name" = 'Human Remains';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1983' WHERE artist = 'Battleaxe' AND "name" = 'Burn This Town';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1983-03' WHERE artist = 'Jaguar' AND "name" = 'Power Games';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1989-06-02' WHERE artist = 'Demon' AND "name" = 'Taking The World By Storm';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2007' WHERE artist = 'Depeche Mode' AND "name" = 'Black Celebration (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2005' WHERE artist = 'Molotov Solution' AND "name" = 'the path to extinction';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2016-10-31' WHERE artist = 'Angelmaker' AND "name" = 'Unholy Alliance';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Thy Art Is Murder' AND "name" = 'Slaves Beyond Death';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2009-07-07' WHERE artist = 'Ease of Disgust' AND "name" = 'The Shell';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2007-12-25' WHERE artist = 'Lil'' Wayne' AND "name" = 'The Leak';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2011-06' WHERE artist = 'One More Victim' AND "name" = 'Dominion';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2013-01-01' WHERE artist = 'Dysphoria' AND "name" = 'To the Perfect Form of Modern Species';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2018-07-13' WHERE artist = 'Chelsea Grin' AND "name" = 'Hostage';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2010-07-10' WHERE artist = 'King Conquer' AND "name" = 'Decomposing Normality';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2007-09-18' WHERE artist = 'Suicide Silence' AND "name" = 'The Cleansing (European Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-01-22' WHERE artist = 'Chelsea Wolfe' AND "name" = 'I Love You All the Time (Play It Forward Campaign)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Chelsea Wolfe' AND "name" = 'Iron Moon - Single';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-06-03' WHERE artist = 'Chelsea Wolfe' AND "name" = 'Carrion Flowers - Single';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Adam Lambert' AND "name" = 'American Idol 2009';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2011-03-31' WHERE artist = 'Disfiguring the Goddess' AND "name" = 'Circle Of Nine';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2004' WHERE artist = 'Paul Wall' AND "name" = 'Chick Magnet Chopped & Skrewed by Micheal Watts';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2010' WHERE artist = 'He The Deceiver' AND "name" = 'The Last Breath Of Humanity';
UPDATE "public"."Album" SET "numberOfTracks" = 5 WHERE artist = 'Eat A Helicopter' AND "name" = 'The Pessimist';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1996' WHERE artist = 'Forest' AND "name" = 'Forest';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2016-08-19' WHERE artist = 'Trash' AND "name" = 'Give Up';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-12-29' WHERE artist = 'LoCash' AND "name" = 'Don''t Get Better Than That';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1998' WHERE artist = 'Astrofaes' AND "name" = 'Dying Emotions Domain';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nokturnal Mortum' AND "name" = 'Nechrist';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2019-02-12' WHERE artist = 'Avril Lavigne' AND "name" = 'Dumb Blonde (feat. Nicki Minaj)';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2005-03' WHERE artist = 'Nokturnal Mortum' AND "name" = 'Weltanschauung';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2005-06-27' WHERE artist = 'Bilskirnir' AND "name" = 'Hyperborea';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2006-05-03' WHERE artist = 'Xenophobia' AND "name" = 'Reclaiming Celtic Glory';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2008-06' WHERE artist = 'Sturmkaiser' AND "name" = 'Veni Vidi Vici';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2000-05' WHERE artist = 'Thor''s Hammer' AND "name" = 'May the Hammer Smash the Cross';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nokturnal Mortum' AND "name" = 'Voice Of Steel';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2002' WHERE artist = '509-E' AND "name" = 'MMII-DC';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2019-05-29' WHERE artist = '100 gecs' AND "name" = 'money machine';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = '100 gecs' AND "name" = 'ringtone (feat. Charli XCX, Rico Nasty, Kero Kero Bonito) [remix] - Single';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1990-11' WHERE artist = 'Impetigo' AND "name" = 'Ultimo Mondo Cannibale';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '1995-09-11' WHERE artist = 'Dead Infection' AND "name" = 'A Chapter Of Accidents';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1997-05-20' WHERE artist = 'Haemorrhage' AND "name" = 'Grume';
UPDATE "public"."Album" SET "numberOfTracks" = 23, "date" = '1996-07' WHERE artist = 'Mortician' AND "name" = 'Hacked Up for Barbecue';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1997-03' WHERE artist = 'Disgorge' AND "name" = 'Chronic Corpora Infest';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1998-11-23' WHERE artist = 'Haemorrhage' AND "name" = 'Anatomical Inferno';
UPDATE "public"."Album" SET "numberOfTracks" = 32, "date" = '2000-10-20' WHERE artist = 'Regurgitate' AND "name" = 'Carnivorous Erection';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2002-06' WHERE artist = 'Cock and Ball Torture' AND "name" = 'Sadochismo';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2002-09' WHERE artist = 'Mortician' AND "name" = 'Darkest Day Of Horror';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2002-04-04' WHERE artist = 'Haemorrhage' AND "name" = 'Morgue Sweet Home';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2002-11-11' WHERE artist = 'Regurgitate' AND "name" = 'Hatefilled Vengeance';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2003-05-13' WHERE artist = 'Ahumado Granujo' AND "name" = 'Splatter-tekk';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Carcass' AND "name" = 'Flesh Ripping Symphony';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2004-04-30' WHERE artist = 'Torsofuck' AND "name" = 'Erotic Diarrhea Fantasy';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2004-05-12' WHERE artist = 'Ahumado Granujo' AND "name" = 'Chemical Holocaust';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2004-12-24' WHERE artist = 'Lord Gore' AND "name" = 'Resickened';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2004-06' WHERE artist = 'Anal Blast' AND "name" = 'Battered Bleeding Bitch';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2005-04' WHERE artist = 'Anal Nosorog' AND "name" = 'You Are a Fat Putridity';
UPDATE "public"."Album" SET "numberOfTracks" = 27, "date" = '2006-07' WHERE artist = 'Last Days of Humanity' AND "name" = 'Putrefaction In Progress';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2007-02-23' WHERE artist = 'Katalepsy' AND "name" = 'Musick Brings Injuries';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rompeprop' AND "name" = 'Rompeprop';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2006-10-31' WHERE artist = 'Meshuggah' AND "name" = 'Nothing [Re-Issue]';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2004-04-02' WHERE artist = 'Spastic Ink' AND "name" = 'Ink Compatible';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2005' WHERE artist = 'Mudvayne' AND "name" = 'Lost and Found (Clean Version)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sikth' AND "name" = 'The Trees Are Dead & Dried Out';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2013-06' WHERE artist = 'Uneven Structure' AND "name" = '8';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2012-03-30' WHERE artist = 'The Korea' AND "name" = 'Колесницы Богов';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'TesseracT' AND "name" = 'Concealing Fate [EP]';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2010' WHERE artist = 'TesseracT' AND "name" = 'Concealing Fate EP';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2013-05-28' WHERE artist = 'TesseracT' AND "name" = 'Altered State';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-05-31' WHERE artist = 'Hacktivist' AND "name" = '2 Rotten';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2005-05-16' WHERE artist = 'Meshuggah' AND "name" = 'Catch ThirtyThree';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Meshuggah' AND "name" = 'Catch 33';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Meshuggah' AND "name" = 'Catch Thirty-Three';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2018-04-20' WHERE artist = 'TesseracT' AND "name" = 'Sonder';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2019-10-25' WHERE artist = 'Jinjer' AND "name" = 'Macro';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2019-03-08' WHERE artist = 'seeyouspacecowboy' AND "name" = 'Songs for the Firing Squad';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2017-08-11' WHERE artist = 'Pyrrhon' AND "name" = 'What Passes For Survival';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2005-06-07', "hidden" = false WHERE artist = 'The Number Twelve Looks Like You' AND "name" = 'Nuclear. Sad. Nuclear.';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Number Twelve Looks Like You' AND "name" = 'Nuclear.Sad.Nuclear';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Number Twelve Looks Like You' AND "name" = 'Nuclear. Sad. Nuclear';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Periphery' AND "name" = 'Demos 2004-2008';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dinosaurs' AND "name" = 'WELCOME TO THE WORLD OF DINOSAURS';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006-08-08' WHERE artist = 'Jonas Brothers' AND "name" = 'It''s About Time';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2006-12-16' WHERE artist = 'Лють' AND "name" = 'The Day Of The Rope';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2007-03-30' WHERE artist = 'Attila' AND "name" = 'Fallacy';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2008-12-01' WHERE artist = 'Der Stürmer' AND "name" = 'Bloodsworn (The First Decade)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2007' WHERE artist = 'Otto Dix' AND "name" = 'Extravaganza!';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2010-03' WHERE artist = 'Bustum' AND "name" = 'The Return of Hate';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2011-09-28' WHERE artist = 'Der Stürmer' AND "name" = 'Transcendental Racial Idealism';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2019-02-15' WHERE artist = 'Avril Lavigne' AND "name" = 'Head Above Water';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2011-08-31' WHERE artist = 'Rusko Star' AND "name" = 'Blonde';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2007-09-14' WHERE artist = 'Rusko Star' AND "name" = 'Attention W***e - EP';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rusko Star' AND "name" = 'Summer Love';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2009-01-20' WHERE artist = 'Combichrist' AND "name" = 'Today We Are All Demons';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Pee Wee Gaskins' AND "name" = 'Compilasi Band AlfaRecords';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2014-05-29' WHERE artist = 'Widek' AND "name" = 'Outside The Universe';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2018-10-26' WHERE artist = 'Haken' AND "name" = 'Vector';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Vildhjarta' AND "name" = 'Masstaden';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Hacktivist' AND "name" = 'Hacktivist EP';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '1995' WHERE artist = 'Deftones' AND "name" = '7 Words';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2011-07-04' WHERE artist = 'Ingested' AND "name" = 'The Surreption';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2002-11-28' WHERE artist = 'Astrofaes' AND "name" = 'Heritage';
UPDATE "public"."Album" SET "numberOfTracks" = 25, "date" = '2010-02-26' WHERE artist = 'Avril Lavigne' AND "name" = 'Girlfriend EP';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Various Artists' AND "name" = '99.1 (Disc 1)';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1999-08-30' WHERE artist = 'Breakbeat Era' AND "name" = 'Ultra Obscene';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2007' WHERE artist = 'Dope Skillz' AND "name" = 'Watch The Ride';
UPDATE "public"."Album" SET "numberOfTracks" = 24, "date" = '2000-05-15' WHERE artist = 'Bad Company' AND "name" = 'Inside The Machine';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2005-06-07' WHERE artist = 'Lamb' AND "name" = 'Best Kept Secrets - The Best Of Lamb 1996 - 2004';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2007-03-26' WHERE artist = 'High Contrast' AND "name" = 'NHS116: Everything''s Different / Green Screen';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2010-07-05' WHERE artist = 'Utah Jazz' AND "name" = 'Vintage';
UPDATE "public"."Album" SET "numberOfTracks" = 41, "date" = '2011-08-01' WHERE artist = 'Various Artists' AND "name" = 'UKF: Bass Culture';
UPDATE "public"."Album" SET "numberOfTracks" = 37, "date" = '2005-08-22' WHERE artist = 'Various Artists' AND "name" = 'Us Against The World';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2003' WHERE artist = 'Calibre' AND "name" = 'DFUNKD017';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1996-06' WHERE artist = 'Funki Porcini' AND "name" = 'Love Pussycats & Carwrecks';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1997-11' WHERE artist = 'Animals on Wheels' AND "name" = 'Designs & Mistakes';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Kylie Minogue' AND "name" = 'Impossible Princess (Deluxe Edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Lamb' AND "name" = 'All In Their Hands';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2009-04-10' WHERE artist = 'Shock One' AND "name" = 'Shock One EP [VPR017]';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2007-03-05' WHERE artist = 'Danny Byrd' AND "name" = 'NHSDL07: Danny Byrd - Medical History';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2005-10-17' WHERE artist = 'Shy FX' AND "name" = 'Diary of a Digital Soundboy';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = '4hero' AND "name" = 'Two Pages (disc 2: Page 2)';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2010' WHERE artist = 'TesseracT' AND "name" = 'Concealing Fate (EP)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'TesseracT' AND "name" = 'Concealing Fate EP';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Ion Dissonance' AND "name" = '...Breathing Is Irrelevant';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2014-06-06' WHERE artist = 'The Algorithm' AND "name" = 'Octopus4';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Dillinger Escape Plan' AND "name" = 'Dillinger Escape Plan';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2013-10-08' WHERE artist = 'Korn' AND "name" = 'Never Never: The Remixes';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2014-12-09' WHERE artist = 'In Flames' AND "name" = 'Clayman (Reissue 2014)';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2014-11-24' WHERE artist = 'In Flames' AND "name" = 'Soundtrack To Your Escape (Reissue 2014)';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2014-10-20' WHERE artist = 'In Flames' AND "name" = 'Come Clarity (Re-issue 2014)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2007-09' WHERE artist = 'Арда' AND "name" = 'Море Исчезающих Времён';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006' WHERE artist = 'Korn' AND "name" = 'MTV Unplugged';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2014-10-20' WHERE artist = 'In Flames' AND "name" = 'A Sense Of Purpose (Re-issue 2014)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2010-01-14' WHERE artist = 'Фактор Страха' AND "name" = 'Мёртвые Сны';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2010-04-30' WHERE artist = 'Emergency Gate' AND "name" = 'The Nemesis Construct';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2010-10-26' WHERE artist = 'Amatory' AND "name" = 'Инстинкт Обреченных';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2014-11-24' WHERE artist = 'In Flames' AND "name" = 'Reroute To Remain (Reissue 2014)';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2016-05-13' WHERE artist = 'Avatar' AND "name" = 'Feathers & Flesh';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dead by April' AND "name" = 'Within My Heart (Single)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Amatory' AND "name" = 'Книга Мёртвых';
UPDATE "public"."Album" SET "numberOfTracks" = 3 WHERE artist = 'Limp Bizkit' AND "name" = 'My Way';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2010-04-01' WHERE artist = 'Эпидемия' AND "name" = 'Дорога Домой';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2017-10-20' WHERE artist = 'Cyhra' AND "name" = 'Letters To Myself';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2010-05-14' WHERE artist = 'Digimortal' AND "name" = 'Парад Мёртвых Планет';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1997-04' WHERE artist = 'Slo Burn' AND "name" = 'Amusing the Amazing';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Queens of the Stone Age' AND "name" = 'Kyuss/Queens Of The Stone Age';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2005-10-05' WHERE artist = 'Abramis Brama' AND "name" = 'När Tystnaden Har Lagt Sig';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Queens of the Stone Age' AND "name" = 'Kyuss / Queens Of The Stone Age';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1999-10-11' WHERE artist = 'Survivor' AND "name" = 'Empires';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2003' WHERE artist = 'Toto' AND "name" = 'Lovy Metal 3';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2012-04' WHERE artist = 'Him' AND "name" = 'LIVE IN HEL. [EP]';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'Ultra Rare Trax, Volume 1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'Razorblade Romance (bonus disc)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'Deep Shadows & Brilliant Highlights';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'The Single Collection (disc 9: In Joy and Sorrow)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2001-07' WHERE artist = 'Him' AND "name" = 'Deep Shadows and Brilliant Highlights (Advance Album) (Promo Edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'Alternative Collection';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'The Single Collection (disc 4: Join Me)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2001-10-15' WHERE artist = 'Gregorian' AND "name" = 'Masters of Chant Chapter II';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2001' WHERE artist = 'Him' AND "name" = 'Heartache Every Moment & Close to the Flame EP';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'The Single Collection (disc 2: Wicked Game)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = '2004-05-29: Landgraaf, The Netherlands';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'The Single Collection (disc 5: Right Here in My Arms)';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2002-01-14' WHERE artist = 'Him' AND "name" = 'Heartache Every Moment';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'Live & Undercover';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'Screamworks: Love In Theory & Practice (Limited Edition 2Xcd)';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2003' WHERE artist = 'Him' AND "name" = 'The Sacrament Vol.2';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2004-03-15' WHERE artist = 'Him' AND "name" = 'And Love Said No: The Greatest Hits 1997-2004';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'And Love Said No - Greatest Hits 1997 - 2004';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2008-04-29' WHERE artist = 'Him' AND "name" = 'Digital Versatile Doom Live at The Orpheum Theater XXXVII A.S.';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2004-06-01' WHERE artist = 'The 69 Eyes' AND "name" = 'Lost Boys';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2004-06-16' WHERE artist = 'For My Pain...' AND "name" = 'Killing Romance';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'And Love Said No: Greatest Hits 1997 - 2004';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'The Single Collection (disc 7: Gone With the Sin)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2005-11' WHERE artist = 'Svenia' AND "name" = 'Black Heart';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1995' WHERE artist = 'Him' AND "name" = 'This Is Only the Beginning';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'The Single Collection (disc 3: When Love and Death Embrace)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2005-09-26' WHERE artist = 'H.I.M.' AND "name" = 'Dark Light';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Negative' AND "name" = 'Sweet And Deceitful';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'The Single Collection (disc 1: It''s All Tears (Drown in This Love))';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = '2003.04.14 - Love Metal [Limited Edition]';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'Wings of a butterfly Vol. 2';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2006' WHERE artist = 'Him' AND "name" = 'Uneasy Listening Vol. 1';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2007-04-25' WHERE artist = 'Him' AND "name" = 'Uneasy Listening Vol. 2';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007-09-07' WHERE artist = 'Him' AND "name" = 'Venus Doom (Deluxe Limited Edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = '2004-06-18: Hultsfred, Sweden';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Various Artists' AND "name" = 'Love Metal';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'Unplugged and More';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'Tears On Tape (BONUS)';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '1999' WHERE artist = 'Him' AND "name" = 'It''s All Tears (Drown In This Love)'
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = '2000.03.29 - Arena, Berlin, Germany';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1990' WHERE artist = 'Various Artists' AND "name" = 'Heavy Metal Love';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2000-01-24' WHERE artist = 'Him' AND "name" = 'Razorblade Romance';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2003-04-11' WHERE artist = 'Him' AND "name" = 'Love Metal';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2001-08-27' WHERE artist = 'Him' AND "name" = 'Deep Shadows And Brilliant Highlights';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1997-11-03' WHERE artist = 'Him' AND "name" = 'Greatest Lovesongs Vol. 666';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2004' WHERE artist = 'Him' AND "name" = 'And Love Said No';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2007-09' WHERE artist = 'Him' AND "name" = 'Venus Doom';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2009' WHERE artist = 'Him' AND "name" = 'Screamworks: Love In Theory And Practice';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2013-04-26' WHERE artist = 'Him' AND "name" = 'Tears On Tape';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1996-10' WHERE artist = 'Him' AND "name" = '666 Ways to Love: Prologue';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2000' WHERE artist = 'Him' AND "name" = 'Right Here In My Arms';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2000' WHERE artist = 'Him' AND "name" = 'Gone With The Sin';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2010-12-07' WHERE artist = 'Him' AND "name" = 'SWRMXS';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '1997-06' WHERE artist = 'Him' AND "name" = 'When Love And Death Embrace';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2012-09-07' WHERE artist = 'Him' AND "name" = 'Strange World';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2005-08-02' WHERE artist = 'Him' AND "name" = 'Wings of A Butterfly';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '1998-09-28' WHERE artist = 'Him' AND "name" = 'Wicked Game';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2006-02-24' WHERE artist = 'Him' AND "name" = 'Killing Loneliness';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2001' WHERE artist = 'Him' AND "name" = 'In Joy And Sorrow';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2012-10-26' WHERE artist = 'Him' AND "name" = 'XX-Two Decades of Love Metal';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2003-05-05' WHERE artist = 'Him' AND "name" = 'Buried Alive by Love';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2003-06-27' WHERE artist = 'Him' AND "name" = 'The Sacrament';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2004-03' WHERE artist = 'Him' AND "name" = 'Solitary Man';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2001-07' WHERE artist = 'Him' AND "name" = 'Pretending';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1999' WHERE artist = 'Him' AND "name" = 'Join Me';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'To Die For' AND "name" = 'All Eternity';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2000' WHERE artist = 'Him' AND "name" = 'Poison Girl';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2009-06-21' WHERE artist = 'Sea of Despair' AND "name" = 'Море Отчаяния';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'After the Burial' AND "name" = 'Forgiving A Future Self';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2010-11-22' WHERE artist = 'Your Memorial' AND "name" = 'Atonement';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017' WHERE artist = 'Like Moths to Flames' AND "name" = 'Nowhere Left To Sink';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2012-06-06' WHERE artist = 'Architects' AND "name" = 'Daybreaker (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018' WHERE artist = 'Annisokay' AND "name" = 'Coma Blue';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2018-12-14' WHERE artist = 'Currents' AND "name" = 'I Let the Devil In';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2009' WHERE artist = 'Conducting From The Grave' AND "name" = 'When Legends Become Dust';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2019-04-24' WHERE artist = 'Volumes' AND "name" = 'Coming Clean';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2018-04-20' WHERE artist = 'Shields' AND "name" = 'Life in Exile';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017' WHERE artist = 'Kehlani' AND "name" = 'Do U Dirty';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dimmu Borgir' AND "name" = 'Stormblåst (bonus disc)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Ghoul' AND "name" = 'We Came for the Dead';
UPDATE "public"."Album" SET "numberOfTracks" = 26, "date" = '2003-11-03' WHERE artist = 'Napalm Death' AND "name" = 'Punishment In Capitals';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2004-05-28' WHERE artist = 'Thy Disease' AND "name" = 'Neurotic World of Guilt';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2009-03-12' WHERE artist = 'General Surgery' AND "name" = 'Corpus In Extremis: Analysing Necrocriticism';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2009-10-30' WHERE artist = 'Milking the Goatmachine' AND "name" = 'Back From The Goats...A Goateborg Fairy Tale';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2010-06-08' WHERE artist = 'Clinging To The Trees of a Forest Fire' AND "name" = 'Songs of Ill Hope and Desperation';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2011-01-18' WHERE artist = 'Abacinate' AND "name" = 'Genesis';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nails' AND "name" = 'Split';
UPDATE "public"."Album" SET "numberOfTracks" = 27, "date" = '2014-10-31' WHERE artist = 'Vulvodynia' AND "name" = 'Cognizant Castigation';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2015-07-31' WHERE artist = 'Vulvodynia' AND "name" = 'Finis Omnium Ignorantiam';
UPDATE "public"."Album" SET "numberOfTracks" = 25, "date" = '2015-02-10' WHERE artist = 'Exhumed' AND "name" = 'Gore Metal - A Necrospective';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2017-09-22' WHERE artist = 'Implore' AND "name" = 'Subjugate';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2010-11-26' WHERE artist = 'Milking the Goatmachine' AND "name" = 'Seven..A Dinner For One';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-07-05' WHERE artist = 'Aborted' AND "name" = 'Squalor Opera';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Circle of Dead Children' AND "name" = 'PSALMS OF THE GRAND DESTROYER';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Aborted' AND "name" = 'Goremageddon';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1986' WHERE artist = '7Seconds' AND "name" = 'Walk Together, Rock Together';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1996' WHERE artist = 'Negative FX' AND "name" = 'Negative FX & Last Rights';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1988' WHERE artist = 'Project X' AND "name" = 'Straight Edge Revenge';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1995' WHERE artist = 'Excessive Force' AND "name" = 'In Your Blood';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '1988' WHERE artist = 'Up Front' AND "name" = 'Spirit';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2001' WHERE artist = 'Champion' AND "name" = 'Come Out Swinging';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2004' WHERE artist = 'Guns Up!' AND "name" = 'All This Is';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Your Demise' AND "name" = 'A New Ending';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2005' WHERE artist = 'xTyrantx' AND "name" = 'Welcome To Hell';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2007-11-08' WHERE artist = 'Balaclava' AND "name" = 'Creativity';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2010-10' WHERE artist = 'ПУРГЕН' AND "name" = 'Бог Рабов';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2013' WHERE artist = 'Freedom' AND "name" = 'Pay The Price';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2014-07-29' WHERE artist = 'FUCKING WEREWOLF ASSO' AND "name" = 'WHY DO YOU LOVE ME SATAN?';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2017-10-13' WHERE artist = 'Stick to Your Guns' AND "name" = 'True View';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2018-03-20' WHERE artist = 'True Love' AND "name" = 'The Pact';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2016-11' WHERE artist = 'Odd Man Out' AND "name" = 'CCHC';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '1999' WHERE artist = '7Seconds' AND "name" = 'Good to Go';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2012' WHERE artist = 'Disengage' AND "name" = 'Expressions';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2018-05-04' WHERE artist = 'Year Of The Knife' AND "name" = 'First State Aggression';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1999' WHERE artist = 'In My Eyes' AND "name" = 'Nothing to Hide';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2017' WHERE artist = 'Year Of The Knife' AND "name" = 'Ultimate Disease';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2014' WHERE artist = 'Danger' AND "name" = 'Danger';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1983' WHERE artist = 'Steeler' AND "name" = 'Steeler';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1988-05' WHERE artist = 'Pantera' AND "name" = 'Power Metal';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Vixen' AND "name" = 'Rev It Up!';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2003-10-07' WHERE artist = 'Mötley Crüe' AND "name" = 'Classic Motley Crue';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2018' WHERE artist = 'Whitesnake' AND "name" = '1987 (2018 Remaster)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2016-10-04' WHERE artist = 'Bon Jovi' AND "name" = 'This House Is Not For Sale';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2011-07-21' WHERE artist = 'Little Dragon' AND "name" = 'Ritual Union';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Danzig' AND "name" = 'How The Gods Kill';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Within Temptation' AND "name" = 'Black Symphony Disc 1';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-03-11' WHERE artist = 'Arion' AND "name" = 'At The Break Of Dawn (feat. Elize Ryd)';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2016' WHERE artist = 'Bring Me the Horizon' AND "name" = 'Drown (Live from Maida Vale)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-01' WHERE artist = 'Thy Art Is Murder' AND "name" = 'No Absolution';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2011-10-13' WHERE artist = 'Korn' AND "name" = 'Narcissistic Cannibal (feat. Skrillex & Kill The Noise)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1992-11-10' WHERE artist = 'Biohazard' AND "name" = 'Urban Discipline';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1999-07-15' WHERE artist = '40 Below Summer' AND "name" = 'Sideshow Freaks';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Linkin Park' AND "name" = 'Project Revolution';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2014-08-01' WHERE artist = 'Limp Bizkit' AND "name" = 'Endless Slaughter';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2004-06-22' WHERE artist = 'Zebrahead' AND "name" = 'Waste of MFZB';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Hollywood Undead' AND "name" = 'Hollywood Undead';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-06-01' WHERE artist = 'Hollywood Undead' AND "name" = 'Gotta Let Go';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2015-03-31' WHERE artist = 'Hollywood Undead' AND "name" = 'Day of the Dead (Deluxe Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2015-08-21' WHERE artist = 'P.O.D.' AND "name" = 'The Awakening';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Skindred' AND "name" = 'Babylon (Revised Online Music)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'P.O.D.' AND "name" = 'Greatest Hits: The Atlantic Years';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Hollywood Undead' AND "name" = 'Swan Songs (Edited Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2011-04-05' WHERE artist = 'Hollywood Undead' AND "name" = 'American Tragedy (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2016-02-26' WHERE artist = 'From Ashes to New' AND "name" = 'Day One (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 25, "date" = '2010' WHERE artist = 'Noize MC' AND "name" = 'The Greatest Hits vol.2';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2005-11-24' WHERE artist = 'Кирпичи' AND "name" = 'Царский альбомъ';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2018-10-11' WHERE artist = 'Anacondaz' AND "name" = 'Я Тебя Никогда';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2013-01-08' WHERE artist = 'Hollywood Undead' AND "name" = 'Notes From The Underground - Unabridged';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-10-14' WHERE artist = 'Sabaton' AND "name" = 'In the Army Now';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2012-01' WHERE artist = 'Dreamstate' AND "name" = 'Evolution';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = '[unknown]';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1997' WHERE artist = 'Section 5' AND "name" = 'They think it''s all over';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1992' WHERE artist = 'Skrewdriver' AND "name" = 'Freedom what Freedom';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = '666 corpses with extracted organs lying on bed filled with blood' AND "name" = 'Hellfire in the Asshole';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1997-07' WHERE artist = 'Solefald' AND "name" = 'The Linear Scaffold';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2017-11-17' WHERE artist = 'The Body' AND "name" = 'Ascending a Mountain of Heavy Light';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2002-04-20' WHERE artist = 'Ram-Zet' AND "name" = 'Escape';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2003-11-01' WHERE artist = 'Unexpect' AND "name" = 'WE, Invaders';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2004-01-24' WHERE artist = 'Fantômas' AND "name" = 'Delìrivm Còrdia';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2008-07-19' WHERE artist = 'Akphaezya' AND "name" = 'Anthology II';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2005-10-31' WHERE artist = 'Sigh' AND "name" = 'Gallows Gallery';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2005-09-26' WHERE artist = 'Kadenzza' AND "name" = 'The Second Renaissance';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Diablo Swing Orchestra' AND "name" = 'Sing-Along Songs For The Damned & Delirious';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Diablo Swing Orchestra' AND "name" = 'Sing Along Songs for the Damne';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Diablo Swing Orchestra' AND "name" = 'Sing-Along Songs for the Damned and Delirious';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Solefald' AND "name" = 'Norron Livskunst';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Diablo Swing Orchestra' AND "name" = 'Pandora''s Pinata';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Diablo Swing Orchestra' AND "name" = 'Pandoras Pinata';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2013-02-22' WHERE artist = 'Terra Tenebrosa' AND "name" = 'The Purging';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2016-05-13' WHERE artist = 'Avatar' AND "name" = 'Feathers & Flesh (Bonus Track Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2015-02-04' WHERE artist = 'sukekiyo' AND "name" = 'VITIUM';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2005-10-25' WHERE artist = 'Buckethead & Friends' AND "name" = 'Enter The Chicken';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2011-08-03' WHERE artist = 'DIR EN GREY' AND "name" = 'Dum Spiro Spero';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2016-04-08' WHERE artist = 'ZHRINE' AND "name" = 'Unortheta';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Blut aus Nord' AND "name" = '777 Sect(s)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2005-10-18' WHERE artist = 'Solefald' AND "name" = 'Red for Fire: An Icelandic Odyssey, Part 1';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1995-10' WHERE artist = 'Ved Buens Ende' AND "name" = 'Written In Waters';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2008-11-01' WHERE artist = 'Black Autumn' AND "name" = 'Rivers Of Dead Leaves';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2015-04-14' WHERE artist = 'Bosse-de-Nage' AND "name" = 'All Fours';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2015-05-15' WHERE artist = 'Hypothermia' AND "name" = 'Svartkonst';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2015-03-17' WHERE artist = 'Pyramids' AND "name" = 'A Northern Meadow';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2016-01-31' WHERE artist = 'Violet Cold' AND "name" = 'Magic Night';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2016-08-26' WHERE artist = 'An Autumn for Crippled Children' AND "name" = 'Eternal';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2018-02-16' WHERE artist = 'Harakiri for the Sky' AND "name" = 'Arson';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2017-09-22' WHERE artist = 'Satyricon' AND "name" = 'Deep Calleth Upon Deep';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2018-04-27' WHERE artist = 'Totalselfhatred' AND "name" = 'Solitude';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2015-09-19' WHERE artist = 'Deluge' AND "name" = 'Æther';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2018-04-13' WHERE artist = 'møl' AND "name" = 'Jord';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2011-10-28' WHERE artist = 'Lantlôs' AND "name" = 'Agape';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2013-03-01' WHERE artist = 'Ash Borer' AND "name" = 'Bloodlands';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2020-09-25' WHERE artist = 'Svalbard' AND "name" = 'When I Die, Will I Get Better?';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-05-23' WHERE artist = 'Myrkur' AND "name" = 'Två Konungabarn';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2011-05-20' WHERE artist = 'Peste Noire' AND "name" = 'L''Ordure à l''état Pur';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Harakiri for the Sky' AND "name" = 'III: Trauma';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Def Leppard' AND "name" = 'High N Dry';
-- UPDATE "public"."Album" SET "numberOfTracks" = , "date" =  WHERE artist =  AND "name" =
-- UPDATE "public"."Album" SET "numberOfTracks" = , "date" =  WHERE artist =  AND "name" =
-- UPDATE "public"."Album" SET "numberOfTracks" = , "date" =  WHERE artist =  AND "name" =
-- UPDATE "public"."Album" SET "numberOfTracks" = , "date" =  WHERE artist =  AND "name" =
-- UPDATE "public"."Album" SET "numberOfTracks" = , "date" =  WHERE artist =  AND "name" =
-- UPDATE "public"."Album" SET "numberOfTracks" = , "date" =  WHERE artist =  AND "name" =
-- UPDATE "public"."Album" SET "numberOfTracks" = , "date" =  WHERE artist =  AND "name" =
-- UPDATE "public"."Album" SET "numberOfTracks" = , "date" =  WHERE artist =  AND "name" =
-- UPDATE "public"."Album" SET "numberOfTracks" = , "date" =  WHERE artist =  AND "name" =
-- UPDATE "public"."Album" SET "numberOfTracks" = , "date" =  WHERE artist =  AND "name" =
-- UPDATE "public"."Album" SET "numberOfTracks" = , "date" =  WHERE artist =  AND "name" =
-- UPDATE "public"."Album" SET "numberOfTracks" = , "date" =  WHERE artist =  AND "name" =
-- UPDATE "public"."Album" SET "numberOfTracks" = , "date" =  WHERE artist =  AND "name" =
-- UPDATE "public"."Album" SET "numberOfTracks" = , "date" =  WHERE artist =  AND "name" =
-- UPDATE "public"."Album" SET "numberOfTracks" = , "date" =  WHERE artist =  AND "name" =
-- UPDATE "public"."Album" SET "numberOfTracks" = , "date" =  WHERE artist =  AND "name" =
-- UPDATE "public"."Album" SET "numberOfTracks" = , "date" =  WHERE artist =  AND "name" =
-- UPDATE "public"."Album" SET "numberOfTracks" = , "date" =  WHERE artist =  AND "name" =
-- UPDATE "public"."Album" SET "numberOfTracks" = , "date" =  WHERE artist =  AND "name" =
-- UPDATE "public"."Album" SET "numberOfTracks" = , "date" =  WHERE artist =  AND "name" =
-- UPDATE "public"."Album" SET "numberOfTracks" = , "date" =  WHERE artist =  AND "name" =
