UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2017-12-01' WHERE artist = 'U2' AND "name" = 'Songs of Experience (Deluxe Edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Poison' AND "name" = 'Open Up And Say.. Ahh!';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1988-08-22' WHERE artist = 'Rata Blanca' AND "name" = 'Rata Blanca';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2002-02-04' WHERE artist = 'Battlelore' AND "name" = '...Where the Shadows Lie';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Battlelore' AND "name" = 'Where the Shadows Lie';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-04-11' WHERE artist = 'Ravenface' AND "name" = 'Fighters';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-11-22' WHERE artist = 'Ravenface' AND "name" = 'Tyrants and Kings';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1985-03-27' WHERE artist = 'Bon Jovi' AND "name" = '7800° Fahrenheit';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1987-07-07' WHERE artist = 'Faster Pussycat' AND "name" = 'Faster Pussycat';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2009-09-03' WHERE artist = 'Europe' AND "name" = 'New Love In Town';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1989-01-27' WHERE artist = 'Warrant' AND "name" = 'Dirty Rotten Filthy Stinking Rich';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1991-07-09' WHERE artist = 'Kix' AND "name" = 'Hot Wire';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2009-06-03' WHERE artist = 'Hardcore Superstar' AND "name" = 'Beg For It';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-11-17' WHERE artist = 'Santa Cruz' AND "name" = 'Drag Me Down';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2008' WHERE artist = 'Here Comes the Kraken' AND "name" = 'Demo 2008';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2009-09-05' WHERE artist = 'Neverending War' AND "name" = 'Muted';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2010-10-22' WHERE artist = 'Ease of Disgust' AND "name" = 'Chaos';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2010-11-23' WHERE artist = 'Applaud The Impaler' AND "name" = 'Anthropophagi';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2010-10-22' WHERE artist = 'Ichor' AND "name" = 'Benthic Horizon';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2011-11-01' WHERE artist = 'Boris the Blade' AND "name" = 'Tides Of Damnation';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2013-11-01' WHERE artist = 'Dissonance in Design' AND "name" = 'Sentient';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2013-06-14' WHERE artist = 'Science of Sleep' AND "name" = 'Exhaust';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Thy Art Is Murder' AND "name" = 'Infinite Death - EP';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2013-10-25' WHERE artist = 'The Raven Autarchy' AND "name" = 'Kaonashi';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2019-09-11' WHERE artist = 'Infant Annihilator' AND "name" = 'The Battle Of Yaldabaoth';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2015-04-30' WHERE artist = 'The Raven Autarchy' AND "name" = 'The Obscene Deliverance';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Chelsea Grin' AND "name" = 'Self Inflicted (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2016-07-29' WHERE artist = 'Infant Annihilator' AND "name" = 'The Elysian Grandeval Galeriarch';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2007' WHERE artist = 'Thy Art Is Murder' AND "name" = 'This Hole is Not Deep Enough';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2003-09-29' WHERE artist = 'The Killers' AND "name" = 'Mr Brightside';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1998-09-14' WHERE artist = 'Океан Ельзи' AND "name" = 'Там, де нас нема';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Океан Ельзи' AND "name" = 'Янанебiбув';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2000-09-04' WHERE artist = 'Illuminate' AND "name" = 'Ein neuer Tag';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Океан Ельзи' AND "name" = 'Суперсиметрiя';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = '5''nizza' AND "name" = '5''nizza';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2006-04-13' WHERE artist = 'С.к.а.й.' AND "name" = 'Те, Що ТреБа';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2006-04' WHERE artist = 'Катя Chilly' AND "name" = 'Я - молодая';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2009-04-23' WHERE artist = 'Фліт' AND "name" = 'Однозначно';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Esthetic Education' AND "name" = 'Esthetic Education';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '2006-04' WHERE artist = 'Various Artists' AND "name" = 'Music For A Changing World';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '2009-04-23' WHERE artist = 'Друга Ріка' AND "name" = 'Best 1999-2009';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-12-04' WHERE artist = 'Крихітка' AND "name" = 'Без імені';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2011-01-31' WHERE artist = 'Сергей Бабкин' AND "name" = 'Снаружи и внутри';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2010-11-21' WHERE artist = 'Вера Брежнева' AND "name" = 'Любовь Спасёт Мир';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2008' WHERE artist = 'Ані Лорак' AND "name" = 'Shady Lady';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Ані Лорак' AND "name" = 'Unreleased';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2010-11-24' WHERE artist = 'С.к.а.й.' AND "name" = '!';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Валентин Стрыкало' AND "name" = 'Смирись и расслабься!';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-03-03' WHERE artist = 'Vivienne Mort' AND "name" = 'Пташечка';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2014-04' WHERE artist = 'Egor Grushin' AND "name" = 'Dominicano';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2014-05-15' WHERE artist = 'Onuka' AND "name" = 'Look';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2017-11-22' WHERE artist = 'daKooka' AND "name" = 'Гордо';
UPDATE "public"."Album" SET "numberOfTracks" = 25, "date" = '2016-01-24' WHERE artist = 'Один В Каное' AND "name" = 'Один в каное';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2015-09-22' WHERE artist = 'Христина Соловій' AND "name" = 'Жива вода';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2015-12' WHERE artist = 'Тартак' AND "name" = 'Ввічність';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2017-04-07' WHERE artist = 'The Hardkiss' AND "name" = 'Perfection Is a Lie';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2010-03-10' WHERE artist = 'Океан Ельзи' AND "name" = 'Dolce Vita';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2013-05-15' WHERE artist = 'Океан Ельзи' AND "name" = 'Земля';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2003-03-12' WHERE artist = 'Океан Ельзи' AND "name" = 'Суперсиметрія';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2013-10-20' WHERE artist = 'Валентин Стрыкало' AND "name" = 'Часть чего-то большего';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2012-02-24' WHERE artist = 'Валентин Стрыкало' AND "name" = 'Смирись и расслабься';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2005' WHERE artist = '5''nizza' AND "name" = 'O5';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2016-10-14' WHERE artist = 'Валентин Стрыкало' AND "name" = 'Развлечение';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2018-01-29' WHERE artist = 'ПОШЛАЯ МОЛЛИ' AND "name" = 'Грустная девчонка с глазами как у собаки';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2016-05-19' WHERE artist = 'Океан Ельзи' AND "name" = 'Без меж';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Вера Брежнева' AND "name" = 'New';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2010' WHERE artist = 'Оркестр Че' AND "name" = 'Предчувствие нулевого года';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2008' WHERE artist = 'ТіК' AND "name" = 'Тихий';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2007' WHERE artist = 'Тінь Сонця' AND "name" = 'Полум''яна рута';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-01-25' WHERE artist = 'Vivienne Mort' AND "name" = 'Ти забув про мене';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2011' WHERE artist = 'O.Torvald' AND "name" = 'В Тобі';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2003' WHERE artist = 'Тартак' AND "name" = 'Сиситема Нервiв';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2006-10-01' WHERE artist = '2sleepy' AND "name" = '[laridae029] fragments of sleep';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007-09-22' WHERE artist = 'Інкунабула' AND "name" = 'НеВиДаНе';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2014-10-15' WHERE artist = 'Onuka' AND "name" = 'ONUKA';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2016-11-25' WHERE artist = 'SunSay' AND "name" = 'Выше головы';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2016-11-11' WHERE artist = 'Грибы' AND "name" = 'Дом На Колесах ч.1';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2006' WHERE artist = 'Юркеш' AND "name" = 'Ой!';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2019-07-05' WHERE artist = 'Время и стекло' AND "name" = 'Vislovo';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2010' WHERE artist = 'Дахабраха' AND "name" = 'Light';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2004' WHERE artist = 'Тартак' AND "name" = 'МУЗИЧНИЙ ЛИСТ ЩАСТЯ (2004)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2015-04-28' WHERE artist = 'Вера Брежнева' AND "name" = 'VERVERA';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2006' WHERE artist = 'Бурдон' AND "name" = 'Re:Karpatia';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2006' WHERE artist = 'Тартак' AND "name" = 'СЛЬОЗИ ТА СОПЛІ (2006)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2013-08-16' WHERE artist = 'Ані Лорак' AND "name" = 'Забирай';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1988-10-01' WHERE artist = 'Sieges Even' AND "name" = 'Lifecycle';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1989-11-06' WHERE artist = 'Watchtower' AND "name" = 'Control And Resistance';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Meshuggah' AND "name" = '17 obZen';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1995-04-11' WHERE artist = 'Meshuggah' AND "name" = 'Selfcaged';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2000-06' WHERE artist = 'Undying' AND "name" = 'The Whispered Lies Of Angels';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2013-05-15' WHERE artist = 'Hybrid' AND "name" = 'Angst';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Meshuggah' AND "name" = '15 Catch Thirtythree';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2006-09-19' WHERE artist = 'Twisted Into Form' AND "name" = 'Then Comes Affliction to Awaken the Dreamer ';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2006-08-08' WHERE artist = 'Lamb of God' AND "name" = 'Walk With Me In Hell';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2009-03-17' WHERE artist = 'Into The Moat' AND "name" = 'The Campaign';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2015-05-19' WHERE artist = 'All Tomorrows' AND "name" = 'Sol Agnates';
UPDATE "public"."Album" SET "numberOfTracks" = 24, "date" = '2016-11-18' WHERE artist = 'A Sense of Gravity' AND "name" = 'Atrament';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2016-11-21' WHERE artist = 'Paul Wardingham' AND "name" = 'Spiritual Machines';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-07-13' WHERE artist = 'Architects' AND "name" = 'Doomsday (Piano Reprise)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'TesseracT' AND "name" = 'Early Demos';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2006' WHERE artist = 'Meshuggah' AND "name" = 'Nothing (Re-release)';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2004-04-20' WHERE artist = 'Buckethead' AND "name" = 'Cuckoo Clocks Of Hell';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Architects' AND "name" = 'Architects';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Meshuggah' AND "name" = '20 Koloss';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2013-03-13' WHERE artist = 'Stories' AND "name" = 'Void';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2012' WHERE artist = 'Aurora' AND "name" = 'Aurora';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Molotov Solution' AND "name" = 'Self Titled';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-07-17' WHERE artist = 'Born of Osiris' AND "name" = 'Silence the Echo';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2010-02-22' WHERE artist = 'The Argent Dawn' AND "name" = 'A Blank Eternity';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Martyr Defiled' AND "name" = 'Martyr Defiled';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2011-09' WHERE artist = 'As They Burn' AND "name" = 'Aeon''s War';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2011-10-29' WHERE artist = 'Abiotic' AND "name" = 'A Universal Plague';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2012-03-01' WHERE artist = 'Slice the Cake' AND "name" = 'The Man With No Face';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2014-03-06' WHERE artist = 'Assemble the Chariots' AND "name" = 'World Architects';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2010-09-10' WHERE artist = 'Price of Blood' AND "name" = 'City Of Diamonds (EP)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Chelsea Grin' AND "name" = 'Evolve (EP)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Born of Osiris' AND "name" = 'Tomorrow We Die ∆live';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2014-03-31' WHERE artist = 'The Healing' AND "name" = 'Transcendence';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2004' WHERE artist = 'Оркестр Че' AND "name" = 'Золотой миллениум';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '1984-05' WHERE artist = 'Corrosion of Conformity' AND "name" = 'Eye for An Eye';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1985-11' WHERE artist = 'Carnivore' AND "name" = 'Carnivore';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1986-10-07' WHERE artist = 'Nuclear Assault' AND "name" = 'Game Over';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1987-09' WHERE artist = 'Carnivore' AND "name" = 'Retaliation';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2001-06-20' WHERE artist = 'Suicidal Tendencies' AND "name" = 'Friends & Family 2';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1997' WHERE artist = 'Suicidal Tendencies' AND "name" = 'Friends & Family';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1989-01-31' WHERE artist = 'Leeway' AND "name" = 'Born To Expire';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2001' WHERE artist = 'Spazztic Blurr' AND "name" = 'Spazztic Blurr';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1990-03-12' WHERE artist = 'Prong' AND "name" = 'Beg To Differ';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2000' WHERE artist = 'Distemper' AND "name" = 'Мы сегодня с Баем';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1989-06' WHERE artist = 'The Exploited' AND "name" = 'Live Lewd Lust';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Suicidal Tendencies' AND "name" = 'Epic Escape';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1989-06-29' WHERE artist = 'Slipknot' AND "name" = 'Slipknot EP';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2003-01-27' WHERE artist = 'Municipal Waste' AND "name" = 'Waste ''em All';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1989-10-17' WHERE artist = 'Suicidal Tendencies' AND "name" = 'Controlled by Hatred/Feel Like Shit...Deja-Vu';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2004' WHERE artist = 'Cancer Bats' AND "name" = 'Cancer Bats';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2006-05' WHERE artist = 'Ratos De Porão' AND "name" = 'Homem Inimigo do Homem';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1992-05-12' WHERE artist = 'Cro-Mags' AND "name" = 'Alpha Omega';
UPDATE "public"."Album" SET "numberOfTracks" = 23, "date" = '1985-03' WHERE artist = 'D.R.I.' AND "name" = 'Dealing With It!';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '1985-08-30' WHERE artist = 'S.O.D.' AND "name" = 'Speak English or Die';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2008' WHERE artist = 'Agnostic Front' AND "name" = 'Warriors [Tour Edition]';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2018-11-16' WHERE artist = 'Mindforce' AND "name" = 'Excalibur';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Slipknot' AND "name" = 'Self Titled Ep';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2020-04-29' WHERE artist = 'Mindforce' AND "name" = 'Swingin Swords, Choppin Lords';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2001' WHERE artist = 'Municipal Waste' AND "name" = 'Municipal Waste';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1995' WHERE artist = 'Dmize' AND "name" = 'Backlash';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2020-09-18' WHERE artist = 'Plague Years' AND "name" = 'Circle of Darkness';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2006-03-15' WHERE artist = 'Crow' AND "name" = 'Bloody Tear';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2009-07-06' WHERE artist = 'Urfaust' AND "name" = 'Einsiedler';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006-10-27' WHERE artist = 'Negură Bunget' AND "name" = 'Om';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1995-04' WHERE artist = 'In The Woods...' AND "name" = 'HEart Of The Ages';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Plasmarifle' AND "name" = 'While You Were Sleeping (The World Forever Changed in an Instant)';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2008-07-19' WHERE artist = 'Destroy The Colossus' AND "name" = 'Centuries';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-07-21' WHERE artist = 'Thy Art Is Murder' AND "name" = 'The Son of Misery';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Infant Annihilator' AND "name" = 'The Elysian Grandeval Galeriarch';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Napalm Death' AND "name" = 'Apex Predator-Easy Meat';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1996-12' WHERE artist = 'Fortress Under Siege' AND "name" = 'Fortress Under Siege';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1996-11-11' WHERE artist = 'Rough Silk' AND "name" = 'Circle of Pain...Or: The Secret Lies of Timekeeping';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2002-11-20' WHERE artist = 'Sonata Arctica' AND "name" = 'Songs of Silence';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Stratovarius' AND "name" = 'Elements, Part 1';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2005-08-24' WHERE artist = 'Vanishing Point' AND "name" = 'Embrace the Silence';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Kamelot' AND "name" = 'Metal Sampler Vol. 3';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Kamelot' AND "name" = 'Metal Sampler Vol 2';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2006-03-24' WHERE artist = 'Rage' AND "name" = 'Speak Of The Dead';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007-06-05' WHERE artist = 'Viper' AND "name" = 'All My Life';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '1997-05-20' WHERE artist = 'Iced Earth' AND "name" = 'Days of Purgatory';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2010-06-18' WHERE artist = 'Ascension' AND "name" = 'Alchemy';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2007' WHERE artist = 'Amon Amarth' AND "name" = 'The Crusher - Reissue';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2010-11-19' WHERE artist = 'Sebastien' AND "name" = 'Tears of White Roses';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2011-07-31' WHERE artist = 'CROSS VEIN' AND "name" = 'Moon Addict';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2011-01-31' WHERE artist = 'Hypersonic' AND "name" = 'Fallen melodies';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dawn of Destiny' AND "name" = 'DAWN OF DESTINY - begins... shark 2034';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2013-01-21' WHERE artist = 'Achillea' AND "name" = 'Fight or Fall';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2008' WHERE artist = 'Судный День' AND "name" = 'Черное Пророчество';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2017-11-17' WHERE artist = 'Terra Atlantica' AND "name" = 'A City Once Divine';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2010-09-24' WHERE artist = 'Soulspell' AND "name" = 'Labyrinth of Truths';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2004-11' WHERE artist = 'Human Factor' AND "name" = 'Unleashed';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2011-05-01' WHERE artist = 'Lightning' AND "name" = 'Brave Heart Re-birth';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Icebound' AND "name" = 'IceBound Demo';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Devil Wears Prada' AND "name" = 'Patterns Of The Horizon';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2005-11-01' WHERE artist = 'The Hope of Change' AND "name" = 'Hourglass';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2007-07-24' WHERE artist = 'Once Nothing' AND "name" = 'Earthmover';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2013-11-25' WHERE artist = 'Fit for a King' AND "name" = 'Descendants - Redux';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'As I Lay Dying' AND "name" = 'Music';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-10-13' WHERE artist = 'Phinehas' AND "name" = 'Know Death; Know Forever';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-10-27' WHERE artist = 'Phinehas' AND "name" = 'Hell Below';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2015-07-10' WHERE artist = 'Phinehas' AND "name" = 'Till The End';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Devil Wears Prada' AND "name" = 'With Roots Above And Branches';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2016-10-07' WHERE artist = 'The Devil Wears Prada' AND "name" = 'Transit Blues';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Now I See' AND "name" = 'Now E P';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2008-10-22' WHERE artist = 'The Devil Wears Prada' AND "name" = 'Plagues (Re-Release)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2007-11-06' WHERE artist = 'Demon Hunter' AND "name" = 'Storm The Gates Of Hell (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2010-01-01' WHERE artist = 'Underoath' AND "name" = 'Ø (Disambiguation) [Deluxe Edition]';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2015-06-29' WHERE artist = 'August Burns Red' AND "name" = 'Found In Far Away Places (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-06-29' WHERE artist = 'Fit for a King' AND "name" = 'The Price of Agony';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-06-30' WHERE artist = 'Killswitch Engage' AND "name" = 'Killswitch Engage [2009]';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-08-10' WHERE artist = 'Fit for a King' AND "name" = 'When Everything Means Nothing';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2013-01-22' WHERE artist = 'Phinehas' AND "name" = 'The Bridge Between';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2006' WHERE artist = 'MyChildren MyBride' AND "name" = 'Demo 2006';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-06-06' WHERE artist = 'As I Lay Dying' AND "name" = 'My Own Grave';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2007-07-06' WHERE artist = 'Inhale Exhale' AND "name" = 'The Lost. The Sick. The Sacred.';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Grace.Will.Fall' AND "name" = 'Self Titled';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-02-13' WHERE artist = 'Any Given Day' AND "name" = 'Diamonds';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1985' WHERE artist = '7Seconds' AND "name" = 'Walk Together, Rock Together';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1999-06-22' WHERE artist = '7Seconds' AND "name" = 'Good to Go';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2000' WHERE artist = 'In My Eyes' AND "name" = 'Nothing to Hide';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1997' WHERE artist = 'Sudarshana' AND "name" = 'Sacrificio';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2003' WHERE artist = 'Scars of Tomorrow' AND "name" = 'Design Your Fate';
UPDATE "public"."Album" SET "numberOfTracks" = 28, "date" = '2005-06-21' WHERE artist = 'Judge' AND "name" = 'What It Meant: The Complete Discography';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2005' WHERE artist = 'Die Young' AND "name" = 'Survival Instinct';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2011-09-16' WHERE artist = 'Dead In The Dirt' AND "name" = 'Fear';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Iron Maiden' AND "name" = 'Ed Hunter CD 2  (CDA)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-06-01' WHERE artist = 'Chelsea Grin' AND "name" = 'Hostage';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2009-08' WHERE artist = 'A.N.S.' AND "name" = 'Pressure Cracks';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2013-03-25' WHERE artist = 'The Korea' AND "name" = 'Saturnus';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1984' WHERE artist = 'Ritual' AND "name" = 'Ritual';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2005-03-22' WHERE artist = 'Converge' AND "name" = 'Petitioning The Empty Sky (Remastered)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Training For Utopia' AND "name" = 'Throwing A Wrench';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2004-06-01' WHERE artist = 'Coalesce' AND "name" = 'Give Them Rope She Said';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2003' WHERE artist = 'Various Artists' AND "name" = 'Black On Black: A Tribute To Black Flag';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '2007-09-28' WHERE artist = 'Botch' AND "name" = 'We Are The Romans (Deluxe Edition) (2xCD)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Norma Jean' AND "name" = 'O'' God, The Aftermath (Deluxe Edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Chariot' AND "name" = 'Unsung (EP)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2005' WHERE artist = 'Converge' AND "name" = 'When Forever Comes Crashing (Re-Issue)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Genghis Tron' AND "name" = 'Cloak of Love (EP)';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2007-01-23' WHERE artist = 'Converge' AND "name" = 'The Poacher Diaries [Re-Issue]';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Korea' AND "name" = 'На сломанных крыльях';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2007' WHERE artist = 'Bird Eater' AND "name" = 'Utah';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2007-10-19' WHERE artist = 'Korea' AND "name" = 'Пульс';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2008-08-26' WHERE artist = 'Narrows' AND "name" = 'Narrows';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nasty Taste' AND "name" = 'Demo 2008';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Code Orange Kids' AND "name" = 'I Am King';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2008' WHERE artist = 'Asking Alexandria' AND "name" = 'Demo';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2017-03-03' WHERE artist = 'Converge' AND "name" = 'Jane Live';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2008-05-13' WHERE artist = 'Coalesce' AND "name" = '012:2';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Norma Jean' AND "name" = 'O'' God The Aftermath';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006-03-01' WHERE artist = 'Korea' AND "name" = 'На сломанных крыльях';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2011-07-05' WHERE artist = 'Oathbreaker' AND "name" = 'Mælstrøm';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2014-02-18' WHERE artist = 'Converge' AND "name" = 'Live at the BBC';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2003' WHERE artist = 'Ed Gein' AND "name" = 'Its a shame that a family can be torn apart by something as simple as a pack of wild dogs';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2014-10-21' WHERE artist = 'Scott Walker' AND "name" = 'Soused';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '1992-11-01' WHERE artist = 'Naked City' AND "name" = 'Leng Tch''e';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2009-06-02' WHERE artist = 'Nadja' AND "name" = 'Belles Bêtes';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sunn O)))' AND "name" = '00 Void';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Earth' AND "name" = 'Earth 2: Special Low Frequency Version';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '1993-02-05' WHERE artist = 'Earth' AND "name" = 'Earth 2';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2001-10-30' WHERE artist = 'Khanate' AND "name" = 'Khanate';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2003-04-22' WHERE artist = 'Sunn O)))' AND "name" = 'White1';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2002-05' WHERE artist = 'Nadja' AND "name" = 'Touched';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2004-03-04' WHERE artist = 'Nadja' AND "name" = 'I Have Tasted the Fire inside your Mouth';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sunn O)))' AND "name" = 'Black 1';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2005-09-18' WHERE artist = 'Indian' AND "name" = 'The Unquiet Sky';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2006-07-07' WHERE artist = 'Nadja' AND "name" = 'Trembled';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2009-02-22' WHERE artist = 'Bong' AND "name" = 'BONG';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2009-05-10' WHERE artist = 'Gnaw Their Tongues' AND "name" = 'All the Dread Magnificence of Perversity';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2009-05-10' WHERE artist = 'Nadja' AND "name" = 'Clinging To The Edge Of The Sky';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2011-03-14' WHERE artist = 'Orthodox' AND "name" = 'Baal';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2014-09-09' WHERE artist = 'Jason Aldean' AND "name" = 'Two Night Town';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2021-05-21' WHERE artist = 'Nadja' AND "name" = 'Luminous Rot';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2011-03' WHERE artist = 'Sunn O)))' AND "name" = 'Agharthi Live 09-10';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2019-09-06' WHERE artist = 'Mizmor' AND "name" = 'Cairn';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2006-10-31' WHERE artist = 'Sunn O)))' AND "name" = 'Altar';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2013-04-30' WHERE artist = 'The Body' AND "name" = 'Master, We Perish';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2017-11-17' WHERE artist = 'The Body & Full of Hell' AND "name" = 'Ascending a Mountain of Heavy Light';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-07-06' WHERE artist = 'Attila' AND "name" = 'Pizza';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-07-07' WHERE artist = 'TesseracT' AND "name" = 'Survival (Errai)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2011-05-11' WHERE artist = 'Legend' AND "name" = 'The Pale Horse';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2001-05-29' WHERE artist = 'Figure Four' AND "name" = 'When It''s All Said And Done';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2003-02-18' WHERE artist = 'Full Blown Chaos' AND "name" = 'Prophet Of Hostility';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2008-12-28' WHERE artist = 'OH!' AND "name" = 'Tentees';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2014-03-04' WHERE artist = 'Emmure' AND "name" = 'Nemesis';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2011-01-18' WHERE artist = 'Emmure' AND "name" = 'Demons With Ryu';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2012-02-26' WHERE artist = 'Circle of Death' AND "name" = 'Violent Intercourse';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2020-07-08' WHERE artist = 'Pain of Truth' AND "name" = 'No Blame... Just Facts';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-02-17' WHERE artist = 'Emmure' AND "name" = 'Flag of the Beast';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-10-20' WHERE artist = 'Dream Awake' AND "name" = 'Symphony';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2014-07-15' WHERE artist = 'I the Breather' AND "name" = 'Life Reaper';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-12-11' WHERE artist = 'Imminence' AND "name" = 'The Sickness';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-09-08' WHERE artist = 'Like Moths to Flames' AND "name" = 'Nowhere Left To Sink';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-05-24' WHERE artist = 'Awake the Dreamer' AND "name" = 'Vigilant';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-06-29' WHERE artist = 'Awake the Dreamer' AND "name" = 'Believe';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2021-07-02' WHERE artist = 'Born of Osiris' AND "name" = 'Angel Or Alien';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2020-03-27' WHERE artist = 'Bleed from Within' AND "name" = 'The End of All We Know';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1992-12-23' WHERE artist = 'Marduk' AND "name" = 'Dark Endless';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1997-09-11' WHERE artist = 'Sacramentum' AND "name" = 'The Coming Of Chaos';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1999-10-25' WHERE artist = 'Behemoth' AND "name" = 'Satanica';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Behemoth' AND "name" = 'Pandemonic Incantation';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1999-09-06' WHERE artist = 'Angelcorpse' AND "name" = 'The Inexorable';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2000-11-27' WHERE artist = 'Behemoth' AND "name" = 'Thelema.6';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-10-01' WHERE artist = 'Behemoth' AND "name" = 'Bartzabel';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2002-03-25' WHERE artist = 'Necrophobic' AND "name" = 'Bloodhymns';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Behemoth' AND "name" = 'Zos Kia Cultus (Here and Beyond)';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2004-11-05' WHERE artist = 'Kat' AND "name" = 'Somewhere in Poland';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2008-10-14' WHERE artist = 'Behemoth' AND "name" = 'At The Arena Ov Aion – Live Apostasy';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2009-06-24' WHERE artist = 'Weapon' AND "name" = 'Drakonian Paradigm';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2010-09-10' WHERE artist = 'Dawn of Ashes' AND "name" = 'Genocide Chapters';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2011-06-29' WHERE artist = 'Azarath' AND "name" = 'Blasphemers'' Maledictions';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2016-03-18' WHERE artist = 'Vredehammer' AND "name" = 'Violator';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2017-04-07' WHERE artist = 'Azarath' AND "name" = 'In extremis';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2020-02-14' WHERE artist = 'Necrowretch' AND "name" = 'The Ones From Hell';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2002' WHERE artist = 'Behemoth' AND "name" = 'Thunders of Erupt';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2012-11-06' WHERE artist = 'Dragged Into Sunlight' AND "name" = 'Widowmaker';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2007-06-14' WHERE artist = 'Afterimage' AND "name" = 'Codex: Triumph In The Eschaton';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2020-05-29' WHERE artist = 'Fit for a King' AND "name" = 'Backbreaker';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-06-01' WHERE artist = 'Fit for a King' AND "name" = 'Tower of Pain';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-08-24' WHERE artist = 'Fit for a King' AND "name" = 'Oblivion';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Inhale Exhale' AND "name" = 'I Swear...';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2013-01-22' WHERE artist = 'Phinehas' AND "name" = 'The Bridge Between Us';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2009' WHERE artist = 'Димна Суміш' AND "name" = 'Димна Суміш';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1991-08-20' WHERE artist = 'Fudge Tunnel' AND "name" = 'Hate Songs in E Minor';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1994-02-08' WHERE artist = 'Jawbox' AND "name" = 'For Your Own Special Sweetheart';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1995-11-14' WHERE artist = 'Polvo' AND "name" = 'This Eclipse';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1996-01-01' WHERE artist = 'Shiner' AND "name" = 'Splay';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1995-02-10' WHERE artist = 'Godheadsilo' AND "name" = 'Elephantitus Of The Night';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1995-05-02' WHERE artist = 'Steel Pole Bath Tub' AND "name" = 'Scars From Falling Down';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1996-04-09' WHERE artist = 'Unwound' AND "name" = 'Repetition';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '1997-07-28' WHERE artist = 'Kerosene 454' AND "name" = 'Race';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1998-01-20' WHERE artist = '...And You Will Know Us by the Trail of Dead' AND "name" = '...And You Will Know Us by the Trail of Dead';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1998-01-20' WHERE artist = 'Godheadsilo' AND "name" = 'Share the Fantasy';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Les Savy Fav' AND "name" = 'Rome (Written Upside Down) [EP]';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2002-09-24' WHERE artist = 'Steel Pole Bath Tub' AND "name" = 'Unlistenable';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1995-09-27' WHERE artist = 'Antioch Arrow' AND "name" = 'Gems of Masochism';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2005' WHERE artist = 'The Jonbenét' AND "name" = 'The Plot Thickens';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '1999-09-14' WHERE artist = 'Unwound' AND "name" = 'A Single History: 1991-1997';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Hoover' AND "name" = 'Lurid Traversal of Route 7';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2006' WHERE artist = 'The Jonbenét' AND "name" = 'Ugly/Heartless';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Citadel' AND "name" = 'Citadel EP (2003-2004)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2004-12-22' WHERE artist = 'The Black Mages' AND "name" = 'The Black Mages II - The Skies Above';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Black Mages' AND "name" = 'The Black Mages II The Skies Above';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-06-19' WHERE artist = 'The Devil Wears Prada' AND "name" = 'Supernova';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1992-01-07' WHERE artist = 'Yngwie Malmsteen' AND "name" = 'Fire & Ice';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2002-02-05' WHERE artist = 'The Crown' AND "name" = 'Eternal Death';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Entombed' AND "name" = 'DCLXVI - To Ride, Shoot Straight and Speak the Truth';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1999-04' WHERE artist = 'Sins Of Omission' AND "name" = 'The creation';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2001-08-07' WHERE artist = 'Meshuggah' AND "name" = 'Rare Trax';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Machinae Supremacy' AND "name" = 'Promo';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '% [disc %]';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '% (disc %)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Closer' AND "name" = 'Occam''s Razor';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2006-10-16' WHERE artist = 'Kayser' AND "name" = 'Frame The World...Hang It On The Wall';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2007-06' WHERE artist = 'Immaculate' AND "name" = 'Thrash, Kill ''n'' Deströy';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2008-06' WHERE artist = 'Syphilitic Vaginas' AND "name" = 'Black Motor Covenant';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2008-05-04' WHERE artist = 'The Black' AND "name" = 'Alongside Death';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'At the Gates' AND "name" = 'Purgatory Unleashed Live At Wacken';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2014-09-30' WHERE artist = 'Rocka Rollas' AND "name" = 'The Road to Destruction';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bathory' AND "name" = 'Demo 83/84';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2015-12-04' WHERE artist = 'Night Viper' AND "name" = 'Night Viper';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Arch Enemy' AND "name" = 'Manifesto of Arch Enemy (Best Of)';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2016-10-31' WHERE artist = 'Blazon Stone' AND "name" = 'Ready For Boarding';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2001-08-06' WHERE artist = 'In Flames' AND "name" = 'The Tokyo Showdown';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2009' WHERE artist = 'Preach' AND "name" = 'Melt To Sand';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dead by April' AND "name" = 'Dead by April (Bonus Version)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Mors Principium Est' AND "name" = 'Embers of a Dying World (Bonus Track Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2002-05-14' WHERE artist = 'In Flames' AND "name" = 'The Jester Race / Black Ash Inheritance';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2003-02-03' WHERE artist = 'HammerFall' AND "name" = 'Glory to the Brave [Deluxe Edition]';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'In Flames' AND "name" = 'Black-Ash Inheritance EP';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2013-06-30' WHERE artist = 'Vagrond' AND "name" = 'Temporal';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2010' WHERE artist = 'A Total Wall' AND "name" = 'True Fear';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Mastodon' AND "name" = 'Call of Mastodon';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2011' WHERE artist = 'Existence' AND "name" = 'Misanthropy';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2013-04-22' WHERE artist = 'Lana Del Rey' AND "name" = 'Young and Beautiful';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-06-05' WHERE artist = 'Zara Larsson' AND "name" = 'Lush Life';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1983-11-26' WHERE artist = 'Amebix' AND "name" = 'No Sanctuary';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1985-09-14' WHERE artist = 'Amebix' AND "name" = 'Arise!';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1985-07-19' WHERE artist = 'Sacrilege' AND "name" = 'Behind The Realms Of Madness';
UPDATE "public"."Album" SET "numberOfTracks" = 36, "date" = '2002' WHERE artist = 'Electro Hippies' AND "name" = 'The Only Good Punk';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1998' WHERE artist = 'Amebix' AND "name" = 'Beginning of the End';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1998-03' WHERE artist = 'His Hero Is Gone' AND "name" = 'The Plot Sickens';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007' WHERE artist = 'Cursed' AND "name" = 'One';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2003-02-25' WHERE artist = 'Cursed' AND "name" = 'I';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006-05-16' WHERE artist = 'Tragedy' AND "name" = 'Nerve Damage';
UPDATE "public"."Album" SET "numberOfTracks" = 25, "date" = '2006-07-18' WHERE artist = 'Deviated Instinct' AND "name" = 'Welcome to the Orgy';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2008-01-22' WHERE artist = 'Disfear' AND "name" = 'Live the Storm';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2009-09-18' WHERE artist = 'Discharge' AND "name" = 'Disensitise';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2010-06-29' WHERE artist = 'Amebix' AND "name" = 'Redux';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2011-06-03' WHERE artist = 'Amebix' AND "name" = 'Knights of the Black Sun';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2012-06-16' WHERE artist = 'Homewrecker' AND "name" = 'Worms and Dirt';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2010-10-02' WHERE artist = 'Alpinist' AND "name" = 'Lichtlærm';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Amebix' AND "name" = 'Arise Plus Two';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2021-03-31' WHERE artist = 'Dödsrit' AND "name" = 'Mortal Coil';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1996' WHERE artist = 'Warcollapse' AND "name" = 'Wandering In Darkness';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Vigilante' AND "name" = 'Dark People volume 1';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2008' WHERE artist = 'Cursed' AND "name" = 'Three: Architects Of Troubled Sleep';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2008-05' WHERE artist = 'Malignant Tumour' AND "name" = 'In Full Swing';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Arch Enemy' AND "name" = 'Khaos Legions [+Digital Booklet]';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2014-05-14' WHERE artist = 'Primordium' AND "name" = 'Todtenbuch';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2015-10-05' WHERE artist = 'Untrop' AND "name" = 'Pale Illusions Of Life';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-03-09' WHERE artist = 'Hollywood Undead' AND "name" = 'How We Roll';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-12-23' WHERE artist = 'Helloween' AND "name" = 'Unarmed';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2004-12-01' WHERE artist = 'Nightwish' AND "name" = 'Once Finnish Double Platinum Edition';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Avantasia' AND "name" = 'The Mystery Of Times';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Led Zeppelin' AND "name" = 'Led Zeppelin I';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = '5''nizza' AND "name" = 'О5';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Валентин Стрыкало' AND "name" = 'The Greatest Hits';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-01-13' WHERE artist = 'Kehlani' AND "name" = 'Do U Dirty';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1983-10-19' WHERE artist = 'Aldo Nova' AND "name" = 'SUBJECT.....ALDO NOVA';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1983-10-26' WHERE artist = 'Night Ranger' AND "name" = 'Midnight Madness';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1987-10-18' WHERE artist = 'Bonfire' AND "name" = 'Fire Works';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1988-10' WHERE artist = 'Hurricane' AND "name" = 'Over The Edge';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1990-07-23' WHERE artist = 'Hurricane' AND "name" = 'Slave To The Thrill';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1990-06-26' WHERE artist = 'Nelson' AND "name" = 'After the Rain';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Devin Townsend' AND "name" = 'Addicted';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2000-01-10' WHERE artist = 'Nine Inch Nails' AND "name" = 'Into the Void';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1997-12-17' WHERE artist = 'Nelson' AND "name" = 'The Silence Is Broken';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2004-07-13' WHERE artist = 'Dokken' AND "name" = 'Hell To Pay';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Amaranthe' AND "name" = 'Amaranthe [Bonus Tracks]';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2012' WHERE artist = 'Dead by April' AND "name" = 'Incomparable (Mystery Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2015-10-23' WHERE artist = 'Amberian Dawn' AND "name" = 'Innuendo';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2019-05-24' WHERE artist = 'Siamese' AND "name" = 'Super Human';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-07-20' WHERE artist = 'Amaranthe' AND "name" = 'The Sacrament of Sin (Deluxe Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-03-31' WHERE artist = 'DEADLIFT LOLITA' AND "name" = 'Kimi Terasu Sairiumu';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Devin Townsend Project' AND "name" = 'ADDICTED!';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1995-10-23' WHERE artist = 'Def Leppard' AND "name" = 'Vault';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Mortiis' AND "name" = 'Grudge';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Devin Townsend' AND "name" = 'Z²';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1991' WHERE artist = 'Tuff' AND "name" = 'What Goes Around Comes Around';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2003-10-07' WHERE artist = 'Mötley Crüe' AND "name" = 'Best Of Motley Crue';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2004-08-10' WHERE artist = 'Hilary Duff' AND "name" = 'Girl Can Rock';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Amaranthe' AND "name" = 'The Nexus [Bonus Tracks]';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nightwish' AND "name" = 'Amaranth [Online Only]';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2015-09-25' WHERE artist = 'Svalbard' AND "name" = 'One Day All This Will End';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Stevie Wonder' AND "name" = 'The Very Best Of (2CDS)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1985-05' WHERE artist = 'Faith No More' AND "name" = 'We Care a Lot';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1989-06-28' WHERE artist = 'Mr. Bungle' AND "name" = 'OU818';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1989-05' WHERE artist = '24-7 Spyz' AND "name" = 'Harder Than You';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2002' WHERE artist = 'Primus' AND "name" = 'Frizzle Fry (Remastered)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1992' WHERE artist = 'Idiot Flesh' AND "name" = 'Tales of Instant Knowledge and Sure Death';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Extreme' AND "name" = 'Pornograffitti';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Red Hot Chili Peppers' AND "name" = 'Red Hot Chili Peppers';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1994-04-05' WHERE artist = 'Sausage' AND "name" = 'Riddles Are Abound Tonight';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1995-04-04' WHERE artist = 'Sugar Ray' AND "name" = 'Lemonade and Brownies';
UPDATE "public"."Album" SET "hidden" = false WHERE artist = 'Powerman 5000' AND "name" = 'Tonight the Stars Revolt';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1995-12-01' WHERE artist = 'Powerman 5000' AND "name" = 'The Blood Splat Rating System';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Faith No More' AND "name" = 'King For A Day - Fool For A Lifetime';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1996-08-27' WHERE artist = 'Les Claypool And The Holy Mackerel' AND "name" = 'Highball With The Devil';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Faith No More' AND "name" = 'Who Cares A Lot';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1999-07-13' WHERE artist = 'I Mother Earth' AND "name" = 'Blue Green Orange';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2002-07-15' WHERE artist = 'Incubus' AND "name" = 'Are You In?';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'O''Funk''illo' AND "name" = 'En El Planeta Aseituna';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2003-04-08' WHERE artist = 'I Mother Earth' AND "name" = 'The Quicksilver Meat Dream';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Moby' AND "name" = 'Go:The Very Best Of Moby';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2006' WHERE artist = 'Red Hot Chili Peppers' AND "name" = 'Californication (Deluxe Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2007-05-08' WHERE artist = 'That 1 Guy' AND "name" = 'The Moon Is Disgusting';
UPDATE "public"."Album" SET "numberOfTracks" = 31, "date" = '2015-06-09' WHERE artist = 'Faith No More' AND "name" = 'Angel Dust (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2011-12' WHERE artist = 'Woods of Infinity' AND "name" = 'Förlåt';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2017-09-29' WHERE artist = 'Primus' AND "name" = 'The Desaturating Seven';
UPDATE "public"."Album" SET "numberOfTracks" = 32, "date" = '2013-11-11' WHERE artist = 'Mr. Bungle' AND "name" = 'The Studio Album Collection';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'U2' AND "name" = 'Best of 1980-1990';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2017-06-23' WHERE artist = '311' AND "name" = 'MOSAIC';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2003' WHERE artist = 'O''Funk''illo' AND "name" = '...en el Planeta Aseituna';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2004-06-23' WHERE artist = 'Maximum the Hormone' AND "name" = 'Rock Bankurawase / Minoreba Rock';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Mr. Bungle' AND "name" = 'Mr Bungle';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1993-11-09' WHERE artist = 'Lacrimosa' AND "name" = 'Satura';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sirenia' AND "name" = 'An Elexier For Existence';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nightwish' AND "name" = 'Bless the Child - The Rarities';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007-06-04' WHERE artist = 'Kamelot' AND "name" = 'Ghost Opera (Limited Edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Amebix' AND "name" = 'Arise Plus Two';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Vigilante' AND "name" = 'Dark People volume 1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Arch Enemy' AND "name" = 'Khaos Legions [+Digital Booklet]';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '% disc _';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '% disc __';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Ripping Corpse' AND "name" = 'Unreleased Album 1992';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2001-07-10' WHERE artist = 'Vinnie Moore' AND "name" = 'Defying Gravity';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2017-07-14' WHERE artist = 'Atreyu' AND "name" = 'The Curse [Instrumental]';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2015-12-01' WHERE artist = 'Corpora' AND "name" = 'Impulse';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2001' WHERE artist = 'Apocalyptica' AND "name" = 'Cult Special Edition 2001';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2020-12-18' WHERE artist = 'Marc A. Pullen' AND "name" = '7 Bad Days';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2007-12-03' WHERE artist = 'Jelonek' AND "name" = 'Jelonek';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2007-09-03' WHERE artist = 'Jin' AND "name" = 'Breaking The Sky';
UPDATE "public"."Album" SET "numberOfTracks" = 22, "date" = '2007-11-07' WHERE artist = 'Guitar Heroes' AND "name" = 'Guitar Heroes';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2007-04-04' WHERE artist = 'Marc A. Pullen' AND "name" = 'Panexypnos Dimiourgia';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006' WHERE artist = 'Preludio' AND "name" = 'Preludio';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2007' WHERE artist = 'Deathmøle' AND "name" = 'Long Songs';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2010-12-19' WHERE artist = 'Hearts of Atlantis' AND "name" = 'Hearts Of Atlantis';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2001-01-25' WHERE artist = 'Jangli Jaggas' AND "name" = 'Vampire Dance Vol. 1';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2002-01' WHERE artist = 'Jangli Jaggas' AND "name" = 'Vampire Dance Vol. 2';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bleeding Skies' AND "name" = 'Im mr derp';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2012-07-24' WHERE artist = 'Daniel Tidwell' AND "name" = 'The Mystic Quest for Metal (A Tribute to the Music of Final Fantasy: Mystic Quest)';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2012-08-03' WHERE artist = 'Tempel' AND "name" = 'On The Steps Of The Temple';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Edyta Bartosiewicz' AND "name" = 'Zlote Przeboje - The Best';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2014-11-18' WHERE artist = 'Second To Sun' AND "name" = 'Three Fairy Tales';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Virgin Steele' AND "name" = 'The House of Atreus Act I';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2004-09-27' WHERE artist = 'Rhapsody' AND "name" = 'Symphony Of Enchanted Lands II - The Dark Secret';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Lunatica' AND "name" = 'Fables and Dreams';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2009-01-11' WHERE artist = 'Gwyllion' AND "name" = 'The Edge of All I Know';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2017-12-20' WHERE artist = 'Epica' AND "name" = 'EPICA VS. ATTACK ON TITAN SONGS';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2016-07-20' WHERE artist = 'Rhapsody of Fire' AND "name" = 'Legendary Tales';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2018-02-16' WHERE artist = 'Visions of Atlantis' AND "name" = 'The Deep & the Dark';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2019-07-05' WHERE artist = 'Turilli / Lione Rhapsody' AND "name" = 'Zero Gravity (Rebirth And Evolution)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2020-01-31' WHERE artist = 'Serenity' AND "name" = 'The Last Knight';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2016-01-29' WHERE artist = 'Serenity' AND "name" = 'Codex Atlanticus';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rhapsody of Fire' AND "name" = 'Rain Of A Thousand Flames';
UPDATE "public"."Album" SET "numberOfTracks" = 23, "date" = '2003-12-25' WHERE artist = 'Aina' AND "name" = 'Days of Rising Doom';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2020-04-03' WHERE artist = 'Ad Infinitum' AND "name" = 'Chapter I: Monarchy';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1995-09' WHERE artist = 'Lacrimas Profundere' AND "name" = '...and the Wings Embraced Us';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1996-09-09' WHERE artist = 'Sirrah' AND "name" = 'Acme';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2014-11-10' WHERE artist = 'Within Temptation' AND "name" = 'Enter / The Dance';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1996-09-02' WHERE artist = 'The Blood Divine' AND "name" = 'Awaken';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1998-01-15' WHERE artist = 'Inner Shrine' AND "name" = 'Nocturnal Rhymes Entangled in Silence';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1999-08-23' WHERE artist = 'Lacrimas Profundere' AND "name" = 'Memorandum';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1999-07' WHERE artist = 'Tower' AND "name" = 'Mercury';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1999' WHERE artist = 'Cultus Sanguine' AND "name" = 'The Sum of All Fears';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2000-04' WHERE artist = 'Abysmal Grief' AND "name" = 'Exsequia Occulta';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2001-08-14' WHERE artist = 'Paragon of Beauty' AND "name" = 'Comfort Me, Infinity';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2003-06-23' WHERE artist = 'Virgin Black' AND "name" = 'Elegant... And Dying';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2007-04-23' WHERE artist = 'My Silent Wake' AND "name" = 'The Anatomy of Melancholy';
