UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Desert Sessions' AND "name" = 'The Desert Sessions Volume 1 (Instrumental Driving Music For Felons) & Volume 2 (Status: Ships Commander Butchered)';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2012-05-22' WHERE artist = 'Felipe Arcazas' AND "name" = 'Induction To The Subconscious';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2002-08-27' WHERE artist = 'Queens of the Stone Age' AND "name" = 'Songs For The Deaf [UK]';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1979-01' WHERE artist = 'Black Flag' AND "name" = 'Nervous Breakdown';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1980-10-01' WHERE artist = 'Circle Jerks' AND "name" = 'Group Sex';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1981-04' WHERE artist ='Adolescents' AND "name" = 'Adolescents';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dead Kennedys' AND "name" = 'Plastic Surgery Disaster';
UPDATE "public"."Album" SET "numberOfTracks" = 25, "date" = '1982' WHERE artist = 'Black Flag' AND "name" = 'Everything Went Black';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1982-04-15' WHERE artist = 'GBH' AND "name" = 'City Baby Attacked by Rats';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1982-03' WHERE artist = 'Misfits' AND "name" = 'Walk Among Us';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1982-05-21' WHERE artist = 'Discharge' AND "name" = 'Hear Nothing See Nothing Say Nothing';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1982-11' WHERE artist = 'Dead Kennedys' AND "name" = 'Plastic Surgery Disasters';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '1983-04-15' WHERE artist = 'Bad Brains' AND "name" = 'Rock for Light';
UPDATE "public"."Album" SET "numberOfTracks" = 23, "date" = '1984' WHERE artist = '7Seconds' AND "name" = 'The Crew';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1984' WHERE artist = 'Agnostic Front' AND "name" = 'Victim In Pain';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1984-03' WHERE artist = 'Black Flag' AND "name" = 'My War';
UPDATE "public"."Album" SET "numberOfTracks" = 23, "date" = '1984-07-01' WHERE artist = 'Hüsker Dü' AND "name" = 'Zen Arcade';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1985-10' WHERE artist = 'Dead Kennedys' AND "name" = 'Frankenchrist';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '1984-12' WHERE artist = 'Black Flag' AND "name" = 'Live ''84';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1985-05-14' WHERE artist = 'Black Flag' AND "name" = 'Loose Nut';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1986-11-21' WHERE artist = 'Bad Brains' AND "name" = 'I Against I';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1988-04-22' WHERE artist = 'NOFX' AND "name" = 'Liberal Animation';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1990' WHERE artist = 'Neurosis' AND "name" = 'The Word As Law';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '1985' WHERE artist = 'Dead Kennedys' AND "name" = 'Plastic Surgery Disasters/In God We Trust, Inc.';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1982-03-30' WHERE artist = 'Flipper' AND "name" = 'Generic';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2012-09-10' WHERE artist = 'Gallows' AND "name" = 'Gallows';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2013-10-15' WHERE artist = 'Fall Out Boy' AND "name" = 'PAX AM Days';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2006-09-25' WHERE artist = 'Gallows' AND "name" = 'Orchestra of Wolves';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2012-11-20' WHERE artist = 'Code Orange Kids' AND "name" = 'Love Is Love // Return to Dust';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2017-05-05' WHERE artist = 'Full of Hell' AND "name" = 'Trumpeting Ecstasy';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Beartooth' AND "name" = 'Disgusting (Deluxe Edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Propagandhi' AND "name" = 'Victory Lap (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1999-05-18' WHERE artist = 'AFI' AND "name" = 'Black Sails in the Sunset';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sirenia' AND "name" = 'An Elexier For Existence';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1985-06-21' WHERE artist = 'Mötley Crüe' AND "name" = 'Theatre Of Pain';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1981-11-10' WHERE artist = 'Mötley Crüe' AND "name" = 'Too Fast For Love';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2010-04-14' WHERE artist = 'Crashdïet' AND "name" = 'Generation Wild';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2007-10-03' WHERE artist = 'Crashdïet' AND "name" = 'The Unattractive Revolution';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2005-11-28' WHERE artist = 'The Darkness' AND "name" = 'One Way Ticket To Hell And Back';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1990-07' WHERE artist = 'Vixen' AND "name" = 'Rev It Up!';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2017-03-24' WHERE artist = 'Steel Panther' AND "name" = 'Lower The Bar';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1982-10-28' WHERE artist = 'Kiss' AND "name" = 'Creatures Of The Night';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1983-04' WHERE artist = 'Fastway' AND "name" = 'Fastway';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2005' WHERE artist = 'Vain' AND "name" = 'On the Line';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bring Me the Horizon' AND "name" = '2010 - There Is a Hell, Believe Me I''ve Seen It. There Is a Heaven, Let''s Keep It a Secret';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Kyuss' AND "name" = 'And the Circus Leaves Town';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1989-01-24' WHERE artist = 'Masters of Reality' AND "name" = 'Masters of Reality';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1987-02' WHERE artist = 'Thin White Rope' AND "name" = 'Moonhead';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1994-01-01' WHERE artist = 'Fu Manchu' AND "name" = 'No One Rides For Free';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1998-10-20' WHERE artist = 'Nebula' AND "name" = 'Let It Burn';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1999-03-19' WHERE artist = 'Nebula' AND "name" = 'Sun Creature';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Desert Sessions' AND "name" = 'Desert Sessions 9 & 10';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Desert Sessions' AND "name" = 'Volumes 9 & 10';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2004-08-10' WHERE artist = 'Mark Lanegan' AND "name" = 'Bubblegum';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Yawning Man' AND "name" = 'Pothead';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2007-11-19' WHERE artist = 'Cortez' AND "name" = 'Thunder In A Forgotten Town';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2016-08-18' WHERE artist = 'Yawning Man' AND "name" = 'Historical Graffiti';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2016-09-26' WHERE artist = '1000mods' AND "name" = 'Repeated exposure to...';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2014-06-13' WHERE artist = 'Lana Del Rey' AND "name" = 'Ultraviolence (Deluxe)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Red Hot Chili Peppers' AND "name" = 'Red Hot Chili Peppers - Blood Sugar Sex Magik';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2004-10-11' WHERE artist = 'Anorexia Nervosa' AND "name" = 'Redemption process';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2017-06-30' WHERE artist = 'Shade Empire' AND "name" = 'Poetry Of The Ill-Minded';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2005-11-11' WHERE artist = 'Dimmu Borgir' AND "name" = 'Stormblåst MMV';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2018-02-23' WHERE artist = 'Dimmu Borgir' AND "name" = 'Interdimensional Summit';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1996-04-22' WHERE artist = 'Cradle of Filth' AND "name" = 'Vempire';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2003' WHERE artist = 'Across Five Aprils' AND "name" = 'A Tragedy in Progess';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Silverstein' AND "name" = 'Arrivals and Departures';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007-06-15' WHERE artist = 'Blind Guardian' AND "name" = 'Imaginations From The Other Side (Remastered 2007)';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2007-10-22' WHERE artist = 'Nightwish' AND "name" = 'Angels Fall First (Official Collector''s Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1983-09-18' WHERE artist = 'Dokken' AND "name" = 'Breaking the Chains';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Skid Row' AND "name" = 'Rhino Hi-Five: Skid Row';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1984-10-09' WHERE artist = 'Autograph' AND "name" = 'Sign In Please';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1984-03-27' WHERE artist = 'Ratt' AND "name" = 'Out of the Cellar';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1984-01-21' WHERE artist = 'Bon Jovi' AND "name" = 'Bon Jovi';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1985-10-07' WHERE artist = 'Kix' AND "name" = 'Midnite Dynamite';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1985-06-13' WHERE artist = 'Ratt' AND "name" = 'Invasion of Your Privacy';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1986-11-24' WHERE artist = 'Tesla' AND "name" = 'Mechanical Resonance';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '1998' WHERE artist = 'Cinderella' AND "name" = 'Bad Attitude';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2010-10-29' WHERE artist = 'Bon Jovi' AND "name" = 'Bon Jovi Greatest Hits';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1987-06-22' WHERE artist = 'White Lion' AND "name" = 'Pride';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1988-05-03' WHERE artist = 'Poison' AND "name" = 'Open Up and Say... Ahh!';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1988-01-04' WHERE artist = 'L.A. Guns' AND "name" = 'L.A. Guns';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1989-10-05' WHERE artist = 'Pretty Boy Floyd' AND "name" = 'Leather Boyz With Electric Toyz';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1989-12-17' WHERE artist = 'Britny Fox' AND "name" = 'Boys In Heat';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1990-09-11' WHERE artist = 'Warrant' AND "name" = 'Cherry Pie';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '1991-04-06' WHERE artist = 'Ratt' AND "name" = 'Ratt & Roll 8191';
UPDATE "public"."Album" SET "numberOfTracks" = 48, "date" = '2017-08-04' WHERE artist = 'Def Leppard' AND "name" = 'Hysteria (Super Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1992-04-21' WHERE artist = 'Slaughter' AND "name" = 'The Wild Life';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2003-05-27' WHERE artist = 'Vince Neil' AND "name" = 'Live at the Whisky: One Night Only';
UPDATE "public"."Album" SET "numberOfTracks" = 38, "date" = '2005-02-01' WHERE artist = 'Mötley Crüe' AND "name" = 'Red White & Crue';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2005-01-25' WHERE artist = 'Cinderella' AND "name" = 'Rocked, Wired & Bluesed: The Greatest Hits';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2009-01-27' WHERE artist = 'Steel Panther' AND "name" = 'Death To All But Metal';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2012-10-31' WHERE artist = 'Black Veil Brides' AND "name" = 'In the End';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Whitesnake' AND "name" = 'Saint''s and Sinners [Remastered] (Remastered Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2006-02-07' WHERE artist = 'Whitesnake' AND "name" = 'The Definitive Collection';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2013-03-19' WHERE artist = 'Def Leppard' AND "name" = 'Hysteria 2013 (Re-Recorded Version) - Single';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2017-12-01' WHERE artist = 'U2' AND "name" = 'Songs of Experience (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '1996-11-26' WHERE artist = 'Poison' AND "name" = 'Poison''s Greatest Hits 1986-1996';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Linkin Park' AND "name" = '2007 - Minutes To Midnight';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Stone Sour' AND "name" = 'Come What(ever) May [CD/DVD] Disc 1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rise Against' AND "name" = 'The Sufferer And The Wittness';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Lagwagon' AND "name" = 'Let`s Talk About Feelings';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Green Day' AND "name" = '1992 - Kerplunk';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Accept' AND "name" = 'Balls To The Walls';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Refused' AND "name" = 'The Shape Of Punk To Come: A C';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1989-06-19' WHERE artist = 'Kreator' AND "name" = 'Extreme Agression';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Gojira' AND "name" = 'From Mars To Sirus';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Swans' AND "name" = 'Soundtracks for the Blind Disc 1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Slowdive' AND "name" = 'Soulvaki';
UPDATE "public"."Album" SET "numberOfTracks" = 26, "date" = '2010-08-06' WHERE artist = 'Queens of the Stone Age' AND "name" = 'Rated R - Deluxe Edition';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Within Temptation' AND "name" = 'Black Symphony Disc 1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Kamelot' AND "name" = '2007 - Ghost Opera';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2007-03-14' WHERE artist = 'Maximum the Hormone' AND "name" = 'Buikikaeso';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Maximum the Hormone' AND "name" = 'Buiiki Kaesu';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Comeback Kid' AND "name" = 'Symptoms And Cures';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Kamelot' AND "name" = '2005 - The Black Halo';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Stratovarius' AND "name" = '1996 - Episode';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Helloween' AND "name" = 'Keeper of the Seven Keys, Pt. II';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Kamelot' AND "name" = '1999 - The Fourth Legacy';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Chimaira' AND "name" = 'New Shit Vol 3';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2014' WHERE artist = 'Jinjer' AND "name" = 'Cloud Factory';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2015-07-24' WHERE artist = 'Lamb of God' AND "name" = 'VII: Sturm Und Drang (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2015-09-03' WHERE artist = 'Five Finger Death Punch' AND "name" = 'Got Your Six (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2018-05-18' WHERE artist = 'Five Finger Death Punch' AND "name" = 'And Justice for None (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '1996-02-21' WHERE artist = 'Sepultura' AND "name" = 'Roots [Special Edition]';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1995-05-27' WHERE artist = 'Naglfar' AND "name" = 'Vittra';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1996-05-15' WHERE artist = 'Sacramentum' AND "name" = 'Far Away from the Sun';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1997-10-06' WHERE artist = 'Graveworm' AND "name" = 'When Daylight''s Gone';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1999-09-13' WHERE artist = 'Graveworm' AND "name" = 'As the Angels Reach the Beauty';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dimmu Borgir' AND "name" = 'Spiritual Black Dimension';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2000-02' WHERE artist = 'Siebenbürgen' AND "name" = 'Delictum';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2001-11-13' WHERE artist = 'Naglfar' AND "name" = 'Ex Inferis';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2000-12' WHERE artist = 'Vampiria' AND "name" = 'Among Mortals';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2001-11-23' WHERE artist = 'Stormlord' AND "name" = 'At The Gates Of Utopia';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1998-05-07' WHERE artist = 'Dawn' AND "name" = 'Slaughtersun (Crown of the Triarchy)';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2007' WHERE artist = 'Taake' AND "name" = '...Doedskvad';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2013-03-01' WHERE artist = 'Rotting Christ' AND "name" = 'Κατα Τον Δαιμονα Εαυτου (Do What Thou Wilt)';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2016-04-29' WHERE artist = 'Mistur' AND "name" = 'In Memoriam';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2017-10-13' WHERE artist = 'Nachtblut' AND "name" = 'Apostasie';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Flipper' AND "name" = 'Album: Generic Flipper';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1990-06-01' WHERE artist = 'Neurosis' AND "name" = 'The Word As Law';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1981' WHERE artist = 'Discharge' AND "name" = 'Why?';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Choking Victim' AND "name" = 'No Gods, No Managers';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'AFI' AND "name" = 'Shut Your Mouth & Open Your Eyes';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bring Me the Horizon' AND "name" = '2006 - Count Your Blessings';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2017-11-24' WHERE artist = 'Bring Me the Horizon' AND "name" = '2004 - 2013';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1982-10' WHERE artist = 'Witchfinder General' AND "name" = 'Death Penalty';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1993' WHERE artist = 'Pentagram' AND "name" = 'Relentless';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1986-10' WHERE artist = 'Saint Vitus' AND "name" = 'Born Too Late';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1986-06-10' WHERE artist = 'Candlemass' AND "name" = 'Epicus Doomicus Metallicus';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1991-05-03' WHERE artist = 'Melvins' AND "name" = 'Bullhead';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1996-11' WHERE artist = 'Katatonia' AND "name" = 'Brave Murder Day';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1999-08-31' WHERE artist = 'Katatonia' AND "name" = 'Tonights Decision';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2002-03-25' WHERE artist = 'Electric Wizard' AND "name" = 'Let Us Prey';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2004-06-28' WHERE artist = 'Electric Wizard' AND "name" = 'We Live';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006-05-29' WHERE artist = 'Celtic Frost' AND "name" = 'Monotheist';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2015-06-01' WHERE artist = 'Paradise Lost' AND "name" = 'The Plague Within';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1983-02' WHERE artist = 'Sonic Youth' AND "name" = 'Confusion Is Sex';
UPDATE "public"."Album" SET "numberOfTracks" = 34, "date" = '2007-06-12' WHERE artist = 'Sonic Youth' AND "name" = 'Daydream Nation (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1986-01-01' WHERE artist = 'Big Black' AND "name" = 'Atomizer';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1986-01-21' WHERE artist = 'The Flaming Lips' AND "name" = 'Hear It Is';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1987-09-10' WHERE artist = 'Big Black' AND "name" = 'Songs About Fucking';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1987-12-14' WHERE artist = 'Dinosaur Jr.' AND "name" = 'You''re Living All Over Me';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1987-06-01' WHERE artist = 'Sonic Youth' AND "name" = 'Sister';
UPDATE "public"."Album" SET "numberOfTracks" = 31, "date" = '2005-09-13' WHERE artist = 'Sonic Youth' AND "name" = 'Goo (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1994-10-24' WHERE artist = 'Shellac' AND "name" = 'At Action Park';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1998-05-25' WHERE artist = 'Boredoms' AND "name" = 'Super Ae';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2005-06-28' WHERE artist = 'Deerhunter' AND "name" = 'Turn It Up Faggot';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2015-06-20' WHERE artist = 'The Velvet Underground' AND "name" = 'The Velvet Underground & Nico 45th Anniversary';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2008-02-11' WHERE artist = 'The Mae Shi' AND "name" = 'HLLLYH';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sonic Youth' AND "name" = 'Daydream Nation (Remastered Original Album)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2003-07-01' WHERE artist = 'Melt-Banana' AND "name" = 'Cell-Scape';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2017-06-23' WHERE artist = 'Alex' AND "name" = 'AKUMA';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-04-16' WHERE artist = 'David Hasselhoff' AND "name" = 'True Survivor';
UPDATE "public"."Album" SET "numberOfTracks" = 22, "date" = '2016-07-05' WHERE artist = 'Various Artists' AND "name" = 'Furi (Original Game Soundtrack)';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2019-11-15' WHERE artist = 'deadmau5' AND "name" = 'SATRN';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2019-04-22' WHERE artist = 'Hyper' AND "name" = 'Cyberpunk EP';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2015-02-02' WHERE artist = 'Waveshaper' AND "name" = 'Solar Drifter';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Perturbator' AND "name" = 'The Uncanny Valley (Expansion)';
UPDATE "public"."Album" SET "numberOfTracks" = 49, "date" = '2011-06-21' WHERE artist = 'Death' AND "name" = 'Human (Deluxe Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2004-09-14' WHERE artist = 'Augury' AND "name" = 'Concealed';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2004-12-03' WHERE artist = 'Persefone' AND "name" = 'Truth Inside the Shades';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006-03-11' WHERE artist = 'Pitbulls in the Nursery' AND "name" = 'Lunatic';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2009-07-22' WHERE artist = 'Persefone' AND "name" = 'Shin-ken';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2010-11-23' WHERE artist = 'Burning the Masses' AND "name" = 'Offspring Of Time';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2015-03-24' WHERE artist = 'Barren Earth' AND "name" = 'On Lonely Towers';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2016-02-05' WHERE artist = 'Obscura' AND "name" = 'Akróasis';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2007-11-19' WHERE artist = 'Death' AND "name" = 'Symbolic (Remastered Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2000-06-20' WHERE artist = 'Extol' AND "name" = 'Undeceived';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1998-11-18' WHERE artist = 'Coalesce' AND "name" = 'Functioning on Impatience';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2021-06-16' WHERE artist = 'Helloween' AND "name" = 'Helloween';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1991-11-05' WHERE artist = 'Corrosion of Conformity' AND "name" = 'Blind';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2016-06-03' WHERE artist = 'Melvins' AND "name" = 'Basses Loaded';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1996-03-25' WHERE artist = 'Eyehategod' AND "name" = 'Dopesick';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1997-09-22' WHERE artist = 'Iron Monkey' AND "name" = 'Iron Monkey';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1998-08-24' WHERE artist = 'Iron Monkey' AND "name" = 'Our Problem';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2002-03-26' WHERE artist = 'Down' AND "name" = 'Down II: A Bustle in Your Hedgerow';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2002-04-02' WHERE artist = 'Kylesa' AND "name" = 'Kylesa';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Down' AND "name" = 'III: Over The Under';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2008' WHERE artist = 'Baroness' AND "name" = 'First & Second';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2012-08-30' WHERE artist = 'Eyehategod' AND "name" = 'New Orleans Is The New Vietnam';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2014-04-01' WHERE artist = 'The Body' AND "name" = 'I Shall Die Here';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2015-02-17' WHERE artist = 'Sumac' AND "name" = 'The Deal';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2020-10-30' WHERE artist = 'Emma Ruth Rundle' AND "name" = 'May Our Chambers Be Full';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2016-08-26' WHERE artist = 'SubRosa' AND "name" = 'For This We Fought The Battle Of Ages';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-12-17' WHERE artist = 'David Bowie' AND "name" = 'Lazarus';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1995-08-14' WHERE artist = 'Krisiun' AND "name" = 'Black Force Domain';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2003-11-17' WHERE artist = 'Gorerotted' AND "name" = 'Only Tools and Corpses';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Paul Wall' AND "name" = 'The Chick Magnet';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2005-04-19' WHERE artist = 'Disgorge' AND "name" = 'Parallels Of Infinite Torture';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Paris Hilton' AND "name" = '[non-album tracks]';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2006-06-05' WHERE artist = 'Paris Hilton' AND "name" = 'Stars Are Blind';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2008-12-06' WHERE artist = 'The Lonely Island' AND "name" = 'Jizz In My Pants';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2008-11-06' WHERE artist = 'The Red Shore' AND "name" = 'Unconsecrated';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2004-02-24' WHERE artist = 'Paul Wall' AND "name" = 'Chick Magnet';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2010-12-28' WHERE artist = 'Chelsea Wolfe' AND "name" = 'The Grime and the Glow';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2007-05-08' WHERE artist = 'Neurosis' AND "name" = 'Given to the Rising';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2009-07-23' WHERE artist = 'Jesu' AND "name" = 'Infinity';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2013-09-24' WHERE artist = 'Jesu' AND "name" = 'Every Day I Get Closer To The Light From Which I Came';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2016-08-05' WHERE artist = 'Russian Circles' AND "name" = 'Guidance';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2014-04-29' WHERE artist = 'Isis' AND "name" = 'Panopticon (Remastered)';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1998' WHERE artist = 'Noothgrush' AND "name" = 'Erode the Person';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1999-04-16' WHERE artist = 'Isis' AND "name" = 'The Red Sea';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2001-09-14' WHERE artist = 'Cult of Luna' AND "name" = 'Cult of Luna';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2003-02-10' WHERE artist = 'Cult of Luna' AND "name" = 'The Beyond';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2003' WHERE artist = 'Graves at Sea' AND "name" = 'Documents of Grief';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Camel' AND "name" = 'Echoes (disc 1)';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2009-12-25' WHERE artist = 'Tyler, the Creator' AND "name" = 'Bastard';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2018-09-07' WHERE artist = '$uicideboy$' AND "name" = 'I Want To Die In New Orleans';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2018-10-12' WHERE artist = 'City Morgue' AND "name" = 'CITY MORGUE VOL 1: HELL OR HIGH WATER';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1999-03-02' WHERE artist = 'Three 6 Mafia' AND "name" = 'Underground Vol. 1';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-04-14' WHERE artist = 'Erikthemc' AND "name" = 'I Spoke to the Devil in Miami, He Said Everything Would Be Fine (Remix)';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2009-05-15' WHERE artist = 'Slon' AND "name" = 'Chore Melodie';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2005' WHERE artist = 'Mister X' AND "name" = 'Punx & Skins Unite & win';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2009' WHERE artist = 'Comrade Malone & DJ Downlow' AND "name" = 'Spontaneous Revolt';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2008' WHERE artist = 'The Orobians' AND "name" = 'Anniversary Album';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2010' WHERE artist = 'Wins Pain' AND "name" = 'EP 2010';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Edelweiss Piraten' AND "name" = 'Split';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2009-12-24' WHERE artist = 'Oktoberklub' AND "name" = 'Auf auf zum Kampf';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1997' WHERE artist = 'Barricata rossa' AND "name" = 'E non si arrende!';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2013-09-24' WHERE artist = 'Various Artists' AND "name" = 'The Music of Grand Theft Auto V, Vol. 1: Original Music';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '2018-01-25' WHERE artist = 'Lena Raine' AND "name" = 'Celeste (Original Soundtrack)';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2017-11-03' WHERE artist = 'The Marías' AND "name" = 'Superclean, Vol. I';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2016-02-12' WHERE artist = 'Swmrs' AND "name" = 'Drive North';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2008' WHERE artist = 'Molly Jenson' AND "name" = 'Fire Relief - A Benefit for the Victims of the 2007 San Diego Wildfires';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1985-03-22' WHERE artist = 'Katrina & The Waves' AND "name" = 'Katrina & The Waves';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '1990-10-23' WHERE artist = 'Adam and the Ants' AND "name" = 'Antics in the Forbidden Zone';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2008' WHERE artist = 'Nazareth' AND "name" = 'Hair Of The Dog (Live)';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2018-02-09' WHERE artist = 'Fu Manchu' AND "name" = 'Clone of the Universe';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '1992-09-22' WHERE artist = 'Foreigner' AND "name" = 'The Very Best... And Beyond';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2013-04-09' WHERE artist = 'Tyga' AND "name" = 'Hotel California (Deluxe Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '1995-08-22' WHERE artist = 'NOFX' AND "name" = 'I Heard They Suck Live!';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-07-10' WHERE artist = 'Billy Talent' AND "name" = 'III';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2020-02-24' WHERE artist = '100 gecs' AND "name" = 'ringtone (Remix) [feat. Charli XCX, Rico Nasty, Kero Kero Bonito]';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2020-07-10' WHERE artist = '100 gecs' AND "name" = 'hand crushed by a mallet (Remix) [feat. Fall Out Boy, Craig Owens, Nicole Dollanganger]';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2020-05-22' WHERE artist = '100 gecs' AND "name" = 'stupid horse (Remix) [feat. GFOTY & Count Baldor]';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2019-11-06' WHERE artist = '100 gecs' AND "name" = '745 sticky (Injury Reserve Remix)';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2012' WHERE artist = 'M8L8TH' AND "name" = 'By The Wing Of Black';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2020-07-10' WHERE artist = '100 gecs' AND "name" = '1000 Gecs & the Tree of Clues';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2009-06-16' WHERE artist = 'Brokencyde' AND "name" = 'Im Not A Fan But The Kids Like It';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dub Buk' AND "name" = 'Idu Na Wy!';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2006' WHERE artist = 'Der Stürmer' AND "name" = 'A Banner Greater than Death';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2020-07-10' WHERE artist = '100 gecs' AND "name" = 'xXXi_wud_nvrstøp_ÜXXx (Remix) [feat. Tommy Cash & Hannah Diamond]';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2020-07-10' WHERE artist = '100 gecs' AND "name" = '1000 gecs and the tree of clues';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2020-02-24' WHERE artist = '100 gecs' AND "name" = 'ringtone (feat. Charli XCX, Rico Nasty, Kero Kero Bonito) [remix] - Single';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Kanye West' AND "name" = '2007 - Graduation';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2011-05-05' WHERE artist = 'Gutalax' AND "name" = 'Shit Beast';
UPDATE "public"."Album" SET "numberOfTracks" = 23, "date" = '2018' WHERE artist = 'Xavlegbmaofffassssitimiwoamndutroabcwapwaeiippohfffx' AND "name" = 'Gore 2.0';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2003' WHERE artist = 'Wormed' AND "name" = 'Planisphærium';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2011-02-10' WHERE artist = 'Rebecca Black' AND "name" = 'Friday';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Vampire Weekend' AND "name" = 'Vampire Weekend (Blue CD-R)';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2009-11-18' WHERE artist = 'Lady Gaga' AND "name" = 'The Fame Monster';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sólstafir' AND "name" = 'Svartir Sandar CD1 (Andvari)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2011-09-21' WHERE artist = 'Machine Head' AND "name" = 'Unto the Locust (Special Edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Adolescents' AND "name" = 'The Adolescents';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2008-11-11' WHERE artist = 'The Bronx' AND "name" = 'The Bronx (III)';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2020-10-30' WHERE artist = 'Shining' AND "name" = 'V - Halmstad';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2009-11-18' WHERE artist = 'Betraying the Martyrs' AND "name" = 'The Hurt the Divine the Light';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Katatonia' AND "name" = 'Tonights Decision';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2013-07-15' WHERE artist = 'D/A/D' AND "name" = 'The Construct';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1997-11-18' WHERE artist = 'Empyrium' AND "name" = 'Songs of Moors & Misty Fields';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1999-08-30' WHERE artist = 'In Extremo' AND "name" = 'Verehrt und Angespien';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1999-06-06' WHERE artist = 'Agalloch' AND "name" = 'Pale Folklore';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2000-05-14' WHERE artist = 'Mägo de Oz' AND "name" = 'Finisterra';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2004-04-15' WHERE artist = 'Ensiferum' AND "name" = 'Iron';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2001-12-03' WHERE artist = 'Moonsorrow' AND "name" = 'Voimasta ja Kunniasta';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2002-01' WHERE artist = 'Týr' AND "name" = 'How Far to Asgaard';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2001-09-03' WHERE artist = 'In Extremo' AND "name" = 'Sünde ohne Zügel';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2003-09-08' WHERE artist = 'Mägo de Oz' AND "name" = 'gaia';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2008-10-30' WHERE artist = 'Alestorm' AND "name" = 'Leviathan';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Eluveitie' AND "name" = 'Everything Remains (As It Never Was)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Finntroll' AND "name" = 'Nattfodd';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1999-08-15' WHERE artist = 'Vega' AND "name" = 'Tamam Sustum';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2005' WHERE artist = 'Apocalyptica' AND "name" = 'Wie Weit';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2001-11-27' WHERE artist = 'Nightwish' AND "name" = 'From Wishes To Eternity - Live';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Within Temptation' AND "name" = 'The Silent Force Tour';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2005-09-28' WHERE artist = 'Nightwish' AND "name" = 'Highest Hopes';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2007-03-23' WHERE artist = 'Imperia' AND "name" = 'Queen of Light';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2007-09-07' WHERE artist = 'Legenda Aurea' AND "name" = 'Sedna';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2008-10-22' WHERE artist = 'Domina Noctis' AND "name" = 'Second Rose';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Ebony Ark' AND "name" = 'When The City Is Quite';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Delain' AND "name" = 'April Rain (Special Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1998-12' WHERE artist = 'Evanescence' AND "name" = 'Evanescence EP';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2019-04' WHERE artist = 'SpiritBox' AND "name" = 'Singles Collection';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-02-20' WHERE artist = 'The Agonist' AND "name" = 'Lullabies Of The Dormant Mind';
UPDATE "public"."Album" SET "numberOfTracks" = 26, "date" = '2011' WHERE artist = 'Nightwish' AND "name" = 'Imaginaerum (Deluxe Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2018-03-02' WHERE artist = 'Deuce' AND "name" = 'Nightmare';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2005' WHERE artist = 'Killswitch Engage' AND "name" = 'The End Of Heartache (Special Edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bullet for My Valentine' AND "name" = 'Hand Of Blood / 4 Words';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2015-08-14' WHERE artist = 'Bullet for My Valentine' AND "name" = 'Venom (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2008-09-24' WHERE artist = 'Trivium' AND "name" = 'Shogun [Limited Edition]';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2018-11-09' WHERE artist = 'August Burns Red' AND "name" = 'Winter Wilderness EP';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2019-06-14' WHERE artist = 'August Burns Red' AND "name" = 'Constellations (Remixed)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-04-01' WHERE artist = 'Bullet for My Valentine' AND "name" = 'Over It';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'In This Moment' AND "name" = 'A Star-Crossed Wasteland (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2012-02-28' WHERE artist = 'I the Breather' AND "name" = 'Truth And Purpose';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2014-09-05' WHERE artist = 'Any Given Day' AND "name" = 'My Longest Way Home';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2015-03-31' WHERE artist = 'Killswitch Engage' AND "name" = 'Disarm the Descent (Special Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2015-02-10' WHERE artist = 'Feed Her to the Sharks' AND "name" = 'Fortitude';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2016-11-11' WHERE artist = 'In Flames' AND "name" = 'Battles';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2013-11-11' WHERE artist = 'Malevolence' AND "name" = 'Reign of Suffering';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2011-02-15' WHERE artist = 'Bullet for My Valentine' AND "name" = 'Fever (Tour Edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'In This Moment' AND "name" = 'Rise of the Blood Legion- The Best of (Chapter 1)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bullet for My Valentine' AND "name" = 'Don''t Need You (Edit)';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2018-10-26' WHERE artist = 'Bullet for My Valentine' AND "name" = 'Gravity (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-09-25' WHERE artist = 'Any Given Day' AND "name" = 'Savior';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2021-04-16' WHERE artist = 'While She Sleeps' AND "name" = 'SLEEPS SOCIETY';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015' WHERE artist = 'The Amity Affliction' AND "name" = 'Shine On';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2007-09-12' WHERE artist = 'Stigmata' AND "name" = 'Stigmata';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2013-02-08' WHERE artist = 'Bullet for My Valentine' AND "name" = 'Temper Temper';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-04-08' WHERE artist = 'The Animal In Me' AND "name" = 'Rap God';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2004-12-06' WHERE artist = 'Fall of a Season' AND "name" = 'Decades in a Bleeding World';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2014-02-18' WHERE artist = 'I Killed the Prom Queen' AND "name" = 'Beloved (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2008' WHERE artist = 'In This Moment' AND "name" = 'The Dream (Limited Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2014-04-11' WHERE artist = 'Conchita Wurst' AND "name" = 'Eurovision Song Contest 2014 Copenhagen';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2004' WHERE artist = 'Infernal War' AND "name" = 'Infernal War';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Year of No Light' AND "name" = 'Year Of No Light ''Ausserwelt''';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1999-09-10' WHERE artist = 'Acid King' AND "name" = 'Busse Woods';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2003-11-04' WHERE artist = 'YOB' AND "name" = 'Catharsis';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2005-06-20' WHERE artist = 'Spiritual Beggars' AND "name" = 'Demons';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2005-02-01' WHERE artist = 'High on Fire' AND "name" = 'Blessed Black Wings';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2002-03-26' WHERE artist = 'Down' AND "name" = 'Down II';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2013-10-31' WHERE artist = 'Big Business' AND "name" = 'Battlefields Forever';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2016-10-10' WHERE artist = 'Red Fang' AND "name" = 'Only Ghosts (Deluxe Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1990-05-01' WHERE artist = 'Atheist' AND "name" = 'Piece of Time';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Various Artists' AND "name" = 'Unquestionable Presence';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1998-06-23' WHERE artist = 'Gorguts' AND "name" = 'Obscura';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1999-09-14' WHERE artist = 'Necrophagist' AND "name" = 'Onset of Putrefaction';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2007-10-15' WHERE artist = 'Burning the Masses' AND "name" = 'Volatile Existence';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2010-09-03' WHERE artist = 'The Red Shore' AND "name" = 'The Avarice of Man';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2016-08-18' WHERE artist = 'Blood Incantation' AND "name" = 'Starspawn';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2007-06-12' WHERE artist = 'Sigh' AND "name" = 'Hangman''s Hymn';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1993-05' WHERE artist = 'Emperor' AND "name" = 'Emperor';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Cradle of Filth' AND "name" = 'Vempire or Dark Faerytales in Phallustein';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2002-09-03' WHERE artist = 'The Kovenant' AND "name" = 'In Times Before the Light';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1997-11' WHERE artist = 'Profanum' AND "name" = 'Profanum Aeternum: Eminence of Satanic Imperial Art';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1997-07-06' WHERE artist = 'Nokturnal Mortum' AND "name" = 'Goat Horns';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1998-01-01' WHERE artist = '...and Oceans' AND "name" = 'The Dynamic Gallery of Thoughts';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dimmu Borgir' AND "name" = 'Stormblast 2005';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2000-04-01' WHERE artist = 'Anorexia Nervosa' AND "name" = 'Drudenhaus';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2001-04-05' WHERE artist = 'Tvangeste' AND "name" = 'Damnation Of Regiomontum';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2002-06' WHERE artist = 'Dimmu Borgir' AND "name" = 'World Misanthropy';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2004-08' WHERE artist = 'Alghazanth' AND "name" = 'The Polarity Axiom';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dimmu Borgir' AND "name" = 'Stormblast';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2006-06-23' WHERE artist = 'Bishop Of Hexen' AND "name" = 'The Nightmarish Compositions';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2006-01' WHERE artist = 'Mirrorthrone' AND "name" = 'Carriers of Dust';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1995' WHERE artist = 'Eric Burdon' AND "name" = 'The Best Of Eric Burdon & War';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '1987' WHERE artist = 'M.O.D.' AND "name" = 'U.S.A. For M.O.D.';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'M.O.D.' AND "name" = 'U.S.A For M.O.D.';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1987-03-09' WHERE artist = 'D.R.I.' AND "name" = 'Crossover';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1987-05-15' WHERE artist = 'Cryptic Slaughter' AND "name" = 'Money Talks';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1989-10-10' WHERE artist = 'D.R.I.' AND "name" = 'Thrash Zone';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Skrewdriver' AND "name" = 'Blood And Honour';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Conchita Wurst' AND "name" = 'Die Große Chance';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009' WHERE artist = 'Киборг' AND "name" = 'Rabble';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2002' WHERE artist = 'Jew Slaughter' AND "name" = 'Alcoholocaust';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2010-03' WHERE artist = 'N.S.D.A.P.' AND "name" = 'Execution Of The Weak!';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2005-03' WHERE artist = 'Iron Youth' AND "name" = 'faith is stronger than fire';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1987' WHERE artist = 'Skullhead' AND "name" = 'White Warrior';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '1999' WHERE artist = 'Коловрат' AND "name" = 'Кровь Патриотов';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2007' WHERE artist = 'Schiffbruch 88' AND "name" = 'Melodien für 6 Milionen';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2014' WHERE artist = 'Lily Allen' AND "name" = 'White Christmas';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2005' WHERE artist = 'Сейтар' AND "name" = 'Смерть Ворогам';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2008' WHERE artist = 'ХОРСС' AND "name" = 'Сопротивляйся';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2005' WHERE artist = 'Warhammer' AND "name" = 'We Are the Law';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2011' WHERE artist = 'Gigi in Musica' AND "name" = '25 Jahre';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2010' WHERE artist = 'Киборг' AND "name" = 'Диктатура';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2005' WHERE artist = 'Киборг' AND "name" = 'Нет Россиянам!';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2000-08-17' WHERE artist = 'Вандал' AND "name" = 'Песни крови и почвы';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Conchita Wurst' AND "name" = 'Music';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2002' WHERE artist = 'Landser' AND "name" = 'tanzorchester immervoll';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2006' WHERE artist = 'ХОРСС' AND "name" = 'Непобедимое войско';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'In Extremo' AND "name" = 'Sünde ohne Zügel';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Finntroll' AND "name" = 'Trollhammaren EP';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2004-04-19' WHERE artist = 'Finntroll' AND "name" = 'Trollhammaren';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Arkona' AND "name" = 'Vozrozhdenie';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Arkona' AND "name" = 'Goi, Rode, Goi!';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2005-05' WHERE artist = 'Catafalque' AND "name" = 'Unique';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-07-29' WHERE artist = 'Epica' AND "name" = 'Universal Death Squad';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Planning for Burial' AND "name" = 'Below The House';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Fall of Efrafa' AND "name" = 'Inle';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2001-03-19' WHERE artist = 'Morgul' AND "name" = 'Sketch Of Supposed Murderer';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2009' WHERE artist = 'Deform' AND "name" = 'Дети телевизора';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2014-11-17' WHERE artist = '書上奈朋子' AND "name" = 'psalm';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '2002-10-27' WHERE artist = 'Racionais Mc''s' AND "name" = 'Nada Como Um Dia Apos O Outro Dia';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2014' WHERE artist = 'Chasin'' Crazy' AND "name" = 'That''s How We Do Summertime';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2016-06-03' WHERE artist = 'Dark Funeral' AND "name" = 'Where shadows forever reign';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2004' WHERE artist = 'Gestapo 666' AND "name" = 'Split';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2001' WHERE artist = 'The Prowlers' AND "name" = 'Hair today, gone tomorrow';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2007-02' WHERE artist = 'Satan''s Revenge On Mankind' AND "name" = '3-Way Penetration';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2020-02-24' WHERE artist = '100 gecs' AND "name" = 'ringtone (Remix) [feat. Charli XCX, Rico Nasty, Kero Kero Bonito]';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2001-04-20' WHERE artist = 'Океан Ельзи' AND "name" = 'Модель';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2019-02-01' WHERE artist = 'White Lies' AND "name" = 'FIVE';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2007-04-25' WHERE artist = 'Океан Ельзи' AND "name" = 'Міра';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2017-07-21' WHERE artist = 'Declan Mckenna' AND "name" = 'What Do You Think About The Car?';
UPDATE "public"."Album" SET "numberOfTracks" = 28, "date" = '2012-12-11' WHERE artist = 'Interpol' AND "name" = 'Turn On The Bright Lights: Tenth Anniversary Edition';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2006' WHERE artist = 'С.к.а.й.' AND "name" = 'Те, Що ТреБа';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2004' WHERE artist = 'Peter Doherty' AND "name" = 'For Lovers';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2005-09-22' WHERE artist = 'Океан Ельзи' AND "name" = 'Gloria';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2009-05-08' WHERE artist = 'Maxïmo Park' AND "name" = 'Quicken The Heart';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1998-09' WHERE artist = 'Океан Ельзи' AND "name" = 'Там, де нас нема';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Soviet Soviet' AND "name" = '2° [EP]';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1995-09-24' WHERE artist = 'Kazik na Żywo' AND "name" = 'Porozumienie Ponad Podziałami';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2007-08-07' WHERE artist = 'Public Enemy' AND "name" = 'How You Sell Soul To A Soulless People Who Sold Their Soul???';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1997' WHERE artist = 'Charlie Brown JR.' AND "name" = 'Transpiração Contínua Prolongada';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Limp Bizkit' AND "name" = 'Significant Other (Explicit Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-11-09' WHERE artist = 'Fever 333' AND "name" = 'Burn It';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Kid Rock' AND "name" = 'History Of Rock';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2019-01-18' WHERE artist = 'Fever 333' AND "name" = 'STRENGTH IN NUMB333RS';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1992' WHERE artist = 'Body Count' AND "name" = 'Cop Killer';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-05-23' WHERE artist = 'Fever 333' AND "name" = 'Trigger';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1996-01-24' WHERE artist = 'The Mad Capsule Markets' AND "name" = '4 Plugs';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2018-07-18' WHERE artist = 'Fever 333' AND "name" = 'Made an America';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Charlie Brown JR.' AND "name" = 'Desenvolvimento em Expans o Acumulada';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Сектор Газа' AND "name" = '2000 - Восставший из Ада';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2000-10-18' WHERE artist = 'Сектор Газа' AND "name" = 'Восставший Из Ада';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Lonely Island' AND "name" = 'The Lonely Island';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1997-08-12' WHERE artist = '(həd) p.e.' AND "name" = '(Hed) Planet Earth';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nyan Cat' AND "name" = 'Nyan  Cat';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2010-08-08' WHERE artist = 'Skull' AND "name" = 'Nancy';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1985-10-25' WHERE artist = 'Corrosion of Conformity' AND "name" = 'Animosity';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1986-07-26' WHERE artist = 'Cryptic Slaughter' AND "name" = 'Convicted';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2016-09-30' WHERE artist = 'Suicidal Tendencies' AND "name" = 'World Gone Mad';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1993-03-05' WHERE artist = 'Green Jellÿ' AND "name" = 'Cereal Killer Soundtrack';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1992-07-07' WHERE artist = '24-7 Spyz' AND "name" = 'Strength In Numbers';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1994-09-06' WHERE artist = 'Body Count' AND "name" = 'Born Dead';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1994-04' WHERE artist = 'Urban Dance Squad' AND "name" = 'Persona Non Grata';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2000-04-03' WHERE artist = 'H-Blockx' AND "name" = 'Ring Of Fire';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1995-01-24' WHERE artist = 'Such A Surge' AND "name" = 'UNDER PRESSURE';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1992-03-10' WHERE artist = 'Body Count' AND "name" = 'Body Count';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '1998-04-20' WHERE artist = 'Senser' AND "name" = 'Asylum';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2004-02-02' WHERE artist = 'Various Artists' AND "name" = 'WWE Originals';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'M.O.D.' AND "name" = 'U.S.A. For M.O.D';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2014-09-02' WHERE artist = 'Ratos De Porão' AND "name" = 'Século Sinistro';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2015-10-23' WHERE artist = 'Gazpacho' AND "name" = 'Molok';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2016-07-29' WHERE artist = 'Ghoul' AND "name" = 'Dungeon Bastards';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1993-05-31' WHERE artist = 'No Use for a Name' AND "name" = 'Daily Grind';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Cults' AND "name" = 'contagious spirits';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2017-09-15' WHERE artist = 'Prophets Of Rage' AND "name" = 'Prophets Of Rage';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1990-07-03' WHERE artist = 'Suicidal Tendencies' AND "name" = 'Lights... Camera... Revolution!';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2011' WHERE artist = 'Gangrena Gasosa' AND "name" = 'Se Deus é 10, Satanás é 666';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2004' WHERE artist = 'H-Blockx' AND "name" = 'More Than a Decade: Best of H-Blockx';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2006-06-06' WHERE artist = 'Various Artists' AND "name" = 'Cars Original Soundtrack (English Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 23, "date" = '1987-07-01' WHERE artist = 'Napalm Death' AND "name" = 'Scum';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '1988-09-16' WHERE artist = 'Napalm Death' AND "name" = 'From Enslavement To Obliteration';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '1989-05-29' WHERE artist = 'Repulsion' AND "name" = 'Horrified';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2015-01-27' WHERE artist = 'Napalm Death' AND "name" = 'Apex Predator - Easy Meat';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '1989-11-13' WHERE artist = 'Terrorizer' AND "name" = 'World Downfall';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1992-10-06' WHERE artist = 'Brutal Truth' AND "name" = 'Extreme Conditions Demand Extreme Responses';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1992-06-23' WHERE artist = 'Napalm Death' AND "name" = 'Utopia Banished';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1995-08-22' WHERE artist = 'Brujeria' AND "name" = 'Raza Odiada';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '1993-07-06' WHERE artist = 'Brujeria' AND "name" = 'Matando Güeros';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Brujeria' AND "name" = 'Mantando Gueros';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1997' WHERE artist = 'Brujeria' AND "name" = 'Marijuana';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2000-08-13' WHERE artist = 'Discordance Axis' AND "name" = 'The Inalienable Dreamless';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2008-01-09' WHERE artist = 'Rotten Sound' AND "name" = 'Cycles';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Anaal Nathrakh' AND "name" = 'Hell Is Empty, All the Devils Are Here';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2018-09-07' WHERE artist = 'Pig Destroyer' AND "name" = 'Head Cage';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2020-03-13' WHERE artist = 'The Garden' AND "name" = 'Kiss My Super Bowl Ring';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2005-04-25' WHERE artist = 'Napalm Death' AND "name" = 'The Code Is Red...Long Live the Code';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2006-05-29' WHERE artist = 'Totalt Jävla Mörker' AND "name" = 'Totalt Jävla Mörker';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2018-08-15' WHERE artist = 'Behemoth' AND "name" = 'God = Dog';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1997-01-20' WHERE artist = 'God Dethroned' AND "name" = 'The Grand Grimoire';
UPDATE "public"."Album" SET "numberOfTracks" = 22, "date" = '1992-01-01' WHERE artist = 'NOFX' AND "name" = 'Maximum Rocknroll';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1997-04-04' WHERE artist = 'Christie Front Drive' AND "name" = 'Christie Front Drive';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Funeral for a Friend' AND "name" = '7 Ways To Scream Your Name EP';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2006-01-03' WHERE artist = 'Dear Whoever' AND "name" = 'Sound the Trumpet';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Saosin' AND "name" = 'Capitol Demos';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2007-02-06' WHERE artist = 'Sparks The Rescue' AND "name" = 'The Secrets We Can''t Keep';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-12-17' WHERE artist = 'Sia' AND "name" = 'Cheap Thrills';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017' WHERE artist = 'Asking Alexandria' AND "name" = 'Where Did It Go?';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rebecca Black' AND "name" = 'Friday - Single';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2008-09-30' WHERE artist = 'In This Moment' AND "name" = 'The Dream (Limited Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2009-08-24' WHERE artist = 'Caliban' AND "name" = 'Say Hello To The Tragedy';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2008-11-25' WHERE artist = 'Furious Styles' AND "name" = 'Menace';
UPDATE "public"."Album" SET "numberOfTracks" = 34 WHERE artist = 'Combatwoundedveteran' AND "name" = 'This Is Not An All Erect, All-Red Neon Body';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1977-05' WHERE artist = 'Quartz' AND "name" = 'Quartz';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1980-06' WHERE artist = 'Samson' AND "name" = 'Head On';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1980-08-23' WHERE artist = 'Tygers of Pan Tang' AND "name" = 'Wild Cat';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1980-04-03' WHERE artist = 'Saxon' AND "name" = 'Wheels Of Steel';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1980-09-19' WHERE artist = 'White Spirit' AND "name" = 'White Spirit';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1980-06-30' WHERE artist = 'Girlschool' AND "name" = 'Demolition';
