UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2005-07-13' WHERE artist = 'King Leoric' AND "name" = 'Thunderforce';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2005-10' WHERE artist = 'Massacration' AND "name" = 'Gates of Metal Fried Chicken of Death';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2007' WHERE artist = 'Ёvil' AND "name" = 'Оружие Возмездия';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2010-09-29' WHERE artist = 'Iron Fire' AND "name" = 'Metalmorphosized';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1990' WHERE artist = 'Green Day' AND "name" = 'Slappy';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2001-11-14' WHERE artist = 'Bolt Thrower' AND "name" = 'Honour Valour Pride';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2016-04-29' WHERE artist = 'Emily Jane White' AND "name" = 'They Moved in Shadow All Together';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2016-11-04' WHERE artist = 'Alicia Keys' AND "name" = 'HERE';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Linkin Park' AND "name" = 'EP''s and Specials';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2010-08-10' WHERE artist = 'Linkin Park' AND "name" = 'A Decade Underground';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rusko Star' AND "name" = 'Unreleased (free album)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Edguy' AND "name" = 'Superheroes [EP]';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1994' WHERE artist = 'Аквариум' AND "name" = 'День Серебра';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1986-01' WHERE artist = 'Кино' AND "name" = 'Ночь';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1986' WHERE artist = 'Пикник' AND "name" = 'Иероглиф';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1989-06-08' WHERE artist = 'Гражданская оборона' AND "name" = 'Здорово и вечно';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1989-08-29' WHERE artist = 'Кино' AND "name" = 'Звезда по имени Солнце';
UPDATE "public"."Album" SET "numberOfTracks" = 29, "date" = '2005' WHERE artist = 'Егор Летов' AND "name" = 'Вершки и корешки';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1992-11' WHERE artist = 'ДДТ' AND "name" = 'Актриса Весна';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1992' WHERE artist = 'Игорь Тальков' AND "name" = 'Моя любовь';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1996-01' WHERE artist = 'Nautilus Pompilius' AND "name" = 'Крылья';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Various Artists' AND "name" = 'The-Best-2';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2000' WHERE artist = 'Настя' AND "name" = 'Брат 1';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1996' WHERE artist = 'Чиж & Co' AND "name" = 'Эрогенная зона';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Various Artists' AND "name" = 'Legend Russian Rock The Best 1';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1997-12' WHERE artist = 'Любэ' AND "name" = 'Песни о людях';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1998-04-01' WHERE artist = 'Сплин' AND "name" = 'Гранатовый альбом';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Кино' AND "name" = 'Черный альбом';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1998-07-30' WHERE artist = 'Tequilajazzz' AND "name" = 'Целлулоид';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1999-05-12' WHERE artist = 'Ляпис Трубецкой' AND "name" = 'Красота';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1999-11-29' WHERE artist = 'ДДТ' AND "name" = 'Просвистела';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2000-02' WHERE artist = 'ДДТ' AND "name" = 'Метель августа';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2001-03-26' WHERE artist = 'Пикник' AND "name" = 'Египтянин';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2001-11-09' WHERE artist = 'АлисА' AND "name" = 'Танцевать';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2002-02-20' WHERE artist = 'Аквариум' AND "name" = 'Сестра Хаос';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2001-03-25' WHERE artist = 'Сплин' AND "name" = '25-й Кадр';
UPDATE "public"."Album" SET "numberOfTracks" = 22, "date" = '2016-09-19' WHERE artist = 'Егор Летов' AND "name" = 'Всё как у людей';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2005-11-19' WHERE artist = 'Umaturman' AND "name" = 'А может это сон?...';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2006-03-09' WHERE artist = 'Звери' AND "name" = 'Когда мы вместе, никто не круче';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2006-11-28' WHERE artist = 'Ленинград' AND "name" = 'Бабье лето';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2006-03' WHERE artist = 'Пилот' AND "name" = 'Ч\Б';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007-05-23' WHERE artist = 'Lumen' AND "name" = 'Правда?';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2011-09-23' WHERE artist = 'Аквариум' AND "name" = 'Архангельск';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2012-10-22' WHERE artist = 'Ленинград' AND "name" = 'Рыба';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006-10-03' WHERE artist = 'Би-2' AND "name" = 'Moloko';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2013-09-23' WHERE artist = 'Lumen' AND "name" = 'Нет времени для любви';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Сплин' AND "name" = 'Резонанс, Часть 1';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2003-01' WHERE artist = 'Сергей Шнуров' AND "name" = 'Второй Магаданский';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2017-09-28' WHERE artist = 'ПорноФильмы' AND "name" = 'В Диапазоне Между Отчаянием и Надеждой';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2000-05-20' WHERE artist = 'Би-2' AND "name" = 'Би-2';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2000-03-28' WHERE artist = 'Zемфира' AND "name" = 'Прости Меня Моя Любовь';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2001-12-03' WHERE artist = 'Би-2' AND "name" = 'Мяу кисс ми';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2002-04-01' WHERE artist = 'Zемфира' AND "name" = 'Четырнадцать недель тишины';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1991-01-12' WHERE artist = 'Кино' AND "name" = 'Чёрный Альбом';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2004' WHERE artist = 'Пилот' AND "name" = 'Рыба, Крот и Свинья';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2004-03-22' WHERE artist = 'Би-2' AND "name" = 'Иномарки';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2009' WHERE artist = 'Би-2' AND "name" = 'Лунапарк';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2005-04-19' WHERE artist = 'Мумий Тролль' AND "name" = 'Слияние и Поглощение';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2011-12-01' WHERE artist = 'Би-2' AND "name" = 'Spirit';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2005-04-23' WHERE artist = 'ДДТ' AND "name" = 'Пропавший без вести';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1989-06-08' WHERE artist = 'Гражданская оборона' AND "name" = 'Здорово и вечно';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Би-2' AND "name" = 'Молоко';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1991' WHERE artist = 'Ноль' AND "name" = 'Песня о безответной любви к Родине';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2000-08-25' WHERE artist = 'Zемфира' AND "name" = 'До свидания...';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2012-10-01' WHERE artist = 'Lumen' AND "name" = 'На части';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2011-10-25' WHERE artist = 'ДДТ' AND "name" = 'Иначе';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1986' WHERE artist = 'Аквариум' AND "name" = 'Десять стрел';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1991-04-25' WHERE artist = 'АлисА' AND "name" = 'Шабаш';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1993' WHERE artist = 'Аукцыон' AND "name" = 'Птица';
UPDATE "public"."Album" SET "numberOfTracks" = 24, "date" = '1993' WHERE artist = 'Крематорий' AND "name" = 'Двойной альбом';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1994' WHERE artist = 'Аквариум' AND "name" = 'День Серебра';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2007' WHERE artist = 'П.Т.В.П.' AND "name" = 'Свобода Слова';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2003-10-27' WHERE artist = 'Atrox' AND "name" = 'Orgasm';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-06-27' WHERE artist = 'Jacob Sartorius' AND "name" = 'Hit Me Back feat. Blackbear';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2015-12-22' WHERE artist = 'Mirkwood' AND "name" = 'Mirkwood';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1998' WHERE artist = 'Nargaroth' AND "name" = 'Orke';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2000-12-05' WHERE artist = 'Sun of the Sleepless' AND "name" = 'Tausend kalte Winter';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2005-06-27' WHERE artist = 'Lurker of Chalice' AND "name" = 'Lurker of Chalice';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2010' WHERE artist = 'Starlit' AND "name" = 'Ataraxis';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Burzum' AND "name" = 'Sol Austan, Mani Vestan';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2008-05-01' WHERE artist = 'Panopticon' AND "name" = 'Panopticon';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2018-01-15' WHERE artist = 'Make a Change... Kill Yourself' AND "name" = 'IV';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-10-01' WHERE artist = 'Arckanum' AND "name" = 'Fran Marder (2009 Reissue)';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1998-09-12' WHERE artist = 'Elffor' AND "name" = 'Into The Dark Forest';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2005-06' WHERE artist = 'Lifelover' AND "name" = 'Promo 2005';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2005' WHERE artist = 'ColdWorld' AND "name" = 'Thestarsaredeadnow';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2008-05-12' WHERE artist = 'ColdWorld' AND "name" = 'The Stars Are Dead Now';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2007' WHERE artist = 'All The Cold' AND "name" = 'Dark Sorrows Of My Microcosm (demo)';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2016-12-21' WHERE artist = 'Hermóðr' AND "name" = 'The Howling Mountains';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2007' WHERE artist = 'Various Artists' AND "name" = 'Within The Church Of Thee Overlords II';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1999-10-12' WHERE artist = 'Sons of Otis' AND "name" = 'Templeball';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2010-10-22' WHERE artist = 'Amarok' AND "name" = 'Amarok';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2002-02-25' WHERE artist = 'Eternal Elysium' AND "name" = 'Share';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2004-05-05' WHERE artist = 'Ocean Chief' AND "name" = 'Tor';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2004-09-21' WHERE artist = 'Goatsnake' AND "name" = 'I + Dog Days';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006' WHERE artist = 'Electric Wizard' AND "name" = 'Pre-Electric Wizard 1989-1994';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2006-05-01' WHERE artist = 'Electric Wizard' AND "name" = 'Electric Wizard (2006 re-issue)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Electric Wizard' AND "name" = 'Come My Fanatics....';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2009-12-05' WHERE artist = 'The Graviators' AND "name" = 'The Graviators';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2009-04' WHERE artist = 'WhiteBuzz' AND "name" = 'Book Of Whyte';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2006-01' WHERE artist = 'Electric Wizard' AND "name" = 'Come My Fanatics.... (2006 Reissue)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2015-09-04' WHERE artist = 'Uncle Acid and the Deadbeats' AND "name" = 'The Night Creeper';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2018-10-31' WHERE artist = 'Belzebong' AND "name" = 'Light the Dankness';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2019-10-06' WHERE artist = 'Kal-el' AND "name" = 'Witches of Mars';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2008' WHERE artist = 'Elder' AND "name" = 'Elder';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Royal Thunder' AND "name" = 'Royal Thunder EP';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '1994-08' WHERE artist = 'Emperor' AND "name" = 'As the Shadows Rise';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1999' WHERE artist = 'Judas Iscariot' AND "name" = 'Distant In Solitary Night';
UPDATE "public"."Album" SET "numberOfTracks" = 29, "date" = '1999' WHERE artist = 'Behemoth' AND "name" = 'Chaotica - The Essence Of The Underworld - Thunders To Erupt';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2003-11' WHERE artist = 'Nargaroth' AND "name" = 'Geliebte des Regens';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Burzum' AND "name" = 'Burzum - Aske';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Moonblood' AND "name" = 'Supreme Black Force of German Steel';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2004-09' WHERE artist = 'Nargaroth' AND "name" = 'Prosatanica Shooting Angels';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2007-04-30' WHERE artist = 'Bestial Raids' AND "name" = 'Reversed Black Trinity';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2008-02-25' WHERE artist = 'Mord' AND "name" = 'Necrosodomic Abyss';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2003' WHERE artist = 'Inferius Torment' AND "name" = 'Prey From Burning church';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Anna Blue' AND "name" = 'Tellement seule';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2011-11' WHERE artist = 'Nefas Terra' AND "name" = 'Жизнь в Темноте';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2013-03-08' WHERE artist = 'Sarkrista' AND "name" = 'The Acheronian Worship';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2014-07-21' WHERE artist = '1349' AND "name" = 'Slaves';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2018-07' WHERE artist = 'Xasthur' AND "name" = 'Aestas Pretium MMXVIII';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-07' WHERE artist = 'Enoid' AND "name" = 'Ataraxiis';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2010-11' WHERE artist = 'Manierisme' AND "name" = '過去と悲哀 (The Past and Sorrow)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2011-12-20' WHERE artist = 'Panychida' AND "name" = 'Woodland Journey';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2004' WHERE artist = 'Ересь' AND "name" = 'Левиафан';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1998' WHERE artist = 'Михаил Круг' AND "name" = 'Мадам';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '1999' WHERE artist = 'Михаил Круг' AND "name" = 'Владимирский централ';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1999' WHERE artist = 'Михаил Круг' AND "name" = 'Роза';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Armagedda' AND "name" = 'I Am [EP]';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Hecate Enthroned' AND "name" = 'Upon Promeathean Shores';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2009' WHERE artist = 'Actum Inferni' AND "name" = 'Kres Panowania Ery Ludzi';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Viking Quest' AND "name" = 'on the streets of melancholy';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1993-04' WHERE artist = 'Therion' AND "name" = 'Symphony Masses: Ho Drakon Ho Megas';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2013-06-07' WHERE artist = 'Necronomicon' AND "name" = 'Rise of the Elder Ones';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1999-07' WHERE artist = 'Depresy' AND "name" = 'Sighting';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Waltari' AND "name" = 'Yeah! Yeah! Die! Die!';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2002' WHERE artist = 'Saruman' AND "name" = 'Ride on the Darkside';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Abigail Williams' AND "name" = 'Gallow Hill';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2002' WHERE artist = 'Darklord' AND "name" = 'Symphony Satanikka';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2016-03-18' WHERE artist = 'Necronomicon' AND "name" = 'advent of the human god';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2009-10-16' WHERE artist = 'Aeternitas' AND "name" = 'Holocaust of Reason';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2010-12-27' WHERE artist = 'The Bridal Procession' AND "name" = 'Astronomical Dimensions';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Arch Enemy' AND "name" = 'Khaos Legions [+Digital Booklet';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2015-04-24' WHERE artist = 'Whorion' AND "name" = 'The Reign of the 7th Sector';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2015-02-20' WHERE artist = 'Nightland' AND "name" = 'Obsession';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2019-03-08' WHERE artist = 'Meadows End' AND "name" = 'The Grand Antiquation';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2013-12-19' WHERE artist = 'Dam' AND "name" = 'Tales of the Mad King';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2019-03-01' WHERE artist = 'Perdition' AND "name" = 'The Arrival';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007' WHERE artist = 'Sonic Syndicate' AND "name" = 'Only Inhuman - Tour Edition';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2016-02-05' WHERE artist = 'Fleshgod Apocalypse' AND "name" = 'King';
UPDATE "public"."Album" SET "numberOfTracks" = 24, "date" = '2019-05-24' WHERE artist = 'Fleshgod Apocalypse' AND "name" = 'Veleno (Deluxe Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2008-03-17' WHERE artist = 'Septic Flesh' AND "name" = 'Communion';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2011-04-18' WHERE artist = 'Septic Flesh' AND "name" = 'The Great Mass';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2018-07-06' WHERE artist = 'Atrocity' AND "name" = 'OKKULT II';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Depressed Mode' AND "name" = '...For Death';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2012' WHERE artist = 'Everlasting Dawn' AND "name" = 'Of Frozen Hearts And Bloody Whores';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2021-06-11' WHERE artist = 'Path of Destiny' AND "name" = 'The Seed of All Evil';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2016-09-30' WHERE artist = 'Epica' AND "name" = 'The Holographic Principle';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Arkona' AND "name" = 'Vo Slavu Velikim';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1999-11-09' WHERE artist = 'Butterfly Temple' AND "name" = 'Велес';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2002-11-11' WHERE artist = 'Minas Morgul' AND "name" = 'Schwertzeit';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Eluveitie' AND "name" = 'Ven';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2004-12' WHERE artist = 'Alkonost' AND "name" = 'Between The Worlds';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2013' WHERE artist = 'Темнозорь' AND "name" = 'Folkstorm of the Azure Nights';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2005-10-23' WHERE artist = 'Сварга' AND "name" = 'Огни на курганах';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-10-27' WHERE artist = 'Eluveitie' AND "name" = 'Rebirth';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2006-12-01' WHERE artist = 'Minas Morgul' AND "name" = 'Todesschwadron Ost';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Eluveitie' AND "name" = 'Epona';
UPDATE "public"."Album" SET "numberOfTracks" = 26, "date" = '2008' WHERE artist = 'Eluveitie' AND "name" = 'Slania (Tour Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-06-28' WHERE artist = 'Eluveitie' AND "name" = 'Lvgvs';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2000' WHERE artist = 'Honor' AND "name" = 'W Płomieniach Wschodzącej Siły';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2012' WHERE artist = 'Ensiferum' AND "name" = 'Unsung Heroes (Digipack)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Arkona' AND "name" = 'Goi, Rode, Goi!!!';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2017-05-08' WHERE artist = 'Nokturnal Mortum' AND "name" = 'Істина';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Equilibrium' AND "name" = 'Turis Fratyr (+Demo 2003)';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2011-04-26' WHERE artist = 'Primordial' AND "name" = 'Redemption at the Puritan''s Hand';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2007-10-31' WHERE artist = 'Аркона' AND "name" = 'От Сердца к Небу';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Moonsorrow' AND "name" = 'Verisakeet';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2008-09-12' WHERE artist = 'Varg' AND "name" = 'Schildfront';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2010-01-03' WHERE artist = 'Темнозорь' AND "name" = 'Урочища Снов';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '1991-04' WHERE artist = 'Demilich' AND "name" = 'Regurgitation of Blood';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1992-08' WHERE artist = 'Demilich' AND "name" = 'The Echo';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2013' WHERE artist = 'Tool' AND "name" = 'Metal Heads';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Fantômas' AND "name" = 'Amenaza al Mundo';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Deftones' AND "name" = '2000-08-31: Two Days a Week Festival, Wieseen, Austria';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2014-09-26' WHERE artist = 'Meshuggah' AND "name" = 'I (Special Edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Deftones' AND "name" = 'Live in Hawaii: Music in High Places (DVD)';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2005' WHERE artist = 'It Will Come' AND "name" = '47';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2007-03-13' WHERE artist = 'Dååth' AND "name" = 'The Hinderers';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2010-06-29' WHERE artist = 'iwrestledabearonce' AND "name" = 'It''s All Remixed';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-03-23' WHERE artist = 'Jason Aldean' AND "name" = 'Tonight Looks Good On You';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2014-12-22' WHERE artist = 'Stasis' AND "name" = 'Bloodhoney';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Orbo' AND "name" = 'Demonstration 2003';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2016-04-01' WHERE artist = 'The Algorithm' AND "name" = 'Brute Force';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2015-04' WHERE artist = 'Thanatopsis' AND "name" = 'Requiem';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2016-11-11' WHERE artist = 'Animals as Leaders' AND "name" = 'The Madness Of Many';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2012-07-13' WHERE artist = 'TesseracT' AND "name" = 'One (Instrumental)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2010-04-23' WHERE artist = 'Deftones' AND "name" = 'Diamond Eyes (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2008-03-28' WHERE artist = 'Scars on Broadway' AND "name" = 'They Say';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2014-11-07' WHERE artist = 'Hacktivist' AND "name" = 'Deceive and Defy';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2010-06-08' WHERE artist = 'Nachtmystium' AND "name" = 'Addicts: Black Meddle Pt. II';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Leech' AND "name" = 'untitled';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2017-10-27' WHERE artist = 'Blut aus Nord' AND "name" = 'Deus Salutis Meæ';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'iwrestledabearonce' AND "name" = 'Next Visible Delicious';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2011-01-26' WHERE artist = 'DIR EN GREY' AND "name" = 'Lotus';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2011-11-11' WHERE artist = 'Blut aus Nord' AND "name" = '777 - The Desanctication';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Of Mice & Men' AND "name" = 'Back To Me';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1978-11' WHERE artist = 'Sham 69' AND "name" = 'That''s Life';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1979-08' WHERE artist = 'Angelic Upstarts' AND "name" = 'Teenage Warning';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1981-06' WHERE artist = 'Angelic Upstarts' AND "name" = '2,000,000 Voices';
UPDATE "public"."Album" SET "numberOfTracks" = 23, "date" = '1999' WHERE artist = 'The 4-Skins' AND "name" = 'Singles and Rarities';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1994' WHERE artist = 'Frank Sidebottom' AND "name" = 'Bollocks To Christmas';
UPDATE "public"."Album" SET "numberOfTracks" = 29, "date" = '1990-06-15' WHERE artist = 'The Adicts' AND "name" = 'Rockers Into Orbit';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1980-03-07' WHERE artist = 'Cockney Rejects' AND "name" = 'Greatest Hits Vol.1';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '1992' WHERE artist = 'The Adicts' AND "name" = 'Twenty-Seven';
UPDATE "public"."Album" SET "numberOfTracks" = 28, "date" = '1992' WHERE artist = 'The Business' AND "name" = 'The Best of The Business';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1982' WHERE artist = 'Abrasive Wheels' AND "name" = 'When The Punks Go Marching In';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1979-06' WHERE artist = 'Samson' AND "name" = 'Survivors';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1983-06-04' WHERE artist = 'Demon' AND "name" = 'The Plague';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2002-09-23' WHERE artist = 'Saxon' AND "name" = 'Heavy metal thunder';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1995-06-26' WHERE artist = 'The 3rd and the Mortal' AND "name" = 'Nightswan';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2014-08-04' WHERE artist = 'Mera' AND "name" = 'Nano EP';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1996-11-22' WHERE artist = 'Godgory' AND "name" = 'Shadow''s Dance';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Gathering' AND "name" = 'How to Measure a Planet? (disc 1)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1999-09-03' WHERE artist = 'Aesma Daeva' AND "name" = 'Here Lies One whose Name was Written in Water';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2002-01-25' WHERE artist = 'On Thorns I Lay' AND "name" = 'Angeldust';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Anathema' AND "name" = 'Resonance, Vol. 2';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2007-12-10' WHERE artist = 'Morgart' AND "name" = 'Die Türme';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Agalloch' AND "name" = 'The White (EP)';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2011-07-01' WHERE artist = 'Black Bile' AND "name" = 'Ascent vol. 1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'My Dying Bride' AND "name" = 'The Lies I Sire';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-09-18' WHERE artist = 'Betray-Ed' AND "name" = 'An Everlasting Drift';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007' WHERE artist = 'Betray-Ed' AND "name" = 'Dreamful Slumber';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2011-09-05' WHERE artist = 'Dylath-Leen' AND "name" = 'CABALE';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2011-07-01' WHERE artist = 'Katabasis' AND "name" = 'Katabasis';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Devin Townsend' AND "name" = 'Accelerated Evolution';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2015-10-19' WHERE artist = 'Perihelion' AND "name" = 'Zeng';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2016-11-01' WHERE artist = 'Clouds' AND "name" = 'Departe';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-01-10' WHERE artist = 'Vexes' AND "name" = 'Helion';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-01-10' WHERE artist = 'Vexes' AND "name" = 'Plasticine';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-01-09' WHERE artist = 'Vexes' AND "name" = 'Lift';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2018-02-22' WHERE artist = 'Vexes' AND "name" = 'Versions';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2013-10-18' WHERE artist = 'Monolithe' AND "name" = 'Monolithe IV';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2004-08-13' WHERE artist = 'It Will Come' AND "name" = 'Bound';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1985-04-07' WHERE artist = 'Demon' AND "name" = 'British Standard Approved';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2014-01-21' WHERE artist = 'Miss Fortune' AND "name" = 'Interstate 44';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2012-06-04' WHERE artist = 'Def Leppard' AND "name" = 'Pour Some Sugar On Me (2012)';
UPDATE "public"."Album" SET "numberOfTracks" = 36, "date" = '2009' WHERE artist = 'Europe' AND "name" = 'The Final Countdown: The Best Of Europe';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Allman Brothers Band' AND "name" = 'At Fillmore East (disc 1)';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1983-12' WHERE artist = 'Manilla Road' AND "name" = 'Crystal Logic';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1986-02-25' WHERE artist = 'Manilla Road' AND "name" = 'The Deluge';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1997-10-29' WHERE artist = 'Domine' AND "name" = 'Champion Eternal';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1998-04-15' WHERE artist = 'Virgin Steele' AND "name" = 'Invictus';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1999-06-25' WHERE artist = 'Metalium' AND "name" = 'Millenium Metal - Chapter One';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1999-08' WHERE artist = 'Stormlord' AND "name" = 'Supreme Art of War';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1999-06-01' WHERE artist = 'Domine' AND "name" = 'Dragonlord (Tales of the Noble Steel)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2008' WHERE artist = 'Equilibrium' AND "name" = 'HiFive - Nuclear Blast Presents Youngsters';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006-09-25' WHERE artist = 'Rhapsody' AND "name" = 'Triumph Or Agony';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rhapsody' AND "name" = 'Symphony Of Enchanted Lands II -The Dark Secret-';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2004-07-04' WHERE artist = 'Brocas Helm' AND "name" = 'Defender of the Crown';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2007-06-22' WHERE artist = 'Atlantean Kodex' AND "name" = 'The Pnakotic Demos';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rhapsody of Fire' AND "name" = 'Symphony Of Enchanted Lands II (The Dark Secret)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Epica' AND "name" = 'The Divine Conspiracy (Bonus Disc)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Moonsorrow' AND "name" = 'V: Havitetty';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2020-12-04' WHERE artist = 'Orden Ogan' AND "name" = 'Heart of the Android';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Epica' AND "name" = 'The Quantum Enigma (Track Commentary Version)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Summoning' AND "name" = 'Let Mortal Heroes Sing Your Fa';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Arkona' AND "name" = 'Ot Serdca K Nebu';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Absurd' AND "name" = 'Der Funfzehnjahrige Krieg';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Primordial' AND "name" = 'Redemption At The Puritans Hand';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2005-07-01' WHERE artist = 'Темнозорь' AND "name" = 'Вольницей в просинь ночей';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2005-10-02' WHERE artist = 'Невидь' AND "name" = 'Зов новой Гипербореи';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2003' WHERE artist = 'Butterfly Temple' AND "name" = 'Тропою крови по воле рода!';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'P.O.D.' AND "name" = 'When Angels And Serpents Dance';
UPDATE "public"."Album" SET "numberOfTracks" = 24, "date" = '2011' WHERE artist = 'Hollywood Undead' AND "name" = 'Swan Songs (Collector’s Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2011-06-28' WHERE artist = 'Limp Bizkit' AND "name" = 'Gold Cobra (Deluxe Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006' WHERE artist = 'Severe Storm' AND "name" = 'Severe Storm';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1998-01-01' WHERE artist = 'Katatonia' AND "name" = 'Saw You Drown';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1997-08-26' WHERE artist = 'Finger Eleven' AND "name" = 'Tip';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2000-11-27' WHERE artist = 'Katatonia' AND "name" = 'Tonight''s Decision (Re-Issue)';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2011-04-25' WHERE artist = 'Katatonia' AND "name" = 'Last Fair Deal Gone Down - 10th Anniversay Edition';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2007-03-26' WHERE artist = 'Katatonia' AND "name" = 'July';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2009-10-06' WHERE artist = 'This Misery Garden' AND "name" = 'Another Great Day On Earth';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2010-02' WHERE artist = 'Grey Waters' AND "name" = 'Below The Ever Setting Sun (EP)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nine Inch Nails' AND "name" = 'And All That Could Have Been (Still)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Katatonia' AND "name" = 'The Black Sessions (Disk 1)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Katatonia' AND "name" = 'The Black Sessions (Disk 2)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Katatonia' AND "name" = 'Night is the New Day (Special Tour Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2010-01-09' WHERE artist = 'Stone Sour' AND "name" = 'Audio Secrecy (Special Edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Thränenkind' AND "name" = 'Hope (Less)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Katatonia' AND "name" = 'Sanctitude (Live)';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2017-03-17' WHERE artist = 'Katatonia' AND "name" = 'The Fall of Hearts (Tour Edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Katatonia' AND "name" = 'The Longest Year [EP]';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2018-12-27' WHERE artist = 'Psychonaut 4' AND "name" = 'Children of The Night';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Katatonia' AND "name" = 'The Black Sessions CD2';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2008' WHERE artist = 'Magilum' AND "name" = 'Kirmizi Kar';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Katatonia' AND "name" = 'VICENZA APRIL 20 2003';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2008-06-20' WHERE artist = 'Klimt 1918' AND "name" = 'Just In Case We''ll Never Meet Again';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-11-03' WHERE artist = 'Beyond Light' AND "name" = 'The Scars Of Daylight';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2017-10-21' WHERE artist = 'King Apathy' AND "name" = 'King Apathy';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Pantera' AND "name" = 'Cowboys From Hell: 20th Anniversary Deluxe Edition (BGCDPT02)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Pride & Glory' AND "name" = 'Pride and Glory';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Down' AND "name" = '1995 - NOLA';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Zakk Wylde' AND "name" = 'Pride & Glory';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Various Artists' AND "name" = 'Sucking The 70''s (disc 2)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1998-04-18' WHERE artist = 'Sixty Watt Shaman' AND "name" = 'Ultra Electric';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2000-03-07' WHERE artist = 'Alabama Thunderpussy' AND "name" = 'Constellation';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1999-02-09' WHERE artist = 'Alabama Thunderpussy' AND "name" = 'River City Revival';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Down' AND "name" = 'II: A Bustle in Your Hedgerow';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2002-09-24' WHERE artist = 'Sixty Watt Shaman' AND "name" = 'Reason to Live';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Down' AND "name" = 'Down IV, Part II';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2002-03-26' WHERE artist = 'Canyon Creep' AND "name" = 'Hijack the World';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2004' WHERE artist = 'Parabellum' AND "name" = 'Stainless';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2004-03' WHERE artist = 'Stereochrist' AND "name" = 'Dead River Blues';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2006-06' WHERE artist = 'Stereochrist' AND "name" = 'Live Like A Man (Die As A God)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2006-12-15' WHERE artist = 'If He Dies He Dies' AND "name" = 'Conquistador';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Alabama Thunderpussy' AND "name" = 'Split';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2008-03-30' WHERE artist = 'Lucky Funeral' AND "name" = 'Lucky Funeral';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2008-11-25' WHERE artist = 'If He Dies He Dies' AND "name" = 'The Rise....The Fall';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2009-10-27' WHERE artist = 'Juggernaught' AND "name" = 'Act of Goat';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2010-01-26' WHERE artist = 'Divide the Sea' AND "name" = 'Man';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2012-11-23' WHERE artist = 'Dirt' AND "name" = 'Rock''n''roll Accident';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2014-01-31' WHERE artist = 'Methane' AND "name" = 'Southern Metal';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2015-02-18' WHERE artist = 'Corroded Realms' AND "name" = 'Widow';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Black Label Society' AND "name" = 'Alcohol Fueled Brewtality Disc 1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Black Label Society' AND "name" = 'Alcohol Fueled Brewtality...Live';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Black Label Society' AND "name" = 'Alcohol Fueled Brewtality Disc 2';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2013-07-11' WHERE artist = 'Stoner Train' AND "name" = 'Back In The Saddle (EP)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Baroness' AND "name" = 'The Red Album';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Weedeater' AND "name" = 'Jason the Dragon';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2014-05-13' WHERE artist = 'Down' AND "name" = 'Down IV Part II';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Death Ape Disco' AND "name" = 'Death Ape Disco';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2009' WHERE artist = 'Death Denied' AND "name" = 'Booze''n''roll';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2009-02-17' WHERE artist = 'Conducting From The Grave' AND "name" = 'When Legends Become Dust';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2000-11-01' WHERE artist = 'Autumnblaze' AND "name" = 'Bleak';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2007-10-31' WHERE artist = 'Shamrain' AND "name" = 'Goodbye to All That';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2010-03-17' WHERE artist = 'Thränenkind' AND "name" = 'Eine Momentaufnahme - Der Rest ist nur Einsamkeit';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2017' WHERE artist = 'Katatonia' AND "name" = 'The Great Cold Distance (10th Anniversary Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2008-12-02' WHERE artist = 'Beyond Light' AND "name" = 'The Blessing Of A Dead Sun';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1992-10-21' WHERE artist = 'Jackyl' AND "name" = 'Jackyl';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2002-10-21' WHERE artist = 'Sourvein' AND "name" = 'Will To Mangle';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2010-02-20' WHERE artist = 'Dirt Communion' AND "name" = 'Antique Mechanic LP';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Down' AND "name" = 'Down IV, Part I: The Purple EP';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2008' WHERE artist = 'Rock''n''Raw Bottled Band' AND "name" = '0,5L';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Various Artists' AND "name" = 'Lucky 313';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2002' WHERE artist = 'Latterman' AND "name" = 'Turn Up the Punk, We''ll Be Singing';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2017-10-24' WHERE artist = 'Sadness' AND "name" = 'Sun into Water';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2011-12-13' WHERE artist = 'Azis' AND "name" = 'Sen Trope';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2019-12-12' WHERE artist = 'Dopamine' AND "name" = 'Dying Away in the Deep Fall';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2010' WHERE artist = 'Silence of the Old Man' AND "name" = 'Carencia De Ausencia';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2012-02-28' WHERE artist = 'Infinitas' AND "name" = 'Journey to Infinity';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2018-11-02' WHERE artist = 'Sylvaine' AND "name" = 'Atoms Aligned, Coming Undone';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2016-03-08' WHERE artist = 'Show Me A Dinosaur' AND "name" = 'show me a dinosaur';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Alcest' AND "name" = 'Ecailles De Lune';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2010-06-14' WHERE artist = 'Lantlôs' AND "name" = '.neon';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2010-07-15' WHERE artist = 'Cold Body Radiation' AND "name" = 'The Great White Emptiness';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2001-06-16' WHERE artist = 'The Beach Boys' AND "name" = 'Surfin'' USA (Remastered)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1965' WHERE artist = 'The Animals' AND "name" = 'The Most of the Animals';
UPDATE "public"."Album" SET "numberOfTracks" = 23, "date" = '1989' WHERE artist = 'Link Wray' AND "name" = 'The Original Rumble';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Lulu Santos' AND "name" = 'Toca Lulu';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '1966-10-14' WHERE artist = 'The Easybeats' AND "name" = 'Friday on My Mind';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '1996' WHERE artist = 'The Beach Boys' AND "name" = '20 Great Love Songs';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '1993' WHERE artist = 'Shadowy Men On A Shadowy Planet' AND "name" = 'Sport Fishin''';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '1995-10-16' WHERE artist = 'Various Artists' AND "name" = 'The Best of Lou Reed & The Velvet Underground';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Beach Boys' AND "name" = 'Good Vibrations: Thirty Years of the Beach Boys (disc 2)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1990-01-16' WHERE artist = 'Joan Jett and the Blackhearts' AND "name" = 'The Hit List';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1963-06' WHERE artist = 'Dick Dale' AND "name" = 'King of the Surf Guitar';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '1963' WHERE artist = 'The Marketts' AND "name" = 'Out of Limits!';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Phantom Surfers' AND "name" = 'The Great Surf Trash Of ´97';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1964-07' WHERE artist = 'The Beach Boys' AND "name" = 'All Summer Long';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1986' WHERE artist = 'Dick Dale' AND "name" = 'The Best of Dick Dale & His Del-tones';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '1976' WHERE artist = 'The Surfaris' AND "name" = 'Surfers Rule';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Tornados' AND "name" = 'Telstar: The Complete Tornados (disc 1)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Tommy Tutone' AND "name" = '867-5309 Jenny';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016' WHERE artist = 'The Shins' AND "name" = 'Name For You';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Satan''s Pilgrims' AND "name" = 'Plymouth Rock: The Best of Satan''s Pilgrims (disc 1)';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2011-10-21' WHERE artist = 'King Gizzard & The Lizard Wizard' AND "name" = 'Willoughby''s Beach';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1964-03-23' WHERE artist = 'The Beach Boys' AND "name" = 'Shut Down Volume 2';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1962-11' WHERE artist = 'Dick Dale' AND "name" = 'Surfer''s Choice';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '1963' WHERE artist = 'The Trashmen' AND "name" = 'Surfin'' Bird';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2015-03-02' WHERE artist = 'SoKo' AND "name" = 'My Dreams Dictate My Reality';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2000' WHERE artist = 'The Black Crowes' AND "name" = 'Greatest Hits 1990-1999: A Tribute To A Work In Progress';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '%(disc %)';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '% CD_';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '% CD__';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2011-06-15' WHERE artist = 'Nocturnal Depression' AND "name" = 'Suicidal thoughts';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006-09-12' WHERE artist = 'Xasthur' AND "name" = 'Subliminal Genocide';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2004-12-12' WHERE artist = 'Veil' AND "name" = 'Dolor';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2005-06-16' WHERE artist = 'Wigrid' AND "name" = 'Die Asche Eines Lebens';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2006-08-02' WHERE artist = 'Peste Noire' AND "name" = 'La Sanie des siècles - Panégyrique de la dégénérescence';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2006-08-20' WHERE artist = 'Life is Pain' AND "name" = 'Bloody Melancholy';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2008-12-11' WHERE artist = 'Totalselfhatred' AND "name" = 'Totalselfhatred';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2013-09-23' WHERE artist = 'Shining' AND "name" = '8 ½ - Feberdrömmar I Vaket Tillstånd';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2016-04-30' WHERE artist = 'Kalmankantaja' AND "name" = 'Tyhjyys';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2005-06-23' WHERE artist = 'Make a Change... Kill Yourself' AND "name" = 'Make A Change... Kill Yourself';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Happy Days' AND "name" = 'Happiness Stops Here...';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2009-07-23' WHERE artist = 'Happy Days' AND "name" = 'Happiness Stops Here';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2020-02-14' WHERE artist = 'Justin Bieber' AND "name" = 'Changes';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rhapsody' AND "name" = 'Ascending To Infinity';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Manowar' AND "name" = 'The Lord Of Steel (Hammer Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2010-10-26' WHERE artist = 'Viking Skull' AND "name" = 'Heavy Metal Thunder';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2016-07-20' WHERE artist = 'Rhapsody of Fire' AND "name" = 'Dawn Of Victory';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Battlelore' AND "name" = 'Swords Song';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2016-11-30' WHERE artist = 'Rhapsody of Fire' AND "name" = 'Power Of The Dragonflame';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2016-09-30' WHERE artist = 'S U R V I V E' AND "name" = 'RR7349';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1985-09-20' WHERE artist = 'Icon' AND "name" = 'Night of the Crime';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1999-09-10' WHERE artist = 'Crimson Glory' AND "name" = 'Astronomica';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2002' WHERE artist = 'Virtuocity' AND "name" = 'Secret Visions';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1997-09-03' WHERE artist = 'Yngwie Malmsteen' AND "name" = 'Facing The Animal';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2019-10-02' WHERE artist = 'Eclipse' AND "name" = 'PARADIGM';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Stratovarius' AND "name" = '2001 - Intermission';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Amorphis' AND "name" = 'Circle (Bonus Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2003-04-28' WHERE artist = 'Passenger' AND "name" = 'Passenger';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2003-01-27' WHERE artist = 'Stratovarius' AND "name" = 'Elements Pt.1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Aina' AND "name" = 'Days Of Rising Doom - The Metal Opera - Disc 2 : The Story Of Aina';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2011-01-14' WHERE artist = 'Apocalyptica' AND "name" = 'Not Strong Enough';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007-08-22' WHERE artist = 'Andre Matos' AND "name" = 'Time To Be Free';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2004-10-01' WHERE artist = 'Stormgarde' AND "name" = 'Demo 2004';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2009-05-25' WHERE artist = 'Pathosray' AND "name" = 'Sunless Skies';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2015-04-17' WHERE artist = 'Falconer' AND "name" = 'Falconer (Ultimate Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2016-08-26' WHERE artist = 'Delain' AND "name" = 'Moonbathers (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2016-04-01' WHERE artist = 'Thunderstone' AND "name" = 'Apocalypse Again';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2017-03-08' WHERE artist = 'Eclipse' AND "name" = 'Monumentum';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Edu Falaschi' AND "name" = 'Almah';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007-06-04' WHERE artist = 'Kamelot' AND "name" = 'Ghost Opera (Limited Edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Avantasia' AND "name" = 'Ghostlights (Bonus Version)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Elvenking' AND "name" = 'Two Tragedy Poets';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1986' WHERE artist = 'Lucifer''s Heritage' AND "name" = 'Battalions Of Fear';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2017-03-03' WHERE artist = 'Within the Ruins' AND "name" = 'Halfway Human';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2017-02-24' WHERE artist = 'Born of Osiris' AND "name" = 'The Eternal Reign';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-07-20' WHERE artist = 'Annisokay' AND "name" = 'Coma Blue';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-07-04' WHERE artist = 'Time, The Valuator' AND "name" = 'In Control';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2018-07-27' WHERE artist = 'Otep' AND "name" = 'Kult 45';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Adolescents' AND "name" = 'The Adolescents';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2015-04-11' WHERE artist = 'Violet Cold' AND "name" = 'Desperate Dreams';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2013-07' WHERE artist = 'Ambersmoke' AND "name" = 'Une femme est une femme';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1983-07' WHERE artist = 'Joan Jett and the Blackhearts' AND "name" = 'Album';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '2015-11-13' WHERE artist = 'Swallow the Sun' AND "name" = 'Songs from the North I, II & III';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Mastodon' AND "name" = 'Jonah Hex';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Ayreon' AND "name" = 'Flight of the Migrator';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-08-10' WHERE artist = 'Dreamshade' AND "name" = 'Lost In The Echo';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-06-01' WHERE artist = 'Bury Tomorrow' AND "name" = 'Knife of Gold';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-08-19' WHERE artist = 'Affiance' AND "name" = 'Africa';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-04-28' WHERE artist = 'Our Hollow, Our Home' AND "name" = 'Shape of You';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2014-10-29' WHERE artist = 'The Animal In Me' AND "name" = 'Iggy Azalea Black Widow';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-06-14' WHERE artist = 'The Animal In Me' AND "name" = 'Don''t Let Me Down';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2014-09-20' WHERE artist = 'The Animal In Me' AND "name" = 'I Knew You Were Trouble';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-02-06' WHERE artist = 'The Animal In Me' AND "name" = 'The Heart Wants What It Wants';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2014-09-23' WHERE artist = 'The Animal In Me' AND "name" = 'Burn';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-03-20' WHERE artist = 'The Animal In Me' AND "name" = 'Starboy';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-12-05' WHERE artist = 'The Animal In Me' AND "name" = 'Heathens';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2000-05-03' WHERE artist = 'Britney Spears' AND "name" = 'Oops!... I Did It Again';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2002' WHERE artist = 'Кино' AND "name" = 'Легенды Русского Рока: Кино: выпуск 2';
UPDATE "public"."Album" SET "numberOfTracks" = 23, "date" = '2005' WHERE artist = 'Егор Летов' AND "name" = 'Русское Поле Эксперимента (Акустика)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1995' WHERE artist = 'Чиж & Co' AND "name" = 'О Любви';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2004-11-11' WHERE artist = 'П.Т.В.П.' AND "name" = '2084';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2001' WHERE artist = 'Игорь Тальков' AND "name" = 'Я вернусь';
UPDATE "public"."Album" SET "numberOfTracks" = 36, "date" = '1992' WHERE artist = 'Гражданская оборона' AND "name" = 'Всё идёт по плану';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2004' WHERE artist = 'Lumen' AND "name" = 'Три пути';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1993' WHERE artist = 'Любэ' AND "name" = 'Зона Любэ';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1989-07-12' WHERE artist = 'Гражданская оборона' AND "name" = 'Песни радости и счастья';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1996' WHERE artist = 'АлисА' AND "name" = 'Jazz';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2013-11-08' WHERE artist = 'Final Sacrifice' AND "name" = 'Follow';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2015-03-03' WHERE artist = 'Quake' AND "name" = 'Insurrection';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2011-03-15' WHERE artist = 'Written In Blood' AND "name" = 'We Are Divinity';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2010-05' WHERE artist = 'Feed Her to the Sharks' AND "name" = 'The Beauty Of Falling';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2012-09-26' WHERE artist = 'A HERO WILL STAND' AND "name" = 'Road To Victory';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2013-04-21' WHERE artist = 'The Greatness Design' AND "name" = 'Pillars of Creation';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2016-07-01' WHERE artist = 'Circle Of Contempt' AND "name" = 'Structures for Creation';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2011-05-24' WHERE artist = 'Within the Ruins' AND "name" = 'Omen EP';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2014-11-17' WHERE artist = 'August Burns Red' AND "name" = 'Punk Goes Pop, Vol. 6';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sikth' AND "name" = 'The Trees Are Dead & Dried Out, Wait For Something Wild';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2013-10-01' WHERE artist = 'Conducting From The Grave' AND "name" = 'Conducting From The Grave';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2013' WHERE artist = 'Scarlet Skies' AND "name" = 'No Warning Shot';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2005' WHERE artist = 'Veil of Maya' AND "name" = 'Veil Of Maya';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2013-09-12' WHERE artist = 'Volumes' AND "name" = 'Vahle';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2012-04-20' WHERE artist = 'Dead Air' AND "name" = 'Ethereal';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2013' WHERE artist = 'Premonition' AND "name" = 'Suicide Civilization';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2009-09-17' WHERE artist = 'Adonai' AND "name" = 'Red Letters';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Veil of Maya' AND "name" = 'download';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Erra' AND "name" = 'Download';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Erra' AND "name" = 'musik';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'August Burns Red' AND "name" = 'ClearMusicDownloader';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Within the Ruins' AND "name" = 'ClearMusicDownloader';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Veil of Maya' AND "name" = 'ClearMusicDownloader';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Circle Of Contempt' AND "name" = 'Download';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2019-11-13' WHERE artist = 'Billie Eilish' AND "name" = 'everything i wanted';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2021-04-09' WHERE artist = 'Doja Cat' AND "name" = 'Kiss Me More (feat. SZA)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-09-07' WHERE artist = 'Kanye West' AND "name" = 'I Love It';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2011-02-08' WHERE artist = 'Jennifer Lopez' AND "name" = 'On the Floor';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '%  %';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1996-08-15' WHERE artist = 'White Zombie' AND "name" = 'Supersexy Swingin'' Sounds';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2015-05-01' WHERE artist = 'Satyricon' AND "name" = 'Live at the Opera';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '1976-02' WHERE artist = 'The Residents' AND "name" = 'The Third Reich ''N Roll';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2001-03-13' WHERE artist = 'Aleister Crowley' AND "name" = 'Satanic Verses';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2002-08-17' WHERE artist = 'Дом Кукол' AND "name" = 'Не Разбирать и не Давать Детям';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Кино' AND "name" = 'Акустический концерт';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2004-08-17' WHERE artist = 'Lumen' AND "name" = 'Три пути';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2011-05-19' WHERE artist = 'Смысловые галлюцинации' AND "name" = 'Сделано в темноте';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Black Sabbath' AND "name" = 'The Mob Rules';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '1998-10-27' WHERE artist = 'Mötley Crüe' AND "name" = 'Greatest Hits';
-- UPDATE "public"."Album" SET "numberOfTracks" = , "date" =  WHERE artist =  AND "name" =
