UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2016-02' WHERE artist = 'Dark Fury' AND "name" = 'This Story Happened Before';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '% (bonus disc)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Blind Guardian' AND "name" = 'Nighfall In Middle Earth';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Blind Guardian' AND "name" = 'Nightfall in Middle-Earch';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Blind Guardian' AND "name" = 'Nightfall in Middle Earth';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Lacuna Coil' AND "name" = 'Lacuna Coil - EP';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rhapsody' AND "name" = 'The Dark Secret EP';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2009' WHERE artist = 'Synthesia' AND "name" = 'The Time Travellers';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Synthesia' AND "name" = 'Tribute to Influences';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2007' WHERE artist = 'Synthesia' AND "name" = 'Rain of Light';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2006-05-15' WHERE artist = 'Manigance' AND "name" = 'L''OMBRE ET LA LUMIERE';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2009-02' WHERE artist = 'Angellore' AND "name" = 'Elégies aux Âmes Perdues';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Synthesia' AND "name" = 'Hero?';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dornfall' AND "name" = 'Dornfall - Precieux Secret';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1982' WHERE artist = 'Voie De Fait' AND "name" = 'Ange ou démon';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1985-04' WHERE artist = 'ADX' AND "name" = 'Exécution';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1985-03' WHERE artist = 'Killers' AND "name" = '...Fils De La Haine';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1999-05-09' WHERE artist = 'Killers' AND "name" = '109';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2001-02-06' WHERE artist = 'Dyslesia' AND "name" = 'Who Dares Wins';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2001-11-24' WHERE artist = 'Aes Dana' AND "name" = 'La Chasse Sauvage';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2003-06-03' WHERE artist = 'Dagoba' AND "name" = 'Dagoba';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007-11-15' WHERE artist = 'Jadallys' AND "name" = 'Labyrinthes';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2003-03-25' WHERE artist = 'Aesthesia' AND "name" = 'Drawn to the flame';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2006-06-06' WHERE artist = 'Auspex' AND "name" = 'Mysteries Of The Stars';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Melvins' AND "name" = 'A Senile Animal';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Refused' AND "name" = 'Shape Of Punk To Come';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Set Your Goals' AND "name" = 'Mutiny';
UPDATE "public"."Album" SET "numberOfTracks" = 26, "date" = '2011-09-30' WHERE artist = 'A Day to Remember' AND "name" = 'For Those Who Have Heart Re-Issue';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Comeback Kid' AND "name" = 'Broadcasting...';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Norma Jean' AND "name" = 'The Anti-Mother';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Norma Jean' AND "name" = '-vs- the Anti Mother';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Reverend Bizarre' AND "name" = 'So Long Suckers';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Reverend Bizarre' AND "name" = 'II - Crush the Insects';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Reverend Bizarre' AND "name" = 'In the Rectory of the Bizarre';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Candlemass' AND "name" = 'Epicus, Doomicus, Metallicus';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Om' AND "name" = 'Live in Jerusalem';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2014-08-12' WHERE artist = 'Black Sabbath' AND "name" = 'Master of Reality (2014 Remaster)';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1986' WHERE artist = 'Paul Chain Violet Theatre' AND "name" = 'In the Darkness';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '1978' WHERE artist = 'Black Sabbath' AND "name" = 'Never Say Die';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1984-02' WHERE artist = 'Saint Vitus' AND "name" = 'Saint Vitus';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1985-08' WHERE artist = 'Saint Vitus' AND "name" = 'Hallow''s Victim';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1988-08-22' WHERE artist = 'Saint Vitus' AND "name" = 'Mournful Cries';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1992-09' WHERE artist = 'Saint Vitus' AND "name" = 'C.O.D.';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1994-04' WHERE artist = 'Pentagram' AND "name" = 'Be Forewarned';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2015-04-14' WHERE artist = 'Mourn' AND "name" = 'Mourn';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1997' WHERE artist = 'Scald' AND "name" = 'Will of the Gods is Great Power';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1999-09-09' WHERE artist = 'Reverend Bizarre' AND "name" = 'Slice of Doom';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2003-02-07' WHERE artist = 'Mirror of Deception' AND "name" = 'Conversion';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2003-02-07' WHERE artist = 'Orodruin' AND "name" = 'Epicurean Mass';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1991-09-22' WHERE artist = 'Blood Farmers' AND "name" = 'Permanent Brain Damage';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2006-06-19' WHERE artist = 'The River' AND "name" = 'Drawing Down The Sun';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2008-06-18' WHERE artist = 'Revelation' AND "name" = 'Release';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2008-05-28' WHERE artist = 'Om' AND "name" = 'Live At Jerusalem';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2008-04-24' WHERE artist = 'Dantesco' AND "name" = 'Pagano';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2009-11-27' WHERE artist = 'Rituals of the Oak' AND "name" = 'Hour Of Judgement';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2010-04-12' WHERE artist = 'Witchsorrow' AND "name" = 'Witchsorrow';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2011-06-01' WHERE artist = 'Evangelist' AND "name" = 'In Partibus Infidelium';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2012-05-28' WHERE artist = 'Witchsorrow' AND "name" = 'God Curse Us';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rammstein' AND "name" = 'Reise Reise';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rob Zombie' AND "name" = 'Hellbilly';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rob Zombie' AND "name" = 'Past, Present and Future [w/ Bonus';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rob Zombie' AND "name" = 'Past, Present and Future';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Marilyn Manson' AND "name" = 'Last Tour On Earth';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'White Zombie' AND "name" = 'Astro-Creep 2000';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Eisbrecher' AND "name" = 'Antikorper';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Eisbrecher' AND "name" = 'Antikoerper';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'KMFDM' AND "name" = 'WW III';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2005-11-14' WHERE artist = 'Mägo de Oz' AND "name" = 'Gaia II La Voz Dormida';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1981-04-27' WHERE artist = 'Barón Rojo' AND "name" = 'Larga Vida Al Rock and Roll';
UPDATE "public"."Album" SET "numberOfTracks" = 22, "date" = '2005-10-24' WHERE artist = 'Gigatron' AND "name" = 'Mar de Cuernos';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1986' WHERE artist = 'Angeles del Infierno' AND "name" = 'Joven Para Morir';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Ars Amandi' AND "name" = 'Autoctono';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1987' WHERE artist = 'Barón Rojo' AND "name" = 'Tierra De Nadie';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2001' WHERE artist = 'Avalanch' AND "name" = 'El Angel Caido';
UPDATE "public"."Album" SET "numberOfTracks" = '10', "date" = '1982-02-22' WHERE artist = 'Barón Rojo' AND "name" = 'Volumen Brutal';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1984-03-12' WHERE artist = 'Obús' AND "name" = 'El Que Más';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2001' WHERE artist = 'Barón Rojo' AND "name" = '20+';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-04-11' WHERE artist = 'Leo' AND "name" = 'Turn Down for What (Metal Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2017-09-08' WHERE artist = 'Leo' AND "name" = 'Leo Metal Covers, Vol. 15';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2015-05-11' WHERE artist = 'Leo' AND "name" = 'Scatman - Metal Cover';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1985-03-01' WHERE artist = 'Angeles del Infierno' AND "name" = 'Diabolicca';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '1987-04' WHERE artist = 'Obus' AND "name" = 'En Directo';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1989' WHERE artist = 'Angeles del Infierno' AND "name" = '666';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1988-04' WHERE artist = 'Muro' AND "name" = 'Telón de Acero';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1989-09' WHERE artist = 'Muro' AND "name" = 'Mutant Hunter';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2002' WHERE artist = 'Hamlet' AND "name" = 'Hamlet';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1994' WHERE artist = 'Ktulu' AND "name" = 'Orden Genetico';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1997-01' WHERE artist = 'Ktulu' AND "name" = 'Confrontacion';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2017-11-15' WHERE artist = 'Leo' AND "name" = 'Metal, Vol. 16';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2018-04-13' WHERE artist = 'Leo' AND "name" = 'Leo Metal, Vol. 18';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-12-17' WHERE artist = 'Leo' AND "name" = 'Baby´s On Fire (Metal Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2015-10-31' WHERE artist = 'Leo' AND "name" = 'Leo Metal Covers Volume 3';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2014-10-31' WHERE artist = 'Leo' AND "name" = 'Leo Metal Covers Volume 2';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2014-10-31' WHERE artist = 'Leo' AND "name" = 'Leo Metal Covers Volume 1';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2016-02-23' WHERE artist = 'Leo' AND "name" = 'Leo Metal Covers Volume 7';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2014-11-01' WHERE artist = 'Leo' AND "name" = 'Leo Metal Covers Volume 4';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2016-05-02' WHERE artist = 'Leo' AND "name" = 'Leo Metal Covers Volume 8';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2015-10-15' WHERE artist = 'Leo' AND "name" = 'Leo Metal Covers Volume 5';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2016-07-11' WHERE artist = 'Leo' AND "name" = 'Leo Metal Covers Volume 9';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2018-01-19' WHERE artist = 'Leo' AND "name" = 'Leo Metal Volume 17';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2015-12-15' WHERE artist = 'Leo' AND "name" = 'Leo Metal Covers Volume 6';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1999-04' WHERE artist = 'Avalanch' AND "name" = 'Llanto de un héroe';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1999-09' WHERE artist = 'Ktulu' AND "name" = 'Ktulu';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2002-01' WHERE artist = 'Azrael' AND "name" = 'Dimension IV';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2002-03-01' WHERE artist = 'Saratoga' AND "name" = 'Agotaras';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2003-09-22' WHERE artist = 'Sphinx' AND "name" = 'Mar de Dioses';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2003-03-10' WHERE artist = 'Ars Amandi' AND "name" = 'Autóctono';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2003-02-24' WHERE artist = 'Tierra Santa' AND "name" = 'Indomable';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2003-04-28' WHERE artist = 'Soziedad Alkoholika' AND "name" = 'Tiempos Oscuros';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2005-03-10' WHERE artist = 'Ars Amandi' AND "name" = 'Camino Al Destino';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-04-20' WHERE artist = 'Zenobia' AND "name" = 'Alma de Fuego';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-11-30' WHERE artist = 'Leo' AND "name" = 'Tubthumping (Metal Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-12-05' WHERE artist = 'Leo' AND "name" = 'Run Rudolph Run (Metal Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2017-06-24' WHERE artist = 'Leo' AND "name" = 'Leo Metal Covers, Vol. 14';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-10-24' WHERE artist = 'Leo' AND "name" = 'This is Halloween (Metal Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-09-26' WHERE artist = 'Leo' AND "name" = 'Hey Ya! (Metal Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-11-08' WHERE artist = 'Leo' AND "name" = 'Rehab (Metal Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1992-09-21' WHERE artist = 'Awesome 3' AND "name" = 'Don’t Go';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '% [Disc._]';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Black Flag' AND "name" = 'First Four Years';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '1991' WHERE artist = 'SL2' AND "name" = 'DJ’s Take Control';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Prodigy' AND "name" = 'Fire - Jericho';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1995' WHERE artist = 'Various Artists' AND "name" = 'XL-Recordings: The 5th Chapter';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'ManiX' AND "name" = '12"';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Roadrunner United' AND "name" = 'The All-Star Session';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Roadrunner United' AND "name" = 'The All Star Sessions';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'All That Remains' AND "name" = 'Fall Of Ideals';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bullet for My Valentine' AND "name" = 'Scream Aim Fire Deluxe Edition';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bullet for My Valentine' AND "name" = 'Scream Aim Fire EP';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Five Finger Death Punch' AND "name" = 'Way Of The Fist';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = '36 Crazyfists' AND "name" = 'A Snow Capped Romance (Advance';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bring Me the Horizon' AND "name" = 'There Is A Hell Believe Me I''ve Seen It. There Is A Heaven Let''s Keep It A Secret.';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bring Me the Horizon' AND "name" = 'There Is A Hell Believe Me I''ve Seen It. There Is A Heaven Let''s Keep It A Secret';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bring Me the Horizon' AND "name" = 'There Is A Hell, Believe Me I''ve Seen It. There Is A Heaven, Let''s Keep It A Secret.';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Avenged Sevenfold' AND "name" = '2001 - Sounding the Seventh Trumpet';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Avenged Sevenfold' AND "name" = '2003 - Waking The Fallen';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Queensrÿche' AND "name" = 'Operation Mindcrime';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Tool' AND "name" = 'Lateralis';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dream Theater' AND "name" = 'Six Degrees of Inner Turbulance';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Ayreon' AND "name" = 'Human Equation';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Tool' AND "name" = '10000 Days';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dream Theater' AND "name" = 'Scenes of a Memory';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2013-09-24' WHERE artist = 'Dream Theater' AND "name" = 'Dream Theater';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-09-29' WHERE artist = 'Paramore' AND "name" = 'Brand New Eyes';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2005-09-25' WHERE artist = 'Panic at the Disco' AND "name" = 'A Fever You Can''t Sweat Out';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = '30 Seconds to Mars' AND "name" = 'BEAUTIFUL LIE, A';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Radiohead' AND "name" = 'Bends';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'U2' AND "name" = 'All That You Cant Leave Behind';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sum 41' AND "name" = 'All Killer No Filler (UK Versi';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2017-05-26' WHERE artist = '$uicideboy$' AND "name" = 'KILL YOURSELF PART XII: The Dark Glacier Saga';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2020-03-27' WHERE artist = 'Kreator' AND "name" = '666 - World Divided';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2019-06-07' WHERE artist = 'City Morgue' AND "name" = '66Slavs';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Stone Sour' AND "name" = 'Stonesour';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Stone Sour' AND "name" = 'Come What';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'AFI' AND "name" = 'Sing of Sorrow';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Billy Talent' AND "name" = 'Billy Talent EP';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Box Car Racer' AND "name" = 'Boxcar Racer';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Green Day' AND "name" = '1995 - Insomniac';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Offspring' AND "name" = 'Xnay On The Hombre';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'blink-182' AND "name" = 'Blink-182: Greatest Hits';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Ramones' AND "name" = 'The Greatest Hits';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rancid' AND "name" = 'And Out Come The Wolves';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Offspring' AND "name" = 'Offspring';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sum 41' AND "name" = 'All Killer, No Filler';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2006-05-06' WHERE artist = 'Yellowcard' AND "name" = 'Rough Landing, Holly';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Stone Sour' AND "name" = 'Come What[ever] May';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2001-08-13' WHERE artist = 'System of a Down' AND "name" = 'Chop Suey!';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Atreyu' AND "name" = 'A Death - Grip On Yesterday';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Escape the Fate' AND "name" = '2006 - Dying Is Your Latest Fashion';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Alexisonfire' AND "name" = 'Watch Out';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Silverstein' AND "name" = 'Arrivals and Departures';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Escape the Fate' AND "name" = '2010 - Escape The Fate';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Asking Alexandria' AND "name" = 'Reckless And Relentless';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-02-22' WHERE artist = 'Palisades' AND "name" = 'Fall';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Testament' AND "name" = 'Legacy';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Kreator' AND "name" = 'Extreme Agression';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dream Theater' AND "name" = 'Change Of Seasons';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rob Zombie' AND "name" = 'Greatest Hits: Past, Present & Future';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nine Inch Nails' AND "name" = 'Broken EP';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2021-06-18' WHERE artist = 'Fear Factory' AND "name" = 'Aggression Continuum';
UPDATE "public"."Album" SET "numberOfTracks" = 26, "date" = '2010-08-06' WHERE artist = 'Queens of the Stone Age' AND "name" = 'Rated R';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Hatebreed' AND "name" = 'Rise Of Brutality';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2012' WHERE artist = 'Agent Orange' AND "name" = 'Living In Darkness (30th Anniversary Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2006-12-10' WHERE artist = 'Adept' AND "name" = 'The Rose Will Decay';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'AC/DC' AND "name" = 'Bonfire - Back In Black';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Guns N'' Roses' AND "name" = 'Use Your Illusion, Vol. 1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Guns N'' Roses' AND "name" = 'Use Your Illusion 1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'AC/DC' AND "name" = 'Higway to Hell';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'AC/DC' AND "name" = 'The Razor''s Edge';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Papa Roach' AND "name" = 'The Paramour Ssessions';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Led Zeppelin' AND "name" = 'Physical Grafitti';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Led Zeppelin' AND "name" = 'Physical Graffitti';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Airbourne' AND "name" = 'Runnin Wild';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Mötley Crüe' AND "name" = 'Dr.Feelgood';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Mötley Crüe' AND "name" = 'Dr Feelgood';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1982-03-29' WHERE artist = 'Scorpions' AND "name" = 'Blackout';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Mötley Crüe' AND "name" = 'Girls,Girls,Girls';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Guns N'' Roses' AND "name" = 'Use Your Illusion 2';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Led Zeppelin' AND "name" = 'In Through The Outdoor';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'DevilDriver' AND "name" = 'Last Kind Words';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'White Zombie' AND "name" = 'La Sexorcisto - Devil Music Vol. 1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Machine Head' AND "name" = 'The More Things Change... Japanese Digipak';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Lamb of God' AND "name" = 'Burn the Priest';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1999-04-04' WHERE artist = 'Burn the Priest' AND "name" = 'Burn the Priest';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nile' AND "name" = 'Black Seeds of Vengence';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Kataklysm' AND "name" = 'Serenity Of Fire';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Kataklysm' AND "name" = '2004 - Serenity in Fire';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Within Temptation' AND "name" = 'The Silence Force';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Tristania' AND "name" = 'Widows Weeds';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Paradise Lost' AND "name" = 'One Second MCD';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Moonspell' AND "name" = 'Darkness & Hope';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Emery' AND "name" = 'Weaks End';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Envy' AND "name" = 'Insomniac Doze-Proper';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Burzum' AND "name" = 'Filosfem';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Mayhem' AND "name" = 'De Mysteriis Dom. Sathanas';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Emperor' AND "name" = 'In The Nightshade Eclipse';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Immortal' AND "name" = 'Out of the Dark';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Darkthrone' AND "name" = 'Transylvanian Hunger';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Darkthrone' AND "name" = '1994 - Transilvanian Hunger';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bathory' AND "name" = '1984 - Bathory';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dissection' AND "name" = 'Storm Of The Light''s Bane/Where Dead Angels Lie';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Immortal' AND "name" = 'At the heart of the winter';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Mayhem' AND "name" = 'Deathcrush EP';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Cradle of Filth' AND "name" = '1998 - Cruelty And The Beast';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bathory' AND "name" = 'Under The Sign Of Black Mark';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Immortal' AND "name" = '1993 - Pure Holocaust';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Cradle of Filth' AND "name" = '1996 - Dusk... And Her Embrace';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '1993-03-10' WHERE artist = 'Burzum' AND "name" = 'Aske';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Mayhem' AND "name" = 'Deathcrush - EP';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Mayhem' AND "name" = 'Deathcrush EP';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Cradle of Filth' AND "name" = 'Dusk and Her Embrace';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dimmu Borgir' AND "name" = 'Enthrone Darkness...';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Cradle of Filth' AND "name" = 'Cruelty & The Beast';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Silencer' AND "name" = 'Death, Pierce Me';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Cradle of Filth' AND "name" = '1998 - Cruelty And The Beast';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Brujeria' AND "name" = 'Matando Gueros';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Terrorizer' AND "name" = '1989 - World Downfall';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Napalm Death' AND "name" = 'From Enslavement To Obliteration + Scum';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Anaal Nathrakh' AND "name" = 'Hell is Empty All the Devils are Here';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nasum' AND "name" = '1998 - Inhale/Exhale';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2006' WHERE artist = '2 0'' Clock Girlfriend' AND "name" = 'A Tale of Two Cities';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dr. Acula' AND "name" = '2008 - Below Me';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '1984-06' WHERE artist = 'Slayer' AND "name" = 'Haunting the Chapel';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Anthrax' AND "name" = 'We''ve Come For You All + Bonus';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Alcest' AND "name" = 'Le secret EP';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Jesu' AND "name" = 'Silver - EP';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nightwish' AND "name" = '02 - Oceanborn';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nightwish' AND "name" = 'Angel Fall First';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nightwish' AND "name" = 'Angels Falls First';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nightwish' AND "name" = '01 - Angels Fall First';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Epica' AND "name" = 'Divine Conspiracy';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Therion' AND "name" = 'Lemura';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '% Disc _';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '% Disc __';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2001-03-04' WHERE artist = 'Beto Vázquez Infinity' AND "name" = 'Beto Vazquez Infinity';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2003' WHERE artist = 'Apocalyptica' AND "name" = 'Reflections Revised';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Decapitated' AND "name" = 'Organic Hallusinosis';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-10-25' WHERE artist = 'Asking Alexandria' AND "name" = 'Where Did It Go?';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Cradle of Filth' AND "name" = 'Dusk ... And Her Embrace';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Lynyrd Skynyrd' AND "name" = 'All-Time Greatest Hits';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Drive-By Truckers' AND "name" = 'Brighter Than Creations Dark';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Allman Brothers Band' AND "name" = 'Brothers & Sisters';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Allman Brothers Band' AND "name" = 'Live at Fillmore East';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Black Crowes' AND "name" = 'Amorica.';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'He Is Legend' AND "name" = 'Suck Out The Posion';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Kings of Leon' AND "name" = 'Youth And Young Manhood';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2017' WHERE artist = 'Outlaws' AND "name" = 'Sweet Home Alabama';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1987-10-05' WHERE artist = 'Lynyrd Skynyrd' AND "name" = 'Legend';
UPDATE "public"."Album" SET "numberOfTracks" = 47, "date" = '1991-11-12' WHERE artist = 'Lynyrd Skynyrd' AND "name" = 'Lynyrd Skynyrd';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Allman Brothers Band' AND "name" = 'Allman Brothers Band';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Allman Brothers Band' AND "name" = 'Live At The Fillmore East';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2017-06-16' WHERE artist = 'Jason Isbell and The 400 Unit' AND "name" = 'The Nashville Sound';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Agalloch' AND "name" = 'Mantle';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'My Dying Bride' AND "name" = 'Songs Of Darkness,Words Of Light';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'My Dying Bride' AND "name" = 'Songs of Darkness Words of Light';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Saturnus' AND "name" = 'Veronica Decides to Die';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1995-03-06' WHERE artist = 'Anathema' AND "name" = 'Pentecost III';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Velvet Underground' AND "name" = 'White Light - White Heat';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Velvet Underground' AND "name" = 'White Light-White Heat';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Liars' AND "name" = 'The Threw Us All In A Trench And Stuck A Monument On Top';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Liars' AND "name" = 'They Threw Us In A Trench And Stuck A Monument On Top';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2012-04-16' WHERE artist = 'Single Mothers' AND "name" = 'Self Titled';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1994-01' WHERE artist = 'Einherjer' AND "name" = 'Aurora Borealis';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Great White' AND "name" = 'Once Bitten...';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bon Jovi' AND "name" = '1988 - New Jersey';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Ratt' AND "name" = 'Dancin'' Undercover';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1994-06-30' WHERE artist = 'Mötley Crüe' AND "name" = 'Mötley Crüe';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-09-15' WHERE artist = 'Santa Cruz' AND "name" = 'River Phoenix';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'As Blood Runs Black' AND "name" = '2006 - Allegiance';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'All Shall Perish' AND "name" = 'Awaken The Dreamer';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Whitechapel' AND "name" = 'Somatic Defilement';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Annotations of an Autopsy' AND "name" = 'Before Throne Of Infection';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-06-08' WHERE artist = 'Aversions Crown' AND "name" = 'The Breeding Process';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rapeman' AND "name" = 'Two Nuns & A Pack Mule';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sonic Youth' AND "name" = 'E.V.O.L.';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Finntroll' AND "name" = 'Nattford';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2006-01' WHERE artist = 'Fejd' AND "name" = 'Eld';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '1999-06-29' WHERE artist = 'Mötley Crüe' AND "name" = 'Supersonic And Demonic Relics';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2005-12-20' WHERE artist = 'Winger' AND "name" = 'Rhino Hi-Five: Winger';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'H.I.M.' AND "name" = 'Dark Light';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2005-09-26' WHERE artist = 'Him' AND "name" = 'Dark Light';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2013' WHERE artist = 'Him' AND "name" = 'Into The Night';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '1999' WHERE artist = 'Him' AND "name" = 'It''s All Tears (Drown In This Love)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Gregorian' AND "name" = 'Masters of Chant Chapter 2';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = '2000.03.29 - Arena, Berlin, Germany';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Jack Riot' AND "name" = 'I''m Ok';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'H.I.M.' AND "name" = 'Razorblade Romance';
UPDATE "public"."Album" SET "numberOfTracks" = 26, "date" = '2010-02-08' WHERE artist = 'H.I.M.' AND "name" = 'Screamworks: Love In Theory And Practice, Chapters 1-13';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'Slippery When Dead (Demo)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'Live at Tavastia';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'Screamworks: Love In Theory And Practice, Baudelaire In Braille (Heartagram Edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'DARK LIGHT' AND "name" = 'My Revolution';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = '1997-11-15: Kelo Club, Kuhmo, Finland';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" = 'ClearMusicDownloader';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rapid Fire' AND "name" = 'Archive';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him & Her' AND "name" = 'Razorblade Romance';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him & Her' AND "name" = 'And Love Said No: Greatest Hits 1997-2004 [Germany]';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'And Love Said No I';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him & Her' AND "name" = 'Deep Shadows and Brilliant Highlights';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sex Mass' AND "name" = 'The Last Words';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = '2000-10-30: London, UK';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2014-03-31' WHERE artist = 'EnkElination' AND "name" = 'Tears of Lust (Single)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'And Love Said No...';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'Uneasy Listening Vol.1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'Greatest Lovesongs Vol.666';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'H.I.M.' AND "name" = 'Uneasy Listening Vol.2';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'H.I.M.' AND "name" = 'Uneasy Listening Vol.1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'H.I.M.' AND "name" = '666 Ways to Love, Prologue';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2000-03-06' WHERE artist = 'Him' AND "name" = 'Right Here In My Arms';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2000-10-23' WHERE artist = 'Him' AND "name" = 'Gone With The Sin';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2000-07-03' WHERE artist = 'Him' AND "name" = 'Poison Girl';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Him' AND "name" = 'Deep Shadows and Brilliant Highlights (Advance Album) (Promo Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2001-10' WHERE artist = 'Him' AND "name" = 'In Joy And Sorrow';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2002-01' WHERE artist = 'Him' AND "name" = 'Heartache Every Moment & Close to the Flame EP';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2004-03-15' WHERE artist = 'Him' AND "name" = 'And Love Said No';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2007-09-14' WHERE artist = 'Him' AND "name" = 'Venus Doom';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Aborted' AND "name" = 'Slaughter and Apparatus: A Methodical Overture';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Aborted' AND "name" = 'Slaughtered Apparatus: A Methodical Overture';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Aborted' AND "name" = 'Slaughter & Apparatus - A Methodical Overture';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-06-01' WHERE artist = 'JoJo Siwa' AND "name" = 'High Top Shoes';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-04-27' WHERE artist = 'JoJo Siwa' AND "name" = 'Every Girl''s a Super Girl';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Acid Bath' AND "name" = 'Pagan Terrorism Tactics';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rosetta' AND "name" = 'Wake / Lift';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Isis' AND "name" = 'Red Sea';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Melvins' AND "name" = 'Eggnog - EP';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1999' WHERE artist = 'Noothgrush' AND "name" = 'Erode the Person';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2009-12-01' WHERE artist = 'Rosetta' AND "name" = 'Three Way Split w/ East Of The Wall & Year Of No Light';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dimmu Borgir' AND "name" = 'Stormblåst 2005';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Abigail Williams' AND "name" = 'In The Shadow of 1000 Suns';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Abigail Williams' AND "name" = 'In The Shadow Of A Thousand Su';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Emperor' AND "name" = 'Prometheus-The Discipline of Fire & Demise';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Graveworm' AND "name" = 'As The Angels Reach The Beauty + Eternal Winds';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Limbonic Art' AND "name" = '1996 - Moon In The Scorpio';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Limbonic Art' AND "name" = 'Moon In Scorpio';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2007-01-26' WHERE artist = 'The Kovenant' AND "name" = 'In Times Before The Light 1995';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Illnath' AND "name" = 'Second Skin Harlequin';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-03-17' WHERE artist = 'Carach Angren' AND "name" = 'Song for the Dead';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Cryptopsy' AND "name" = 'Whisper Supermacy';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Cryptopsy' AND "name" = '...And Then You''ll Beg';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Psycroptic' AND "name" = 'Ob[servant]';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Anata' AND "name" = 'The Conductors Departure';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Psycroptic' AND "name" = 'The Sceptor of the Ancients';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '1998' WHERE artist = 'Dahmer' AND "name" = 'Dahmerized';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2005-04-26' WHERE artist = 'Some Girls' AND "name" = 'The DNA Will Have Its Say';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2009-02-20' WHERE artist = 'Viraemia' AND "name" = 'EP';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Viraemia' AND "name" = 'Viraemia';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-07-20' WHERE artist = 'Lil Xan' AND "name" = 'Betrayed';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2008-04-23' WHERE artist = 'Lil'' Wayne' AND "name" = 'A Milli';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2006' WHERE artist = 'Grenouer' AND "name" = 'Try';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '% (bonus disc)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Green Day' AND "name" = '1992 - Kerplunk!';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Cradle of Filth' AND "name" = '1994 - The Principle Of Evil Made Flesh';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2006-10-13' WHERE artist = 'Amatory' AND "name" = 'Книга Мертвых';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Mechanical Poet' AND "name" = 'Eidoline - The Arrakeen Code';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dead by April' AND "name" = 'Mystery - Single';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2014-11-12' WHERE artist = 'Outtrigger' AND "name" = 'The Last of Us';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2016-05-06' WHERE artist = 'Fear Of Domination' AND "name" = 'Atlas';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-03-02' WHERE artist = 'Fear Of Domination' AND "name" = 'Obsession';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2016-09-15' WHERE artist = 'State Of Mine' AND "name" = 'Devil in Disguise';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-03-29' WHERE artist = 'Demotional' AND "name" = 'Invincible';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2017-05-27' WHERE artist = 'Demotional' AND "name" = 'Discovery';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2019-05-17' WHERE artist = 'Eyes Wide Open' AND "name" = 'THE UPSIDE DOWN';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2011-03-29' WHERE artist = 'Of Legends' AND "name" = 'Stranded';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Cult of Luna' AND "name" = 'Beyond';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Catamenia' AND "name" = 'Location:COLD';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Catamenia' AND "name" = 'Location - Cold';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Graveworm' AND "name" = 'When Daylight''s Gone & Underne';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Taake' AND "name" = '"...Doedskvad"';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Taake' AND "name" = '...Doedeskvad';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Catamenia' AND "name" = 'VIII - The Time Unchained';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1995-03-15' WHERE artist = 'Darkwoods My Betrothed' AND "name" = 'Heirs of the Northstar';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Vypsaná Fixa' AND "name" = 'Fenomen';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Kylesa' AND "name" = 'Time Will Fuse It''s Worth';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Down' AND "name" = 'II - A Bustle In Your Headgrow';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bon Jovi' AND "name" = '1986 - Slippery When Wet';
UPDATE "public"."Album" SET "numberOfTracks" = 22, "date" = '2020-08-28' WHERE artist = 'Metallica' AND "name" = 'S&M2';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Manowar' AND "name" = '2007-Gods Of War';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rhapsody' AND "name" = 'The Magic Of The Wizard''s Dreams';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Stratovarius' AND "name" = 'Elements Part 1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Stratovarius' AND "name" = 'Elements - Part 1';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1989-10-17' WHERE artist = 'Kiss' AND "name" = 'Hot In The Shade';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1983-10' WHERE artist = 'Streets' AND "name" = '1st';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2016-05-30' WHERE artist = 'NECRONOMIDOL' AND "name" = 'NEMESIS';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sonata Arctica' AND "name" = '1999 - Ecliptica';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sonata Arctica' AND "name" = '2004 - Reckoning Night';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sonata Arctica' AND "name" = '2003 - Winterheart''s Guild';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2015-09-11' WHERE artist = 'Stratovarius' AND "name" = 'Eternal';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Blind Guardian' AND "name" = 'The Forgotten Tales.';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2015-05-04' WHERE artist = 'Imminence' AND "name" = 'A Mark on My Soul';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2015-05-12' WHERE artist = 'Veil of Maya' AND "name" = 'Matriarch';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-09-13' WHERE artist = 'Veil of Maya' AND "name" = 'Overthrow';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2017-10-27' WHERE artist = 'SpiritBox' AND "name" = 'Spiritbox';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2019-06-04' WHERE artist = 'SpiritBox' AND "name" = 'Singles Collection';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-04-29' WHERE artist = 'Annisokay' AND "name" = 'What''s Wrong';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-07-08' WHERE artist = 'Annisokay' AND "name" = 'Unaware';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1993-02-07' WHERE artist = 'Belphegor' AND "name" = 'Bloodbath In Paradise';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Falkenbach' AND "name" = 'Heralding - The Fireblade';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2010-04-03' WHERE artist = 'Avantasia' AND "name" = 'The Wicked Symphony';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2010-04-03' WHERE artist = 'Avantasia' AND "name" = 'Angel of Babylon';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2006-08-25' WHERE artist = 'Catamenia' AND "name" = 'Location: COLD';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Darkspace' AND "name" = 'Dark Space -I';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Darkspace' AND "name" = 'Darkspace I';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Katy Perry' AND "name" = '2008 - One Of The Boys';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1991' WHERE artist = 'Sepultura' AND "name" = 'Morbid Visions/bestial Devastation';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1990' WHERE artist = 'Dragon' AND "name" = 'Horda Goga';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Suicidal Tendencies' AND "name" = 'How Will I Laugh Tomorrow When I Can´t Even Smile Today';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Destruction' AND "name" = '1985 - Infernal Overkill';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2010-07-30' WHERE artist = 'Nuclear Test' AND "name" = 'Biohazard (Demo)';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1984' WHERE artist = 'Znöwhite' AND "name" = 'All Hail to Thee';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '1988' WHERE artist = 'Mayhem' AND "name" = 'Warfare Noise II';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Anthrax' AND "name" = 'Among The Living (USA Island 7 90584-2, DIDX 1652)';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2009' WHERE artist = 'Tornado' AND "name" = 'fire at will';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Alastor' AND "name" = 'Przeznaczenie';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Anthrax' AND "name" = 'Spreading The Disease (USA Island 7 90480-2)';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1990' WHERE artist = 'Corpse' AND "name" = 'I Live, You Die';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2002' WHERE artist = 'Violator' AND "name" = 'Killer Instinct';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1985-07-07' WHERE artist = 'Abattoir' AND "name" = 'Vicious Attack';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1986-05' WHERE artist = 'Onslaught' AND "name" = 'The Force';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1987-02-13' WHERE artist = 'Blood Feast' AND "name" = 'Kill for Pleasure';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1988-03' WHERE artist = 'Attomica' AND "name" = 'Attomica';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1987-10' WHERE artist = 'Virus' AND "name" = 'Pray For War';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1988' WHERE artist = 'Toxic Shock' AND "name" = 'Change From Reality';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1989-12' WHERE artist = 'Brainicide' AND "name" = 'Brutal Mentality';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1990' WHERE artist = 'Stos' AND "name" = 'Stos';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1989-10' WHERE artist = 'Bellzlleb' AND "name" = 'Bellzlleb';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1989-05-16' WHERE artist = 'Stone' AND "name" = 'No Anaesthesia!';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1989-06-30' WHERE artist = 'Forced Entry' AND "name" = 'Uncertain Future';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1989-08' WHERE artist = 'Intruder' AND "name" = 'A Higher Form Of Killing';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1989-09' WHERE artist = 'Evildead' AND "name" = 'Annihilation of Civilization';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1989-02-06' WHERE artist = 'Defiance' AND "name" = 'Product Of Society';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1989-08' WHERE artist = 'The Horde of Torment' AND "name" = 'Product Of A Sick Mind';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1992-03-27' WHERE artist = 'Defiance' AND "name" = 'Beyond Recognition';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1989-09' WHERE artist = 'Kreator' AND "name" = 'Endless Pain (Bonus Track Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1992' WHERE artist = 'Wrekking Machine' AND "name" = 'Mechanistic Termination';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1993-11' WHERE artist = 'Ferat' AND "name" = 'Rainhold';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1995-03-09' WHERE artist = 'Metalium' AND "name" = 'Suffer';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Kreator' AND "name" = 'Past Life Trauma (1985-1992)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Slaughter' AND "name" = 'Strappado & Bonus';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1998' WHERE artist = 'Arbitrator' AND "name" = 'Kill Their Religion';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2004-10-19' WHERE artist = 'Cardinal Sin' AND "name" = 'Resurrection';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1989' WHERE artist = 'Axe Minister' AND "name" = 'Evil Grows';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2007-12' WHERE artist = 'Code Red' AND "name" = 'Wolves Of Warfield';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2007-08-31' WHERE artist = 'Tankard' AND "name" = 'Best Case Scenario - 25 Years in Beers';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2008-04' WHERE artist = 'Sun Descends' AND "name" = 'The Entropy Formula';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2008-12' WHERE artist = 'Détente' AND "name" = 'History 1';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2009-11' WHERE artist = 'Bazöoka' AND "name" = 'Toxic Warriors';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2011-02-11' WHERE artist = 'Gae Bolga' AND "name" = 'Violent Metalstorm';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2012-02-24' WHERE artist = 'Lost World Order' AND "name" = 'Parasites';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2015' WHERE artist = 'Arbitrator' AND "name" = 'The Killing SSS';
UPDATE "public"."Album" SET "numberOfTracks" = 31, "date" = '1998-09-02' WHERE artist = 'ROT' AND "name" = 'Sociopathic Behaviour';
UPDATE "public"."Album" SET "numberOfTracks" = 32, "date" = '1994' WHERE artist = 'ROT' AND "name" = 'Cruel Face of Life';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009' WHERE artist = 'e123' AND "name" = 'Demo';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2006-05-22' WHERE artist = 'Archagathus' AND "name" = 'Archagathus / Unholy Grave split 7''''';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Camphora Monobromata' AND "name" = 'Demo 2009-2010';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2008' WHERE artist = 'Anarkitran' AND "name" = '...Donde quedo la igualdad';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2014-04-04' WHERE artist = 'Pretty Little Flower' AND "name" = 'Ultimate Whirlwind Of Incineration';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2008' WHERE artist = 'Crowd Control' AND "name" = 'Agathocles & Crowd Control Split';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2008-08-11' WHERE artist = 'Sakatat' AND "name" = 'Split';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '1998' WHERE artist = 'Agathocles' AND "name" = 'v/a Rotten Fake!';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2007' WHERE artist = 'Archagathus' AND "name" = 'Sad Monkey';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2011' WHERE artist = 'e123' AND "name" = '2 way split [E123 & I Know]';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2007' WHERE artist = 'Agathocles' AND "name" = 'Bastard Breed';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2008' WHERE artist = 'Bangsat' AND "name" = 'archagathus/bangsat';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Camphora Monobromata' AND "name" = 'Archagathus / Camphora Monobromata';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Camphora Monobromata' AND "name" = 'smg / camphora monobromata / amnogomusikimalo';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Path' AND "name" = 'The Path 7" split';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2006-09-28' WHERE artist = 'Warscars' AND "name" = 'Leng Tch''e / Warscars';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2007' WHERE artist = 'SMG' AND "name" = 'archagathus / smg';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2007' WHERE artist = 'Archagathus' AND "name" = 'archagathus / smg';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'e123' AND "name" = 'S/T EP';
UPDATE "public"."Album" SET "numberOfTracks" = 47, "date" = '1998' WHERE artist = 'Malignant Tumour' AND "name" = '...From Grind Gore ...To Mince-Core (Compilation)';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2010' WHERE artist = 'Misanthropic Noise' AND "name" = 'Lt. Dan / Misanthropic Noise';
UPDATE "public"."Album" SET "numberOfTracks" = 38, "date" = '2010-07' WHERE artist = 'Archagathus' AND "name" = 'Mincecore Fever: 7 Inch Anthology';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2011-01-23' WHERE artist = 'Kerenaneko' AND "name" = 'agathocles / kerenaneko / prostuck / rvota';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2011-01-23' WHERE artist = 'Rvota' AND "name" = 'agathocles / kerenaneko / prostuck / rvota';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2012-02-02' WHERE artist = 'Vomit Contest' AND "name" = 'Mesrine / Camphora Monobromata / Vomit Contest / Rotocles';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2011-03-01' WHERE artist = 'Violent Gorge' AND "name" = 'violent gorge / agathocles';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Camphora Monobromata' AND "name" = 'Camphora Monobromata / WxTxDxHxRx';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1998' WHERE artist = 'Unholy Grave' AND "name" = 'Nein';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2011-04-10' WHERE artist = 'Multinational Corporations' AND "name" = 'Equality';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2002' WHERE artist = 'Ulcerrhoea' AND "name" = 'Agathocles / Ulcerrhoea';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2009-12-01' WHERE artist = 'e123' AND "name" = '3 way split [E123 & Axidance & Ground Zero]';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Новые Властелины Твоего Анала' AND "name" = 'Ой Люли Мои Люли';
UPDATE "public"."Album" SET "numberOfTracks" = 32, "date" = '1994' WHERE artist = 'excreted alive' AND "name" = 'Injusta Situación';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2009' WHERE artist = 'xAnal Firthx' AND "name" = 'Split with Gay President Kamikaze Asassination Mission';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Shitnoise Bastards' AND "name" = 'Split';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Beherit' AND "name" = 'Morbid Rehearsals (Demo)';
