UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nightwish' AND "name" = 'Angels Falls First';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nightwish' AND "name" = '01 - Angels Fall First';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nightwish' AND "name" = 'Angel Fall First';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2003-05-06' WHERE artist = 'Within Temptation' AND "name" = 'Running Up That Hill';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2004-04-19' WHERE artist = 'Nightwish' AND "name" = 'Nemo';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2006-05-19' WHERE artist = 'Apocalyptica' AND "name" = 'Repressed';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Therion' AND "name" = 'Lemura';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Within Temptation' AND "name" = 'Black Symphony Disc 1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Within Temptation' AND "name" = 'Black Symphony (disc 2)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Within Temptation' AND "name" = 'The Silence Force';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Avantasia' AND "name" = 'The Metal Opera - part I';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nightwish' AND "name" = '02 - Oceanborn';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2004-11-15' WHERE artist = 'Within Temptation' AND "name" = 'The Silent Force';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2011-03-29' WHERE artist = 'Within Temptation' AND "name" = 'The Unforgiving';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-03-20' WHERE artist = 'Delain' AND "name" = 'April Rain';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2007-07-24' WHERE artist = 'Within Temptation' AND "name" = 'The Heart of Everything';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2002' WHERE artist = 'Nightwish' AND "name" = 'Bless the Child';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2005-01-28' WHERE artist = 'Within Temptation' AND "name" = 'Memories';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Within Temptation' AND "name" = 'Black Symphony';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2004-10-25' WHERE artist = 'Within Temptation' AND "name" = 'Stand My Ground';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2008-07-16' WHERE artist = 'Versailles' AND "name" = 'NOBLE';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2012-03-09' WHERE artist = 'Epica' AND "name" = 'Requiem for the Indifferent';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2014-05-02' WHERE artist = 'Epica' AND "name" = 'The Quantum Enigma';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'P.O.D.' AND "name" = 'The Fundamental Elements Of South';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2003-02-25' WHERE artist = 'Molotov' AND "name" = 'Dance And Dense Denso';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Кирпичи' AND "name" = 'Царский Альбом';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Noize MC' AND "name" = '08''-The Greatest Hits Vol. 1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Green Day' AND "name" = '2004 - American Idiot';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2021-03-12' WHERE artist = 'Machine Gun Kelly' AND "name" = 'DAYWALKER! (feat. CORPSE)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Green Day' AND "name" = 'American Idiot-ADVANCE';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Linkin Park' AND "name" = 'Meteora (Bonus Track Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2016-04-08' WHERE artist = 'Deftones' AND "name" = 'Gore';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2015' WHERE artist = 'Iron Maiden' AND "name" = 'The Number Of The Beast (2015 Remaster)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Skid Row' AND "name" = 'Slave to the Grid';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Megadeth' AND "name" = 'Peace Sells... But Who''s Buyin';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Do Make Say Think' AND "name" = 'Winter Hymn Country Hymn Secre';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sigur Ros' AND "name" = '( )';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'toe' AND "name" = 'Book About My Idle Plot On A Vague Anxiety';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Album Leaf' AND "name" = 'Into The Blue';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'This Will Destroy You' AND "name" = 'S/T';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2008-11-09' WHERE artist = 'Sigur Rós' AND "name" = 'Við spilum endalaust';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1999-06-12' WHERE artist = 'Sigur Ros' AND "name" = 'Ágætis Byrjun';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sigur Rós' AND "name" = 'ágætis byrjun';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2016-10-28' WHERE artist = 'Avenged Sevenfold' AND "name" = 'The Stage';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1998-03-10' WHERE artist = 'Liquid Tension Experiment' AND "name" = 'Liquid Tension Experiment';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2009-12-18' WHERE artist = 'Uneven Structure' AND "name" = '8';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2004-01-12' WHERE artist = 'Oomph!' AND "name" = 'Augen Auf';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2000-11-11' WHERE artist = 'Marilyn Manson' AND "name" = 'Holy Wood';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2012-03-16' WHERE artist = 'Unheilig' AND "name" = 'Lichter Der Stadt';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2010-04-16' WHERE artist = 'Eisbrecher' AND "name" = 'Eiszeit';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2005-07-26' WHERE artist = 'Dope' AND "name" = 'American Apathy';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2003-03-31' WHERE artist = 'The Kovenant' AND "name" = 'SETI';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2008-10-31' WHERE artist = 'Pain' AND "name" = 'Cynic Paradise';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2001-02' WHERE artist = 'Spineshank' AND "name" = 'New Disease';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2001-05-08' WHERE artist = 'Mushroomhead' AND "name" = 'XX';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1989-11-13' WHERE artist = 'Godflesh' AND "name" = 'Streetcleaner';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2005-08-22' WHERE artist = 'Fear Factory' AND "name" = 'Transgression';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'A.F.I.' AND "name" = 'Decemberunderground';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Hatebreed' AND "name" = 'Rise of Brutality';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007-01-22' WHERE artist = 'A Day to Remember' AND "name" = 'For Those Who Have Heart';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1996-11-13' WHERE artist = 'Hatebreed' AND "name" = 'Under The Knife';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Norma Jean' AND "name" = '-vs- the Anti Mother ';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2020-08-07' WHERE artist = 'Tkay Maidza' AND "name" = 'Last Year Was Weird, Vol. 2';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2006-07' WHERE artist = 'Ceremony' AND "name" = 'Violence Violence';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2002' WHERE artist = 'Jane Air' AND "name" = 'Pull Ya? Let it doll go';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2021-06-11' WHERE artist = 'Machine Head' AND "name" = 'Arrows In Words from the Sky';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '1996-02-21' WHERE artist = 'Sepultura' AND "name" = 'Roots [Special Edition]';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2007-02-23' WHERE artist = 'Volbeat' AND "name" = 'Rock The Rebel / Metal The Devil';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2017-07-07' WHERE artist = 'Decapitated' AND "name" = 'Anticult';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2015-05-01' WHERE artist = 'Casey' AND "name" = 'Fade';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2020-05-15' WHERE artist = 'Paradise Lost' AND "name" = 'Obsidian';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sirenia' AND "name" = 'An Elexier for Existence';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Lacuna Coil' AND "name" = 'Comalies CD1';
