UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2000-02-21' WHERE artist = 'Океан Ельзи' AND "name" = 'Янанебібув';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2004-12-22' WHERE artist = 'Jay-Z' AND "name" = 'Collision Course (Deluxe Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2004-12-13' WHERE artist = 'Jay-Z' AND "name" = 'Numb/Encore: MTV Ultimate Mash-Ups Presents Collision Course';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2007-10-30' WHERE artist = 'Otep' AND "name" = 'The Ascension';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2014-12-10' WHERE artist = 'DIR EN GREY' AND "name" = 'Arche';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2018-05-18'  WHERE artist = 'Five Finger Death Punch' AND "name" = 'And Justice for None (Deluxe)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Deftones' AND "name" = 'White Pony (U.S. Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '1998-02-27' WHERE artist = 'Oomph!' AND "name" = 'Unrein';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2007-10-30' WHERE artist = 'Flyleaf' AND "name" = 'Flyleaf (Special Edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'System of a Down' AND "name" = 'Mesmerize';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2006' WHERE artist = 'Tracktor Bowling' AND "name" = 'Шаги По Стеклу';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Linkin Park' AND "name" = 'Minutes To Midnight (Explicit Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2002' WHERE artist = 'Linkin Park' AND "name" = 'Hybrid Theory (Bonus Track Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2001-09-18' WHERE artist = 'Ill Niño' AND "name" = 'Revolution Revolución';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2016-10-26' WHERE artist = 'Linkin Park' AND "name" = 'Meteora (Bonus Track Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2004-10-05' WHERE artist = 'Korn' AND "name" = 'Greatest Hits Vol. 1';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2004-03-24' WHERE artist = 'Soil' AND "name" = 'Redefine';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2005-04-26' WHERE artist = 'Egypt Central' AND "name" = 'Egypt Central';
UPDATE "public"."Album" SET "numberOfTracks" = 22, "date" = '2016-12-16' WHERE artist = 'Stone Sour' AND "name" = 'Come What(ever) May [10th Anniversary Edition]';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2006-11-21' WHERE artist = 'P.O.D.' AND "name" = 'Greatest Hits (The Atlantic Years)';
UPDATE "public"."Album" SET "numberOfTracks" = 55, "date" = '2014-10-17' WHERE artist = 'Slipknot' AND "name" = 'The Studio Album Collection 1999 - 2008';
UPDATE "public"."Album" SET "numberOfTracks" =16 , "date" = '2010-09-10' WHERE artist = 'Linkin Park' AND "name" = 'A Thousand Suns (Bonus Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 25, "date" = '2009-09-07' WHERE artist = 'Slipknot' AND "name" = 'Slipknot 10th Anniversary Edition';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Hurt' AND "name" = 'Other Tracks';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2002' WHERE artist = 'Linkin Park' AND "name" = '[Reanimation]';
UPDATE "public"."Album" SET "numberOfTracks" = 23, "date" = '2007' WHERE artist = 'Charlie Brown JR.' AND "name" = 'Ritmo, Ritual e Responsa';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Maximum the Hormone' AND "name" = 'Buiiki Kaesu';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Otep' AND "name" = 'Ascension';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-10-31' WHERE artist = 'Slipknot' AND "name" = 'All Out Life';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-10-16' WHERE artist = 'Rammstein' AND "name" = 'Liebe ist fur alle da';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1995' WHERE artist = 'Metallica' AND "name" = 'master of puppets (remastered)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2016-03-29' WHERE artist = 'BABYMETAL' AND "name" = 'Metal Resistance';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2006-10-25' WHERE artist = 'カヒミ・カリィ' AND "name" = 'Nunki';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2000-09-20' WHERE artist = 'Queens of the Stone Age' AND "name" = 'R [Japan Bonus Track]';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2018-10-31' WHERE artist = 'Poppy' AND "name" = 'Am I A Girl?';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2009-04-17' WHERE artist = 'Eluveitie' AND "name" = 'Evocation I: The Arcane Dominion';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2017-09-05' WHERE artist = 'GhosteMane' AND "name" = 'HEXADA';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1994-05-09' WHERE artist = 'The Pretenders' AND "name" = 'Last Of The Independents';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1988-01-19' WHERE artist = 'Megadeth' AND "name" = 'So Far, So Good, ... So What!';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1966' WHERE artist = 'The Animals' AND "name" = 'The Most of the Animals';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2009-06-06' WHERE artist = 'Cautiva' AND "name" = 'Human';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'pumpkin jacket' AND "name" = 'Master of Pumpkins';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2011' WHERE artist = 'Mane Horse' AND "name" = 'Lord Unicorn & The Masters';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2010-11-12' WHERE artist = 'Mane Horse' AND "name" = 'What do you mean We''re just Friends?!';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2011-05-31' WHERE artist = 'Ozzy Osbourne' AND "name" = 'Blizzard Of Ozz (Expanded Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2000-08-22' WHERE artist = '(həd) p.e.' AND "name" = 'Broke';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Stasis' AND "name" = 'Exacerbate the Misery';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2006-01-01' WHERE artist = 'Stasis' AND "name" = 'A Stasis Was Born';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2009-12-21' WHERE artist = 'Stasis' AND "name" = 'Red';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Apocalyptica' AND "name" = 'AMPLIFIED-A Decade of Reinventing the Cello';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2003-09-23' WHERE artist = 'Pantera' AND "name" = 'Reinventing Hell (The Best Of Pantera)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2008-08-04' WHERE artist = 'NEIZAN' AND "name" = 'Beijing 2008';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2008-11-10' WHERE artist = 'NEIZAN' AND "name" = 'Broken Toys';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2014-07-14' WHERE artist = 'Karliene' AND "name" = 'The Ballad of Anne Boleyn';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-09-18' WHERE artist = 'Eurielle' AND "name" = 'The Bridge Of Khazad-Dum (from "The Lord Of The Rings")';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Slipknot' AND "name" = 'Vol. 3: (The Subliminal Verses)';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2002' WHERE artist = 'Linkin Park' AND "name" = 'Hybrid Theory (Bonus Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2000-06-20' WHERE artist = 'Deftones' AND "name" = 'White Pony';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2009' WHERE artist = 'Rammstein' AND "name" = 'Liebe Ist für Alle Da (Special Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2004-10-05' WHERE artist = 'Korn' AND "name" = 'Greatest Hits, Vol. 1';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2010-12-19' WHERE artist = 'The Lonely Island' AND "name" = 'I Just Had Sex';
UPDATE "public"."Album" SET "numberOfTracks" = 24, "date" = '2020-12-04' WHERE artist = 'Rina Sawayama' AND "name" = 'Sawayama (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2004-11-30' WHERE artist = 'Jay-Z and Linkin Park' AND "name" = 'Collision Course';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2006-07-18' WHERE artist = 'The Red Jumpsuit Apparatus' AND "name" = 'Don''t You Fake It';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1993-09-14' WHERE artist = 'Counting Crows' AND "name" = 'August And Everything After';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2018-05-11' WHERE artist = 'Arctic Monkeys' AND "name" = 'Tranquility Base Hotel & Casino';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '1968-10-16' WHERE artist = 'The Jimi Hendrix Experience' AND "name" = 'Electric Ladyland';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1999-04-19' WHERE artist = 'The Cranberries' AND "name" = 'Bury The Hatchet';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Linkin Park' AND "name" = 'Hybrid Theory (Bonus Edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Limp Bizkit' AND "name" = 'Lost & Found: Limp Bizkit';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Korn' AND "name" = 'Greatest Hits, Vol. 1';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1996' WHERE artist = 'Black Sabbath' AND "name" = 'Paranoid (Remastered)';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1988-08-25' WHERE artist = 'Metallica' AND "name" = '...and Justice for All';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-08-18' WHERE artist = 'Metallica' AND "name" = 'Hardwired';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '1999' WHERE artist = 'System of a Down' AND "name" = 'System Of A Down (Bonus Pack)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-06-03' WHERE artist = 'Machine Head' AND "name" = 'Is There Anybody Out There?';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2006' WHERE artist = 'Electric Wizard' AND "name" = 'Dopethrone (Remaster)';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1986-03-03' WHERE artist = 'Metallica' AND "name" = 'Master of Puppets';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2002-09-24' WHERE artist = 'CKY' AND "name" = 'Infiltrate Destroy Rebuild';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2004-09-28' WHERE artist = 'Marilyn Manson' AND "name" = 'Lest We Forget - The Best Of';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2006-10-31' WHERE artist = 'Deftones' AND "name" = 'Saturday Night Wrist';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2007-12-04' WHERE artist = 'Godsmack' AND "name" = 'Good Times, Bad Times - Ten Years of Godsmack';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2019-03-28' WHERE artist = 'Rammstein' AND "name" = 'Deutschland';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Metallica' AND "name" = '... And Justice For All';
UPDATE "public"."Album" SET "numberOfTracks" = 26, "date" = '2016-11-18' WHERE artist = 'Metallica' AND "name" = 'Hardwired…To Self-Destruct (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2011-10-24' WHERE artist = 'Machine Head' AND "name" = 'Unto the Locust (Special Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2017-02-16' WHERE artist = 'Linkin Park' AND "name" = 'Heavy (feat. Kiiara)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1981-07-17' WHERE artist = 'Journey' AND "name" = 'Escape';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1990-08-21' WHERE artist = 'Jane''s Addiction' AND "name" = 'Ritual de lo Habitual';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2008-05-20' WHERE artist = '3 Doors Down' AND "name" = '3 Doors Down';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2006-01-23' WHERE artist = 'Arctic Monkeys' AND "name" = 'Whatever People Say I Am, That''s What I''m Not';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2000-10-24' WHERE artist = 'Lenny Kravitz' AND "name" = 'Greatest Hits';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2009-08-03' WHERE artist = 'The Temper Trap' AND "name" = 'Sweet Disposition';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '1993-11-16' WHERE artist = 'Tom Petty and The Heartbreakers' AND "name" = 'Greatest Hits';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2001-09-04' WHERE artist = 'System of a Down' AND "name" = 'Toxicity';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2004-05-25' WHERE artist = 'Slipknot' AND "name" = 'Vol. 3: The Subliminal Verses';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2007-09-25' WHERE artist = 'Dethklok' AND "name" = 'The Dethalbum';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1995-10-03' WHERE artist = 'Deftones' AND "name" = 'Adrenaline';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2015-04-17' WHERE artist = 'Apocalyptica' AND "name" = 'Shadowmaker';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2001' WHERE artist = 'System of a Down' AND "name" = 'Chop Suey!';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2017-05-19' WHERE artist = 'Papa Roach' AND "name" = 'Crooked Teeth';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2003-12-16' WHERE artist = 'Machine Head' AND "name" = 'Through the Ashes of Empires';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2004-05-24' WHERE artist = 'Exilia' AND "name" = 'Unleashed';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2011-09-05' WHERE artist = 'Grouplove' AND "name" = 'Never Trust A Happy Song';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2016-02-26' WHERE artist = 'The 1975' AND "name" = 'I Like It When You Sleep, For You Are So Beautiful Yet So Unaware Of It';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2006-01-24' WHERE artist = 'Gossip' AND "name" = 'Standing in the Way of Control';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2005-03-22' WHERE artist = 'Lifehouse' AND "name" = 'Lifehouse';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2004-04-13' WHERE artist = 'Crossfade' AND "name" = 'Crossfade';
UPDATE "public"."Album" SET "numberOfTracks" = 26, "date" = '2009-06-16' WHERE artist = 'Incubus' AND "name" = 'Monuments And Melodies';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2009-08-25' WHERE artist = 'Skillet' AND "name" = 'Awake';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2003-07-22' WHERE artist = 'Gavin DeGraw' AND "name" = 'Chariot';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2013-03-04' WHERE artist = 'Bastille' AND "name" = 'Bad Blood';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2005-10-04' WHERE artist = 'Flyleaf' AND "name" = 'Flyleaf';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2000-05-23' WHERE artist = 'A Perfect Circle' AND "name" = 'Mer De Noms';
UPDATE "public"."Album" SET "numberOfTracks" = 28, "date" = '2012-12-04' WHERE artist = 'The Smashing Pumpkins' AND "name" = 'Mellon Collie and the Infinite Sadness (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2003-03-11' WHERE artist = 'AFI' AND "name" = 'Sing the Sorrow';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2013-10-02' WHERE artist = 'Nirvana' AND "name" = 'In Utero - 20th Anniversary Remaster';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2009-07' WHERE artist = 'Florence + the Machine' AND "name" = 'Lungs (Deluxe Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2011-05-23' WHERE artist = 'Lady Gaga' AND "name" = 'Born This Way';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2019-03-29' WHERE artist = 'Billie Eilish' AND "name" = 'when we all fall asleep, where do we go?';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2020-11-20' WHERE artist = 'BTS' AND "name" = 'BE';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2019-02-08' WHERE artist = 'Ariana Grande' AND "name" = 'Thank U, Next';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2017-11-10' WHERE artist = 'Taylor Swift' AND "name" = 'Reputation';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2016-02-05' WHERE artist = 'Rihanna' AND "name" = 'Anti (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2016-10-21' WHERE artist = 'Lady Gaga' AND "name" = 'JOANNE (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2015-11-13' WHERE artist = 'One Direction' AND "name" = 'Made In the A.M. (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 22, "date" = '2012-10-22' WHERE artist = 'Taylor Swift' AND "name" = 'Red (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2017-10-02' WHERE artist = 'Halsey' AND "name" = 'hopeless fountain kingdom (deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2016-03-25' WHERE artist = 'Zayn' AND "name" = 'Mind Of Mine (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2009-11-23' WHERE artist = 'Adam Lambert' AND "name" = 'For Your Entertainment';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2019-04-12' WHERE artist = 'BTS' AND "name" = 'MAP OF THE SOUL : PERSONA';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2012-07-03' WHERE artist = 'Flo Rida' AND "name" = 'Wild Ones';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2009-03-24' WHERE artist = 'Keri Hilson' AND "name" = 'In a Perfect World...';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2015-11-12' WHERE artist = 'Justin Bieber' AND "name" = 'Purpose (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007-11-03' WHERE artist = 'The Veronicas' AND "name" = 'Hook Me Up';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1997-09-16' WHERE artist = 'Mariah Carey' AND "name" = 'Butterfly';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-10-25' WHERE artist = 'Steve Aoki' AND "name" = 'Waste It On Me (feat. BTS)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-01-24' WHERE artist = 'Rihanna' AND "name" = 'FourFiveSeconds';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-02-05' WHERE artist = 'The Chainsmokers' AND "name" = 'Don''t Let Me Down';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2008-11-28' WHERE artist = 'Britney Spears' AND "name" = 'Circus';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2014-11-24' WHERE artist = 'Ariana Grande' AND "name" = 'Santa Tell Me';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-05-06' WHERE artist = 'Justin Timberlake' AND "name" = 'Can''t Stop The Feeling! (Original Song From Dreamworks Animation''s "Trolls")';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2005-07-26' WHERE artist = 'Daniel Powter' AND "name" = 'Daniel Powter';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-08-17' WHERE artist = 'Ava Max' AND "name" = 'Sweet but Psycho';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2010-06-04' WHERE artist = 'Christina Aguilera' AND "name" = 'Bionic';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2018-05-11' WHERE artist = 'Charlie Puth' AND "name" = 'Voicenotes';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-05-18' WHERE artist = 'Selena Gomez' AND "name" = 'Bad Liar';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2013-01-01' WHERE artist = 'Lana Del Rey' AND "name" = 'Summertime Sadness [Lana Del Rey vs. Cedric Gervais] (Cedric Gervais Remix)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Swedish House Mafia' AND "name" = 'Don''t You Worry Child (Radio Edit) [feat. John Martin]';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-01-06' WHERE artist = 'Ed Sheeran' AND "name" = 'Shape of You';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2013-10-07' WHERE artist = 'Pitbull' AND "name" = 'Timber';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1984-11-12' WHERE artist = 'Madonna' AND "name" = 'Like a Virgin';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2009-05-03' WHERE artist = 'Ciara' AND "name" = 'Fantasy Ride';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-03-30' WHERE artist = 'Billie Eilish' AND "name" = 'bitches broken hearts';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-03-16' WHERE artist = 'Troye Sivan' AND "name" = 'Strawberries & Cigarettes';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1997-07-21' WHERE artist = 'Eagle-Eye Cherry' AND "name" = 'Desireless';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2006-09-08' WHERE artist = 'Justin Timberlake' AND "name" = 'FutureSex/LoveSounds';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2019-08-23' WHERE artist = 'Taylor Swift' AND "name" = 'Lover';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2013-10-08' WHERE artist = 'Miley Cyrus' AND "name" = 'Bangerz (Deluxe Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2014-08-22' WHERE artist = 'Ariana Grande' AND "name" = 'My Everything (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2015-10-09' WHERE artist = 'Selena Gomez' AND "name" = 'Revival (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2017-06-02' WHERE artist = 'Halsey' AND "name" = 'hopeless fountain kingdom (deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2018-01-12' WHERE artist = 'Camila Cabello' AND "name" = 'Camila';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2018-08-31' WHERE artist = 'Troye Sivan' AND "name" = 'Bloom';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2006-11-13' WHERE artist = '+44' AND "name" = 'When Your Heart Stops Beating';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2009-05-18' WHERE artist = 'Linkin Park' AND "name" = 'New Divide';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-05-05' WHERE artist = 'The Dangerous Summer' AND "name" = 'Reach For The Sun';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1994-01-25' WHERE artist = 'Alice in Chains' AND "name" = 'Jar of Flies';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2009-02-10' WHERE artist = 'Red' AND "name" = 'Innocence & Instinct';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2016-06-17' WHERE artist = 'Red Hot Chili Peppers' AND "name" = 'The Getaway';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2012-04-30' WHERE artist = 'Marina' AND "name" = 'Electra Heart (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2005-01-25' WHERE artist = 'Bright Eyes' AND "name" = 'I''m Wide Awake It''s Morning';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1997-06-30' WHERE artist = 'The Prodigy' AND "name" = 'The Fat Of The Land';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2005-10-09' WHERE artist = 'Cansei de Ser Sexy' AND "name" = 'Cansei de Ser Sexy';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2011-08-26' WHERE artist = 'David Guetta' AND "name" = 'Nothing But The Beat';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2002-05-20' WHERE artist = 'múm' AND "name" = 'Finally We are No One';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2004-05-18' WHERE artist = 'Alanis Morissette' AND "name" = 'So-Called Chaos';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1986-06-02' WHERE artist = 'Queen' AND "name" = 'A Kind Of Magic';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2007-06-04' WHERE artist = 'Biffy Clyro' AND "name" = 'Puzzle';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1992-11-03' WHERE artist = 'Bon Jovi' AND "name" = 'Keep The Faith';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2002-08-13' WHERE artist = 'Bright Eyes' AND "name" = 'Lifted or The Story Is in the Soil, Keep Your Ear to the Ground';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2017-08-11' WHERE artist = 'Billie Eilish' AND "name" = 'dont smile at me';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-04-18' WHERE artist = 'Billie Eilish' AND "name" = 'lovely (with Khalid)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2011-06-21' WHERE artist = 'Maroon 5' AND "name" = 'Moves Like Jagger';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2014-09-29' WHERE artist = 'Lorde' AND "name" = 'Yellow Flicker Beat (From The Hunger Games: Mockingjay Part 1)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-06-30' WHERE artist = 'J Balvin' AND "name" = 'Mi Gente';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1999-01-12' WHERE artist = 'Britney Spears' AND "name" = '...Baby One More Time';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2016-10-21' WHERE artist = 'Korn' AND "name" = 'The Serenity of Suffering';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2012-09-21' WHERE artist = 'Mumford & Sons' AND "name" = 'Babel (Deluxe Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2009-04-06' WHERE artist = 'Black Sabbath' AND "name" = 'Black Sabbath (2009 Remastered Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 25, "date" = '2012-11-27' WHERE artist = 'Rage Against the Machine' AND "name" = 'Rage Against The Machine - XX (20th Anniversary Special Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2013-01-08' WHERE artist = 'Twenty One Pilots' AND "name" = 'Vessel';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2008-09-08' WHERE artist = 'Emilíana Torrini' AND "name" = 'Me And Armini';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2018-10-16' WHERE artist = 'Dominic Fike' AND "name" = 'Don''t Forget About Me, Demos';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1999-02-02' WHERE artist = 'Built to Spill' AND "name" = 'Keep It Like a Secret';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2005-10-04' WHERE artist = 'Broken Social Scene' AND "name" = 'Broken Social Scene';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2008-01-29' WHERE artist = 'Vampire Weekend' AND "name" = 'Vampire Weekend';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2005-02-02' WHERE artist = 'Bloc Party' AND "name" = 'Silent Alarm';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2002-10-14' WHERE artist = 'The Libertines' AND "name" = 'Up the Bracket';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1999-09-14' WHERE artist = 'American Football' AND "name" = 'American Football';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2002-10-01' WHERE artist = 'Rilo Kiley' AND "name" = 'The Execution of All Things';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2008-08-05' WHERE artist = 'The Airborne Toxic Event' AND "name" = 'The Airborne Toxic Event';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2000-06-08' WHERE artist = 'Phoenix' AND "name" = 'United';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2003-09-02' WHERE artist = 'The National' AND "name" = 'Sad Songs for Dirty Lovers';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2004-03-09' WHERE artist = 'CocoRosie' AND "name" = 'La Maison de Mon Reve';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006-05-09' WHERE artist = 'Beirut' AND "name" = 'Gulag Orkestar';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bright Eyes' AND "name" = 'I''m Wide Awake It''s Morning';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2008-06-03' WHERE artist = 'Fleet Foxes' AND "name" = 'Fleet Foxes';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2011-04-20' WHERE artist = 'Daughter' AND "name" = 'His Young Heart';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2020-07-20' WHERE artist = 'Billie Eilish' AND "name" = 'my future';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1963-05-27' WHERE artist = 'Bob Dylan' AND "name" = 'The Freewheelin'' Bob Dylan';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1969-07-03' WHERE artist = 'Nick Drake' AND "name" = 'Five Leaves Left';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1971-03-05' WHERE artist = 'Nick Drake' AND "name" = 'Bryter Layter';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1971-03-19' WHERE artist = 'Leonard Cohen' AND "name" = 'Songs of Love and Hate';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1971-06-22' WHERE artist = 'Joni Mitchell' AND "name" = 'Blue';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1974-01-24' WHERE artist = 'Paul Simon' AND "name" = 'Paul Simon';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1964-01-13' WHERE artist = 'Bob Dylan' AND "name" = 'The Times They Are A-Changin''';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1965-08-30' WHERE artist = 'Bob Dylan' AND "name" = 'Highway 61 Revisited';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1968-04-03' WHERE artist = 'Simon & Garfunkel' AND "name" = 'Bookends';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1999-01-19' WHERE artist = 'Bonnie ''Prince'' Billy' AND "name" = 'I See a Darkness';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2008-06-03' WHERE artist = 'Fleet Foxes' AND "name" = 'Fleet Foxes';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2007-09-04' WHERE artist = 'Deer Tick' AND "name" = 'War Elephant';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2009-10-27' WHERE artist = 'The Middle East' AND "name" = 'The Recordings Of The Middle East';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2003-03-18' WHERE artist = 'M. Ward' AND "name" = 'Transfiguration of Vincent';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2011-10-02' WHERE artist = 'Daughter' AND "name" = 'The Wild Youth EP';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2011-06-21' WHERE artist = 'Bon Iver' AND "name" = 'Bon Iver';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2016-05-27' WHERE artist = 'Big Thief' AND "name" = 'Masterpiece';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2014-03-31' WHERE artist = 'First Aid Kit' AND "name" = 'My Silver Lining';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2009-10-27' WHERE artist = 'Devendra Banhart' AND "name" = 'What Will We Be';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2007-07-03' WHERE artist = 'Velvet Revolver' AND "name" = 'Libertad';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1983-09-26' WHERE artist = 'Mötley Crüe' AND "name" = 'Shout at the Devil';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1968-01-29' WHERE artist = 'Steppenwolf' AND "name" = 'Steppenwolf';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1968-07-17' WHERE artist = 'Deep Purple' AND "name" = 'Shades of Deep Purple';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1972-03-25' WHERE artist = 'Deep Purple' AND "name" = 'Machine Head';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1975-08-04' WHERE artist = 'Rainbow' AND "name" = 'Ritchie Blackmore''s Rainbow';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1975-04-03' WHERE artist = 'Nazareth' AND "name" = 'Hair of the Dog';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1976-03-26' WHERE artist = 'Thin Lizzy' AND "name" = 'Jailbreak';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1976-05-15' WHERE artist = 'Rainbow' AND "name" = 'Rising';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1976-08-25' WHERE artist = 'Boston' AND "name" = 'Boston';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1982-06-08' WHERE artist = 'Survivor' AND "name" = 'Eye of the Tiger';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1984-01-09' WHERE artist = 'Van Halen' AND "name" = '1984';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1984-03-27' WHERE artist = 'Scorpions' AND "name" = 'Love at First Sting';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1986-05-26' WHERE artist = 'Europe' AND "name" = 'The Final Countdown';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1976-09-20' WHERE artist = 'AC/DC' AND "name" = 'Dirty Deeds Done Dirt Cheap';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1970-06-05' WHERE artist = 'Deep Purple' AND "name" = 'In Rock';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2004-08-31' WHERE artist = 'Papa Roach' AND "name" = 'Getting Away With Murder';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2010-03-31' WHERE artist = 'Slash' AND "name" = 'Slash';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2011-03-25' WHERE artist = 'Graveyard' AND "name" = 'Hisingen Blues';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2009-10-23' WHERE artist = 'Wolfmother' AND "name" = 'Cosmic Egg';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1997-03-18' WHERE artist = 'Aerosmith' AND "name" = 'Nine Lives';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2010-08-31' WHERE artist = 'Disturbed' AND "name" = 'Asylum';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2016-08-19' WHERE artist = 'Eden' AND "name" = 'I Think You Think Too Much of Me';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1996-04-16' WHERE artist = 'Rage Against the Machine' AND "name" = 'Evil Empire';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '1997-12-01' WHERE artist = 'Robbie Williams' AND "name" = 'Angels';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-05-10' WHERE artist = 'John Mayer' AND "name" = 'New Light';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007-04-18' WHERE artist = 'Arctic Monkeys' AND "name" = 'Favourite Worst Nightmare (Standard Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2011-10-07' WHERE artist = 'Lana Del Rey' AND "name" = 'Video Games';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-02-25' WHERE artist = 'Clairo' AND "name" = 'bubble gum';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2005-03-29' WHERE artist = 'Beck' AND "name" = 'Guero';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2013-07-11' WHERE artist = 'Lana Del Rey' AND "name" = 'Summertime Sadness [Lana Del Rey vs. Cedric Gervais] (Cedric Gervais Remix)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Lana Del Rey' AND "name" = 'Summertime Sadness [Lana Del Rey vs. Cedric Gervais]';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2003-05-27' WHERE artist = 'O.A.R.' AND "name" = 'In Between Now and Then';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '1999-10-04' WHERE artist = 'Bloodhound Gang' AND "name" = 'Hooray for Boobies';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2013-04-05' WHERE artist = 'Milky Chance' AND "name" = 'Stolen Dance';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2019-05-17' WHERE artist = 'Lana Del Rey' AND "name" = 'Doin'' Time';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2018-05-25' WHERE artist = 'Clairo' AND "name" = 'diary 001';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2005-10-07' WHERE artist = 'The Fray' AND "name" = 'Over My Head (Cable Car)';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1997-11-18' WHERE artist = 'Metallica' AND "name" = 'Reload';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2002-09-17' WHERE artist = 'Disturbed' AND "name" = 'Believe';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Slipknot' AND "name" = 'Vol. 3: (The Subliminal Verses)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2005-06-06' WHERE artist = 'Avenged Sevenfold' AND "name" = 'City of Evil';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2005-09-20' WHERE artist = 'Disturbed' AND "name" = 'Ten Thousand Fists';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2008-06-03' WHERE artist = 'Disturbed' AND "name" = 'Indestructible';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2013-04-01' WHERE artist = 'Bring Me the Horizon' AND "name" = 'Sempiternal (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2008-11-11' WHERE artist = 'DIR EN GREY' AND "name" = 'Uroboros';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1987-04-23' WHERE artist = 'Faith No More' AND "name" = 'Introduce Yourself';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2015-05-19' WHERE artist = 'Faith No More' AND "name" = 'Sol Invictus';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1999-11-02' WHERE artist = 'Rage Against the Machine' AND "name" = 'The Battle of Los Angeles';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2006-10-17' WHERE artist = 'Primus' AND "name" = 'They Can''t All Be Zingers';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'System of a Down' AND "name" = 'Steal This Album';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2018-11-09' WHERE artist = 'Bad Wolves' AND "name" = 'Zombie';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2006-11-07' WHERE artist = 'Three Days Grace' AND "name" = 'Pain';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2016-05-27' WHERE artist = 'Lacuna Coil' AND "name" = 'Delirium';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1996-09-17' WHERE artist = 'Tool' AND "name" = 'Ænima';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2020-09-25' WHERE artist = 'Deftones' AND "name" = 'ohms';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2011-11-30' WHERE artist = 'Korn' AND "name" = 'The Path of Totality (Special Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2002-07-01' WHERE artist = 'Rob Dougan' AND "name" = 'Furious Angels';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2002-01-28' WHERE artist = 'The Chemical Brothers' AND "name" = 'Come With Us';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2005-01-13' WHERE artist = 'The Chemical Brothers' AND "name" = 'Push the Button';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2013-04-19' WHERE artist = 'Daft Punk' AND "name" = 'Get Lucky';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2005-04-29' WHERE artist = 'Robyn' AND "name" = 'Robyn';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2005-10-03' WHERE artist = 'Ladytron' AND "name" = 'Witching Hour';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2008-09-16' WHERE artist = 'Passion Pit' AND "name" = 'Chunk of Change';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2007-10-11' WHERE artist = 'Róisín Murphy' AND "name" = 'Overpowered';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007-07-02' WHERE artist = 'The Chemical Brothers' AND "name" = 'We Are The Night';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2015-12-04' WHERE artist = 'Alan Walker' AND "name" = 'Faded';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-10-21' WHERE artist = 'Clean Bandit' AND "name" = 'Rockabye (feat. Sean Paul & Anne-Marie)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-01-13' WHERE artist = 'The Chainsmokers' AND "name" = 'Paris';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007-06-11' WHERE artist = 'Justice' AND "name" = 'Cross';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-02-23' WHERE artist = 'The Prodigy' AND "name" = 'Invaders Must Die';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2008-03-18' WHERE artist = 'Crystal Castles' AND "name" = 'Crystal Castles';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2005-04-05' WHERE artist = 'Fischerspooner' AND "name" = 'Odyssey';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2009-08-14' WHERE artist = 'Calvin Harris' AND "name" = 'Ready for the Weekend';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2009-08-24' WHERE artist = 'David Guetta' AND "name" = 'One Love';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2008-03-03' WHERE artist = 'MGMT' AND "name" = 'Time To Pretend';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-08-11' WHERE artist = 'Marshmello' AND "name" = 'Silence';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2014-03-14' WHERE artist = 'Calvin Harris' AND "name" = 'Summer';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2013-12-18' WHERE artist = 'DJ Snake' AND "name" = 'Turn Down For What';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2018-01-23' WHERE artist = 'Zedd' AND "name" = 'The Middle';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2015-04-27' WHERE artist = 'Blur' AND "name" = 'The Magic Whip';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2011' WHERE artist = 'The Smashing Pumpkins' AND "name" = 'Siamese Dream (2011 - Remaster)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1996-12-03' WHERE artist = 'Bloodhound Gang' AND "name" = 'One Fierce Beer Coaster';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2005-08-30' WHERE artist = '30 Seconds to Mars' AND "name" = 'A Beautiful Lie';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007-05-14' WHERE artist = 'Linkin Park' AND "name" = 'Minutes to Midnight';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2009-12-08' WHERE artist = '30 Seconds to Mars' AND "name" = 'This Is War';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2002-08-27' WHERE artist = 'Breaking Benjamin' AND "name" = 'Saturate';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2015-12-04' WHERE artist = 'Coldplay' AND "name" = 'A Head Full Of Dreams';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1989-05-02' WHERE artist = 'The Stone Roses' AND "name" = 'The Stone Roses';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2001-07-30' WHERE artist = 'The Strokes' AND "name" = 'Is This It';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2003-10-28' WHERE artist = 'The Strokes' AND "name" = 'Room on Fire';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2009' WHERE artist = 'Lily Allen' AND "name" = 'Alright, Still (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2009' WHERE artist = 'Beyoncé' AND "name" = 'I Am...Sasha Fierce - Platinum Edition';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006-07-13' WHERE artist = 'Lily Allen' AND "name" = 'Alright Still';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-02-24' WHERE artist = 'Billie Eilish' AND "name" = 'Bellyache';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-05-18' WHERE artist = 'Selena Gomez' AND "name" = '13 Reasons Why (Season 2)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2006-06-13' WHERE artist = 'Three Days Grace' AND "name" = 'One X';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2000-01-11' WHERE artist = 'Kittie' AND "name" = 'Spit';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1987-04-01' WHERE artist = 'Suzanne Vega' AND "name" = 'Solitude Standing';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1994-10-03' WHERE artist = 'The Cranberries' AND "name" = 'No Need to Argue';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2002-02-26' WHERE artist = 'Alanis Morissette' AND "name" = 'Under Rug Swept';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2005-10-03' WHERE artist = 'Fiona Apple' AND "name" = 'Extraordinary Machine';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2007-01-30' WHERE artist = 'Norah Jones' AND "name" = 'Not Too Late';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006-04-04' WHERE artist = 'Bitter:Sweet' AND "name" = 'The Mating Game';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-09-21' WHERE artist = 'The Asteroids Galaxy Tour' AND "name" = 'Fruit';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2011-01-11' WHERE artist = 'Britney Spears' AND "name" = 'Hold It Against Me - Single';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-03-30' WHERE artist = 'Billie Eilish' AND "name" = 'Bored';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2007-04-03' WHERE artist = 'Brandi Carlile' AND "name" = 'The Story';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-08-28' WHERE artist = 'A Fine Frenzy' AND "name" = 'Bomb in a Birdcage';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1998-11-17' WHERE artist = 'Whitney Houston' AND "name" = 'My Love Is Your Love';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2010-12-07' WHERE artist = 'Natasha Bedingfield' AND "name" = 'Strip Me';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2004-08-09' WHERE artist = 'Nouvelle Vague' AND "name" = 'Nouvelle Vague';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-11-17' WHERE artist = 'Billie Eilish' AND "name" = 'Six Feet Under';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2005-04-12' WHERE artist = 'Martha Wainwright' AND "name" = 'Martha Wainwright';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2008' WHERE artist = 'The Asteroids Galaxy Tour' AND "name" = 'Around the Bend';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2006-04-10' WHERE artist = 'El Perro del Mar' AND "name" = 'El Perro Del Mar';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2013-11-27' WHERE artist = 'Taylor Swift' AND "name" = 'I Knew You Were Trouble.';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2009-03-16' WHERE artist = 'Melody Gardot' AND "name" = 'My One And Only Thrill';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2020-10-25' WHERE artist = 'Wilbur' AND "name" = 'Your City Gave Me Asthma';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1989-01' WHERE artist = 'The Police' AND "name" = 'Synchronicity (Remastered)';
UPDATE "public"."Album" SET "numberOfTracks" = 27, "date" = '2008-12' WHERE artist = 'Radiohead' AND "name" = 'OK Computer (Collector''s Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-08-18' WHERE artist = 'The Rolling Stones' AND "name" = 'Tattoo You (2009 Re-Mastered)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2004' WHERE artist = 'Gavin DeGraw' AND "name" = 'Chariot - Stripped';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Arctic Monkeys' AND "name" = 'Who the Fuck Are Arctic Monkeys';
UPDATE "public"."Album" SET "numberOfTracks" = 33, "date" = '2013-09-02' WHERE artist = 'The 1975' AND "name" = 'The 1975 (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-10-16' WHERE artist = 'Izzy Bizu' AND "name" = 'White Tiger';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2017-11-24' WHERE artist = 'Little Mix' AND "name" = 'Glory Days: The Platinum Edition';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2011-11-04' WHERE artist = 'Birdy' AND "name" = 'Birdy (Deluxe Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2017-02-24' WHERE artist = 'Ed Sheeran' AND "name" = 'Shape of You';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2016-05-27' WHERE artist = 'Catfish and The Bottlemen' AND "name" = 'The Ride';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2009-05-29' WHERE artist = 'Paolo Nutini' AND "name" = 'Sunny Side Up';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2018-04-27' WHERE artist = 'Anne-Marie' AND "name" = 'Speak Your Mind (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2009-11-09' WHERE artist = 'Robbie Williams' AND "name" = 'Reality Killed the Video Star';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2006-04-24' WHERE artist = 'Arctic Monkeys' AND "name" = 'Who The F*** Are Arctic Monkeys?';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2005-05-30' WHERE artist = 'Turin Brakes' AND "name" = 'JackInABox';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2006-07-17' WHERE artist = 'The Pipettes' AND "name" = 'We Are The Pipettes';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2010-12-15' WHERE artist = 'Matt Cardle' AND "name" = 'When We Collide';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2018-04-20' WHERE artist = 'Bishop Briggs' AND "name" = 'Church Of Scars';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1967-03-12' WHERE artist = 'The Velvet Underground' AND "name" = 'The Velvet Underground & Nico';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1969-03' WHERE artist = 'The Velvet Underground' AND "name" = 'The Velvet Underground';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1972-11-08' WHERE artist = 'Lou Reed' AND "name" = 'Transformer';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1984-06-04' WHERE artist = 'Bruce Springsteen' AND "name" = 'Born in the U.S.A.';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2004-05-19' WHERE artist = 'Avril Lavigne' AND "name" = 'Under My Skin';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2005-06-06' WHERE artist = 'Coldplay' AND "name" = 'X & Y';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '1969-09-26' WHERE artist = 'The Beatles' AND "name" = 'Abbey Road';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006-08-28' WHERE artist = 'Kasabian' AND "name" = 'Empire';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2021-05-21' WHERE artist = 'Olivia Rodrigo' AND "name" = 'SOUR';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2018-10-05' WHERE artist = 'Twenty One Pilots' AND "name" = 'trench';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2011-02-25' WHERE artist = 'Jessie J' AND "name" = 'Who You Are';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1992-10-20' WHERE artist = 'Madonna' AND "name" = 'Erotica';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2017-06-23' WHERE artist = 'Imagine Dragons' AND "name" = 'eVolvE';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2019-04-19' WHERE artist = 'Lizzo' AND "name" = 'Cuz I Love You';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2020-04-17' WHERE artist = 'Rina Sawayama' AND "name" = 'Sawayama';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1988-10-18' WHERE artist = 'Sonic Youth' AND "name" = 'Daydream Nation';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Coldplay' AND "name" = 'X & Y';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2020-07-24' WHERE artist = 'Taylor Swift' AND "name" = 'FOlKlORE';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2019-04-25' WHERE artist = 'Kevin Abstract' AND "name" = 'ARIZONA baby';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2010-04-02' WHERE artist = 'Kavinsky' AND "name" = 'Nightcall';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2016-05-06' WHERE artist = 'Kaytranada' AND "name" = '99.9%';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2000-10-24' WHERE artist = 'PJ Harvey' AND "name" = 'Stories from the City, Stories from the Sea';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1993-11-09' WHERE artist = 'Wu-Tang Clan' AND "name" = 'Enter the Wu-Tang (36 Chambers)';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2007-12-24' WHERE artist = 'Wu-Tang Clan' AND "name" = 'Enter The Wu-Tang (36 Chambers) [Expanded Edition]';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2001-09-11' WHERE artist = 'Jay-Z' AND "name" = 'The Blueprint';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1996-06-25' WHERE artist = 'Jay-Z' AND "name" = 'Reasonable Doubt';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2009-09-08' WHERE artist = 'Jay-Z' AND "name" = 'The Blueprint 3';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '2004-02-10' WHERE artist = 'Kanye West' AND "name" = 'The College Dropout';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '1993-11-23' WHERE artist = 'Snoop Dogg' AND "name" = 'Doggystyle';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '2005-08-30' WHERE artist = 'Kanye West' AND "name" = 'Late Registration';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2003-11-14' WHERE artist = 'Jay-Z' AND "name" = 'The Black Album';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2020-05-01' WHERE artist = 'Drake' AND "name" = 'Dark Lane Demo Tapes';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-03-26' WHERE artist = 'Rihanna' AND "name" = 'Bitch Better Have My Money';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2016-04-29' WHERE artist = 'Drake' AND "name" = 'Views';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-10-05' WHERE artist = 'Trevor Daniel' AND "name" = 'Falling';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2018-02-09' WHERE artist = 'Kendrick Lamar' AND "name" = 'Black Panther the Album Music From and Inspired By';
UPDATE "public"."Album" SET "numberOfTracks" = 22, "date" = '2019-03-08' WHERE artist = 'Juice WRLD' AND "name" = 'Death Race For Love';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2019-12-06' WHERE artist = 'Roddy Ricch' AND "name" = 'Please Excuse Me For Being Antisocial';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2018-04-27' WHERE artist = 'Post Malone' AND "name" = 'Beerbongs & Bentleys';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2018-03-16' WHERE artist = 'xxxtentacion' AND "name" = '?';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2003-02-06' WHERE artist = '50 Cent' AND "name" = 'Get Rich Or Die Tryin''';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2006-09-19' WHERE artist = 'Lupe Fiasco' AND "name" = 'Food & Liquor';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2019-05-17' WHERE artist = 'Tyler, the Creator' AND "name" = 'Igor';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2018-08-24' WHERE artist = 'BTS' AND "name" = 'LOVE YOURSELF 結 ''Answer''';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2016-09-02' WHERE artist = 'Travis Scott' AND "name" = 'Birds In The Trap Sing McKnight';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2017-08-25' WHERE artist = 'xxxtentacion' AND "name" = '17';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2006-07-25' WHERE artist = 'Gym Class Heroes' AND "name" = 'As Cruel As School Children';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2015-09-20' WHERE artist = 'Drake' AND "name" = 'What a Time To Be Alive';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2018-11-30' WHERE artist = 'SKI MASK THE SLUMP GOD' AND "name" = 'Stokeley';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2017-12-15' WHERE artist = 'BROCKHAMPTON' AND "name" = 'Saturation III';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '2004-02-10' WHERE artist = 'Kanye West' AND "name" = 'College Dropout';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Coldplay' AND "name" = 'B-Sides (disc 2)';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1999-10-11' WHERE artist = 'Coldplay' AND "name" = 'The Blue Room E.P.';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Coldplay' AND "name" = '2005-07-13: Peazza Grande Locarno, Italy';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Coldplayers' AND "name" = 'Coldplayers Demo CD';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Tom Hancock' AND "name" = 'Thirteen [disc 2]';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Coldplay' AND "name" = '2005: Coachella, CA, USA';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2011-01-08' WHERE artist = 'Matt Lucca' AND "name" = 'In Between Love and Hate';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2008' WHERE artist = 'Jay-Z & Coldplay' AND "name" = 'Viva La Hova';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2014-05-19' WHERE artist = 'Coldplay' AND "name" = 'Ghost Stories (Deluxe Edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Good Golly! It''s Mr. Nick!' AND "name" = 'Home Demos. Tape One - www.myspace.com/goodgollyitsmrnick';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2007-06-25' WHERE artist = 'Catoan' AND "name" = 'and will i';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016' WHERE artist = 'Coldplay' AND "name" = 'Up&Up (Freedo Remix)';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2009-08-11' WHERE artist = 'Bridge Underwater' AND "name" = 'Feeling';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Tyler Adam' AND "name" = 'Maybe You Could Be';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Coldplay' AND "name" = 'Left Right Left Right Left EP';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'TyGuy Productions' AND "name" = 'Tyler Adam & TyGuy Productions Presents: reMIX3D Vol. 1';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2011-02-10' WHERE artist = 'Heavyplastic' AND "name" = 'Another Town Another Life';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Coldplay' AND "name" = 'Speed Of Sound (Live)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2004-01-01' WHERE artist = 'KALIMOTO' AND "name" = 'Multicore (UK)';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2006-01-01' WHERE artist = 'afar a bird' AND "name" = '3 Song Cycle';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Soylent Green' AND "name" = 'soylent green (Germany) - believe (1998)';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '1998-05-25' WHERE artist = 'Coldplay' AND "name" = 'Safety';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'KALIMOTO' AND "name" = 'Some Of Them Are Killers';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Tom Hancock' AND "name" = 'Thirteen [disc 1]';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2006-01-01' WHERE artist = 'NomadsLand' AND "name" = 'The Art of Flight [Original Soundtrack]';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Chris Krohm' AND "name" = 'The Grandeur that was Rome';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2009-04-20' WHERE artist = 'Nathan Clarke' AND "name" = 'The Junktion Sessions';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Coldplay' AND "name" = 'Speed of Sound Ep';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2005-06-01' WHERE artist = 'XanaX' AND "name" = 'First Pill';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2008-03-03' WHERE artist = 'Noneworks' AND "name" = 'Nanolife';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2008-11-14' WHERE artist = 'Bridge Underwater' AND "name" = 'The Music In Your Mind';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Soylent Green' AND "name" = 'soylent green (Germany) - signals & sentiments (2002)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Vanguard Villains' AND "name" = 'The Brooklyn Demos';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Soylent Green' AND "name" = 'soylent green (Germany) - the space between us (2000)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Opaque Nature' AND "name" = 'The Sea-side single';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2019-08-28' WHERE artist = 'A$AP Rocky' AND "name" = 'Babushka Boi';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2017-08-25' WHERE artist = 'BROCKHAMPTON' AND "name" = 'Saturation II';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2011-08-08' WHERE artist = 'Jay-Z' AND "name" = 'Watch The Throne (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2015-02-14' WHERE artist = 'Blackbear' AND "name" = 'deadroses';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2017-06-30' WHERE artist = 'Jay-Z' AND "name" = '4:44';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-02-13' WHERE artist = 'Matt Champion' AND "name" = 'Fangs';
UPDATE "public"."Album" SET "numberOfTracks" = 46, "date" = '2015-09-25' WHERE artist = 'Various Artists' AND "name" = 'Hamilton (Original Broadway Cast Recording)';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2017-07-14' WHERE artist = 'Mura Masa' AND "name" = 'MURA MASA';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dr. Dre' AND "name" = '2001 (Explicit Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-01-16' WHERE artist = 'A$AP Mob' AND "name" = 'Yamborghini High';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2018-11-30' WHERE artist = 'Earl Sweatshirt' AND "name" = 'some rap songs';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2015-10-30' WHERE artist = 'LIL UZI VERT' AND "name" = 'Luv Is Rage';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2005-10-10' WHERE artist = 'DANGERDOOM' AND "name" = 'The Mouse & The Mask';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2012-09-14' WHERE artist = 'Kanye West' AND "name" = 'Kanye West Presents Good Music Cruel Summer';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2019-03-08' WHERE artist = 'Dave' AND "name" = 'Psychodrama';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1967-05-12' WHERE artist = 'Jimi Hendrix' AND "name" = 'Are You Experienced';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1967-12-01' WHERE artist = 'Jimi Hendrix' AND "name" = 'Axis: Bold As Love';
UPDATE "public"."Album" SET "numberOfTracks" = 27, "date" = '2000-11-13' WHERE artist = 'The Beatles' AND "name" = 'The Beatles 1';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1977-10-28' WHERE artist = 'Queen' AND "name" = 'News Of The World';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1997-11-17' WHERE artist = 'The Police' AND "name" = 'The Very Best Of Sting And The Police';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1994-10-25' WHERE artist = 'Bob Seger' AND "name" = 'Greatest Hits';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Various Artists' AND "name" = 'Let''s Get Out Of This Country';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-06-30' WHERE artist = 'Wilco' AND "name" = 'Wilco (The Album)';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2001-06-05' WHERE artist = 'Manu Chao' AND "name" = 'Próxima Estación: Esperanza';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2008-11-21' WHERE artist = 'Coldplay' AND "name" = 'Prospekt''s March';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2014-10-07' WHERE artist = 'The Unicorns' AND "name" = 'Who Will Cut Our Hair When We''re Gone? (Remastered)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1999-11-09' WHERE artist = 'Fiona Apple' AND "name" = 'When the Pawn';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2009-06-05' WHERE artist = 'Kasabian' AND "name" = 'The West Rider Pauper Lunatic Asylum';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2000-04-10' WHERE artist = 'Moloko' AND "name" = 'Things to Make and Do';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2003-03-03' WHERE artist = 'Moloko' AND "name" = 'Statues';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1996-09-16' WHERE artist = 'DJ Shadow' AND "name" = 'Endtroducing...';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2018-06-22' WHERE artist = 'Panic! at the Disco' AND "name" = 'Pray for the Wicked';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2015-05-26' WHERE artist = 'A$AP Rocky' AND "name" = 'At.Long.Last.A$AP';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1998-08-25' WHERE artist = 'Ms. Lauryn Hill' AND "name" = 'The Miseducation Of Lauryn Hill';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Pink Floyd' AND "name" = 'The Dark Side Of The Moon [Remastered] (Remastered Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1974-09-13' WHERE artist = 'Supertramp' AND "name" = 'Crime of the Century';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2003-06-24' WHERE artist = 'The Mars Volta' AND "name" = 'Deloused in the Comatorium';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Pink Floyd' AND "name" = 'The Wall (disc 2)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Pink Floyd' AND "name" = 'The Wall (disc 1)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1973-03-01' WHERE artist = 'Pink Floyd' AND "name" = 'The Dark Side Of The Moon';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '2020-05-15' WHERE artist = 'Future' AND "name" = 'High Off Life';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2015-05-17' WHERE artist = 'Twenty One Pilots' AND "name" = 'Blurryface';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2019-08-02' WHERE artist = 'Clairo' AND "name" = 'Immunity';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1998-09-07' WHERE artist = 'Belle and Sebastian' AND "name" = 'The Boy With the Arab Strap';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2014-07-22' WHERE artist = 'Alvvays' AND "name" = 'Alvvays';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2006-06-06' WHERE artist = 'Camera Obscura' AND "name" = 'Let''s Get Out Of This Country';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2018-05-31' WHERE artist = 'Lauv' AND "name" = 'I met you when I was 18. (the playlist)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nirvana' AND "name" = 'Nervermind';
UPDATE "public"."Album" SET "numberOfTracks" = 60, "date" = '2013-10-02' WHERE artist = 'Nirvana' AND "name" = 'In Utero - 20th Anniversary Super Deluxe';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2001-11-20' WHERE artist = 'The Smashing Pumpkins' AND "name" = 'Greatest Hits - Rotten Apples';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2000-05-16' WHERE artist = 'Pearl Jam' AND "name" = 'Binaural';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2019-11-27' WHERE artist = 'ECCO2k' AND "name" = 'E';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2006-09-19' WHERE artist = 'Fear Before The March Of Flames' AND "name" = 'The Always Open Mouth';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2019-10-04' WHERE artist = 'Superm' AND "name" = 'SuperM - The 1st Mini Album';
UPDATE "public"."Album" SET "numberOfTracks" = 24, "date" = '1994-11-22' WHERE artist = 'John Frusciante' AND "name" = 'Niandra LaDes And Usually Just A T-Shirt';
-- UPDATE "public"."Album" SET "numberOfTracks" = , "date" =  WHERE artist =  AND "name" =
