UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '% [bonus %]';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Limp Bizkit' AND "name" = 'Three Dollar Bill, Y''all $';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Limp Bizkit' AND "name" = 'Three Dollar Bill, Yall';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Limp Bizkit' AND "name" = 'Chocolate Starfish and the Hotdog Flavored Water';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Limp Bizkit' AND "name" = 'Chocolate Starfish & The Hot Dog Flavoured Water';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Limp Bizkit' AND "name" = 'Chocolate Starfish And The Hot Dog Flavored Wat';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Papa Roach' AND "name" = '2000 - Infest';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Linkin Park' AND "name" = '2002 - Reanimation';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Linkin Park' AND "name" = '2003 - Meteora';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Drowning Pool' AND "name" = 'Desensitize';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'P.O.D.' AND "name" = 'Greatest Hits [The Atlantic Years]';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Linkin Park' AND "name" = '2003 - Live In Texas';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Slipknot' AND "name" = '1999 - Slipknot';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Slipknot' AND "name" = '2004 - Vol. 3: (The Subliminal Verses)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Slipknot' AND "name" = 'Vol. 3 The Subliminal Verses';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Slipknot' AND "name" = '2004 - Vol. 3: (The Subliminal Verses)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Slipknot' AND "name" = 'Vol. 3 - The Subliminal Verses';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Slipknot' AND "name" = 'Vol. 3 : (The Subliminal Verses)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Slipknot' AND "name" = 'Vol.3: The Subliminal Verses';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Deftones' AND "name" = 'Adrenalin';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Linkin Park' AND "name" = 'Linkin Park Live In Texas';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'DragonForce' AND "name" = 'Inhuman Rampage Advance Promo';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sonata Arctica' AND "name" = '2001 - Silence';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Avantasia' AND "name" = 'The Metal Opera - part I';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Avantasia' AND "name" = 'Scarecrow';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Iced Earth' AND "name" = 'Dark Saga';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Stratovarius' AND "name" = '2000 - Infinite';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Blind Guardian' AND "name" = 'Imaginations From The Other...';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Blind Guardian' AND "name" = 'Imagination From The Other Side';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Demons & Wizards' AND "name" = 'Touched by the Crimson King (L';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Gamma Ray' AND "name" = 'No World Order!';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'HammerFall' AND "name" = 'Chapter V:Unbent,Unbowed,Unbroken';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Stratovarius' AND "name" = '1998 - Destiny';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Blasphemy' AND "name" = 'Fallen Angel Of Doom....';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Vision Divine' AND "name" = 'The 25th Hour : 2007';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2006-08-10' WHERE artist = '7Days' AND "name" = 'The Weight Of The World';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006' WHERE artist = 'Children of Bodom' AND "name" = 'Follow The Reaper - Deluxe Edition';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2004' WHERE artist = 'Children of Bodom' AND "name" = 'Hate Crew Deathroll Limited';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dethklok' AND "name" = 'Dethalbum';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Insomnium' AND "name" = 'Since the Day All Came Down';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Hypocrisy' AND "name" = 'Arrival';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Soilwork' AND "name" = 'A predators portrait';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Scar Symmetry' AND "name" = 'Symmetric in Design Digipak';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '1995-02-25' WHERE artist = 'Godkiller' AND "name" = 'The Warlord';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1996-10-29' WHERE artist = 'Godkiller' AND "name" = 'The Rebirth of the Middle Ages';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1998-06-27' WHERE artist = 'Godkiller' AND "name" = 'The End of the World';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Vogelfrey' AND "name" = 'The Essence of Steel - Metal Summer Festival Anthems 2011';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2005-05-30' WHERE artist = 'In Extremo' AND "name" = 'Mein rasend Herz (ltd. Version)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'In Extremo' AND "name" = 'Kein Blick zurück (Digital Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-08-09' WHERE artist = 'Saltatio Mortis' AND "name" = 'Spur des Lebens';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2010-02' WHERE artist = 'Subway to Sally' AND "name" = 'Bastard Tour Edition';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'In Extremo' AND "name" = 'Saengerkrieg';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '% (regular edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '% (regular version)';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '% (standard edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '% (standard version)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-07-13' WHERE artist = 'Saltatio Mortis' AND "name" = 'We Drink Your Blood';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2010' WHERE artist = 'Subway to Sally' AND "name" = 'Best Of "Kleid aus Rosen"';
UPDATE "public"."Album" SET "numberOfTracks" = 24, "date" = '2009-05-15' WHERE artist = 'In Extremo' AND "name" = 'Am Goldenen Rhein - Live';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Saltatio Mortis' AND "name" = 'Manufactum II (Live)';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2011-04-01' WHERE artist = 'Ignis Fatuu' AND "name" = 'Neue Ufer';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Saltatio Mortis' AND "name" = 'Das Schwarze IXI';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2004-09-27' WHERE artist = 'New Order' AND "name" = 'The Acid House Mixes by 808 State';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-08-14' WHERE artist = 'Subway to Sally' AND "name" = 'Zirkus Zeitgeist (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2012-06-18' WHERE artist = 'Lex Talion' AND "name" = 'Blood & Mead (EP 2012)';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2015-08-14' WHERE artist = 'Saltatio Mortis' AND "name" = 'Zirkus Zeitgeist (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 23, "date" = '2016-04-01' WHERE artist = 'Saltatio Mortis' AND "name" = 'Zirkus Zeitgeist (Live aus der Grossen Freiheit)';
UPDATE "public"."Album" SET "numberOfTracks" = 26, "date" = '2018-08-17' WHERE artist = 'Saltatio Mortis' AND "name" = 'Brot und Spiele (Deluxe)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Ritual Moon' AND "name" = 'Forgotten Crucible (SINGLE)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-07-20' WHERE artist = 'Saltatio Mortis' AND "name" = 'The Sacrament of Sin (Deluxe Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-07-19' WHERE artist = 'Saltatio Mortis' AND "name" = 'Dorn im Ohr';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-06-14' WHERE artist = 'Saltatio Mortis' AND "name" = 'Brunhild';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-06-28' WHERE artist = 'Saltatio Mortis' AND "name" = 'Heimdall';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2008-10-21' WHERE artist = 'Centr' AND "name" = 'Эфир в норме';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2002' WHERE artist = 'Каста' AND "name" = 'Что нам делать в греции';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '2011' WHERE artist = 'Рем Дигга' AND "name" = 'Глубина';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2009-05-03' WHERE artist = 'Грот' AND "name" = 'Никто, Кроме Нас';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2008-10-28' WHERE artist = 'ST' AND "name" = 'Сто Из Ста';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2007-11-16' WHERE artist = 'Рыночные Отношения' AND "name" = 'Мишкин 1988-1488';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2010-04-10' WHERE artist = 'Грот' AND "name" = 'Вершители судеб';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2012' WHERE artist = 'Триада' AND "name" = 'Мои глаза открыты';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2012' WHERE artist = 'Грот' AND "name" = 'Больше, чем живы';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2009-09-22' WHERE artist = '25/17' AND "name" = 'только для своих';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1999-07-02' WHERE artist = 'Каста' AND "name" = 'Трехмерные Рифмы';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2016-02-10' WHERE artist = 'Рем Дигга' AND "name" = 'Черника и Циклоп';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2009' WHERE artist = 'Рем Дигга' AND "name" = 'Периметр';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2014-08-31' WHERE artist = 'Рем Дигга' AND "name" = 'Людоед';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2001-04-19' WHERE artist = 'Bad Balance' AND "name" = 'Каменный Лес';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2014-12-29' WHERE artist = 'Рем Дигга' AND "name" = 'Граната';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2009' WHERE artist = 'Ar-SiDE' AND "name" = 'Вне грима EP';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-10-30' WHERE artist = 'Грот' AND "name" = 'Откуда мне знать тебя';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1999-11' WHERE artist = 'Ю.Г.' AND "name" = 'Семья Ю.Г.А';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2013' WHERE artist = 'БАСТА' AND "name" = 'Crocus City Hall (Live 2012)';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '2003' WHERE artist = 'Rage Against the Machine' AND "name" = 'Rage Against The Machine/Evil Empire';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Cypress Hill' AND "name" = 'Skull And Bones';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'O''Funk''illo' AND "name" = 'O''Funkillo';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Public Enemy' AND "name" = 'How You Sell Soul To A Souless People Who Sold Their Soul';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Lock Up' AND "name" = 'Pleasure Paves Sewers';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2002-01-12' WHERE artist = 'Ghoul' AND "name" = 'We Came For the Dead!!!';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sleep' AND "name" = 'Sleeps Holy Mountain';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Electric Wizard' AND "name" = 'Come My Fanatics';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Electric Wizard' AND "name" = '2000 - Dopethrone';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Red Hot Chili Peppers' AND "name" = 'Californication Unmastered';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Red Hot Chili Peppers' AND "name" = '2006 - Stadium Arcadium';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Coldplay' AND "name" = 'Viva la Vida or Death and All';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Red Hot Chili Peppers' AND "name" = 'By the Way';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Coldplay' AND "name" = '2002 - A Rush of Blood to the Head';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Foo Fighters' AND "name" = 'Echoes, Silence, Patience and Grace';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Maroon 5' AND "name" = '2002 - Songs About Jane';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = '30 Seconds to Mars' AND "name" = '2005 - A Beautiful Lie';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Avril Lavigne' AND "name" = 'Under My Skin B-Sides';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Arctic Monkeys' AND "name" = 'Whatever People Say I Am, That''s What I Am Not';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Queens of the Stone Age' AND "name" = 'Songs For The Deaf-RETAIL';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Green Day' AND "name" = '2004 - American Idiot';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Green Day' AND "name" = 'American Idiot-ADVANCE';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Jimmy Eat World' AND "name" = 'Bleed American EP';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '%-retail';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '%-advance';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Draconian' AND "name" = '2005 - Arcane Rain Fell';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2020-10-30' WHERE artist = 'Draconian' AND "name" = 'Under A Godless Veil';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Corrosion of Conformity' AND "name" = 'America`s Volume Dealer';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dillinger Four' AND "name" = '"Situationist Comedy"';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Amebix' AND "name" = 'Arise!!';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Extreme Noise Terror' AND "name" = '1988 - A Holocaust In Your Head';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Aus-Rotten' AND "name" = 'Not One Single Fucking Hit Discography';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Saddest Landscape' AND "name" = 'Life Your Burdens High For This is Where We Cross';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Saddest Landscape' AND "name" = 'Lift Your Burdens High, For This Is Where We Cross';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Suis la lune' AND "name" = 'Heir EP';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Pg.99' AND "name" = 'Document #07';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2004' WHERE artist = 'La quiete' AND "name" = 'La fine non è la fine';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Eths' AND "name" = 'Teratologie';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Eths' AND "name" = 'Soma';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '% (cd_)';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '% (cd__)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'M83' AND "name" = 'Dead Cities, Red Seas, and Lost Ghosts';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'M83' AND "name" = 'DeadCities,RedSeas&LostGhosts';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'M83' AND "name" = 'Dead Cities, Red Seas and Lost Ghosts';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'M83' AND "name" = 'Digital Shades, Vol. 1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Twilight Sad' AND "name" = 'Fourteen Autumns, Fifteen Winters';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Twilight Sad' AND "name" = 'Fourteen Autumns and Fifteen Winters';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'My Bloody Valentine' AND "name" = 'Glider Ep';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2009' WHERE artist = '210' AND "name" = 'Первая Кровь';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2007' WHERE artist = 'Moshpit' AND "name" = 'Mirror Of An Unbroken Faith';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2010' WHERE artist = 'Outlaw Heroes Standing' AND "name" = 'За Кровь и Нефть (For Blood And Oil)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2006' WHERE artist = 'Fear Rains Down' AND "name" = 'No turning back';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2010' WHERE artist = 'Death Penalty' AND "name" = 'новый мир';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2003' WHERE artist = 'Blue Eyed Devils' AND "name" = 'It End''s';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2009' WHERE artist = 'Project Vandal' AND "name" = 'Bullseye!!!';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1996' WHERE artist = 'Blue Eyed Devils' AND "name" = 'Hate Crimes';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2004-08-16' WHERE artist = 'Grinded Nig' AND "name" = 'Nazi Headbanger';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2007' WHERE artist = 'Eternal Bleeding' AND "name" = 'Dead Eyes Kissed The Light';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Kiborg' AND "name" = 'Лжегуманизм';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2003-01-01' WHERE artist = 'Iron Eagle' AND "name" = 'Sieg Heil';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2008' WHERE artist = '9 Вал' AND "name" = 'Ни шагу назад';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2011-03-22' WHERE artist = 'Трезвый Заряд' AND "name" = 'Без лица';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1996' WHERE artist = 'Aggravated Assault' AND "name" = 'Hate Crimes';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006' WHERE artist = 'Hatelordz' AND "name" = 'Hellsgate N.Y.C';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2006-10-28' WHERE artist = 'Zetazeroalfa' AND "name" = 'Nel dubbio mena';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2006' WHERE artist = 'Christian Weston Chandler' AND "name" = 'Christian & the Hedgehog Boys';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1991' WHERE artist = 'Sheer Terror' AND "name" = 'Ugly and Proud';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'White Aryan Rebels' AND "name" = 'Noten des Hasses';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2001' WHERE artist = 'H8Machine' AND "name" = 'Cheated';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Blue Eyed Devils' AND "name" = '...It Ends';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2006' WHERE artist = 'Die Lunikoff Verschwörung' AND "name" = 'Niemals auf Knien';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1998' WHERE artist = 'Chaos 88' AND "name" = 'Welcome to Atlantic City';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2005-12-19' WHERE artist = 'Hate for breakfast' AND "name" = 'Hatecore Connection';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2010' WHERE artist = 'Tormentia' AND "name" = 'Krew za krew';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2008' WHERE artist = 'Aryan Brotherhood' AND "name" = 'Die Schatten einer kranken Welt';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2003' WHERE artist = 'Aryan Brotherhood' AND "name" = 'Fanatiker';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2006' WHERE artist = 'Brutal Begude' AND "name" = '... Forever ours';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2007-04' WHERE artist = 'Anger Within' AND "name" = 'Lost path';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2009-05' WHERE artist = 'Hate for breakfast' AND "name" = 'Squadrismo HardCore';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Woods of Infinity' AND "name" = 'Hamptjarn';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Marduk' AND "name" = 'Heaven Shall Burn ... When We Are Gathered';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2002-05-21' WHERE artist = 'Various Artists' AND "name" = 'Under Wings of Hell';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1998-02-11' WHERE artist = 'Watain' AND "name" = 'Go Fuck Your Jewish God';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2016-02-29' WHERE artist = 'Hermóðr' AND "name" = 'The Darkness of December';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '1991-09-05' WHERE artist = 'Dissection' AND "name" = 'Into Infinite Obscurity';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '1991-02' WHERE artist = 'Dissection' AND "name" = 'The Grief Prophecy';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1995' WHERE artist = 'Throne of Ahaz' AND "name" = 'Nifelheim';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1997-03-04' WHERE artist = 'Necrophobic' AND "name" = 'Darkside';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1999-10' WHERE artist = 'Watain' AND "name" = 'Black Metal Sacrifice';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2000-06' WHERE artist = 'Thy Primordial' AND "name" = 'The Heresy Of An Age Of Reason';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2001' WHERE artist = 'Watain' AND "name" = 'The Ritual Macabre';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dark Funeral' AND "name" = 'Devil Pigs';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2001-01' WHERE artist = 'Armagedda' AND "name" = 'The Final War Approaching';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2013-11-25' WHERE artist = 'Dark Funeral' AND "name" = 'Diabolis Interium (Re-issue + Bonus)';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2004-12-06' WHERE artist = 'Woods of Infinity' AND "name" = 'Förintelse & Libido';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2003-11-17' WHERE artist = 'Watain' AND "name" = 'Casus Luciferi';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2002' WHERE artist = 'Pest' AND "name" = 'Blasphemy Is My Throne';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1996-05' WHERE artist = 'Nefandus' AND "name" = 'The Nightwinds Carried Our Names';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2007-02-01' WHERE artist = 'Snötårar' AND "name" = 'Vredeslusta';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2010-03-15' WHERE artist = 'Orcivus' AND "name" = 'Est Deus In Nobis';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2011-08-15' WHERE artist = 'Bekëth Nexëhmü' AND "name" = 'De dunkla herrarna';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2013-04-15' WHERE artist = 'Wulkanaz' AND "name" = 'Paúrpura Fræovíbôkôs';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Watain' AND "name" = 'All That May Bleed (Single)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Meshuggah' AND "name" = 'Psykisk Testbild';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1989' WHERE artist = 'Accu§er' AND "name" = 'Who Dominates Who?';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2018-06-08' WHERE artist = 'Exmortus' AND "name" = 'The Sound Of Steel';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1990' WHERE artist = 'Turbo' AND "name" = 'Dead End';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Savage Messiah' AND "name" = 'Insurrecton Rising';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1985-11-30' WHERE artist = 'Watchtower' AND "name" = 'Energetic Disassembly';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Coroner' AND "name" = 'R.I.P';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1987-04-24' WHERE artist = 'Artillery' AND "name" = 'Terror Squad';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1987-09-01' WHERE artist = 'Deathrow' AND "name" = 'Raging Steel';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1989-06-12' WHERE artist = 'Deathrow' AND "name" = 'Deception Ignored';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1988-11-08' WHERE artist = 'Realm' AND "name" = 'Endless War';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1989-10-13' WHERE artist = 'Toxik' AND "name" = 'Think This';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1990' WHERE artist = 'Turbo' AND "name" = 'Epidemic';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1988-11-15' WHERE artist = 'Target' AND "name" = 'Master Project Genesis';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1989-01-01' WHERE artist = 'Destruction' AND "name" = 'Live Without Sense';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1990-12' WHERE artist = 'Hellwitch' AND "name" = 'Syzygial Miscreancy';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1991-04-10' WHERE artist = 'Invocator' AND "name" = 'Excursion Demise';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1991-10' WHERE artist = 'Ravenous' AND "name" = 'Book of Covetous Souls';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1993-05' WHERE artist = 'Аспид' AND "name" = 'Кровоизлияние';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1992' WHERE artist = 'Fatal Opera' AND "name" = 'Fatal Opera';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2008-06' WHERE artist = 'Thirteen Wars' AND "name" = 'Fire At Will';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2009-03-01' WHERE artist = 'Death Over Threat' AND "name" = 'Sangre';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2010-04-21' WHERE artist = 'Endovein' AND "name" = 'Waiting for Disaster';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2018-10-19' WHERE artist = 'Sacral Rage' AND "name" = 'Beyond Celestial Echoes';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2020-09-18' WHERE artist = 'Heathen' AND "name" = 'Empire Of The Blind';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2003' WHERE artist = 'Opeth' AND "name" = 'Still Life/Digi';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Death' AND "name" = 'The sounds of perseverance';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Faceless' AND "name" = 'Planetary Dulaity';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Orphaned Land' AND "name" = 'Mabool: The Story Of Three Sons Of Seven';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2007-02-07' WHERE artist = 'A Plea for Purging' AND "name" = 'Quick is the Word ; Steady is the Action';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Every Time I Die' AND "name" = 'Hot Damn';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Number Twelve Looks Like You' AND "name" = 'Put On Your Rosey Red Glasses';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'I the Breather' AND "name" = 'Musik';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Misery Signals' AND "name" = 'We Are the Romans';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Polaris' AND "name" = 'The Guilt';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-10-03' WHERE artist = 'Veil of Maya' AND "name" = 'doublespeak';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2008-08-19' WHERE artist = 'Human Abstract' AND "name" = 'Midheaven';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2018-04-26' WHERE artist = 'Sectioned' AND "name" = 'Annihilated';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Ephel Duath' AND "name" = 'The Painter`s Palette';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Ephel Duath' AND "name" = 'Painter''s Palette';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '1991' WHERE artist = 'Cynic' AND "name" = '1991 Demo (Roadrunner)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Diablo Swing Orchestra' AND "name" = 'The Butchers Ballroom';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'A Fashionable Disease' AND "name" = 'Untitled Album';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2002' WHERE artist = 'Citriniti' AND "name" = 'Hydra Odd World';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Don Caballero' AND "name" = '2006 - World Class Listening Problem';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2020-06-16' WHERE artist = 'Echidna' AND "name" = 'Escape from Civilization';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2010-09-10' WHERE artist = 'Horeja' AND "name" = 'La Mas Desechable De Todas Las Maquinas';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Shining' AND "name" = 'Black Jazz';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2014-02-01' WHERE artist = 'Uzumaki' AND "name" = 'Knowledge of a Language One Has Never Learned';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006-04-18' WHERE artist = 'John Zorn' AND "name" = 'Moonchild';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1981-09' WHERE artist = 'Massacre' AND "name" = 'Killing Time';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '1988' WHERE artist = 'Cynic' AND "name" = '1988 Demo';
UPDATE "public"."Album" SET "numberOfTracks" = 29, "date" = '1992' WHERE artist = 'Naked City' AND "name" = 'Grand Guignol';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1993' WHERE artist = 'Jonas Hellborg Group' AND "name" = 'E';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1998' WHERE artist = 'Anomaly' AND "name" = 'Anomaly';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2000-06-06' WHERE artist = 'Planet X' AND "name" = 'Universe';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2001' WHERE artist = 'Red Tide' AND "name" = 'Type II';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2001-03-06' WHERE artist = 'Dog Fashion Disco' AND "name" = 'Anarchists of Good Taste';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2000' WHERE artist = 'Coprofago' AND "name" = 'Genesis';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2002-04-03' WHERE artist = 'Planet X' AND "name" = 'Live From Oz';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2003-10-10' WHERE artist = 'Pavor' AND "name" = 'Furioso';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2006' WHERE artist = 'Panzerballett' AND "name" = 'Panzerballett';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2007-04' WHERE artist = 'Black Engine' AND "name" = 'Ku Klux Klowns';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2010-10-12' WHERE artist = 'White Walls' AND "name" = 'Mad Man Circus';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2012-11-30' WHERE artist = 'Mindwork' AND "name" = 'Eterea';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2018-11-16' WHERE artist = 'STEORRAH' AND "name" = 'The Altstadt Abyss';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Dillinger Escape Plan' AND "name" = 'Irony Is A Dead Scene EP';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sikth' AND "name" = 'Trees Are Dead & Dried Out, Wait for Something Wild';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sikth' AND "name" = 'The Trees Are Dead & Dried Out... Wait For Something Wild';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Norma Jean' AND "name" = 'O''God, The Aftermath';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Dillinger Escape Plan' AND "name" = 'The Dillinger Escape Plan EP';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Norma Jean' AND "name" = 'Bless The Martry, Kiss The Child';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Norma Jean' AND "name" = 'Bless the Martyr and Kiss...';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2012-11-12' WHERE artist = 'Darkenhöld' AND "name" = 'Echoes From The Stone Keeper';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Subway to Sally' AND "name" = 'Mitgift – Mördergeschichten';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2013-10-27' WHERE artist = 'Letharia' AND "name" = 'Irgendwo ～遺されし者の追想曲～';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2010' WHERE artist = 'Saltatio Mortis' AND "name" = 'M''ERA LUNA 2010';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Subway to Sally' AND "name" = 'WhatsApp Audio';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Oasis' AND "name" = '(What''s The Story) Morning Glory';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = '...And You Will Know Us by the Trail of Dead' AND "name" = 'And You Will Know Us By the Trail of Dead';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Tequilajazzz' AND "name" = 'Стреляли?';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Shape of Despair' AND "name" = 'Angel Of Distress';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nortt' AND "name" = 'Ligfaerd';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Colosseum' AND "name" = 'Chapter I : Delirium';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Venom' AND "name" = '1981 - Welcome to Hell';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '% (CD _)';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '% (CD __)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Throane' AND "name" = 'Derrière-Nous, La Lumière';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Beatles' AND "name" = 'Help';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1977-10-14' WHERE artist = 'David Bowie' AND "name" = 'Heroes';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2001-09-04' WHERE artist = 'System of a Down' AND "name" = 'Toxicity';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2016-05-06' WHERE artist = 'Skepta' AND "name" = 'KONNICHIWA';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nirvana' AND "name" = 'Never Mind';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nirvana' AND "name" = '1991 - Nevermind';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE '% ';
UPDATE "public"."Album" SET "hidden" = true WHERE "name" ILIKE ' %';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Coldplay' AND "name" = 'Viva la Vida';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2020-01-17' WHERE artist = 'BTS' AND "name" = 'Black Swan';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2021-04-02' WHERE artist = 'BTS' AND "name" = 'Film out';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Possessed' AND "name" = 'Death Metal Demo';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bolt Thrower' AND "name" = 'Honour-Valour-Pride';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bolt Thrower' AND "name" = 'Honour, Valour, Pride';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2006-06' WHERE artist = 'Death Breath' AND "name" = 'Death Breath';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '1997' WHERE artist = 'Sadistic Intent' AND "name" = 'Ancient Black Earth';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bathory' AND "name" = 'Nordland';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bathory' AND "name" = 'Nordland, Vol. 2';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Windir' AND "name" = 'Soknardalr';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Turisas' AND "name" = 'Varangain Way';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Moonsorrow' AND "name" = 'Verifakeet';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2007' WHERE artist = 'Demonaz' AND "name" = 'Promo';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nile' AND "name" = 'Amongst The Catacombs Of Neph';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Behemoth' AND "name" = 'Apostasy';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Carcass' AND "name" = 'Necroticism - Descanting the Insalubrious';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Carcass' AND "name" = 'Necroticism-Descanting The Insalubrious';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Morbid Angel' AND "name" = '1991 - Blessed Are The Sick';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nile' AND "name" = 'Anihilation of the Wicked';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Roadrunner United' AND "name" = 'The All-Star Session';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Roadrunner United' AND "name" = 'The All Star Sessions';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Gojira' AND "name" = 'From Mars To Sirus';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'DevilDriver' AND "name" = 'Devil Driver';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bloodbath' AND "name" = 'Fathomless Mastery';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Behemoth' AND "name" = 'Zos Kia Cultus - Here And Beyond';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Behemoth' AND "name" = '1999 - Satanica';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2021-06-04' WHERE artist = 'Sordide' AND "name" = 'Les Idées Blanches';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Black Sabbath' AND "name" = 'We Sould Our Soul for Rock ''N''';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Metallica' AND "name" = 'Re-Load';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Metallica' AND "name" = '1991 - Metallica';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Metallica' AND "name" = 'Mettalica';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Avenged Sevenfold' AND "name" = '2007 - Avenged Sevenfold';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Megadeth' AND "name" = 'Countdown To Extinction [Remix';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Metallica' AND "name" = '2008 - Death Magnetic';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Ghost' AND "name" = '2010 - Opus Eponymous';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Judas Priest' AND "name" = 'Paint Killer';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Volbeat' AND "name" = 'Rock The Rebel - Metal The Devil';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sepultura' AND "name" = 'Chaos a. d.';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Slayer' AND "name" = 'Diablous in musica';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Testament' AND "name" = 'Gathering';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Megadeth' AND "name" = 'That One Night Live in Buenos Aires';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Megadeth' AND "name" = 'That One Night Live In Buenos Aires';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Slayer' AND "name" = '1994 - Divine Intervention';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Slayer' AND "name" = 'God hate Us All';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Municipal Waste' AND "name" = '2007 - The Art Of Partying';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Anthrax' AND "name" = 'Fistul Of Metal';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Metallica' AND "name" = 'Black';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2015' WHERE artist = 'Black Sabbath' AND "name" = 'Paranoid (2014 Remaster)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Judas Priest' AND "name" = 'Stained Glass';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dropkick Murphys' AND "name" = 'Sing Loud Sing Proud';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dropkick Murphys' AND "name" = 'Sing Loud, Sing Proud';
UPDATE "public"."Album" SET "numberOfTracks" = 52, "date" = '1989-10-27' WHERE artist = 'Sore Throat' AND "name" = 'Never Mind The Napalm... Here''s Sore Throat';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sore Throat' AND "name" = 'Never Mind The Napalm Here''s Sore Throat';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2014-01-27' WHERE artist = 'Bleed the Pigs' AND "name" = 'Mortis Fatum EP';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Violent Headache' AND "name" = 'Therapy of Noise Demo';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2010' WHERE artist = 'Putrefaction Pestilence' AND "name" = 'Stenching Putrefaction Of Decomposing Cadaveric Organs';
UPDATE "public"."Album" SET "numberOfTracks" = 26, "date" = '2020-05-10' WHERE artist = 'c@' AND "name" = 'copy';
UPDATE "public"."Album" SET "numberOfTracks" = 23, "date" = '1998-08-25' WHERE artist = 'Gore Beyond Necropsy' AND "name" = 'Noise-A-Go Go !!!';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2011-01-23' WHERE artist = 'Agathocles' AND "name" = 'agathocles / kerenaneko / prostuck / rvota';
UPDATE "public"."Album" SET "numberOfTracks" = 22, "date" = '2011-09-08' WHERE artist = 'Alonso Lopez' AND "name" = 'Segunda Violacion Sonora';
UPDATE "public"."Album" SET "numberOfTracks" = 30, "date" = '1998' WHERE artist = 'Machetazo' AND "name" = 'Realmente Disfruto Comiendo Cadáveres';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2011' WHERE artist = 'Liquidised' AND "name" = 'Viceral Fetishism';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2001' WHERE artist = 'Last Days of Humanity' AND "name" = '138 Minutes Body Disposal';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1995' WHERE artist = 'Merzbow & Gore Beyond Necropsy' AND "name" = 'Rectal Grinder';
UPDATE "public"."Album" SET "numberOfTracks" = 23, "date" = '2013-04-14' WHERE artist = 'Corvid Canine' AND "name" = 'Sleep Betrays Us';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1995' WHERE artist = 'agacoples' AND "name" = 'Agacoples / Brutal Noise';
UPDATE "public"."Album" SET "numberOfTracks" = 38, "date" = '2009' WHERE artist = 'Violent Headache' AND "name" = 'The Noisecore Days';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2020-12-01' WHERE artist = 'Germen' AND "name" = 'Te Pudres';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Various Artists' AND "name" = '3-Way Mushroom Split';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2013-12-18' WHERE artist = 'Kusari Gama Kill' AND "name" = 'The Zombies EP (Kusari Gama Kill/Sarkofachocrss88 7" split)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Havoc on Fire' AND "name" = 'Why Untitled?';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Anal Cunt' AND "name" = '5643 Song EP (7'''' EP)';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2013' WHERE artist = 'Gorgonized Dorks' AND "name" = 'Maximum Thrash / Gorgonized Dorks';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1995' WHERE artist = 'Cripple Bastards' AND "name" = 'cripple bastards/psychotic noise';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2018-07-29' WHERE artist = 'Necrologyst' AND "name" = 'The Dance Of The Disembowel';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2020-04-24' WHERE artist = 'Bloody Vomit' AND "name" = 'Spectrophobia';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2012-08-07' WHERE artist = 'Maläd' AND "name" = 'eat pussy,not animals ep';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2002-04' WHERE artist = 'Various Artists' AND "name" = 'Dynamite With a Laserbeam - Queen as Heard Through the Meat Grinder of Three One G';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1995' WHERE artist = 'Machetazo' AND "name" = '46 Cabezas Aplastadas Por Un Yunque Oxidado';
UPDATE "public"."Album" SET "numberOfTracks" = 33, "date" = '1999-11-09' WHERE artist = 'Anal Cunt' AND "name" = 'It Just Gets Worse';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2001-07' WHERE artist = 'Enbilulugugal' AND "name" = 'Demos I & II';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2011-04-13' WHERE artist = 'Enbilulugugal' AND "name" = 'taoGtnepreS';
UPDATE "public"."Album" SET "numberOfTracks" = 27, "date" = '2006' WHERE artist = 'Sore Throat' AND "name" = 'Death To Capitalist Halmshaw';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2007-03-15' WHERE artist = 'Insect Warfare' AND "name" = 'Evolved Into Obliteration';
UPDATE "public"."Album" SET "numberOfTracks" = 28, "date" = '2007-11' WHERE artist = 'Enbilulugugal' AND "name" = 'Goatfucked Demology: The Years of HellNoize';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2011-08-01' WHERE artist = 'Anal Cunt' AND "name" = 'Wearing Out Our Welcome';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2010-12-15' WHERE artist = 'Alonso Lopez' AND "name" = 'Beibi Beibi Beibi EP';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2006' WHERE artist = 'Slaughtergrave' AND "name" = 'permanent death / slaughtergrave';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '2012-10-31' WHERE artist = 'Enbilulugugal' AND "name" = 'Frostfucked SaGoatan Blasphemies';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-06-06' WHERE artist = 'Enbilulugugal' AND "name" = 'Satanism''s for Pussy''s';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2017-01-01' WHERE artist = 'Enbilulugugal' AND "name" = 'LORD OF THE LARD';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2017-03-19' WHERE artist = 'Enbilulugugal' AND "name" = 'Let Us In';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2011-04-08' WHERE artist = 'Enbilulugugal' AND "name" = 'tnepreStaoG';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2017-06-09' WHERE artist = 'Enbilulugugal' AND "name" = 'Offerings to Curlyton';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2015-09-23' WHERE artist = 'Enbilulugugal' AND "name" = 'Another Fucking Pointless Enbilulugugal Compilation';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2002-03' WHERE artist = 'Sissy Spacek' AND "name" = 'Scissors';
UPDATE "public"."Album" SET "numberOfTracks" = 26, "date" = '2018-09-05' WHERE artist = 'Sissy Spacek' AND "name" = 'Expanding Antiverse';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2020-01' WHERE artist = 'Fucked' AND "name" = 'JapariGate';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '1998' WHERE artist = 'Silencer' AND "name" = 'Death, Pierce Me';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Xasthur' AND "name" = 'A Gate Through Bloodstained Mi';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Voivod' AND "name" = 'Nothing Face';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Metallica' AND "name" = '...And Justica For All';
UPDATE "public"."Album" SET "numberOfTracks" = 26, "date" = '2000-02-22' WHERE artist = 'S.O.D.' AND "name" = 'Speak English or Die - Platinum Edition';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2017-06-23' WHERE artist = 'Municipal Waste' AND "name" = 'Slime And Punishment';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Suicidal Tendencies' AND "name" = 'Free your Soul...and Save my mind';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Suicidal Tendencies' AND "name" = 'How Will I Laugh Tomorrow...When I Can''t Even Smile Today';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Agnostic Front' AND "name" = 'Riot, Riot Upstart';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Excel' AND "name" = 'Joke''s On You';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Suicidal Tendencies' AND "name" = 'Lights...Camera...Revolution';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Suicidal Tendencies' AND "name" = 'Free your Soul...and Save my mind';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Siege' AND "name" = 'Drop Dead LP 1984';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2005' WHERE artist = 'R.A.M.B.O.' AND "name" = 'Bring It';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Big D And The Kids Table' AND "name" = 'Good-Luck';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2005' WHERE artist = 'Discarga' AND "name" = 'I Shot Cyrus & Discarga - Split LP';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2004' WHERE artist = 'Bullet Treatment' AND "name" = 'What More Do You Want';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2008' WHERE artist = 'Один Из Тысячи' AND "name" = 'Начало Пути';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'D.R.I.' AND "name" = 'Dealing With It';
UPDATE "public"."Album" SET "numberOfTracks" = 24, "date" = '1985-03' WHERE artist = 'D.R.I.' AND "name" = 'Dealing With It!';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2014-04-15' WHERE artist = 'Spell' AND "name" = 'The Full Moon Sessions';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Cast Iron' AND "name" = 'Leather & Steel';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2016-08-30' WHERE artist = 'Rotör' AND "name" = 'Musta käsi';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'In Solitude' AND "name" = 'The World.The Flesh.The Devil';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2012-08-07' WHERE artist = 'Sister Sin' AND "name" = 'End of the Line';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2003-09-09' WHERE artist = 'Ram' AND "name" = 'Sudden Impact';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2005-11-25' WHERE artist = 'Ram' AND "name" = 'Forced Entry';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2006-05-01' WHERE artist = 'Crowning Glory' AND "name" = 'Path To Glory';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2006-12-16' WHERE artist = 'Helvetets Port' AND "name" = 'Metal Strike';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2008-09-15' WHERE artist = 'Viper' AND "name" = 'Strike of the Viper';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2018-04-08' WHERE artist = 'Pulver' AND "name" = 'Pulver';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2009-11-19' WHERE artist = 'Holy Grail' AND "name" = 'Improper Burial';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2009-04' WHERE artist = 'Helvetets Port' AND "name" = 'Exodus to Hell';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2009-07-13' WHERE artist = 'White Wizzard' AND "name" = 'High Speed GTO';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2010' WHERE artist = 'Razorwyre' AND "name" = 'Coming Out';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2009-01-16' WHERE artist = 'Nasty Tendency' AND "name" = 'Wild And Nasty';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2011-04-29' WHERE artist = 'Alpha Tiger' AND "name" = 'Men Or Machine';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2011-02-10' WHERE artist = 'Nasty Tendency' AND "name" = 'Hello Suckers';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2012-12-03' WHERE artist = 'Air Raid' AND "name" = 'Night of the Axe';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2014-04-25' WHERE artist = 'Hitten' AND "name" = 'First Strike With The Devil';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2014-11-25' WHERE artist = 'Midnight Priest' AND "name" = 'Midnight Steel';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2016-09-03' WHERE artist = 'Liquid Steel' AND "name" = 'Midnight Chaser';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2017-09-01' WHERE artist = 'Lethal Night' AND "name" = 'Visions In The Night';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2018-03-25' WHERE artist = 'Leathürbitch' AND "name" = 'Leathürbitch';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2020-11-06' WHERE artist = 'Eternal Champion' AND "name" = 'Ravening Iron';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2013-10-30' WHERE artist = 'Iron Curtain' AND "name" = 'Jaguar Spirit';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2015-01-16' WHERE artist = 'Herzel' AND "name" = 'Unis Dans La Gloire';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2011-11' WHERE artist = 'Pyramids' AND "name" = 'A Throne Without A King';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2019' WHERE artist = 'Wędrowcy~Tułacze~Zbiegi' AND "name" = 'Marynistyka Suchego Lądu';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2011-11' WHERE artist = 'Horseback' AND "name" = 'A Throne Without A King';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2020-05-22' WHERE artist = 'Cold Deck' AND "name" = 'Nether Wound';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2010-01-13' WHERE artist = 'Koester' AND "name" = 'De Innerlijke Gevangenis';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2020-02-17' WHERE artist = 'Dola' AND "name" = 'Dola';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2010' WHERE artist = 'Xerbittert' AND "name" = 'Black Fog';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2010' WHERE artist = 'War for War' AND "name" = 'Vez smrti';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2019-03-27' WHERE artist = 'Steingrab' AND "name" = 'Manifestierte Alpträume';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1997-11' WHERE artist = 'Ewigkeit' AND "name" = 'Battle Furies';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2000-09' WHERE artist = 'Tormentor' AND "name" = 'Recipe Ferrum';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2004-03' WHERE artist = 'Lugubrum' AND "name" = 'De Vette Cuecken';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2010-08' WHERE artist = 'Chronaexus' AND "name" = 'Algedonic Awakening';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2011-11-25' WHERE artist = 'Seagulls Insane and Swans Deceased Mining Out the Void' AND "name" = 'Seagulls Insane and Swans Deceased Mining Out the Void';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2013-02-28' WHERE artist = 'The Phantom Carriage' AND "name" = 'Falls';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2014-04-07' WHERE artist = 'Licho' AND "name" = 'Pogrzeb w karczmie';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2020-07-03' WHERE artist = 'Botanist' AND "name" = 'Ecosystem version B';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2016-05-30' WHERE artist = 'Master''s Hammer' AND "name" = 'Formulæ';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2013-05-30' WHERE artist = 'Stara Rzeka' AND "name" = 'Cién Chmury Nad Ukrytym Polem';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Motörhead' AND "name" = 'Live At Brixton 87';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Cult' AND "name" = 'Cult';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Saxon' AND "name" = 'The Eagle Has Landed - Live';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Saxon' AND "name" = 'Denim And Leather (Digitally Remastered + Bonus Tracks)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006-03-07' WHERE artist = 'Tipton, Entwistle & Powell' AND "name" = 'Edge Of The World';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2000-11-13' WHERE artist = 'Charger' AND "name" = 'Foul Year of Our Lord';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Saxon' AND "name" = 'Power And The Glory (Digitally Remastered + Bonus Tracks)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rainbow' AND "name" = 'Final Vinyl';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Saxon' AND "name" = 'Killing Ground (bonus disc: Classics Re-Recorded)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Saxon' AND "name" = 'Denim & Leather';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1980-05-31' WHERE artist = 'Whitesnake' AND "name" = 'Ready An'' Willing';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1982-11-27' WHERE artist = 'Ozzy Osbourne' AND "name" = 'Speak Of The Devil';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1982-10' WHERE artist = 'Budgie' AND "name" = 'Deliver Us From Evil';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1984-09-10' WHERE artist = 'The Cult' AND "name" = 'Dreamtime';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1986-05' WHERE artist = 'Warfare' AND "name" = 'Mayhem, Fuckin'' Mayhem';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1991-10-17' WHERE artist = 'Skyclad' AND "name" = 'the wayward sons of mother earth';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '1991-08-19' WHERE artist = 'Napalm Death' AND "name" = 'Death By Manipulation';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Coverdale/Page' AND "name" = 'Coverdale Page';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2000-06' WHERE artist = 'The Cult' AND "name" = 'Pure Cult';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1994-10-12' WHERE artist = 'The Cult' AND "name" = 'The Cult';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '1996-11-05' WHERE artist = 'The Cult' AND "name" = 'High Octane Cult';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1995-10-13' WHERE artist = 'Siam' AND "name" = 'Prayer';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Saxon' AND "name" = 'Live at Monsters of Rock';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2007-05-13' WHERE artist = 'DragonForce' AND "name" = 'Inhuman Rampage [Special Edition]';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2005-01-03' WHERE artist = 'Area 54' AND "name" = 'A Fistful of Gravy';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2007-11-19' WHERE artist = 'Lazarus Blackstar' AND "name" = 'Funeral Voyeur';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2011-08-11' WHERE artist = 'Achren' AND "name" = 'The Forgotten King';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Furia' AND "name" = 'Płoń!';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2009-10-31' WHERE artist = 'Cultes des Ghoules' AND "name" = 'Conjurers of Archaic Powers';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Infernal War' AND "name" = 'Infernal SS (EP)';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2019-02-28' WHERE artist = 'Ashes' AND "name" = 'Ashes';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1994-09-10' WHERE artist = 'Infernum' AND "name" = '...Taur-Nu-Fuin...';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1995-02' WHERE artist = 'North' AND "name" = 'Thorns of the Black Rose';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1997-06' WHERE artist = 'Besatt' AND "name" = 'In Nomine Satanas';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '1997-09' WHERE artist = 'Veles' AND "name" = 'Black Hateful Metal';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1998-04' WHERE artist = 'North' AND "name" = 'From The Dark Past';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2000-06' WHERE artist = 'Besatt' AND "name" = 'Hail Lucifer';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2000-11-15' WHERE artist = 'Misteria' AND "name" = 'Masquerade of Shadows';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1999-06' WHERE artist = 'Thunderbolt' AND "name" = 'Black Clouds Over Dark Majesty';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Furia' AND "name" = 'Plon';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2011-02' WHERE artist = 'Actum Inferni' AND "name" = 'The Embodiment Of Death';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2012-09' WHERE artist = 'Sytris' AND "name" = 'Confessions of the fall';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2015-03-21' WHERE artist = 'Kres' AND "name" = 'Na Krawędziach Nocy';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2007-05-30' WHERE artist = 'Mgła' AND "name" = 'Mdłości / Further Down the Nest';
