UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Forest Stream' AND "name" = 'Crown of Winter';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2006-06-06' WHERE artist = 'Casey Jones' AND "name" = 'The Messenger';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-11-13' WHERE artist = 'The Amity Affliction' AND "name" = 'Shine On';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-12-09' WHERE artist = 'The Amity Affliction' AND "name" = 'All Messed Up (Acoustic)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Edguy' AND "name" = 'F***ing With Fire (Live)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1989-04-24' WHERE artist = 'Autopsy' AND "name" = 'Severed Survival';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1992-06-20' WHERE artist = 'Asphyx' AND "name" = 'Crush The Cenotaph';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1989-06-14' WHERE artist = 'Obituary' AND "name" = 'Slowly We Rot';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1995' WHERE artist = 'Obituary' AND "name" = 'Slowly We Rot (Re-Issue)';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1990-10-15' WHERE artist = 'Atrocity' AND "name" = 'Hallucinations';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1991-09-13' WHERE artist = 'Goatlord' AND "name" = 'Reflections of the Solstice';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1991-08-02' WHERE artist = 'Death Strike' AND "name" = 'Fuckin'' Death';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Obituary' AND "name" = 'Cause Of Death [Bonus Tracks]';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1991-04-24' WHERE artist = 'Morgoth' AND "name" = 'Cursed';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1992-11' WHERE artist = 'Demigod' AND "name" = 'Slumber of Sullen Eyes';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1992-04' WHERE artist = 'Timeghoul' AND "name" = 'Tumultuous Travelings';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1992-10-05' WHERE artist = 'Hypocrisy' AND "name" = 'Penetralia';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1993-03' WHERE artist = 'Wombbath' AND "name" = 'Internal Caustic Torments';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2014-05-01' WHERE artist = 'Entombed' AND "name" = 'Wolverine Blues (Full Dynamic Range Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '1993-04-13' WHERE artist = 'Macabre' AND "name" = 'Sinister Slaughter';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Morbid Angel' AND "name" = 'Altars Of Madness [Bonus Tracks]';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1996-11' WHERE artist = 'Vomitory' AND "name" = 'Raped in Their Own Blood';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1991' WHERE artist = 'Sepultura' AND "name" = 'Morbid Visions/Bestial Devastation (Reissue)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Morbid Angel' AND "name" = 'Gateways to Anihilation';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1998' WHERE artist = 'Death' AND "name" = 'Human - Reissue';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2005-04-25' WHERE artist = 'Nihilist' AND "name" = 'Nihilist (1987-1989)';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2005-05-31' WHERE artist = 'Coffins' AND "name" = 'Mortuary in Darkness';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2005-05-01' WHERE artist = 'Dead Congregation' AND "name" = 'Purifying Consecrated Ground';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1987-02' WHERE artist = 'Necrophagia' AND "name" = 'Season of the Dead';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Hail of Bullets' AND "name" = '... Of Frost And War';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2009-05-25' WHERE artist = 'Paradise Lost' AND "name" = 'Drown In Darkness - The Early Demos';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2014-10-27' WHERE artist = 'Obituary' AND "name" = 'Inked in Blood (Deluxe Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2018-01-26' WHERE artist = 'Mammoth Grinder' AND "name" = 'Cosmic Crypt';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2013-12-04' WHERE artist = 'Bolt Thrower' AND "name" = 'War Master (Full Dynamic Range Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2018-11-09' WHERE artist = 'Ulthar' AND "name" = 'Cosmovore';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2018' WHERE artist = 'Entombed' AND "name" = 'Left Hand Path (Full Dynamic Range Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2020-08-08' WHERE artist = 'Carcass' AND "name" = 'Symphonies of Sickness (Full Dynamic Range Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2010-07-23' WHERE artist = 'Obituary' AND "name" = 'World Demise (Reissue)';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2013-11-19' WHERE artist = 'Entombed' AND "name" = 'Clandestine (Full Dynamic Range Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2008-05-12' WHERE artist = 'Hail of Bullets' AND "name" = 'Of Frost And War';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2008-05' WHERE artist = 'Asphyx' AND "name" = 'Death The Brutal Way';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Deicide' AND "name" = 'Once Upon a Cross';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Capitalist Casualties' AND "name" = 'Split';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '1998' WHERE artist = 'Dropdead' AND "name" = 'Dropdead';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2012' WHERE artist = 'Man Is the Bastard' AND "name" = 'Thoughtless';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Capitalist Casualties' AND "name" = 'Capitalist Casualties';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2000' WHERE artist = 'Hellnation' AND "name" = 'Cheerleaders for Imperialism';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '1999-06-30' WHERE artist = 'Combatwoundedveteran' AND "name" = 'I Know a Girl Who Develops Crime Scene Photos';
UPDATE "public"."Album" SET "numberOfTracks" = 88, "date" = '1999' WHERE artist = 'Charles Bronson' AND "name" = 'Complete Discocrappy';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '1999' WHERE artist = 'Crossed Out' AND "name" = '1990-1993';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2002-04' WHERE artist = 'Hellnation' AND "name" = 'Thrash Wave';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2002-08-20' WHERE artist = 'A Days Refrain' AND "name" = 'A Days Refrain/Neil Perry split';
UPDATE "public"."Album" SET "numberOfTracks" = 41, "date" = '2000' WHERE artist = 'Asterisk*' AND "name" = 'Dogma';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2008' WHERE artist = 'Magrudergrind' AND "name" = 'This Comp Kills Fascists Vol 1';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2002-08-20' WHERE artist = 'Neil Perry' AND "name" = 'A Days Refrain/Neil Perry Split';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Jeromes Dream' AND "name" = 'Completed 1997-2001 Disc 1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Man Is the Bastard' AND "name" = 'Sum Of The Men - The Brutality';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2007' WHERE artist = 'Extortion' AND "name" = 'Sick';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2012-10-05' WHERE artist = 'The Kill' AND "name" = 'Make ''Em Suffer';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2013-06-02' WHERE artist = 'Hatred Surge' AND "name" = 'Human Overdose';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2016-01-08' WHERE artist = 'Full of Hell' AND "name" = 'Amber Mote in the Black Vault';
UPDATE "public"."Album" SET "numberOfTracks" = 25, "date" = '2002' WHERE artist = 'Los Crudos' AND "name" = 'Discografía';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2013-10-31' WHERE artist = 'Full of Hell' AND "name" = 'Music From The Dial';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dropdead' AND "name" = 'Dropdead';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1993' WHERE artist = 'Dropdead' AND "name" = 'Self Titled 1993';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '1998' WHERE artist = 'Dropdead' AND "name" = 'Self Titled 1998';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2005' WHERE artist = 'ACxDC' AND "name" = 'He Had it Comin''';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2010' WHERE artist = 'Harm''s Way' AND "name" = 'No Gods, No Masters';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2002' WHERE artist = 'XFilesX' AND "name" = 'Beaten Straight';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '1996' WHERE artist = 'Spazz' AND "name" = 'Brutal Truth & Spazz - Split';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2002' WHERE artist = 'XFilesX' AND "name" = 'NBC Mayhem';
UPDATE "public"."Album" SET "numberOfTracks" = 24, "date" = '2005' WHERE artist = 'Magrudergrind' AND "name" = '62 Trax of Thrash';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2001' WHERE artist = 'Spazz' AND "name" = 'Sweatin'' 3: Skatin'' Satan & Katon';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006' WHERE artist = 'Fakultet' AND "name" = '[мить]...';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2021-06-18' WHERE artist = 'Pharaoh' AND "name" = 'The Powers That Be';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Пилот' AND "name" = 'Сказка';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1986-07' WHERE artist = 'Cro-Mags' AND "name" = 'The Age Of Quarrel';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '1989-07-12' WHERE artist = 'Sick of It All' AND "name" = 'Blood, Sweat, and No Tears';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1985' WHERE artist = 'Cro-Mags' AND "name" = 'Age of Quarrel';
UPDATE "public"."Album" SET "numberOfTracks" = 22, "date" = '2006' WHERE artist = 'Fahrenheit 451' AND "name" = 'If I Knew Then What I Know Now';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1988' WHERE artist = 'Side By Side' AND "name" = 'You''re Only Young Once';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '1998' WHERE artist = 'Reagan Youth' AND "name" = 'Live & Rare';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1987' WHERE artist = 'Token Entry' AND "name" = 'From Beneath The Streets';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1999-07-06' WHERE artist = '25 Ta Life' AND "name" = 'Friendship, Loyalty, Commitment';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2016-08-01' WHERE artist = 'Hangman' AND "name" = 'Hangman II';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2011' WHERE artist = 'Full Blown Chaos' AND "name" = 'Full Blown Chaos';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2005-11-28' WHERE artist = 'Irate' AND "name" = 'New York Metal';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Madball' AND "name" = 'NYCH';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1996' WHERE artist = 'Bulldoze' AND "name" = 'The Final Beatdown';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2008-03-18' WHERE artist = 'H2O' AND "name" = 'CBGB OMFUG Masters:Live August 19, 2002 - The Bowery Collection';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2009-03-24' WHERE artist = '25 Ta Life' AND "name" = 'Strength Integrity Brotherhood';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-08-11' WHERE artist = 'Merauder' AND "name" = 'God Is I';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1996-06-25' WHERE artist = 'H2O' AND "name" = 'H2O';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2013-05-28' WHERE artist = 'Downpresser' AND "name" = 'Don''t Need a Reason';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2017-11-03' WHERE artist = 'Hangman' AND "name" = 'A Vile Decree';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2008' WHERE artist = 'What We Feel' AND "name" = 'What We Feel & Last Hope - Split CD';
UPDATE "public"."Album" SET "numberOfTracks" = 22, "date" = '1994' WHERE artist = 'Warzone' AND "name" = 'Don''t Forget the Struggle Don''t Forget the Streets - Open Your Eyes';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1991' WHERE artist = 'The Icemen' AND "name" = 'Rest In Peace [E.P.]';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Billy Talent' AND "name" = 'II';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1997-06-17' WHERE artist = 'blink-182' AND "name" = 'Dude Ranch';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2008' WHERE artist = 'Pisschrist' AND "name" = 'Victims Of Faith';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Devin Townsend Project' AND "name" = 'ADDICTED!';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Devin Townsend' AND "name" = 'Addicted';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1994-07-21' WHERE artist = 'Stryper' AND "name" = 'The Yellow and Black Attack';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1985-06-16' WHERE artist = 'Stryper' AND "name" = 'Soldiers Under Command';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2018-04-20' WHERE artist = 'Stryper' AND "name" = 'God Damn Evil';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1994-11-10' WHERE artist = 'Mortification' AND "name" = 'Break the Curse';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1998-05-20' WHERE artist = 'Deuteronomium' AND "name" = 'Street Corner Queen';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2018-11-16' WHERE artist = 'P.O.D.' AND "name" = 'Circles';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2000' WHERE artist = 'Soul Embraced' AND "name" = 'For the Incomplete';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2003-08-22' WHERE artist = 'Haste the Day' AND "name" = 'That They May Know You';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2003-11' WHERE artist = 'Project 86' AND "name" = 'Songs to Burn Your Bridges By';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2005' WHERE artist = 'Holy Blood' AND "name" = 'Waves Are Dancing';
UPDATE "public"."Album" SET "numberOfTracks" = 24, "date" = '2005-08-25' WHERE artist = 'Immortal Souls' AND "name" = 'Once Upon a Time in the North';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2008-04-30' WHERE artist = 'Menahem' AND "name" = 'Angels and Shadows';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2007-06-20' WHERE artist = 'Pantokrator' AND "name" = 'Aurum';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2008-07-11' WHERE artist = 'Fratello Metallo' AND "name" = 'Misteri';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2010-11-26' WHERE artist = 'Golden Resurrection' AND "name" = 'Glory To My King';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2008-06-30' WHERE artist = 'Holy Blood' AND "name" = 'The Patriot';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2017-10-13' WHERE artist = 'MyChildren MyBride' AND "name" = 'Vicious World';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2017-09-15' WHERE artist = 'Fleshkiller' AND "name" = 'Awaken';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Massive Assault' AND "name" = 'Massive Assault Demo Compilation';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2005-01' WHERE artist = 'Alcest' AND "name" = 'Le secret EP';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2018-05-30' WHERE artist = 'Opium' AND "name" = 'Extended Virtual Reality Play (Vol. 1)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1991-09-01' WHERE artist = 'Tiamat' AND "name" = 'The Astral Sleep';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '1991-06' WHERE artist = 'My Dying Bride' AND "name" = 'God Is Alone';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '1992-03-12' WHERE artist = 'My Dying Bride' AND "name" = 'Symphonaire Infernus et Spera Empyrium';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1993-10-11' WHERE artist = 'My Dying Bride' AND "name" = 'Turn Loose the Swans';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1997-01' WHERE artist = 'Saturnus' AND "name" = 'Paradise Belongs to You';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1995-02-10' WHERE artist = 'Novembers Doom' AND "name" = 'Amid Its Hallowed Mirth';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1998' WHERE artist = 'Thorr''s Hammer' AND "name" = 'Dommedagsnatt';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1992-11' WHERE artist = 'Anathema' AND "name" = 'Crestfallen EP';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2015-03-06' WHERE artist = 'Red Moon Architect' AND "name" = 'Fall';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2017-10-13' WHERE artist = 'Spectral Voice' AND "name" = 'Eroded Corridors of Unbeing';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1993' WHERE artist = 'Disembowelment' AND "name" = 'Transcendence Into the Peripheral';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Tequilajazzz' AND "name" = 'Абориген (макси-сингл)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2001-11-13' WHERE artist = 'Marilyn Manson' AND "name" = 'Tainted Love';
UPDATE "public"."Album" SET "hidden" = false WHERE artist = 'Sigur Rós' AND "name" = 'ágætis byrjun';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2004-06-29' WHERE artist = 'Lil'' Wayne' AND "name" = 'Tha Carter';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2018-01-07' WHERE artist = 'Mental Cruelty' AND "name" = 'Purgatorium';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Storyteller' AND "name" = 'The Storyteller';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2003-09-23' WHERE artist = 'White Zombie' AND "name" = 'Past, Present & Future';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2021-06-25' WHERE artist = 'White Ward' AND "name" = 'Debemur Morti';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1994-08' WHERE artist = 'Bethlehem' AND "name" = 'Dark Metal';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Moonspell' AND "name" = 'Sin/Pecado';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1998-03' WHERE artist = 'Bethlehem' AND "name" = 'Sardonischer Untergang Im Zeichen Irreligiöser Darbietung';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2000-01' WHERE artist = 'Eisregen' AND "name" = 'Leichenlager';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2000-10-30' WHERE artist = 'Thy Serpent' AND "name" = 'Death';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2001-11-27' WHERE artist = 'Root' AND "name" = 'Black Seal';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2004-07-25' WHERE artist = 'Throes of Dawn' AND "name" = 'Quicksilver Clouds';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2004-02-21' WHERE artist = 'The Wounded' AND "name" = 'Atlantic';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2004-10-04' WHERE artist = 'Dorn' AND "name" = 'Suriel';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Ajattara' AND "name" = 'Apare';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2005-08-29' WHERE artist = 'The Vision Bleak' AND "name" = 'Carpathia';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2006-05-26' WHERE artist = 'Axamenta' AND "name" = 'Ever-Arch-I-Tech-Ture';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2006-10-11' WHERE artist = 'Dominia' AND "name" = 'Divine Revoluion';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2011-04-29' WHERE artist = 'Mantus' AND "name" = 'Zeichen';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-09-15' WHERE artist = 'Nachtblut' AND "name" = 'Lied für die Götter';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Septic Flesh' AND "name" = 'Titan';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2013-03-01' WHERE artist = 'Rotting Christ' AND "name" = 'Κατά τον δαίμονα εαυτού';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2018-12-07' WHERE artist = 'Revenge' AND "name" = 'Deceiver.Diseased.Miasmic';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '1993-07-06' WHERE artist = 'Blasphemy' AND "name" = 'Gods Of War';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1990-08' WHERE artist = 'Blasphemy' AND "name" = 'Fallen Angel of Doom';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Deströyer 666' AND "name" = 'Terror Abraxas (EP)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2004-10-30' WHERE artist = 'Goatpenis' AND "name" = 'Inhumanization';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2004-09' WHERE artist = 'Axis of Advance' AND "name" = 'Obey';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2004-09' WHERE artist = 'Revenge' AND "name" = 'Victory.Intolerance.Mastery';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006-06-25' WHERE artist = 'Proclamation' AND "name" = 'Advent Of The Black Omen';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Blasphemy' AND "name" = 'Gods Of War + Blood Upon The Altar';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2002' WHERE artist = 'Vomitor' AND "name" = 'Bleeding the Priest';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2010-06-28' WHERE artist = 'Sadomator' AND "name" = 'Goatblood Panspermia';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2010-01-19' WHERE artist = 'Nocturnal Blood' AND "name" = 'Invocation Of Spirits';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2010-05-31' WHERE artist = 'Abominator' AND "name" = 'Barbarian War Worship';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2012-01-25' WHERE artist = 'Proclamation' AND "name" = 'Nether Tombs of Abaddon';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1999-02-15' WHERE artist = 'Archgoat' AND "name" = 'Messe des Morts/Angelcunt (Tales of Desecration)';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2010-09-24' WHERE artist = 'Sabaton' AND "name" = 'The Art Of War (Re-Armed)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Panzerfaust' AND "name" = 'The Suns of Perdition - Chapter I: War, Horrid War';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2010-10-01' WHERE artist = 'Diocletian' AND "name" = 'War of All Against All';
UPDATE "public"."Album" SET "numberOfTracks" = 27, "date" = '2010-09-24' WHERE artist = 'Sabaton' AND "name" = 'Metalizer (Re-Armed)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2010-09-24' WHERE artist = 'Sabaton' AND "name" = 'Attero Dominatus (Re-Armed)';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2010-09-24' WHERE artist = 'Sabaton' AND "name" = 'Primo Victoria (Re-Armed)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sabaton' AND "name" = 'The Last Stand (Track Commentary Version)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sabaton' AND "name" = 'Heroes (Track Commentary Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2019-06-14' WHERE artist = 'Panzerfaust' AND "name" = 'The Suns of Perdition, Ch. 1: War, Horrid War';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2009-08-03' WHERE artist = 'Proclamation' AND "name" = 'Execration of Cruel Beastiality';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2019-03-10' WHERE artist = 'Sankara' AND "name" = 'Total Liberation of the Human Race';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Hatebreed' AND "name" = 'Rise Of Brutality';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-07-24' WHERE artist = 'From First to Last' AND "name" = 'Surrender';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1999-07-20' WHERE artist = 'Powerman 5000' AND "name" = 'Tonight the Stars Revolt';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Powerman 5000' AND "name" = 'Tonight the Stars Revolt!';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2011' WHERE artist = 'Full of Hell' AND "name" = 'Full of Hell/Goldust';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2018-09-05' WHERE artist = 'Endon' AND "name" = 'BOY MEETS GIRL';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Анна Седокова' AND "name" = 'Anna Sedokova';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1977-02-09' WHERE artist = 'David Coverdale' AND "name" = 'Whitesnake';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Whitesnake' AND "name" = 'Live In The Heart Of The City';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1980-11-03' WHERE artist = 'Whitesnake' AND "name" = 'Live... in the Heart of the City';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Whitesnake' AND "name" = 'Saints And Sinners';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1981-04' WHERE artist = 'Vardis' AND "name" = 'The World''s Insane';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1982-11' WHERE artist = 'Samson' AND "name" = 'Before the Storm';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '1984-01-20' WHERE artist = 'Venom' AND "name" = 'Warhead';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1984-05-24' WHERE artist = 'Battleaxe' AND "name" = 'Power From the Universe';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1986-10-13' WHERE artist = 'Saxon' AND "name" = 'Rock The Nations';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2003' WHERE artist = 'Tygers of Pan Tang' AND "name" = 'Live In The Roar';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1986' WHERE artist = 'Blood Money' AND "name" = 'Red, Raw and Bleeding';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1983' WHERE artist = 'Wildfire' AND "name" = 'Brute Force and Ignorance';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '1981-10-15' WHERE artist = 'Arc' AND "name" = 'War of the Ring';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1985' WHERE artist = 'Tobruk' AND "name" = 'Wild on the Run';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2006' WHERE artist = 'Sparta' AND "name" = 'Sparta';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1980-10-23' WHERE artist = 'A-II-Z' AND "name" = 'The Witch Of Berkeley';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2008-04-12' WHERE artist = 'Tygers of Pan Tang' AND "name" = 'Animal Instinct';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2013-05-06' WHERE artist = 'Dendera' AND "name" = 'The Killing Floor';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '1982-09' WHERE artist = 'Jaguar' AND "name" = 'Axe crazy';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Saxon' AND "name" = 'Crusader (Digitally Remastered + Bonus Tracks)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Machine Head' AND "name" = '2003 - Hellalive';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2002' WHERE artist = 'Коловрат' AND "name" = 'Эра правой руки';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1994' WHERE artist = 'Любэ' AND "name" = 'Зона Любэ';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2000-05-10' WHERE artist = 'Любэ' AND "name" = 'Полустаночки';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2003-10-30' WHERE artist = 'Полюса' AND "name" = 'Поэзия';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-05-06' WHERE artist = 'JoJo Siwa' AND "name" = 'Boomerang';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1997-03' WHERE artist = 'Moonblood' AND "name" = 'Blut & Krieg';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2006-03-03' WHERE artist = 'Vulture Lord' AND "name" = 'Blasphemy';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Viking Quest' AND "name" = 'The Collective EP Vol. 1';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2009-09-21' WHERE artist = 'A Textbook Tragedy' AND "name" = 'Rain City State Of Mind';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2002-01-22' WHERE artist = 'Sunn O)))' AND "name" = 'Flight of the Behemoth';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1998' WHERE artist = 'E.Town Concrete' AND "name" = 'Fuck the World';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1977-09-24' WHERE artist = 'Motörhead' AND "name" = 'Motörhead';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2004-05-12' WHERE artist = 'Various Artists' AND "name" = 'Tämän maailman ruhtinaan hovi';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1996-02-14' WHERE artist = 'Inearthed' AND "name" = 'Shining';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2004-02-02' WHERE artist = 'Misery Inc.' AND "name" = 'Yesterday''s Grave';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2004-08-12' WHERE artist = 'Bride Adorned' AND "name" = 'Blessed Stillness';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2005-09-13' WHERE artist = 'Venia' AND "name" = 'In Our Weakness';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007-10-10' WHERE artist = 'Misery Inc.' AND "name" = 'bReedgReedbRreed';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Amorphis' AND "name" = 'Silent Waters [Bonus Track]';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Omnium Gatherum' AND "name" = 'The Redshift (Bonus Version)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Crimfall' AND "name" = 'As The Path Unfolds…';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-10-13' WHERE artist = 'Omnium Gatherum' AND "name" = 'Blade Reflections';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2003' WHERE artist = 'Various Artists' AND "name" = 'Kurimus';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2017-03-04' WHERE artist = 'Chevalier' AND "name" = 'A Call To Arms';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Wintersun' AND "name" = 'Time';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Children of Bodom' AND "name" = 'Covers';
UPDATE "public"."Album" SET "numberOfTracks" = 23, "date" = '2001' WHERE artist = 'Anomie' AND "name" = 'Discography (1994-1997)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'I Would Set Myself on Fire for You' AND "name" = 'Self-Titled';
UPDATE "public"."Album" SET "numberOfTracks" = 23, "date" = '2005-03-05' WHERE artist = 'You and I' AND "name" = 'Discography';
UPDATE "public"."Album" SET "numberOfTracks" = 24, "date" = '2004' WHERE artist = 'Usurp Synapse' AND "name" = 'Disinformation Fix';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2004-06-21' WHERE artist = 'The Kodan Armada' AND "name" = 'A Collection of Songs';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2007-06' WHERE artist = 'Cease Upon the Capitol' AND "name" = '2007 ep';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '2008' WHERE artist = 'Ampere' AND "name" = 'The First Five Years';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Mihai Edrisch' AND "name" = 'L'' Un Sans L'' Autre';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2007-09-01' WHERE artist = 'We Were Skeletons' AND "name" = 'Summers';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2016-05-13' WHERE artist = 'Things Fall Apart' AND "name" = 'Things Fall Apart';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2011-06' WHERE artist = 'Ampere' AND "name" = 'Like Shadows';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2011-12-24' WHERE artist = 'Old Gray' AND "name" = 'Old Gray/Girl Scouts Split';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Various Artists' AND "name" = 'Death to Fake Screamo';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2013-06-11' WHERE artist = 'The Saddest Landscape' AND "name" = 'Live At New Alliance';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2010-11-08' WHERE artist = 'Pianos Become the Teeth' AND "name" = 'Split';
UPDATE "public"."Album" SET "numberOfTracks" = 22, "date" = '2016-07-15' WHERE artist = 'Saetia' AND "name" = 'Collected';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2016-04-08' WHERE artist = 'Gillian Carter' AND "name" = 'Dreams Of Suffocation';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'I Create' AND "name" = 'Complete Medley';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2005-03' WHERE artist = 'I Spoke' AND "name" = 'Fieldtrips and Friendships';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-08-07' WHERE artist = 'La Dispute' AND "name" = 'The Castle Builders (10th Anniversary)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2009-09' WHERE artist = 'Daïtro' AND "name" = 'Y';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2003' WHERE artist = 'Sailboats' AND "name" = 'Demo';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2003' WHERE artist = 'Raein' AND "name" = 'Il n''y Pas de Orchestre';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2007' WHERE artist = 'Swallow! Swallow! Splinter!' AND "name" = 'demo';
UPDATE "public"."Album" SET "numberOfTracks" = 25, "date" = '2005' WHERE artist = 'Index for Potential Suicide' AND "name" = '"Sex, Violence, Whatever": The Complete Recordings';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Julian Thome' AND "name" = 'Lung Cancer';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2000' WHERE artist = 'Crucifixion BR' AND "name" = 'Live Possession';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1997-05-01' WHERE artist = 'Kong' AND "name" = 'EARMINeD';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2009' WHERE artist = 'Omega Massif' AND "name" = 'Omega Massif / Mount Logan';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2009-03-27' WHERE artist = 'Irminsul' AND "name" = 'Irminsul';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Epica' AND "name" = '2 Meter Sessies: We Will Take You With Us';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1997' WHERE artist = 'Lacrimas Profundere' AND "name" = 'La Naissance D''un Reve';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Amederia' AND "name" = 'Sometimes we have wings';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Down' AND "name" = 'Down IV – Part Two';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '1993' WHERE artist = 'Strid' AND "name" = 'End of Life';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1995-10-14' WHERE artist = 'Burzum' AND "name" = 'Burzum/Aske';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Burzum' AND "name" = 'Burzum / Aske';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Gorgoroth' AND "name" = 'Black Mass Krakow';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Kampfar' AND "name" = 'Norse (EP)';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1999-01-07' WHERE artist = 'Taake' AND "name" = 'Nattestid Ser Porten Vid';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Burzum' AND "name" = 'Once Emperor';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2003-02' WHERE artist = 'Orcustus' AND "name" = 'Demo 2002';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2002-10-01' WHERE artist = 'Carpathian Forest' AND "name" = 'We''re Going to Hell for This - Over a Decade of Perversions';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2003-04-14' WHERE artist = 'Koldbrann' AND "name" = 'Nekrotisk Inkvisition';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2004-02-18' WHERE artist = 'Nattefrost' AND "name" = 'Blood & Vomit';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Gorgoroth' AND "name" = 'Quantos Possunt ad Satanitatem';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Malignant Eternal' AND "name" = 'Tarnet';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Various Artists' AND "name" = 'Hate Them';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Taake' AND "name" = 'Nekro (EP)';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2008-08-05' WHERE artist = 'Gorgoroth' AND "name" = 'Live In Grieghallen';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Gorgoroth' AND "name" = 'True Norwegian Black Metal';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Mayhem' AND "name" = 'Of Lord Satans Mysteries';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Satyricon' AND "name" = 'Nemesis Divina (The Conquering)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Carpathian Forest' AND "name" = 'Fuck You All';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '1994-03-28' WHERE artist = 'Isengard' AND "name" = 'Vinterskugge';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Gorgoroth' AND "name" = 'Destroyer – Or About How to Philosophize With the Hammer';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2017-04-28' WHERE artist = 'Dimmu Borgir' AND "name" = 'Forces Of The Northern Night';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Isengard' AND "name" = 'Vinterskugge - Copilation';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2002-03-25' WHERE artist = 'Taake' AND "name" = 'Over Bjoergvin Graater Himmerik';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '1991' WHERE artist = 'Burzum' AND "name" = 'Demo';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2005-02-28' WHERE artist = 'Taake' AND "name" = 'Hordalands doedskvad';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2005-06-06' WHERE artist = 'Beastcraft' AND "name" = 'Into the Burning Pit of Hell';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Taake' AND "name" = 'Hordaland Doedskvad';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1994' WHERE artist = 'Ildjarn' AND "name" = 'Norse';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Satyricon' AND "name" = 'Now, Diabolical [Bonus Track]';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2008-04-07' WHERE artist = 'Celestial Bloodshed' AND "name" = 'Cursed, Scarred And Forever Possessed';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2008-05' WHERE artist = 'Faustcoven' AND "name" = 'Rising From Below the Earth';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2011-06-13' WHERE artist = 'Djevel' AND "name" = 'Dodssanger';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2011-08-24' WHERE artist = 'One Tail, One Head' AND "name" = 'One Tail, One Head';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2011-08-06' WHERE artist = 'Isvind' AND "name" = 'Intet Lever';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1997' WHERE artist = 'Covenant' AND "name" = 'In Times Before the Light';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Hades' AND "name" = '...Again Shall Be';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2011-04-12' WHERE artist = 'So Hideous, My Love...' AND "name" = 'To Clasp a Fallen Wish with Broken Fingers';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Shining' AND "name" = '2009 - VI - Klagopsalmer';
UPDATE "public"."Album" SET "numberOfTracks" = 22, "date" = '2006' WHERE artist = 'Various Artists' AND "name" = 'Ketnet Partykids 6';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2007-06' WHERE artist = 'Shining' AND "name" = 'V - Halmstad (Niklas Angеende Niklas)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Shining' AND "name" = 'VII: Född förlorare';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2007-11' WHERE artist = 'Sterbeklang' AND "name" = 'Alleinsein';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1998-01-30' WHERE artist = 'Ляпис Трубецкой' AND "name" = 'Ты кинула';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2011-03-09' WHERE artist = 'Ляпис Трубецкой' AND "name" = 'Весёлые Картинки';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2013-10-21' WHERE artist = 'Макс Корж' AND "name" = 'Жить В Кайф';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2017-04-28' WHERE artist = 'ЛСП' AND "name" = 'Tragic City';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2015-07-19' WHERE artist = 'ЛСП' AND "name" = 'Magic City';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2012-05-01' WHERE artist = 'Макс Корж' AND "name" = 'Животный мир';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'beZ bileta' AND "name" = 'кино (cinema)';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2006-02-15' WHERE artist = 'Ляпис Трубецкой' AND "name" = 'Мужчины не плачут';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2014-11-08' WHERE artist = 'Макс Корж' AND "name" = 'Домашний';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2010' WHERE artist = 'MAŬZER' AND "name" = 'Porna';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2019-02-15' WHERE artist = 'Петля Пристрастия' AND "name" = 'Гул';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2006' WHERE artist = 'J:морс' AND "name" = 'Босиком по мостовой';
UPDATE "public"."Album" SET "numberOfTracks" = 24, "date" = '2007' WHERE artist = 'Various Artists' AND "name" = 'Песьні Свабоды 3';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2000' WHERE artist = 'N.R.M.' AND "name" = 'Try čarapachi';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2019-12-25' WHERE artist = 'pavluchenko & Alexey Krivdin' AND "name" = 'Река';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2011-05' WHERE artist = 'Пан Жыжма' AND "name" = 'Хто тут?';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Республика Полина' AND "name" = 'Республика Полина';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2010' WHERE artist = 'Лявон Вольскі' AND "name" = 'Белая яблыня грому';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Ляпис Трубецкой' AND "name" = 'Грай (mp3)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2008' WHERE artist = 'Нестандартный Вариант' AND "name" = 'Еле Слышно';
UPDATE "public"."Album" SET "numberOfTracks" = 23, "date" = '2006-02-22' WHERE artist = 'Various Artists' AND "name" = 'Песьні Свабоды';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2016-04-22' WHERE artist = 'Mustelide' AND "name" = 'SPI';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2008-04-16' WHERE artist = 'Лявон Вольскі' AND "name" = 'Куплеты і прыпевы';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Pavel Ambiont' AND "name" = 'heartless e.p.';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2013' WHERE artist = 'Mister X' AND "name" = '... какими мы стали!';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2014-07' WHERE artist = '(((о)))' AND "name" = 'Motherland';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2006' WHERE artist = 'Various Artists' AND "name" = 'Песьні Свабоды 2';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2008' WHERE artist = 'Пост Мортем' AND "name" = 'Infandum Renovare Dolorem';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2013-02-11' WHERE artist = 'THE PRAGA' AND "name" = 'my summer';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2003-07-17' WHERE artist = 'Крамбамбуля' AND "name" = 'Каралі раёну';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2004-09-13' WHERE artist = 'Atmoravi' AND "name" = 'Chertopoloh (Weed)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Pavel Ambiont' AND "name" = 'eat2dub / eat2die';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2009' WHERE artist = 'Atmoravi' AND "name" = 'Beloe Zoloto (white gold)';
UPDATE "public"."Album" SET "date" = '2007-12' WHERE artist = 'Amaroka' AND "name" = 'Raketa';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Людзі на балоце' AND "name" = '«Людзі на балоце» - прэзэнтацыя на Tuzin.fm';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2013-05-31' WHERE artist = 'Check Your Chest' AND "name" = 'Exodus';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Tanin Jazz' AND "name" = 'ibad.ru promopack';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Garoldovich' AND "name" = 'Counter';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-12-04' WHERE artist = 'ULIS' AND "name" = 'Tancy Na Dachu';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2012-04' WHERE artist = 'Chiefs Band' AND "name" = 'Jazz Pirates';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2014-10-06' WHERE artist = 'Siver' AND "name" = 'Сьцяг брыгады';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2014-03-10' WHERE artist = 'Clover Club' AND "name" = 'Five Bones';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2010-12' WHERE artist = 'PANaNieba' AND "name" = 'На Балоце';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2013-07-23' WHERE artist = 'Сяргей Балахонаў' AND "name" = 'Спірт і жоўць распятага Тэзэя';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2012-02-18' WHERE artist = 'Massenhinrichtung' AND "name" = 'Adzinota Kruka';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2003-10' WHERE artist = 'Randomajestiq' AND "name" = 'Digitally Produced';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2019-01-19' WHERE artist = 'ThornyWay' AND "name" = 'Awaken';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2014-01-13' WHERE artist = 'Ride Too Slow' AND "name" = 'Не прощаемся (EP)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2006-11-26' WHERE artist = 'Atmoravi' AND "name" = 'ROMANTIKA';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2015-03-22' WHERE artist = 'Massenhinrichtung' AND "name" = 'Zakon Zbroi';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2012-04' WHERE artist = 'Markuts' AND "name" = 'Demo';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Garoldovich' AND "name" = 'fm singles';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Van2S' AND "name" = 'DEMO2008';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Scenario' AND "name" = 'split';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Kauan' AND "name" = 'Tietajan Laulu';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2018-06-14' WHERE artist = 'Blasphamagoatachrist' AND "name" = 'Black Metal Warfare';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2011-06-02' WHERE artist = 'Apocalypse Command' AND "name" = 'Damnation Scythes Of Invincible Abomination';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2009-09-30' WHERE artist = 'Conqueror' AND "name" = 'Songs from E.P. (Edizione Limitata + Live)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Unwound' AND "name" = 'A Single History: 1991-1997';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2011' WHERE artist = 'Fuck on the Beach' AND "name" = 'EAT ''EM ALL';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sigur Rós' AND "name" = 'Agaetis Byrjun';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1984' WHERE artist = 'Millennium' AND "name" = 'Millennium';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1983' WHERE artist = 'Savage' AND "name" = 'Loose ''n Lethal';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1984' WHERE artist = 'Bronz' AND "name" = 'Taken By Storm';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1982' WHERE artist = 'Fist' AND "name" = 'Back With a Vengeance';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '1987' WHERE artist = 'Def Leppard' AND "name" = 'Ride Into The Sun EP';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1982' WHERE artist = 'Axewitch' AND "name" = 'Pray For Metal';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1982' WHERE artist = 'Diamond Head' AND "name" = '4 Cuts EP';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1998' WHERE artist = 'Mythra' AND "name" = 'The Death and Destiny LP';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '1983' WHERE artist = 'Hell' AND "name" = 'Save Us From Those Who Would Save Us';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2010-01-10' WHERE artist = 'Dimmu Borgir' AND "name" = 'Nuclear Blast Showdown Fall 2010';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1995' WHERE artist = 'Inearthed' AND "name" = 'Ubiquitos Absence Of Remission';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2016-05-13' WHERE artist = 'Embreach' AND "name" = 'The World That We Have Lost';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2010-10-14' WHERE artist = 'Kamni' AND "name" = 'EP';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Various Artists' AND "name" = 'Metal Storm - The Epic Tales';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2001-06-18' WHERE artist = 'Dargaard' AND "name" = 'The Dissolution of Eternity';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2001-10' WHERE artist = 'Ufych Sormeer' AND "name" = 'Anthem to the Glory of the Great Octagon';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2003-11-24' WHERE artist = 'The Storyteller' AND "name" = 'Tales of a Holy Quest';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rhapsody of Fire' AND "name" = 'Visions from the Enchanted Lands';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2009-10-30' WHERE artist = 'Rhapsody of Fire' AND "name" = 'Symphony of Enchanted Lands, Vol. 2: The Dark Secret';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2016-07-20' WHERE artist = 'Rhapsody of Fire' AND "name" = 'Symphony of Enchanted Lands';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rhapsody of Fire' AND "name" = 'Tales from the Emerald Sword';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2016-11-11' WHERE artist = 'Freedom Call' AND "name" = 'Master of Light';
UPDATE "public"."Album" SET "numberOfTracks" = 22, "date" = '2019-05-20' WHERE artist = 'Power Tale' AND "name" = 'Огненный Бог Марранов';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2011-06-03' WHERE artist = 'Dethlehem' AND "name" = 'The Ghorusalem Codex, Vol. 2: Of Magick & Tyranny';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2015-09-25' WHERE artist = 'Gloryhammer' AND "name" = 'Space 1992: Rise Of The Chaos Wizards (Deluxe Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2004-02-13' WHERE artist = 'Эпидемия' AND "name" = 'Эльфийская рукопись';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2007' WHERE artist = 'Sound Horizon' AND "name" = 'Seisen no Iberia';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2003' WHERE artist = 'Gary Hughes' AND "name" = 'Once and Future King, Pt. 1';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sonic Prophecy' AND "name" = '2010 EP';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2003' WHERE artist = 'Gary Hughes' AND "name" = 'Once and Future King, Pt. 2';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-04-13' WHERE artist = 'Richard Benson' AND "name" = 'I nani';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2002-12' WHERE artist = 'N.R.M.' AND "name" = 'Дом культуры';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2002-08' WHERE artist = 'Randomajestiq' AND "name" = 'Evidence of Utopia';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2015-10-14' WHERE artist = 'Крамбамбуля' AND "name" = 'Чырвоны штраль';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2012' WHERE artist = 'Shot' AND "name" = 'S.H.O.T.';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2009' WHERE artist = 'L''One' AND "name" = 'Phlatline In Da Building';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Mr. J' AND "name" = 'Battle Shit';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2004-10-25' WHERE artist = 'Krec' AND "name" = 'Нет волшебства';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2004-10-19' WHERE artist = 'Иезекииль 25:17' AND "name" = 'Честное Слово Третьего Подземелья';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2006-09-14' WHERE artist = 'Смоки Мо' AND "name" = 'Планета 46';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2006-10-10' WHERE artist = 'Карандаш' AND "name" = 'Американщина';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2007-12-03' WHERE artist = 'V-Style' AND "name" = 'Grabbin'' Some Money';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2008-09-13' WHERE artist = 'Ассаи' AND "name" = 'Фаталист';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2008-11-13' WHERE artist = 'Карандаш' AND "name" = 'Бедные тоже смеются';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2008-01-22' WHERE artist = 'Кровосток' AND "name" = 'Гантеля';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2011-06-03' WHERE artist = 'Vendetta' AND "name" = 'Салам Маслам';
UPDATE "public"."Album" SET "numberOfTracks" = 29, "date" = '2010' WHERE artist = 'пражектор' AND "name" = 'Пена';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2008-04-01' WHERE artist = 'Ноггано' AND "name" = 'Первый';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2009-10-29' WHERE artist = 'Птаха' AND "name" = 'Ни О Чём';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Noize MC' AND "name" = 'Noize Mc';
UPDATE "public"."Album" SET "numberOfTracks" = 22, "date" = '2009-09-29' WHERE artist = 'Кажэ Обойма' AND "name" = 'The Most Dangerous LP';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2009-09-01' WHERE artist = 'Ноггано' AND "name" = 'Тёплый';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2010-04-20' WHERE artist = 'БАСТА' AND "name" = 'Баста 3';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2010-08-31' WHERE artist = 'Зануда' AND "name" = 'Папиросы';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2010-03-24' WHERE artist = 'АК-47' AND "name" = 'МегаPOLICE';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2009-02-02' WHERE artist = 'Eminem' AND "name" = 'Crack A Bottle';
UPDATE "public"."Album" SET "numberOfTracks" = 22, "date" = '2011-05-10' WHERE artist = 'Смоки Мо' AND "name" = 'Время Тигра';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2009-06-20' WHERE artist = 'Идефикс' AND "name" = 'Амальгама';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2008' WHERE artist = 'Marselle' AND "name" = 'MARS FM (Mixtape)';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2008' WHERE artist = 'D-Man 55' AND "name" = 'Соблюдай Спокойствие';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2011-04-17' WHERE artist = 'Loc-Dog' AND "name" = 'Апокалипсис 2012';
UPDATE "public"."Album" SET "numberOfTracks" = 23, "date" = '2012-11-01' WHERE artist = 'Guf' AND "name" = 'Сам и...';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2012-04-11' WHERE artist = '25/17' AND "name" = 'Песни О Любви И Смерти';
UPDATE "public"."Album" SET "numberOfTracks" = 28, "date" = '2012-03-12' WHERE artist = 'Oxxxymiron' AND "name" = 'miXXXtape I';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2011' WHERE artist = 'Булат' AND "name" = 'Причина (LP) 2011';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2006-11-30' WHERE artist = 'Тимати' AND "name" = 'Black Star';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2013-05-25' WHERE artist = 'Ассаи' AND "name" = 'Задеть за Мёртвое';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2006' WHERE artist = 'Кажэ Обойма' AND "name" = 'Выпуск 1: Inferno';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2013' WHERE artist = 'Brick Bazuka' AND "name" = 'Ешь';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2013' WHERE artist = 'Loc-Dog' AND "name" = 'Electrodog 2';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '2012' WHERE artist = '4SGM' AND "name" = 'Дни Ядерной Стабильности';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2011' WHERE artist = 'Dredd' AND "name" = 'Долгая Память';
UPDATE "public"."Album" SET "numberOfTracks" = 23, "date" = '2011' WHERE artist = 'Dredd' AND "name" = 'Новый Мир';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2012' WHERE artist = 'Dredd' AND "name" = 'Лабиринт';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2010' WHERE artist = 'Dredd' AND "name" = 'Я Против';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dredd' AND "name" = 'Remixes';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2009' WHERE artist = 'Dredd' AND "name" = 'Ghost Buster';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dredd' AND "name" = 'Темнота';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2015-11-04' WHERE artist = 'Guf' AND "name" = 'Ещё';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2017-10-13' WHERE artist = 'Овсянкин' AND "name" = 'Мементо мори';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Seryoga' AND "name" = 'The Music Of Grand Theft Auto IV';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1997' WHERE artist = 'Various Artists' AND "name" = 'РЭП МАСТЕР 2';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1997' WHERE artist = 'Various Artists' AND "name" = 'РЭП МАСТЕР 1';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2016-02-26' WHERE artist = 'Jubilee' AND "name" = 'Эмоджи фм';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2007-03-24' WHERE artist = 'Guf' AND "name" = 'Город Дорог';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2011-10-15' WHERE artist = 'Грот' AND "name" = 'О Пути По Встречной';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2008' WHERE artist = 'the Chemodan' AND "name" = 'Не Сегодня';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2017-10-25' WHERE artist = 'Слава КПСС' AND "name" = 'Солнце мёртвых';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2019-03-22' WHERE artist = 'Слава КПСС' AND "name" = 'Бутер Бродский';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '2011' WHERE artist = 'Артем Татищевский' AND "name" = 'Живым';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2012-02-13' WHERE artist = 'Каста' AND "name" = 'Ясно!';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2008' WHERE artist = 'Marselle' AND "name" = 'Mic On Mars';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2014' WHERE artist = 'Артем Татищевский' AND "name" = 'Пыльный';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2006' WHERE artist = 'Дымовая завеса' AND "name" = 'Этажи';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '2010-05-28' WHERE artist = 'Noize MC' AND "name" = 'Последний Альбом';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2010' WHERE artist = 'Loc-Dog' AND "name" = 'Паранойя 2';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2009' WHERE artist = '25/17' AND "name" = 'На городской карте';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2012' WHERE artist = 'Ка-тет' AND "name" = 'Узлы';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2006' WHERE artist = 'Скато' AND "name" = 'Я вижу дым';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2008' WHERE artist = 'Полумягкие' AND "name" = 'Пробуй (2008)';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2006' WHERE artist = 'MC T' AND "name" = 'Кусочек славы';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2009' WHERE artist = 'Ti-Jay' AND "name" = 'Блокбастер';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2008-02-23' WHERE artist = '25/17' AND "name" = 'Держитесь Крепче (DJ Navvy Mix)';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2011' WHERE artist = 'Non Cadenza' AND "name" = 'Сингл Вода (Ион и Саша Алмазова)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2012-10-25' WHERE artist = 'MC T' AND "name" = 'Крупицы 2';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2012-04-14' WHERE artist = 'Moresebya' AND "name" = 'hearts and minds';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '2010' WHERE artist = 'НАВАХУ' AND "name" = 'Люди лица';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1987-04-03' WHERE artist = 'Voivod' AND "name" = 'Killing Technology';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1991-05-01' WHERE artist = 'Anacrusis' AND "name" = 'Manic Impressions';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Mekong Delta' AND "name" = 'Dances of Death';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1991-10-14' WHERE artist = 'Wolf Spider' AND "name" = 'Drifting In The Sullen Sea';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1992-08' WHERE artist = 'Mekong Delta' AND "name" = 'Kaleidoscope';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1992-03-30' WHERE artist = 'Depressive Age' AND "name" = 'First Depression';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1988-03' WHERE artist = 'Voivod' AND "name" = 'Dimension Hatröss';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1994-04' WHERE artist = 'Geisha Goner' AND "name" = 'Hunting For The Human';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1994' WHERE artist = 'Aftermath' AND "name" = 'Eyes of Tomorrow';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Botch' AND "name" = 'The Unifying Themes of Sex, Death and Religion';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1998' WHERE artist = 'Alarum' AND "name" = 'Fluid Motion';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2001-09-30' WHERE artist = 'Eldritch' AND "name" = 'Reverse';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Mekong Delta' AND "name" = 'Visions Fugitive';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2002-09-30' WHERE artist = 'Pathos' AND "name" = 'Katharsis';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Tourniquet' AND "name" = 'Where Moth & Rust Destroy';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2005-04' WHERE artist = 'Nevermore' AND "name" = 'Enemies Of Reality (Remastered)';
