UPDATE "public"."Album" SET "numberOfTracks" = 22, "date" = '2011-10-18' WHERE artist = 'M83' AND "name" = 'Hurry Up We''re Dreaming';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2001-10-08' WHERE artist = 'A Silver Mt. Zion' AND "name" = 'Born Into Trouble as the Sparks Fly Upward';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2005-02-22' WHERE artist = 'Red Sparowes' AND "name" = 'At The Soundless Dawn';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1995-04-11' WHERE artist = 'White Zombie' AND "name" = 'Astro-Creep: 2000';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1994-01-25' WHERE artist = 'Prong' AND "name" = 'Cleansing';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1997-02-11' WHERE artist = 'Strapping Young Lad' AND "name" = 'City';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Powerman 5000' AND "name" = 'Tonight the Stars Revolt';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2019-05-17' WHERE artist = 'Rammstein' AND "name" = 'Rammstein';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2003-11-24' WHERE artist = 'Deathstars' AND "name" = 'Synthetic Generation';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rammstein' AND "name" = 'The Very Best of';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Marilyn Manson' AND "name" = 'Lest We Forget: The Best Of';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2020-10-21' WHERE artist = 'GhosteMane' AND "name" = 'ANTI-ICON';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2006-10-20' WHERE artist = 'Eisbrecher' AND "name" = 'Antikörper';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2001-04-02' WHERE artist = 'Rammstein' AND "name" = 'Mutter';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1994-07-19' WHERE artist = 'Marilyn Manson' AND "name" = 'Portrait Of An American Family';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2000-10-10' WHERE artist = 'Spineshank' AND "name" = 'The Height of Callousness';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Marilyn Manson' AND "name" = 'Holy Wood (In The Shadow Of The Valley Of Death)';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2001-02-12' WHERE artist = 'Rammstein' AND "name" = 'Sonne';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2006-03-24' WHERE artist = 'Oomph!' AND "name" = 'GlaubeLiebeTod';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2004-02-08' WHERE artist = 'Oomph!' AND "name" = 'Wahrheit Oder Pflicht';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1999-11-12' WHERE artist = 'Marilyn Manson' AND "name" = 'The Last Tour On Earth';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2008-08-22' WHERE artist = 'Oomph!' AND "name" = 'Monster';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2003-09-23' WHERE artist = 'Rob Zombie' AND "name" = 'Past, Present & Future';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2001-07-07' WHERE artist = 'Oomph!' AND "name" = 'Ego';
UPDATE "public"."Album" SET "numberOfTracks" = 38, "date" = '2006-12-01' WHERE artist = 'Oomph!' AND "name" = 'Delikatessen';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2011-02-23' WHERE artist = 'Turmion Kätilöt' AND "name" = 'Perstechnique';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2019-02-08' WHERE artist = 'Health' AND "name" = 'VOL. 4 :: SLAVES OF FEAR';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2020-10-13' WHERE artist = 'Code Orange' AND "name" = 'Underneath';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1999-07-20' WHERE artist = 'Powerman 5000' AND "name" = 'Tonight the Stars Revolt!';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1990-09-01' WHERE artist = 'Galaxie 500' AND "name" = 'This Is Our Music';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1985-11-18' WHERE artist = 'The Jesus and Mary Chain' AND "name" = 'Psychocandy';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1988-08-08' WHERE artist = 'My Bloody Valentine' AND "name" = 'You Made Me Realise';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2004-04-05' WHERE artist = 'Cocteau Twins' AND "name" = 'Heaven Or Las Vegas (Remastered)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1992-06-19' WHERE artist = 'Drop Nineteens' AND "name" = 'Delaware';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1992-03-22' WHERE artist = 'The Jesus and Mary Chain' AND "name" = 'Honey''s Dead';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1993-03-26' WHERE artist = 'Swirlies' AND "name" = 'Blonder Tongue Audio Baton';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2003-04-14' WHERE artist = 'M83' AND "name" = 'Dead Cities, Red Seas & Lost Ghosts';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2019-10-04' WHERE artist = 'DIIV' AND "name" = 'Deceiver';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2019-08-16' WHERE artist = 'Terno Rei' AND "name" = 'Violeta';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2007-03-09' WHERE artist = 'Within Temptation' AND "name" = 'The Heart of Everything';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1998-08-18' WHERE artist = 'Theatre of Tragedy' AND "name" = 'Aegis';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1997-08-12' WHERE artist = 'Tiamat' AND "name" = 'A Deeper Kind Of Slumber';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2004-01-26' WHERE artist = 'The Gathering' AND "name" = 'Sleepy Buildings';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2016-11-04' WHERE artist = 'Dark Tranquillity' AND "name" = 'Atoma';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2002-09-03' WHERE artist = 'In Flames' AND "name" = 'Reroute to Remain';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2005-02-28' WHERE artist = 'Soilwork' AND "name" = 'Stabbing the Drama';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2014-06-06' WHERE artist = 'Arch Enemy' AND "name" = 'War Eternal';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2004-03-29' WHERE artist = 'In Flames' AND "name" = 'Soundtrack to Your Escape';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2011-03-29' WHERE artist = 'Amon Amarth' AND "name" = 'Surtur Rising';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2013-03-22' WHERE artist = 'Hypocrisy' AND "name" = 'End of Disclosure';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2015-03-13' WHERE artist = 'Sleeping with Sirens' AND "name" = 'Madness (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2013-06-18' WHERE artist = 'Falling in Reverse' AND "name" = 'Fashionably Late (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2004-06-29' WHERE artist = 'From First to Last' AND "name" = 'Dear Diary, My Teen Angst Has A Body Count';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2018-11-09' WHERE artist = 'La Dispute' AND "name" = 'Somewhere at the Bottom of the River Between Vega and Altair (10th Anniversary)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2020-11-31' WHERE artist = 'City Morgue' AND "name" = 'Toxic Boogaloo';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2005' WHERE artist = 'Various Artists' AND "name" = 'Kerrang! Awards 2005: The Nominees';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Various Artists' AND "name" = 'Suicide Season';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2008' WHERE artist = 'Hollywood Undead' AND "name" = 'Swan Songs (UK Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2003-10-13' WHERE artist = 'Funeral for a Friend' AND "name" = 'Casually Dressed And Deep In Conversation';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2007-01-23' WHERE artist = 'Atreyu' AND "name" = 'The Best Of Atreyu';
UPDATE "public"."Album" SET "numberOfTracks" = 40, "date" = '2003-05-27' WHERE artist = 'Neil Perry' AND "name" = 'Lineage Situation';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2018-09-14' WHERE artist = 'HOLY FAWN' AND "name" = 'DEATH SPELLS';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Brokencyde' AND "name" = 'Brokencyde';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2000-08-08' WHERE artist = 'Scorpions' AND "name" = 'Moment of Glory';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2001-12-27' WHERE artist = 'After Forever' AND "name" = 'Decipher';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2013-11-19' WHERE artist = 'Five Finger Death Punch' AND "name" = 'The Wrong Side of Heaven and the Righteous Side of Hell, Volume 2';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2019-05-03' WHERE artist = 'Lamb of God' AND "name" = 'Ashes of the Wake (15th Anniversary)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2013-07-30' WHERE artist = 'Five Finger Death Punch' AND "name" = 'The Wrong Side of Heaven and the Righteous Side of Hell, Vol. 1';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1997-03-26' WHERE artist = 'Machine Head' AND "name" = 'The More Things Change';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2016-06-03' WHERE artist = 'Hellyeah' AND "name" = 'Unden!able';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1992-02-25' WHERE artist = 'Pantera' AND "name" = 'Vulgar Display Of Power (US Release)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Five Finger Death Punch' AND "name" = 'The Wrong Side of Heaven and the Righteous Side of Hell, Vol. 2';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1999-04-03' WHERE artist = 'Lamb of God' AND "name" = 'Burn the Priest';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2015-07-24' WHERE artist = 'Lamb of God' AND "name" = 'VII: Sturm Und Drang (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2003-05-06' WHERE artist = 'Within Temptation' AND "name" = 'Running Up That Hill';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2004-04-19' WHERE artist = 'Nightwish' AND "name" = 'Nemo';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2005-09-28' WHERE artist = 'Nightwish' AND "name" = 'Highest Hopes-The Best Of Nightwish';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2000-10-09' WHERE artist = 'Godspeed You! Black Emperor' AND "name" = 'Lift Your Skinny Fists Like Antennas to Heaven';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2015-03-31' WHERE artist = 'Godspeed You! Black Emperor' AND "name" = 'Asunder, Sweet And Other Distress';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-09-14' WHERE artist = 'Within Temptation' AND "name" = 'The Reckoning';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2015-03-25' WHERE artist = 'Nightwish' AND "name" = 'Endless Forms Most Beautiful';
UPDATE "public"."Album" SET "numberOfTracks" = 56, "date" = '2008-12-22' WHERE artist = 'Within Temptation' AND "name" = 'Black Symphony';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2007-07-24' WHERE artist = 'Within Temptation feat. Keith Caputo' AND "name" = 'The Heart Of Everything';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2003-10-20' WHERE artist = 'Penumbra' AND "name" = 'Seclusion';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2013-10-14' WHERE artist = 'Tim Hecker' AND "name" = 'Virgins';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2009-06-16' WHERE artist = 'Major Lazer' AND "name" = 'Guns Don''t Kill People... Lazers Do';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2011-06-07' WHERE artist = 'Skrillex' AND "name" = 'More Monsters And Sprites';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2012-10-22' WHERE artist = 'Nero' AND "name" = 'Welcome Reality (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2010-06-07' WHERE artist = 'Skrillex' AND "name" = 'My Name Is Skrillex EP';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2010-11-25' WHERE artist = 'James Blake' AND "name" = 'Limit to Your Love';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2013-08-05' WHERE artist = 'Memphis May Fire' AND "name" = 'Miles Away (Acoustic) (feat. Kellin Quinn)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Five Finger Death Punch' AND "name" = 'The Way Of The Fist (UK Import)';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2003-11-18' WHERE artist = 'Red Hot Chili Peppers' AND "name" = 'Greatest Hits';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2000-09-19' WHERE artist = 'Van Halen' AND "name" = '1984 (Remastered)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1989-06-15' WHERE artist = 'The Offspring' AND "name" = 'The Offspring';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1994-09-06' WHERE artist = 'Bad Religion' AND "name" = 'Stranger Than Fiction';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '1995-02-17' WHERE artist = 'blink-182' AND "name" = 'Cheshire Cat';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2002-07-02' WHERE artist = 'Green Day' AND "name" = 'Shenanigans';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2006-07-04' WHERE artist = 'Rise Against' AND "name" = 'The Sufferer and the Witness';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2006-06-05' WHERE artist = 'Ramones' AND "name" = 'Greatest Hits';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2009-05-15' WHERE artist = 'Green Day' AND "name" = '21st Century Breakdown';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'blink-182' AND "name" = 'Blink 182';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1996-09-17' WHERE artist = 'Social Distortion' AND "name" = 'White Light, White Heat, White Trash';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1990-09-04' WHERE artist = 'Queensrÿche' AND "name" = 'Empire';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1996-11' WHERE artist = 'Symphony X' AND "name" = 'The Divine Wings Of Tragedy';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2006-03-06' WHERE artist = 'Mogwai' AND "name" = 'Mr. Beast';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2003-07-01' WHERE artist = 'Ohgr' AND "name" = 'SunnyPsyOp';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2017-09-08' WHERE artist = 'Arch Enemy' AND "name" = 'Will To Power';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Nightwish' AND "name" = 'Highest Hopes-The Best Of Nightwish';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2005-07-25' WHERE artist = 'Krypteria' AND "name" = 'In Medias Res';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2004-06-07' WHERE artist = 'The Killers' AND "name" = 'Hot Fuss';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2003-03-04' WHERE artist = 'Evanescence' AND "name" = 'Fallen';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2007-06-12' WHERE artist = 'Paramore' AND "name" = 'RIOT!';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2008-06-12' WHERE artist = 'Coldplay' AND "name" = 'Viva la Vida or Death and All His Friends';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2008-10-07' WHERE artist = 'Rise Against' AND "name" = 'Appeal to Reason';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2002-10-01' WHERE artist = 'Good Charlotte' AND "name" = 'The Young and the Hopeless';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'blink-182' AND "name" = 'Take Off Your Pants & Jacket';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Slipknot' AND "name" = 'Slipknot (10th Anniversary Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 28, "date" = '2009-05-08' WHERE artist = 'Epica' AND "name" = 'The Classical Conspiracy';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-03-20' WHERE artist = 'Delain' AND "name" = 'April Rain';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2007-08-22' WHERE artist = 'Nightwish' AND "name" = 'Amaranth';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1983-04' WHERE artist = 'Minor Threat' AND "name" = 'Out of Step';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1996-06-07' WHERE artist = 'Refused' AND "name" = 'Songs to Fan the Flames of Discontent';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1997-05-27' WHERE artist = 'Snot' AND "name" = 'Get Some';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2014-07-29' WHERE artist = 'Silverstein' AND "name" = 'Discovering The Waterfront (Reissue)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2008-05-27' WHERE artist = 'H2O' AND "name" = 'Nothing To Prove';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-06-23' WHERE artist = 'Alexisonfire' AND "name" = 'Old Crows/Young Cardinals';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1999-10-05' WHERE artist = 'AFI' AND "name" = 'All Hallow''s E.P.';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bring Me the Horizon' AND "name" = 'That''s The Spirit (Track by Track Commentary)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2001-08-14' WHERE artist = 'From Autumn To Ashes' AND "name" = 'Too Bad You''re Beautiful';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2004-09-07' WHERE artist = 'Fear Before The March Of Flames' AND "name" = 'Art Damage';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2011-05-23' WHERE artist = 'deadmau5' AND "name" = 'Raise Your Weapon (Remixes)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-07-22' WHERE artist = 'Skrillex' AND "name" = 'Purple Lamborghini (with Rick Ross)';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2009-01-19' WHERE artist = 'Excision' AND "name" = 'Wasted';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2011-02-14' WHERE artist = 'Gemini' AND "name" = 'Blue EP';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2011-08-05' WHERE artist = 'Nero' AND "name" = 'Promises';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2012-05-01' WHERE artist = 'Skrillex' AND "name" = 'Make It Bun Dem';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Skrillex' AND "name" = 'My Name Is Skrillex EP';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2009-09-29' WHERE artist = 'Bassnectar' AND "name" = 'Cozza Frenzy';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2005-10-01' WHERE artist = 'SKisM' AND "name" = 'Skism EP';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2013-01-21' WHERE artist = 'FaltyDL' AND "name" = 'Hardcourage';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2009-10-06' WHERE artist = 'Relient K' AND "name" = 'Forget and Not Slow Down';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2004-10-26' WHERE artist = 'Sixpence None the Richer' AND "name" = 'The Best Of';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2006-11-21' WHERE artist = 'P.O.D.' AND "name" = 'Greatest Hits: The Atlantic Years';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2005-09-25' WHERE artist = 'David Crowder Band' AND "name" = 'A Collision or (3+4=7)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2006-02-15' WHERE artist = 'Amorphis' AND "name" = 'Eclipse';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2010-08-31' WHERE artist = 'Comeback Kid' AND "name" = 'Symptoms And Cures';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2018-08-03' WHERE artist = 'Trophy Eyes' AND "name" = 'The American Dream';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2008-04-01' WHERE artist = 'Veil of Maya' AND "name" = 'The Common Man''s Collapse';
UPDATE "public"."Album" SET "numberOfTracks" = 23, "date" = '2009-09-22' WHERE artist = 'Parkway Drive' AND "name" = 'Horizons (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2007-03-27' WHERE artist = 'Paul Wall' AND "name" = 'Im Throwed';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2014-07-15' WHERE artist = 'Betraying the Martyrs' AND "name" = 'Phantom';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2003-08-19' WHERE artist = 'All Shall Perish' AND "name" = 'Hate, Malice, Revenge';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2011-11-21' WHERE artist = 'Sepalcure' AND "name" = 'Sepalcure';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Skrillex' AND "name" = 'More Monsters And Sprites';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '1998-10-27' WHERE artist = 'Kid Dynamite' AND "name" = 'Kid Dynamite';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2019-05-03' WHERE artist = 'Bad Religion' AND "name" = 'Age of Unreason';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2001-05-15' WHERE artist = 'H2O' AND "name" = 'Go';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2002-10' WHERE artist = 'CPM 22' AND "name" = 'Chegou A Hora De Recomeçar';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2004-09-29' WHERE artist = 'Rise Against' AND "name" = 'Siren Song Of The Counter-Culture (Japan Version / International Version)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Rise Against' AND "name" = 'The Sufferer and the Witness';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-10-29' WHERE artist = 'While She Sleeps' AND "name" = 'Anti-Social';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2009-08-07' WHERE artist = 'Behemoth' AND "name" = 'Evangelion';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1985-10-16' WHERE artist = 'Possessed' AND "name" = 'Seven Churches';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1989-05-12' WHERE artist = 'Morbid Angel' AND "name" = 'Altars of Madness';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1989-12-04' WHERE artist = 'Carcass' AND "name" = 'Symphonies of Sickness';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1990-06-04' WHERE artist = 'Entombed' AND "name" = 'Left Hand Path';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1990-06-25' WHERE artist = 'Deicide' AND "name" = 'Deicide';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1991-07-01' WHERE artist = 'Cannibal Corpse' AND "name" = 'Butchered at Birth';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1991-02' WHERE artist = 'Bolt Thrower' AND "name" = 'War Master';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1991-10-30' WHERE artist = 'Carcass' AND "name" = 'Necroticism: Descanting the Insalubrious';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1992-10' WHERE artist = 'Bolt Thrower' AND "name" = 'The IVth Crusade';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1994-04-12' WHERE artist = 'Cannibal Corpse' AND "name" = 'The Bleeding';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1996-06-10' WHERE artist = 'Carcass' AND "name" = 'Swansong';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2005-11-15' WHERE artist = 'Death' AND "name" = 'The Sound of Perseverance - Reissue';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2012-06-26' WHERE artist = 'Gojira' AND "name" = 'L''Enfant Sauvage (Special Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2019-11-22' WHERE artist = 'Blood Incantation' AND "name" = 'Hidden History Of The Human Race';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2005-03-17' WHERE artist = 'Paradise Lost' AND "name" = 'Paradise Lost';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1995-05-17' WHERE artist = 'Lacrimosa' AND "name" = 'Inferno';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1997-04-06' WHERE artist = 'Within Temptation' AND "name" = 'Enter';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1997-07-14' WHERE artist = 'Paradise Lost' AND "name" = 'One Second';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1998-01-26' WHERE artist = 'Moonspell' AND "name" = 'Sin / Pecado';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1999-09-13' WHERE artist = 'Tristania' AND "name" = 'Beyond the Veil';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2001-02-26' WHERE artist = 'Paradise Lost' AND "name" = 'Believe in Nothing';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Type O Negative' AND "name" = 'October Rust [Special Edition]';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2003-03-31' WHERE artist = 'For My Pain...' AND "name" = 'Fallen';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2005-01-24' WHERE artist = 'Tristania' AND "name" = 'Ashes';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2002-10-29' WHERE artist = 'Lacuna Coil' AND "name" = 'Comalies';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2000-12-04' WHERE artist = 'Within Temptation' AND "name" = 'Mother Earth';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2006-10-10' WHERE artist = 'A Static Lullaby' AND "name" = 'A Static Lullaby';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2001-06-13' WHERE artist = 'Pg.99' AND "name" = 'Document #8';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2002-05-01' WHERE artist = 'City of Caterpillar' AND "name" = 'City of Caterpillar';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2004-01-06' WHERE artist = 'Circle Takes the Square' AND "name" = 'As the Roots Undo';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Hollywood Undead' AND "name" = 'Swan Songs (UK Version)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Hawthorne Heights' AND "name" = 'The Silence In Black and White - Re-Issue';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2003-09-16' WHERE artist = 'Story of the Year' AND "name" = 'Page Avenue (US Non-PA Version)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Devil Wears Prada' AND "name" = 'With Roots Above And Branches Below (Standard Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2013-06-05' WHERE artist = 'Escape the Fate' AND "name" = 'Ungrateful (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2015-02-24' WHERE artist = 'Falling in Reverse' AND "name" = 'Just Like You (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2015-03-13' WHERE artist = 'Sleeping with Sirens' AND "name" = 'Madness (Deluxe Edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Saosin' AND "name" = 'Along the Shadow (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2010-12-06' WHERE artist = 'Martin Solveig & Dragonette' AND "name" = 'Hello';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Black Sun Empire' AND "name" = 'Driving Insane LP';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2015-01-13' WHERE artist = 'Нейромонах Феофан' AND "name" = 'В душе драм, в сердце светлая русь!';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2018-06-29' WHERE artist = 'Pendulum' AND "name" = 'The Reworks';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Pendulum' AND "name" = 'Greatest Hits';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1995-07-31' WHERE artist = 'Goldie' AND "name" = 'Timeless';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '1996' WHERE artist = 'Origin Unknown' AND "name" = 'Valley of the Shadows';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2007-06-11' WHERE artist = 'Pendulum' AND "name" = 'Blood Sugar';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2000-01' WHERE artist = 'LTJ Bukem' AND "name" = 'Producer 01';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2016-06-24' WHERE artist = 'Fred V & Grafix' AND "name" = 'Oxygen';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2011-09-13' WHERE artist = 'The Crystal Method' AND "name" = 'Play For Real (featuring The Heavy)';
UPDATE "public"."Album" SET "numberOfTracks" = 22, "date" = '1997-06-23' WHERE artist = 'Roni Size' AND "name" = 'New Forms';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2020-02-14' WHERE artist = 'Justin Bieber' AND "name" = 'CHANGES';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1981-12' WHERE artist = 'Venom' AND "name" = 'Welcome To Hell';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1982-11-02' WHERE artist = 'Venom' AND "name" = 'Black Metal';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1987-08-16' WHERE artist = 'Mayhem' AND "name" = 'Deathcrush';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1997-01' WHERE artist = 'Summoning' AND "name" = 'Dol Guldur';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1996-09-19' WHERE artist = 'Cradle of Filth' AND "name" = 'Dusk and Her Embrace';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2008-10-28' WHERE artist = 'Cradle of Filth' AND "name" = 'Godspeed on the Devil''s Thunder';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1995-02' WHERE artist = 'Ulver' AND "name" = 'Bergtatt';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2015-10-02' WHERE artist = 'Deafheaven' AND "name" = 'New Bermuda';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Jesus and Mary Chain' AND "name" = 'Psychocandy (Expanded Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2016-07-08' WHERE artist = 'Boris' AND "name" = 'Pink (Deluxe Edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Kyuss' AND "name" = 'Sky Valley';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1996-10-15' WHERE artist = 'Corrosion of Conformity' AND "name" = 'Wiseblood';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1997-10-07' WHERE artist = 'Fu Manchu' AND "name" = 'The Action Is Go';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2005-06-21' WHERE artist = 'Clutch' AND "name" = 'Robot Hive / Exodus';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2000' WHERE artist = 'Dead Meadow' AND "name" = 'Dead Meadow';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2000-11-28' WHERE artist = 'Kyuss' AND "name" = 'Muchas Gracias: The Best of Kyuss';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2000-10-30' WHERE artist = 'Monster Magnet' AND "name" = 'God Says No';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2002-08-27' WHERE artist = 'Queens of the Stone Age' AND "name" = 'Songs For The Deaf (UK Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2003-09-23' WHERE artist = 'Desert Sessions' AND "name" = 'The Desert Sessions Volume 9 & 10';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2005' WHERE artist = 'Colour Haze' AND "name" = 'Colour Haze';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007-09-25' WHERE artist = 'Down' AND "name" = 'Over the Under';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2008-12-01' WHERE artist = 'My Sleeping Karma' AND "name" = 'Satya';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2016-11-18' WHERE artist = 'Soundgarden' AND "name" = 'Badmotorfinger (25th Anniversary Remaster)';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2010-08-14' WHERE artist = 'Fu Manchu' AND "name" = 'Godzilla''s / Eatin'' Dust';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2010-11-04' WHERE artist = 'Alpine' AND "name" = 'Hands';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2017-08-25' WHERE artist = 'Thee Oh Sees' AND "name" = 'Orc';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2007-06-12' WHERE artist = 'Queens of the Stone Age' AND "name" = 'Era Vulgaris';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2000-06-06' WHERE artist = 'Queens of the Stone Age' AND "name" = 'Rated R';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1998-09-22' WHERE artist = 'Queens of the Stone Age' AND "name" = 'Queens of the Stone Age';
UPDATE "public"."Album" SET "numberOfTracks" = 26, "date" = '2010' WHERE artist = 'Queens of the Stone Age' AND "name" = 'Rated R - Deluxe Edition';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2005-11-18' WHERE artist = 'Boris' AND "name" = 'Pink';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2002-08-27' WHERE artist = 'Queens of the Stone Age' AND "name" = 'Songs For The Deaf (UK Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007-03-20' WHERE artist = 'Clutch' AND "name" = 'From Beale Street to Oblivion';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2015-07-24' WHERE artist = 'Gunship' AND "name" = 'Gunship';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2012-12-31' WHERE artist = 'Perturbator' AND "name" = 'I Am The Night';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2018-10-05' WHERE artist = 'Gunship' AND "name" = 'Dark All Day';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2015-04-17' WHERE artist = 'Gost' AND "name" = 'Behemoth';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2013-01-01' WHERE artist = 'El Tigr3' AND "name" = '¡ROAR!';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2018-05-18' WHERE artist = 'TWRP' AND "name" = 'Together Through Time';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2014-05-16' WHERE artist = 'Mega Drive' AND "name" = '198XAD';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2015-07-14' WHERE artist = 'Various Artists' AND "name" = 'Magnatron';
UPDATE "public"."Album" SET "numberOfTracks" = 31, "date" = '2019-03-08' WHERE artist = 'Mr.kitty' AND "name" = 'EPHEMERAL';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2018-04' WHERE artist = 'Zoé' AND "name" = 'Aztlán';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2016-08-30' WHERE artist = 'Gost' AND "name" = 'Non Paradisi';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2014-07-29' WHERE artist = 'Mitch Murder' AND "name" = 'Interceptor';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bob Dylan' AND "name" = 'Blonde on Blonde (disc 1)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Joni Mitchell' AND "name" = 'Travelogue (disc 1)';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2010-02-19' WHERE artist = 'Eluveitie' AND "name" = 'Everything Remains As It Never Was';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2004-04-19' WHERE artist = 'Finntroll' AND "name" = 'Nattfodd';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2003' WHERE artist = 'Mägo de Oz' AND "name" = 'gaia';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2019-09-13' WHERE artist = 'The Hu' AND "name" = 'The Gereg';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2004-09' WHERE artist = 'Epica' AND "name" = 'We Will Take You With Us';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2009-06-22' WHERE artist = 'PANTyRAiD' AND "name" = 'Beba';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Skrillex' AND "name" = 'Bangarang';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Pantera' AND "name" = 'Vulgar Display Of Power (US Release)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'White Zombie' AND "name" = 'Astro Creep: 2000 Songs Of Love, Destruction And Other Synthetic Delusions Of The Electric Head';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '1996-09-20' WHERE artist = 'Sepultura' AND "name" = 'Roots [Special Edition]';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Machine Head' AND "name" = 'The More Things Change';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Five Finger Death Punch' AND "name" = 'The Wrong Side of Heaven and the Righteous Side of Hell, Vol. 1';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2015-07-24' WHERE artist = 'Lamb of God' AND "name" = 'VII: Sturm Und Drang (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2015-09-03' WHERE artist = 'Five Finger Death Punch' AND "name" = 'Got Your Six';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2015-09-04' WHERE artist = 'Five Finger Death Punch' AND "name" = 'Got Your Six (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-04-22' WHERE artist = 'Gojira' AND "name" = 'Stranded';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2018-05-18' WHERE artist = 'Five Finger Death Punch' AND "name" = 'And Justice for None (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2013-05-02' WHERE artist = 'Five Finger Death Punch' AND "name" = 'Lift Me Up';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2009-11-10' WHERE artist = 'Throwdown' AND "name" = 'Deathless';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2018-03-30' WHERE artist = 'The Voidz' AND "name" = 'Virtue';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2012-06-04' WHERE artist = 'Liars' AND "name" = 'WIXIW';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2019-06-21' WHERE artist = 'BLACK MIDI' AND "name" = 'schlagenheim';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1988' WHERE artist = 'Psychic TV' AND "name" = 'Allegory & Self';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2019-08-23' WHERE artist = 'Tropical Fuck Storm' AND "name" = 'Braindrops';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2019-05-29' WHERE artist = 'Harunemuri' AND "name" = 'Harutosyura';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2001-10-23' WHERE artist = 'Tom Waits' AND "name" = 'Used Songs';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1966-06-27' WHERE artist = 'The Mothers of Invention' AND "name" = 'Freak Out!';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2003-01-28' WHERE artist = 'Faith No More' AND "name" = 'This Is It, The Best Of';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2015-10-16' WHERE artist = 'Nothing But Thieves' AND "name" = 'Nothing but Thieves';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '1968-03-04' WHERE artist = 'The Mothers of Invention' AND "name" = 'We''re Only In It For The Money';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2003-09-23' WHERE artist = 'Desert Sessions' AND "name" = 'Volumes 9 & 10';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2004-08-23' WHERE artist = 'Melvins & Lustmord' AND "name" = 'Pigs of the Roman Empire';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2001' WHERE artist = 'Chimaira' AND "name" = 'New Shit Vol 3';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1994-07-08' WHERE artist = 'Helloween' AND "name" = 'Master Of The Rings';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1995-04-18' WHERE artist = 'Iced Earth' AND "name" = 'Burnt Offerings';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1999-09-19' WHERE artist = 'Kamelot' AND "name" = 'The Fourth Legacy';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2001-06-21' WHERE artist = 'Sonata Arctica' AND "name" = 'Silence';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Helloween' AND "name" = 'Keeper of the Seven Keys (Part 2)';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1988-08-01' WHERE artist = 'Helloween' AND "name" = 'Keeper Of The Seven Keys Part II';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006-10-18' WHERE artist = 'HammerFall' AND "name" = 'Threshold';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2009-05-27' WHERE artist = 'Alestorm' AND "name" = 'Black Sails at Midnight';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2010-05-21' WHERE artist = 'Sabaton' AND "name" = 'Coat of Arms';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2012-05-25' WHERE artist = 'Sabaton' AND "name" = 'Carolus Rex';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2013-03-13' WHERE artist = 'Amaranthe' AND "name" = 'The Nexus';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2005-03-15' WHERE artist = 'Kamelot' AND "name" = 'The Black Halo';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007-05-25' WHERE artist = 'Sonata Arctica' AND "name" = 'Unia';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1990-02-26' WHERE artist = 'Gamma Ray' AND "name" = 'Heading For Tomorrow';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2012-08-12' WHERE artist = 'While She Sleeps' AND "name" = 'This Is the Six (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2017' WHERE artist = 'Basement' AND "name" = 'Promise Everything (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2015-12-04' WHERE artist = 'Batushka' AND "name" = 'Litourgiya';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2016-01-08' WHERE artist = 'Ignite' AND "name" = 'A War Against You';
UPDATE "public"."Album" SET "numberOfTracks" = 22, "date" = '2013-05-28' WHERE artist = 'Rise Against' AND "name" = 'RPM10';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2001-03-19' WHERE artist = 'Gojira' AND "name" = 'Terra Incognita';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2016-04-22' WHERE artist = 'Aborted' AND "name" = 'Retrogore';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1998-10-26' WHERE artist = 'Within Temptation' AND "name" = 'The Dance';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Theatre of Tragedy' AND "name" = 'Aégis';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Black Light Burns' AND "name" = 'Cruel Melody [Explicit Version]';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2015-03-06' WHERE artist = 'Moonspell' AND "name" = 'Extinct';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1995-07-11' WHERE artist = 'Kyuss' AND "name" = 'And the Circus Leaves Town';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Falling in Reverse' AND "name" = 'Fashionably Late [Deluxe Edition]';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2009-11-02' WHERE artist = 'Chase & Status' AND "name" = 'End Credits';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2017-06-16' WHERE artist = 'Nickelback' AND "name" = 'Feed The Machine';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Foo Fighters' AND "name" = 'In Your Honor Disc 1';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2007' WHERE artist = 'Stone Sour' AND "name" = 'Come What(Ever) May [Special Edition]';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2001-09-25' WHERE artist = 'Days of the New' AND "name" = 'Days of the New III';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2008-08-05' WHERE artist = 'Trapt' AND "name" = 'Only Through The Pain...';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2019-10-18' WHERE artist = 'Foals' AND "name" = 'part 2 everything not saved will be lost';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2008-10-13' WHERE artist = 'TTNG' AND "name" = 'Animals';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2018-07-13' WHERE artist = 'CoVet' AND "name" = 'effloresce';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2020-01-29' WHERE artist = 'tricot' AND "name" = '真っ黒';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2008-10-07' WHERE artist = 'Marnie Stern' AND "name" = 'This Is it and I Am it and You Are it and so Is That and He Is it and She Is it and it Is it and That is That';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2015-10-06' WHERE artist = 'Macross 82-99' AND "name" = 'CHAM!';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2018-10-05' WHERE artist = 'TTNG' AND "name" = 'Animals Acoustic';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2016-07-08' WHERE artist = 'TTNG' AND "name" = 'Disappointment Island';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2015-12-20' WHERE artist = 'CoVet' AND "name" = 'Currents';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Battles' AND "name" = 'Glass Drop';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2005-11-25' WHERE artist = 'Falkenbach' AND "name" = 'Heralding - The Fireblade';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009' WHERE artist = 'Ensiferum' AND "name" = 'Iron (2009 Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2017-09-22' WHERE artist = 'Godspeed You! Black Emperor' AND "name" = 'Luciferian Towers';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1999-09-02' WHERE artist = 'Amon Amarth' AND "name" = 'Avenger';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2015-11-06' WHERE artist = 'Ride' AND "name" = 'Nowhere (Expanded)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'M83' AND "name" = 'Saturdays=Youth';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'M83' AND "name" = 'Hurry Up We''re Dreaming';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Alcest' AND "name" = 'Shelter (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 25, "date" = '1999-03-06' WHERE artist = 'Charlie Brown JR.' AND "name" = 'Preço Curto, Prazo Longo';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2000-11' WHERE artist = 'Charlie Brown JR.' AND "name" = 'Nadando Com Os Tubarões';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2004-11-13' WHERE artist = 'Король и Шут' AND "name" = 'Бунт на корабле';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '1999-03-30' WHERE artist = 'Choking Victim' AND "name" = 'No Gods, No Managers';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1985' WHERE artist = '7Seconds' AND "name" = 'Walk Together, Rock Together';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2010-04-13' WHERE artist = 'Cancer Bats' AND "name" = 'Bears, Mayors, Scraps and Bones';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2018-04-13' WHERE artist = 'Carpathian Forest' AND "name" = 'Likeim';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1995-02' WHERE artist = 'Storm' AND "name" = 'Nordavind';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1998-12-08' WHERE artist = 'Vintersorg' AND "name" = 'Till Fjälls';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1998-03-04' WHERE artist = 'Thyrfing' AND "name" = 'Thyrfing';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1999-11-16' WHERE artist = 'Vintersorg' AND "name" = 'Ödemarkens Son';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1999-11-23' WHERE artist = 'Thyrfing' AND "name" = 'Hednaland';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2000-08' WHERE artist = 'Thyrfing' AND "name" = 'Urkraft';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2001-07-09' WHERE artist = 'Ensiferum' AND "name" = 'Ensiferum';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2008-04-30' WHERE artist = 'Moonsorrow' AND "name" = 'Tulimyrsky';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Amon Amarth' AND "name" = 'Once Sent From The Golden Hall (Bonus Edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Chelsea Wolfe' AND "name" = 'Abyss (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2001-07-09' WHERE artist = 'Ensiferum' AND "name" = 'Iron';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1990-04-16' WHERE artist = 'Bathory' AND "name" = 'Hammerheart';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2007-04-27' WHERE artist = 'Ensiferum' AND "name" = 'Victory Songs';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2005-02-15' WHERE artist = 'Ensiferum' AND "name" = 'Dragonheads';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2007-09-24' WHERE artist = 'Turisas' AND "name" = 'Rasputin';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Queens of the Stone Age' AND "name" = '…Like Clockwork';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1969-03-28' WHERE artist = 'Led Zeppelin' AND "name" = 'Led Zeppelin';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1997-04' WHERE artist = 'The Dillinger Escape Plan' AND "name" = 'The Dillinger Escape Plan';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2002' WHERE artist = 'Botch' AND "name" = 'Unifying Themes Redux';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1998-05-20' WHERE artist = 'Botch' AND "name" = 'American Nervoso';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1999-11' WHERE artist = 'Botch' AND "name" = 'We Are the Romans';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2017-11-03' WHERE artist = 'Converge' AND "name" = 'The Dusk in Us';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Number Twelve Looks Like You' AND "name" = 'Nuclear. Sad. Nuclear.';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2002-08-27' WHERE artist = 'The Dillinger Escape Plan' AND "name" = 'Irony Is a Dead Scene';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2016-06-17' WHERE artist = 'Converge' AND "name" = 'You Fail Me Redux';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2004-11-16' WHERE artist = 'The Chariot' AND "name" = 'Everything Is Alive, Everything Is Breathing Nothing Is Dead and Nothing Is Bleeding';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Architects' AND "name" = 'Royal Beggars';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-10-29' WHERE artist = 'Architects' AND "name" = 'Modern Misery';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2007-10-25' WHERE artist = 'Architects' AND "name" = 'Ruin';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2012-10-09' WHERE artist = 'Converge' AND "name" = 'All We Love We Leave Behind (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2010-11-23' WHERE artist = 'The Chariot' AND "name" = 'Long Live';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2018-06-22' WHERE artist = 'Vein' AND "name" = 'Errorzone';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2018-03-02' WHERE artist = 'Rolo Tomassi' AND "name" = 'Time Will Die And Love Will Bury It';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2007' WHERE artist = 'iwrestledabearonce' AND "name" = 'Iwrestledabearonce';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2017' WHERE artist = 'SpiritBox' AND "name" = 'Spiritbox';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2007-10-16' WHERE artist = 'The Tony Danza Tapdance Extravaganza' AND "name" = 'Danza II: The Electric Boogalo';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2019-09-27' WHERE artist = 'Car Bomb' AND "name" = 'Mordial';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2008' WHERE artist = 'Duck Duck Goose' AND "name" = 'Noise, Noise and more Noise';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'All Shall Perish' AND "name" = 'Hate.Malice.Revenge';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2011-10-25' WHERE artist = 'Molotov Solution' AND "name" = 'Insurrection';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2017' WHERE artist = 'Bring Me the Horizon' AND "name" = '2004 - 2013';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2010-02-16' WHERE artist = 'Carnifex' AND "name" = 'Hell Chose Me';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2015-10-23' WHERE artist = 'Born of Osiris' AND "name" = 'Soul Sphere';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-01-20' WHERE artist = 'Rose Funeral' AND "name" = 'The Resting Sonata';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2007-10-08' WHERE artist = 'I Declare War' AND "name" = 'Amidst the Bloodshed';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2005-08-30' WHERE artist = 'From Autumn To Ashes' AND "name" = 'Abandon Your Friends';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2003-04-21' WHERE artist = 'Funeral for a Friend' AND "name" = 'Four Ways To Scream Your Name';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2002-07-23' WHERE artist = 'My Chemical Romance' AND "name" = 'I Brought You My Bullets You Brought Me Your Love';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-03-10' WHERE artist = 'The Word Alive' AND "name" = 'Misery';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2006-07-06' WHERE artist = 'Eyes Set to Kill' AND "name" = 'When Silence Is Broken the Night Is Torn';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2009-03-09' WHERE artist = 'Silverstein' AND "name" = 'Punk Goes Pop Volume Two';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2005-09-01' WHERE artist = 'Stigmata' AND "name" = 'Больше Чем Любовь';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2009-03-09' WHERE artist = 'A Day to Remember' AND "name" = 'Punk Goes Pop Volume Two';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2016-01-29' WHERE artist = 'Sia' AND "name" = 'This is Acting';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Slipknot' AND "name" = 'Vol. 3: (The Subliminal Verses)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2012-10-16' WHERE artist = 'The Tony Danza Tapdance Extravaganza' AND "name" = 'Danza IIII: The Alpha - The Omega';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1998-05-11' WHERE artist = 'Opeth' AND "name" = 'My Arms Your Hearse';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2004-02-23' WHERE artist = 'Orphaned Land' AND "name" = 'Mabool - The Story Of The Three Sons Of Seven';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Opeth' AND "name" = 'My Arms, Your Hearse [Bonus Tracks]';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2019-12-19' WHERE artist = 'lildeath' AND "name" = 'moment';
UPDATE "public"."Album" SET "numberOfTracks" = 48, "date" = '2010-11-26' WHERE artist = 'Various Artists Mixed By Kid Kenobi & Glovecats' AND "name" = 'ONELOVE Presents Dubstep Invasion';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2019-03-29' WHERE artist = 'Show Me The Body' AND "name" = 'Dog Whistle';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2018-09-14' WHERE artist = 'the spirit of the beehive' AND "name" = 'Hypnic Jerks';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2015-01-20' WHERE artist = 'Preoccupations' AND "name" = 'Viet Cong';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2017-03-27' WHERE artist = 'Show Me The Body' AND "name" = 'Corpus I';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2014-11-18' WHERE artist = 'Whirr' AND "name" = 'Whirr & Nothing (Split Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 27, "date" = '2005-11-15' WHERE artist = 'Motörhead' AND "name" = 'Ace Of Spades (Expanded Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1983-06-14' WHERE artist = 'Exciter' AND "name" = 'Heavy Metal Maniac';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1984-12-26' WHERE artist = 'Running Wild' AND "name" = 'Gates to Purgatory';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1984-02' WHERE artist = 'Exciter' AND "name" = 'Violence & Force';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1984-04-16' WHERE artist = 'Venom' AND "name" = 'At War With Satan';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1985-04' WHERE artist = 'Helloween' AND "name" = 'Helloween';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1985-06-12' WHERE artist = 'Megadeth' AND "name" = 'Killing Is My Business...And Business Is Good!';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1986-07-04' WHERE artist = 'Flotsam and Jetsam' AND "name" = 'Doomsday for the Deceiver';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1986-05-12' WHERE artist = 'Rage' AND "name" = 'Reign Of Fear';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1988-06-06' WHERE artist = 'Rage' AND "name" = 'Perfect Man';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Slayer' AND "name" = 'Soundtrack To The Apocalypse -';
UPDATE "public"."Album" SET "numberOfTracks" = 29, "date" = '2008' WHERE artist = 'Motörhead' AND "name" = 'Overkill (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2013-09-24' WHERE artist = 'Metallica' AND "name" = 'Metallica Through The Never (Music From The Motion Picture)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Judas Priest' AND "name" = 'Painkiller [Bonus Tracks]';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2004-07-24' WHERE artist = 'Megadeth' AND "name" = 'Risk (Remastered)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Metallica' AND "name" = 'Garage Inc. [Disc 2]';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2008-10-08' WHERE artist = 'Sonata Arctica' AND "name" = 'Ecliptica (2008 Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1988-05-18' WHERE artist = 'Blind Guardian' AND "name" = 'Batallions of Fear';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2017-10-27' WHERE artist = 'Blind Guardian' AND "name" = 'Follow the Blind (Remastered 2017)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'DragonForce' AND "name" = 'The Valley of the Damned';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Motörhead' AND "name" = 'Everything Louder Than Everyone Else (disc 1)';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2010-02-23' WHERE artist = 'DragonForce' AND "name" = 'Sonic Firestorm (2010 Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2001' WHERE artist = 'Judas Priest' AND "name" = 'Painkiller (The Remasters)';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2007-02-20' WHERE artist = 'Helloween' AND "name" = 'Keeper Of The Seven Keys - The Legacy World Tour 2005/2006 - Live In Sao Paulo';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2006-10-11' WHERE artist = 'Children of Bodom' AND "name" = 'Chaos Ridden Years - Stockholm Knockout Live';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sonata Arctica' AND "name" = 'Deliverance';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2007-08-08' WHERE artist = 'Blind Guardian' AND "name" = 'The Forgotten Tales (Remastered 2007)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2011-08-26' WHERE artist = 'Skull Fist' AND "name" = 'Head Of The Pack';
UPDATE "public"."Album" SET "numberOfTracks" = 29, "date" = '2007-10-23' WHERE artist = 'HammerFall' AND "name" = 'Steel Meets Steel';
UPDATE "public"."Album" SET "numberOfTracks" = 29, "date" = '2010' WHERE artist = 'Motörhead' AND "name" = 'No Remorse (Deluxe Edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Slayer' AND "name" = 'Decade of Aggression (Disc 1)';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2004-07-24' WHERE artist = 'Megadeth' AND "name" = 'Rust In Peace (Remastered)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Five Finger Death Punch' AND "name" = 'The Wrong Side Of Heaven And The Righteous Side Of Hell';
UPDATE "public"."Album" SET "numberOfTracks" = 25, "date" = '2015-01-30' WHERE artist = 'Gamma Ray' AND "name" = 'The Best (Of)';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2004-07-20' WHERE artist = 'Static-X' AND "name" = 'Beneath... Between... Beyond';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1993-08-01' WHERE artist = 'Rage' AND "name" = 'The Missing Link';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2004-11-23' WHERE artist = 'Anthrax' AND "name" = 'The Greater Of Two Evils';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2018-10-12' WHERE artist = 'Gama Bomb' AND "name" = 'Speed Between the Lines';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1992-10-21' WHERE artist = 'Running Wild' AND "name" = 'Pile of Skulls';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1986-05-12' WHERE artist = 'Rage' AND "name" = 'Reign Of Fear';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1987-05-11' WHERE artist = 'Rage' AND "name" = 'Execution Guaranteed';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Motörhead' AND "name" = 'Ace Of Spades (Reissue - Expanded Bonus Track Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1983' WHERE artist = 'Burn' AND "name" = 'Burn';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2007-06-15' WHERE artist = 'Blind Guardian' AND "name" = 'Somewhere Far Beyond (Remastered 2007)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Metallica' AND "name" = 'Garage Inc. [Disc 1]';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2018-08-10' WHERE artist = 'Haunt' AND "name" = 'Burst Into Flame';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2013-08-23' WHERE artist = 'King Krule' AND "name" = '6 Feet Beneath The Moon';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2008-03-03' WHERE artist = 'Nick Cave & The Bad Seeds' AND "name" = 'Dig, Lazarus, Dig!!!';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2020-08-07' WHERE artist = 'Eyedress' AND "name" = 'Let''s Skip to the Wedding';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2013-08-19' WHERE artist = 'Drenge' AND "name" = 'drenge';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2016-01-08' WHERE artist = 'Hinds' AND "name" = 'Leave me alone';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2017-06-16' WHERE artist = 'Royal Blood' AND "name" = 'How Did We Get So Dark?';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2012-02-06' WHERE artist = 'Vivendo do Ócio' AND "name" = 'O Pensamento é um Imã';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Palaye Royale' AND "name" = 'Boom Boom Room (Side B)';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1996-04-02' WHERE artist = 'Neurosis' AND "name" = 'Through Silver In Blood';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2011-10-14' WHERE artist = 'Sólstafir' AND "name" = 'Svartir Sandar';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2017-03-10' WHERE artist = 'Planning for Burial' AND "name" = 'Below The House';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2014-05-02' WHERE artist = 'Lantlôs' AND "name" = 'Melting Sun';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2009-10-24' WHERE artist = 'Fall of Efrafa' AND "name" = 'Inle';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2016-04-08' WHERE artist = 'Cult of Luna' AND "name" = 'Mariner';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2007-02-26' WHERE artist = 'Minsk' AND "name" = 'The Ritual Fires of Abandonment';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '1998' WHERE artist = 'Sleep' AND "name" = 'Jerusalem';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1998' WHERE artist = 'Isis' AND "name" = 'Mosquito Control';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2011-04-15' WHERE artist = 'Obscure Sphinx' AND "name" = 'Anaesthetic Inhalation Ritual';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Desert Sessions' AND "name" = 'Desert Session 9&10/Desert Sessions';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2002' WHERE artist = 'Hermano' AND "name" = 'Only a Suggestion';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1999-09-10' WHERE artist = 'Desert Sessions' AND "name" = 'Volumes 5 & 6';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1998-02-24' WHERE artist = 'Desert Sessions' AND "name" = 'Volumes 1 & 2';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007-10-22' WHERE artist = 'Hermano' AND "name" = '...Into The Exam Room';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Kyuss' AND "name" = 'Queens of the Stone Age';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Unida' AND "name" = 'Unreleased';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Queens of the Stone Age' AND "name" = 'Stone Age Complications (EP)';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '1997-12-05' WHERE artist = 'Various Artists' AND "name" = 'Kyuss / Queens of the Stone Age';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2005-08-01' WHERE artist = 'Brant Bjork' AND "name" = 'Saved By Magic';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2003' WHERE artist = 'Desert Sessions' AND "name" = 'Desert Sessions 9 & 10';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Desert Sessions' AND "name" = 'Desert Sessions, Vols. 5 & 6';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2001' WHERE artist = 'Abramis Brama' AND "name" = 'När Tystnaden Har Lagt Sig';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2010' WHERE artist = 'Tuber' AND "name" = 'Tuber EP';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2011-03-07' WHERE artist = 'Queens of the Stone Age' AND "name" = 'Queens Of The Stone Age (Remastered)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Desert Sessions' AND "name" = 'Desert Sessions, Vols. 1 & 2';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Desert Sessions' AND "name" = 'The Desert Sessions Volume 1 & 2';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2001-10-16' WHERE artist = 'Desert Sessions' AND "name" = 'Volumes 7 & 8';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Arctic Monkeys' AND "name" = 'Web Transmission';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Desert Sessions' AND "name" = 'Desert Sessions 3 & 4';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2019-09-27' WHERE artist = 'Hashshashin' AND "name" = 'Badakhshan';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2005' WHERE artist = 'Yawning Man' AND "name" = 'Pothead';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Desert Sessions' AND "name" = 'Vol. 7 & 8';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '1997-12-05' WHERE artist = 'Queens of the Stone Age' AND "name" = 'Kyuss/Queens Of The Stone Age';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Desert Sessions' AND "name" = 'Vol. 1 & 2';
