
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2000-10-30' WHERE artist = 'Blur' AND "name" = 'The Best of Blur';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2006-09-08' WHERE artist = 'Justin Timberlake' AND "name" = 'Future Sex/Love Sounds';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'José González' AND "name" = 'Imperial Recordings Best of';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Iron & Wine' AND "name" = '2005-06-11: Bonnaroo Festival, TN, USA (disc 2)';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2012-06-26' WHERE artist = 'Sleeping with Sirens' AND "name" = 'If You Were a Movie, This Would Be Your Soundtrack';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2018-04-06' WHERE artist = 'Cardi B' AND "name" = 'Invasion Of Privacy';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2018-05-25' WHERE artist = 'A$AP Rocky' AND "name" = 'TESTING';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2020-11-27' WHERE artist = 'Bad Bunny' AND "name" = 'El Último Tour del Mundo';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2018-03-02' WHERE artist = 'J-Hope' AND "name" = 'Hope World';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2015-09-04' WHERE artist = 'Travis Scott' AND "name" = 'Rodeo (Expanded Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2016-11-11' WHERE artist = 'A Tribe Called Quest' AND "name" = 'We got it from Here... Thank You 4 Your service';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2008-03-18' WHERE artist = 'Flo Rida' AND "name" = 'Mail On Sunday';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-05-18' WHERE artist = 'xxxtentacion' AND "name" = 'Revenge';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2018-06-16' WHERE artist = 'The Carters' AND "name" = 'Everything is Love';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2019-11-02' WHERE artist = 'Frank Ocean' AND "name" = 'In My Room';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2019-06-28' WHERE artist = 'Freddie Gibbs' AND "name" = 'Bandana';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2020-10-30' WHERE artist = 'Ariana Grande' AND "name" = 'positions';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2014-06-09' WHERE artist = 'SZA' AND "name" = 'CTRL';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2020-03-20' WHERE artist = 'The Weeknd' AND "name" = 'After Hours';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2019-07-12' WHERE artist = 'Lizzo' AND "name" = 'Cuz I Love You (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2018-12-14' WHERE artist = 'Zayn' AND "name" = 'Icarus Falls';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2018-08-24' WHERE artist = 'Blood Orange' AND "name" = 'Negro Swan';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2018-02-14' WHERE artist = 'Joji' AND "name" = 'In Tongues (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-12-26' WHERE artist = 'DEAN' AND "name" = 'instagram';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2019-07-05' WHERE artist = 'Jaden' AND "name" = 'ERYS (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2007-11-09' WHERE artist = 'Alicia Keys' AND "name" = 'As I Am';
UPDATE "public"."Album" SET "numberOfTracks" = 23, "date" = '2015-11-06' WHERE artist = 'Sam Smith' AND "name" = 'In The Lonely Hour (Drowning Shadows Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2003-09-16' WHERE artist = 'Joss Stone' AND "name" = 'The Soul Sessions';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '1994-10-31' WHERE artist = 'Sade' AND "name" = 'The Best Of Sade';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2013-09-10' WHERE artist = 'Zedd' AND "name" = 'Stay The Night';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-11-12' WHERE artist = 'Jennie' AND "name" = 'sOlO';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2006-06-27' WHERE artist = 'Dashboard Confessional' AND "name" = 'Dusk And Summer';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2018-11-09' WHERE artist = 'LIL PEEP' AND "name" = 'Come Over When You''re Sober, Pt. 2';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2009-12-29' WHERE artist = 'Twenty One Pilots' AND "name" = 'Twenty One Pilots';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2005-02-22' WHERE artist = 'Armor for Sleep' AND "name" = 'What To Do When You Are Dead';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-08-04' WHERE artist = 'Tove Lo' AND "name" = 'Cool Girl';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2016-09-25' WHERE artist = 'LIL PEEP' AND "name" = 'HELLBOY';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2020-09-25' WHERE artist = 'Machine Gun Kelly' AND "name" = 'Tickets To My Downfall (SOLD OUT Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2005-07-26' WHERE artist = 'Paramore' AND "name" = '"All We Know Is Falling"';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2020-12-04' WHERE artist = 'Yungblud' AND "name" = 'Weird!';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2017-03-16' WHERE artist = 'Remo Drive' AND "name" = 'Greatest Hits';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2019-04-26' WHERE artist = 'Blackbear' AND "name" = 'ANONYMOUS';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2018-04-06' WHERE artist = 'Simple Plan' AND "name" = 'No Pads, No Helmets...Just Balls (15th Anniversary Tour Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1987-06-02' WHERE artist = 'Whitney Houston' AND "name" = 'Whitney';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1998-11-09' WHERE artist = 'George Michael' AND "name" = 'Ladies And Gentlemen... The Best Of George Michael';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2001' WHERE artist = 'Europe' AND "name" = 'The Final Countdown (Expanded Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1994-05-10' WHERE artist = 'Weezer' AND "name" = 'Weezer (Blue)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1997-06-30' WHERE artist = 'Prodigy' AND "name" = 'The Fat Of The Land';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2006-11-08' WHERE artist = 'Depeche Mode' AND "name" = 'The Best of Depeche Mode Volume 1';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-09-29' WHERE artist = 'Paramore' AND "name" = 'Brand New Eyes';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2016-05-08' WHERE artist = 'Radiohead' AND "name" = 'A Moon Shaped Pool';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2003-11-18' WHERE artist = 'blink-182' AND "name" = 'Blink 182';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2006-06-27' WHERE artist = 'Billy Talent' AND "name" = 'II';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '2001-11-13' WHERE artist = 'Green Day' AND "name" = 'International Superhits';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2013-01-22' WHERE artist = 'Fidlar' AND "name" = 'FIDLAR';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2003-05-06' WHERE artist = 'NOFX' AND "name" = 'The War on Errorism';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '1999' WHERE artist = 'The Clash' AND "name" = 'London Calling (Remastered)';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2001-06-12' WHERE artist = 'blink-182' AND "name" = 'Take Off Your Pants & Jacket';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1977-10-28' WHERE artist = 'Sex Pistols' AND "name" = 'Never Mind the Bollocks, Here’s the Sex Pistols';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '1995-11-07' WHERE artist = 'Coolio' AND "name" = 'Gangsta''s Paradise';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2007-08-21' WHERE artist = 'Cartel' AND "name" = 'Cartel';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1997-01-28' WHERE artist = 'Mineral' AND "name" = 'The Power of Failing';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2005-02-22' WHERE artist = 'Hidden in Plain View' AND "name" = 'Life In Dreaming';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2009-05-11' WHERE artist = 'Go:Audio' AND "name" = 'Made Up Stories';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2016-07-03' WHERE artist = 'Mom Jeans.' AND "name" = 'Best Buds';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2006-09-26' WHERE artist = 'Saosin' AND "name" = 'Saosin';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-09-29' WHERE artist = 'Empire! Empire! (I Was a Lonely Estate)' AND "name" = 'What It Takes to Move Forward';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1986-04-14' WHERE artist = 'Cocteau Twins' AND "name" = 'Victorialand';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1989-10-20' WHERE artist = 'Galaxie 500' AND "name" = 'On Fire';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Flaming Lips' AND "name" = 'Yoshimi Battles The Pink Robots (U.S. Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2003-06-10' WHERE artist = 'Sweet Trip' AND "name" = 'Velocity: design: comfort.';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1993-10-18' WHERE artist = 'Cocteau Twins' AND "name" = 'Four-Calendar Café';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2008-02-26' WHERE artist = 'Beach House' AND "name" = 'Devotion';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2008-10-28' WHERE artist = 'School of Seven Bells' AND "name" = 'Alpinisms';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2015-08-28' WHERE artist = 'Beach House' AND "name" = 'Depression Cherry';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2015-05-04' WHERE artist = 'Turnover' AND "name" = 'Peripheral Vision';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-02-19' WHERE artist = 'FKA twigs' AND "name" = 'Good to Love';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-03-15' WHERE artist = 'Grimes' AND "name" = 'Entropy';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-08-17' WHERE artist = 'LIL PEEP' AND "name" = 'star shopping';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2017-06-30' WHERE artist = 'Lany' AND "name" = 'Lany';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-11-15' WHERE artist = 'Cigarettes After Sex' AND "name" = 'K.';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2014-06-13' WHERE artist = 'Lana Del Rey' AND "name" = 'Ultraviolence';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2015-05-13' WHERE artist = 'Florence + the Machine' AND "name" = 'How Big, How Blue, How Beautiful (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1968-11-29' WHERE artist = 'Van Morrison' AND "name" = 'Astral Weeks';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1971-10-24' WHERE artist = 'Don McLean' AND "name" = 'American Pie';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1973-03-06' WHERE artist = 'Tom Waits' AND "name" = 'Closing Time';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '2008' WHERE artist = 'Billy Joel' AND "name" = 'The Stranger (Legacy Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '1985-09-30' WHERE artist = 'Tom Waits' AND "name" = 'Rain Dogs';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '1992-09-08' WHERE artist = 'Tom Waits' AND "name" = 'Bone Machine';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1971-11' WHERE artist = 'Harry Nilsson' AND "name" = 'Nilsson Schmilsson';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2002-05-07' WHERE artist = 'Tom Waits' AND "name" = 'Alice';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2001-02-01' WHERE artist = 'Jack Johnson' AND "name" = 'Brushfire Fairytales';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1969-05-14' WHERE artist = 'Neil Young' AND "name" = 'Everybody Knows This Is Nowhere';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2003-10-29' WHERE artist = 'José González' AND "name" = 'Veneer';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2005-07-26' WHERE artist = 'Matt Costa' AND "name" = 'Songs We Sing';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2005-07-04' WHERE artist = 'Sufjan Stevens' AND "name" = 'Illinoise';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2005-11-28' WHERE artist = 'Shakira' AND "name" = 'Oral Fixation Vol. 2';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2008-06-29' WHERE artist = 'Russian Red' AND "name" = 'I Love Your Glasses';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2010-11-08' WHERE artist = 'James Blunt' AND "name" = 'Some Kind of Trouble';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2014-10-17' WHERE artist = 'Various Artists' AND "name" = 'reVerse';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2005-11-15' WHERE artist = 'Bright Eyes' AND "name" = 'Motion Sickness';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1975-11-10' WHERE artist = 'Patti Smith' AND "name" = 'Horses';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1980-04-26' WHERE artist = 'X' AND "name" = 'Los Angeles';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1980-09-02' WHERE artist = 'Dead Kennedys' AND "name" = 'Fresh Fruit for Rotting Vegetables';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1981-12-05' WHERE artist = 'Black Flag' AND "name" = 'Damaged';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1982-02-05' WHERE artist = 'Bad Brains' AND "name" = 'Bad Brains';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1981-08-31' WHERE artist = 'The Gun Club' AND "name" = 'Fire of Love';
UPDATE "public"."Album" SET "numberOfTracks" = 45, "date" = '1984-07-03' WHERE artist = 'Minutemen' AND "name" = 'Double Nickels on the Dime';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '1987-06' WHERE artist = 'Dead Kennedys' AND "name" = 'Give Me Convenience or Give Me Death';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sex Pistols' AND "name" = 'Never Mind the Bollocks';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '1996-08-20' WHERE artist = 'Anti-Flag' AND "name" = 'Die for the Government';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1999-06-01' WHERE artist = 'blink-182' AND "name" = 'Enema of the State';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2003-11-18' WHERE artist = 'blink-182' AND "name" = 'blink-182';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2004-09-21' WHERE artist = 'Green Day' AND "name" = 'American Idiot (Deluxe)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sex Pistols' AND "name" = 'Never Mind the Bollocks Here''s the Sex Pistols';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2007-07-10' WHERE artist = 'Against Me!' AND "name" = 'New Wave';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2001-06-12' WHERE artist = 'blink-182' AND "name" = 'Take Off Your Pants and Jacket';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2004-09-21' WHERE artist = 'Green Day' AND "name" = 'American Idiot';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007' WHERE artist = 'Avril Lavigne' AND "name" = 'The Best Damn Thing (Expanded Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1973-12-01' WHERE artist = 'Black Sabbath' AND "name" = 'Sabbath Bloody Sabbath';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '1975-12-01' WHERE artist = 'Black Sabbath' AND "name" = 'We Sold Our Soul for Rock ''n'' Roll';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1976-03-23' WHERE artist = 'Judas Priest' AND "name" = 'Sad Wings of Destiny';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1978-02-10' WHERE artist = 'Judas Priest' AND "name" = 'Stained Class';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2009-04-06' WHERE artist = 'Black Sabbath' AND "name" = 'Paranoid (2009 Remastered Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1982-06-07' WHERE artist = 'Manowar' AND "name" = 'Battle Hymns';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1983-12-05' WHERE artist = 'Accept' AND "name" = 'Balls to the Wall';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1983-10-30' WHERE artist = 'Mercyful Fate' AND "name" = 'Melissa';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2016-11-18' WHERE artist = 'Metallica' AND "name" = 'Hardwired…To Self-Destruct';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1985-11-09' WHERE artist = 'W.A.S.P.' AND "name" = 'The Last Command';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Metallica' AND "name" = 'The Black Album';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1991-06-11' WHERE artist = 'Skid Row' AND "name" = 'Slave to the Grind';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1984-08-17' WHERE artist = 'W.A.S.P.' AND "name" = 'W.A.S.P.';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1980-04-21' WHERE artist = 'Black Sabbath' AND "name" = 'Heaven and Hell';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1980-09-20' WHERE artist = 'Ozzy Osbourne' AND "name" = 'Blizzard of Ozz';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2015-09-04' WHERE artist = 'Iron Maiden' AND "name" = 'The Book of Souls';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1982-04-17' WHERE artist = 'Motörhead' AND "name" = 'Iron Fist';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1982-03-22' WHERE artist = 'Iron Maiden' AND "name" = 'The Number of the Beast';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1983-11-15' WHERE artist = 'Ozzy Osbourne' AND "name" = 'Bark at the Moon';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1984-07-02' WHERE artist = 'Dio' AND "name" = 'The Last In Line';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1986-09-29' WHERE artist = 'Iron Maiden' AND "name" = 'Somewhere In Time';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1991-06-11' WHERE artist = 'Skid Row' AND "name" = 'Slave to the Grind';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1991-09-17' WHERE artist = 'Ozzy Osbourne' AND "name" = 'No More Tears';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1992-07-14' WHERE artist = 'Megadeth' AND "name" = 'Countdown To Extinction';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2018-06-01' WHERE artist = 'Ghost' AND "name" = 'Prequelle';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1994-11-01' WHERE artist = 'Megadeth' AND "name" = 'Youthanasia';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1995-10-23' WHERE artist = 'Ozzy Osbourne' AND "name" = 'Ozzmosis';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1996-06-04' WHERE artist = 'Metallica' AND "name" = 'Load';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1997-06-17' WHERE artist = 'Megadeth' AND "name" = 'Cryptic Writings';
UPDATE "public"."Album" SET "numberOfTracks" = 27, "date" = '1998-11-24' WHERE artist = 'Metallica' AND "name" = 'Garage Inc.';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1998-03-23' WHERE artist = 'Iron Maiden' AND "name" = 'Virtual XI';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2015-08-21' WHERE artist = 'Ghost' AND "name" = 'Meliora';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2000-05-29' WHERE artist = 'Iron Maiden' AND "name" = 'Brave New World';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2001-10-16' WHERE artist = 'Ozzy Osbourne' AND "name" = 'Down To Earth';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2002-06-04' WHERE artist = 'Manowar' AND "name" = 'Warriors of the World';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2003-04-22' WHERE artist = 'Black Label Society' AND "name" = 'The Blessed Hellride';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2003-06-05' WHERE artist = 'Metallica' AND "name" = 'St. Anger';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2003-09-02' WHERE artist = 'Iron Maiden' AND "name" = 'Dance Of Death';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2006-08-25' WHERE artist = 'Iron Maiden' AND "name" = 'A Matter of Life and Death';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2007-05-22' WHERE artist = 'Ozzy Osbourne' AND "name" = 'Black Rain';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2007-10-30' WHERE artist = 'Avenged Sevenfold' AND "name" = 'Avenged Sevenfold';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2008-09-01' WHERE artist = 'Volbeat' AND "name" = 'Guitar Gangsters & Cadillac Blood';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2008-09-12' WHERE artist = 'Metallica' AND "name" = 'Death Magnetic';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2009-09-22' WHERE artist = 'Five Finger Death Punch' AND "name" = 'War Is the Answer';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2010-04-26' WHERE artist = 'Bullet for My Valentine' AND "name" = 'Fever';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2010-07-27' WHERE artist = 'Avenged Sevenfold' AND "name" = 'Nightmare';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2010-09-10' WHERE artist = 'Volbeat' AND "name" = 'Beyond Hell / Above Heaven';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2013-05-28' WHERE artist = 'Alice in Chains' AND "name" = 'The Devil Put Dinosaurs Here';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2013-06-10' WHERE artist = 'Black Sabbath' AND "name" = '13';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2013-08-27' WHERE artist = 'Avenged Sevenfold' AND "name" = 'Hail To The King';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2019-10-25' WHERE artist = 'Kanye West' AND "name" = 'Jesus Is King';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2018-06-01' WHERE artist = 'Kanye West' AND "name" = 'Ye';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2019-04-15' WHERE artist = 'LIL UZI VERT' AND "name" = 'Lil Uzi Vert vs. The World';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2018-04-20' WHERE artist = 'J. Cole' AND "name" = 'KOD';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '1999-06-29' WHERE artist = 'Alice in Chains' AND "name" = 'Nothing Safe: Best of the Box';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1988-04-11' WHERE artist = 'Iron Maiden' AND "name" = 'Seventh Son Of A Seventh Son';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2005-02-23' WHERE artist = 'Judas Priest' AND "name" = 'Angel Of Retribution';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '1997-11-11' WHERE artist = 'Ozzy Osbourne' AND "name" = 'The OZZman Cometh';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2020-02-21' WHERE artist = 'Grimes' AND "name" = 'Miss Anthropocene (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2012-06' WHERE artist = 'David Bowie' AND "name" = 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars (2012 Remaster)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1970-04-10' WHERE artist = 'Elton John' AND "name" = 'Elton John';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1978-01-20' WHERE artist = 'Gerry Rafferty' AND "name" = 'City To City';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Paul McCartney & Wings' AND "name" = 'Wings Over America (Disc 1)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2015-09-25' WHERE artist = 'David Bowie' AND "name" = 'Hunky Dory (2015 Remaster)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1973-06-30' WHERE artist = 'Sly & The Family Stone' AND "name" = 'Fresh';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1994' WHERE artist = 'Led Zeppelin' AND "name" = 'Led Zeppelin III (Remaster)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2021-02-05' WHERE artist = 'Hayley Williams' AND "name" = 'Flowers For Vases / Descansos';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2017-08-25' WHERE artist = 'LIL UZI VERT' AND "name" = 'Luv Is Rage 2';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2011-05-10' WHERE artist = 'Tyler, the Creator' AND "name" = 'Goblin';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2010-08-27' WHERE artist = 'Hurts' AND "name" = 'Happiness';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2020-03-23' WHERE artist = 'The Weeknd' AND "name" = 'aFTeR hoURs (dElUXe)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2015-02-27' WHERE artist = 'Purity Ring' AND "name" = 'Another Eternity';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2018-09-07' WHERE artist = 'Molchat Doma' AND "name" = 'этажи';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2016-07-22' WHERE artist = 'Honne' AND "name" = 'Warm On a Cold Night (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2018-05-25' WHERE artist = 'CHVRCHES' AND "name" = 'Love is Dead';
UPDATE "public"."Album" SET "numberOfTracks" = 21, "date" = '2018-11-09' WHERE artist = 'Muse' AND "name" = 'Simulation Theory (Super Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2015-10-16' WHERE artist = 'BØRNS' AND "name" = 'Dopamine';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2015-10-16' WHERE artist = 'Neon Indian' AND "name" = 'VEGA INTL. NIGHT SCHOOL';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '1994-11-21' WHERE artist = 'New Order' AND "name" = '(the best of) New Order';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2021-05-30' WHERE artist = 'Bo Burnham' AND "name" = 'Inside (The Songs)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2011-04-29' WHERE artist = 'Jennifer Lopez' AND "name" = 'Love?';
UPDATE "public"."Album" SET "numberOfTracks" = 29, "date" = '2012-12-07' WHERE artist = 'David Guetta' AND "name" = 'Nothing But The Beat (Ultimate Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2013-07-04' WHERE artist = 'Jay-Z' AND "name" = 'Magna Carta... Holy Grail';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2020-05-29' WHERE artist = 'Freddie Gibbs' AND "name" = 'Alfredo';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2018-01-19' WHERE artist = 'JPEGMAFIA' AND "name" = 'VETERAN';
UPDATE "public"."Album" SET "numberOfTracks" = 27, "date" = '2004-11-09' WHERE artist = 'NOFX' AND "name" = 'The Greatest Songs Ever Written (By Us)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Green Day' AND "name" = '2005-01-15: Boeblingen, Germany';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-01-25' WHERE artist = 'Coldplay' AND "name" = 'Hymn for the Weekend (SeeB Remix)';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2008-11-25' WHERE artist = 'Coldplay' AND "name" = 'Viva la Vida (Prospekt''s March Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2015-11-06' WHERE artist = 'Coldplay' AND "name" = 'Adventure Of A Lifetime';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2008-11-21' WHERE artist = 'Coldplay' AND "name" = 'Prospekt''s March [EP]';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2013-09-06' WHERE artist = 'Coldplay' AND "name" = 'Atlas (From “The Hunger Games: Catching Fire” Soundtrack)';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1999-10-11' WHERE artist = 'Coldplay' AND "name" = 'The Blue Room EP';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Coldplay' AND "name" = 'X And Y';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2002-08-26' WHERE artist = 'Coldplay' AND "name" = 'Rush of Blood to the Head';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Coldplay' AND "name" = 'Lost?';
UPDATE "public"."Album" SET "numberOfTracks" = 33, "date" = '2007-03-26' WHERE artist = 'Coldplay' AND "name" = 'The Singles 1999-2006';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bridge Underwater' AND "name" = 'The Love EP';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2012-11-14' WHERE artist = 'Coldplay' AND "name" = 'Coldplay Live 2012';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Luzabril' AND "name" = 'Dreamcatcher / Cazador de Sueños';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2007' WHERE artist = 'The Cedar' AND "name" = 'The Fire EP 2007';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2018-06-15' WHERE artist = '5 Seconds of Summer' AND "name" = 'Youngblood (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2021-06-11' WHERE artist = 'Marina' AND "name" = 'Ancient Dreams In A Modern Land';
UPDATE "public"."Album" SET "numberOfTracks" = 65, "date" = '2014-11-21' WHERE artist = 'The Velvet Underground' AND "name" = 'The Velvet Underground (45th Anniversary)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2014-07-11' WHERE artist = 'Jason Mraz' AND "name" = 'Yes!';
UPDATE "public"."Album" SET "numberOfTracks" = 22, "date" = '2015-10-30' WHERE artist = 'Alanis Morissette' AND "name" = 'Jagged Little Pill (Remastered)';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2010-10-22' WHERE artist = 'Lady Gaga' AND "name" = 'The Fame Monster (Explicit Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2008-12-10' WHERE artist = 'Fall Out Boy' AND "name" = 'Folie à deux';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2020-09-25' WHERE artist = 'Machine Gun Kelly' AND "name" = 'Tickets To My Downfall';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006-10-10' WHERE artist = 'Cobra Starship' AND "name" = 'While The City Sleeps, We Rule The Streets';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2002-03-19' WHERE artist = 'Simple Plan' AND "name" = 'No Pads, No Helmets...Just Balls';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2004-10-26' WHERE artist = 'Simple Plan' AND "name" = 'Still Not Getting Any...';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2011-03-08' WHERE artist = 'Avril Lavigne' AND "name" = 'Goodbye Lullaby (Expanded Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1967-04-29' WHERE artist = 'The Turtles' AND "name" = 'Happy Together';
UPDATE "public"."Album" SET "numberOfTracks" = 26, "date" = '1996-03-21' WHERE artist = 'The Yardbirds' AND "name" = 'Psycho Blues: The Best Collection of the Yardbirds 1963-1966';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '1997' WHERE artist = 'The Jimi Hendrix Experience' AND "name" = 'Experience Hendrix: The Best of Jimi Hendrix';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Kinks' AND "name" = 'The Ultimate Collection (disc 2)';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1994-07-18' WHERE artist = 'Led Zeppelin' AND "name" = 'Led Zeppelin II (1994 Remaster)';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2014-09-05' WHERE artist = 'Banks' AND "name" = 'Goddess (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2019-10-01' WHERE artist = 'Kim Petras' AND "name" = 'Turn Off The Light';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2016-03-04' WHERE artist = 'Miike Snow' AND "name" = 'III';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2019-07-12' WHERE artist = 'Banks' AND "name" = 'III';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2020-08-21' WHERE artist = 'Troye Sivan' AND "name" = 'In A Dream';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2014-01-31' WHERE artist = 'BROODS' AND "name" = 'BROODS';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2018-01-12' WHERE artist = 'BØRNS' AND "name" = 'Blue Madonna';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2020-11-26' WHERE artist = 'Pabllo Vittar' AND "name" = '111 Deluxe';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2016-07-29' WHERE artist = 'CHVRCHES' AND "name" = 'Every Open Eye (Extended Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-10-20' WHERE artist = 'Rita Ora' AND "name" = 'Anywhere';
UPDATE "public"."Album" SET "numberOfTracks" = 25, "date" = '2018' WHERE artist = 'Dua Lipa' AND "name" = 'Dua Lipa (Complete Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2020-05-15' WHERE artist = 'Charli XCX' AND "name" = 'How I''m Feeling Now';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2011-08-08' WHERE artist = 'Jay-Z' AND "name" = 'Watch The Throne';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Dogboy!' AND "name" = '12" vinyl release in spring 09 preview';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Ryan Hess' AND "name" = 'Standing in Elysium';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'TheMainstream' AND "name" = 'TheMainstream';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Replica Sounds' AND "name" = 'Progress';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2017-07-10' WHERE artist = 'Letrux' AND "name" = 'Letrux em Noite de Climão';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2006-03-29' WHERE artist = 'Daft Punk' AND "name" = 'Musique, Vol. 1: 1993-2005';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2016-02-19' WHERE artist = 'Kungs' AND "name" = 'This Girl (Kungs Vs. Cookin'' On 3 Burners)';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2019-12-27' WHERE artist = 'JackBoys' AND "name" = 'JACKBOYS';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2013-02-18' WHERE artist = 'Nick Cave & The Bad Seeds' AND "name" = 'Push the Sky Away';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2012-05-01' WHERE artist = 'The Lumineers' AND "name" = 'The Lumineers (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2019-05-10' WHERE artist = 'Logic' AND "name" = 'Confessions of a Dangerous Mind';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2019-06-28' WHERE artist = 'The Black Keys' AND "name" = '"Let''s Rock"';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-10-16' WHERE artist = 'Billie Eilish' AND "name" = 'When The Party''s Over';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2020-11-27' WHERE artist = 'Lewis Capaldi' AND "name" = 'Divinely Uninspired To a Hellish Extent (Extended Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2019-12-13' WHERE artist = 'Lizzo' AND "name" = 'Cuz I Love You (Super Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2012-09-06' WHERE artist = 'Odesza' AND "name" = 'Summer''s Gone';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Air' AND "name" = 'Live BBC Int Shephard''s Bush E';
UPDATE "public"."Album" SET "numberOfTracks" = 31, "date" = '2007-05-29' WHERE artist = 'Various Artists' AND "name" = 'Café del Mar Vol. 14';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Tool' AND "name" = 'Aenima';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2009-04-28' WHERE artist = 'Animals as Leaders' AND "name" = 'Animals As Leaders';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-11-02' WHERE artist = 'Katatonia' AND "name" = 'Night is the New Day';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2014-06-24' WHERE artist = 'Animals as Leaders' AND "name" = 'The Joy Of Motion';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1995-09-19' WHERE artist = 'Dream Theater' AND "name" = 'A Change of Seasons';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2012-07-03' WHERE artist = 'Periphery' AND "name" = 'Periphery II';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2005-05-16' WHERE artist = 'Meshuggah' AND "name" = 'Catch 33';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1999-06-12' WHERE artist = 'Sigur Rós' AND "name" = 'ágætis byrjun';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '1997-08-14' WHERE artist = 'Godspeed You! Black Emperor' AND "name" = 'F#a#infinity';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '1978-03' WHERE artist = 'Brian Eno' AND "name" = 'Ambient 1/Music For Airports';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2004-08-31' WHERE artist = 'Lamb of God' AND "name" = 'Ashes Of The Wake';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '1997-07-29' WHERE artist = 'Pantera' AND "name" = 'Official Live : 101 Proof';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1989' WHERE artist = 'Metallica' AND "name" = 'Ride The Lightning (Remastered)';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2019-08-16' WHERE artist = 'King Gizzard & The Lizard Wizard' AND "name" = 'INFEST THE RATS'' NEST';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2016-02-14' WHERE artist = 'Kanye West' AND "name" = 'The Life Of Pablo';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2020-03-06' WHERE artist = 'LIL UZI VERT' AND "name" = 'Eternal Atake';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2020-03-13' WHERE artist = 'LIL UZI VERT' AND "name" = 'Eternal Atake (Deluxe) - LUV vs. The World 2';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2016-09-30' WHERE artist = 'Banks' AND "name" = 'The Altar';
UPDATE "public"."Album" SET "numberOfTracks" = 24, "date" = '2014-04-19' WHERE artist = 'The Notorious B.I.G.' AND "name" = 'Life After Death (2014 Remastered Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 22, "date" = '2017-09-22' WHERE artist = 'Jhené Aiko' AND "name" = 'TRIP';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2018-04-06' WHERE artist = 'Alina Baraz' AND "name" = 'The Color Of You';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2017-02-24' WHERE artist = 'Steve Lacy' AND "name" = 'Steve Lacy''s Demo';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2018-11-02' WHERE artist = 'Rosalía' AND "name" = 'El Mal Querer';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2019-11-08' WHERE artist = 'FKA twigs' AND "name" = 'magdalene';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2016-07-15' WHERE artist = 'Jamila Woods' AND "name" = 'Heavn';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2015-04-13' WHERE artist = 'Tyler, the Creator' AND "name" = 'Cherry Bomb';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2019-02-15' WHERE artist = 'Homeshake' AND "name" = 'Helium';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2018-08-03' WHERE artist = 'H.E.R.' AND "name" = 'I Used To Know Her: The Prelude';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2017-07-21' WHERE artist = 'Tyler, the Creator' AND "name" = 'Flower Boy';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2021-03-21' WHERE artist = 'The Weeknd' AND "name" = 'House of Balloons (Original)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2018-06-08' WHERE artist = 'SERPENTWITHFEET' AND "name" = 'soil';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2018-08-15' WHERE artist = 'Sabrina Claudio' AND "name" = 'no rain, no flowers';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2014' WHERE artist = 'Banks' AND "name" = 'Brain';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2019-05-16' WHERE artist = 'Erika de Casier' AND "name" = 'Essentials';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2014-09-05' WHERE artist = 'Banks' AND "name" = 'Goddess';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2019-01-25' WHERE artist = 'Terror Jr' AND "name" = 'Unfortunately, Terror Jr';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2018-11-02' WHERE artist = 'Pink Sweat$' AND "name" = 'Volume 1';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1984-07-27' WHERE artist = 'Metallica' AND "name" = 'Ride the Lightning';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1988-09-06' WHERE artist = 'Metallica' AND "name" = '...and Justice for All';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1990-09-24' WHERE artist = 'Megadeth' AND "name" = 'Rust In Peace';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1986-10-07' WHERE artist = 'Slayer' AND "name" = 'Reign in Blood';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2018-11-26' WHERE artist = 'Jid' AND "name" = 'DiCaprIo 2';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1990-10-09' WHERE artist = 'Slayer' AND "name" = 'Seasons in the Abyss';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2007-03-27' WHERE artist = 'Machine Head' AND "name" = 'The Blackening';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1994-03-22' WHERE artist = 'Pantera' AND "name" = 'Far Beyond Driven';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2011-09-23' WHERE artist = 'Machine Head' AND "name" = 'Unto the Locust';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2001-09-11' WHERE artist = 'Slayer' AND "name" = 'God Hates Us All';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1993-09-02' WHERE artist = 'Sepultura' AND "name" = 'Chaos A.D.';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '1996-03-12' WHERE artist = 'Sepultura' AND "name" = 'Roots';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1983-12-03' WHERE artist = 'Slayer' AND "name" = 'Show No Mercy';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1994-06-01' WHERE artist = 'Machine Head' AND "name" = 'Burn My Eyes';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1996-05-07' WHERE artist = 'Pantera' AND "name" = 'The Great Southern Trendkill';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Metallica' AND "name" = 'Black Album';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2008-09-27' WHERE artist = 'Trivium' AND "name" = 'Shogun';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2007-05-15' WHERE artist = 'Megadeth' AND "name" = 'United Abominations';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2006-10-06' WHERE artist = 'Trivium' AND "name" = 'The Crusade';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '1985-03' WHERE artist = 'Slayer' AND "name" = 'Hell Awaits';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Metallica' AND "name" = 'And Justice For All';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2017-01-27' WHERE artist = 'Kreator' AND "name" = 'Gods Of Violence';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2006-08-08' WHERE artist = 'Slayer' AND "name" = 'Christ Illusion';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1991-03-25' WHERE artist = 'Sepultura' AND "name" = 'Arise';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2004-09-14' WHERE artist = 'Megadeth' AND "name" = 'The System Has Failed';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-11-03' WHERE artist = 'Slayer' AND "name" = 'World Painted Blood';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2017-03-24' WHERE artist = 'Mount Eerie' AND "name" = 'A Crow Looked at Me';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2010-03-26' WHERE artist = 'Neethio' AND "name" = 'My Way - Single';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Ariel Borgna' AND "name" = 'Ariel Borgna';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2017-09-01' WHERE artist = 'LCD Soundsystem' AND "name" = 'American Dream';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '1987-05-25' WHERE artist = 'The Cure' AND "name" = 'Kiss Me Kiss Me Kiss Me';
UPDATE "public"."Album" SET "numberOfTracks" = 23, "date" = '2008-11-10' WHERE artist = 'The Smiths' AND "name" = 'The Sound Of The Smiths (The Very Best Of)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2010-05-21' WHERE artist = 'Tame Impala' AND "name" = 'Innerspeaker';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1967' WHERE artist = 'The Jimi Hendrix Experience' AND "name" = 'Are You Experienced?';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Pink Floyd' AND "name" = 'Wish You Were Here [Remastered] (Remastered Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '1998' WHERE artist = 'The Beach Boys' AND "name" = 'Smiley Smile (Remastered)';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2009-09-09' WHERE artist = 'The Beatles' AND "name" = 'Sgt. Pepper''s Lonely Hearts Club Band (Deluxe Edition)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Pink Floyd' AND "name" = 'The Wall [disc 1]';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2017-06-23' WHERE artist = 'King Gizzard & The Lizard Wizard' AND "name" = 'Murder of The Universe';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '1991-03-05' WHERE artist = 'Various Artists' AND "name" = 'The Doors';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Pink Floyd' AND "name" = 'The Wall Disc 2';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1990-08-21' WHERE artist = 'Anthrax' AND "name" = 'Persistence Of Time';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2009-09-14' WHERE artist = 'Megadeth' AND "name" = 'Endgame';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2005-01-11' WHERE artist = 'Kreator' AND "name" = 'Enemy of God';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2001-05-15' WHERE artist = 'Megadeth' AND "name" = 'The World Needs A Hero';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Megadeth' AND "name" = 'Peace Sells...But Who''s Buying?';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1995-07-18' WHERE artist = 'Megadeth' AND "name" = 'Hidden Treasures';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2000-03-21' WHERE artist = 'Pantera' AND "name" = 'Reinventing the Steel';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1989-04-07' WHERE artist = 'Sepultura' AND "name" = 'Beneath the Remains';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1985-04-25' WHERE artist = 'Exodus' AND "name" = 'Bonded by Blood';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Metallica' AND "name" = 'Garage, Inc.';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1988-09-20' WHERE artist = 'Anthrax' AND "name" = 'State Of Euphoria';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1995-06-20' WHERE artist = 'Metallica' AND "name" = 'Kill ''em All (Remastered)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2003-12-16' WHERE artist = 'Machine Head' AND "name" = 'Through the Ashes of Empires';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1989' WHERE artist = 'Metallica' AND "name" = 'Ride The Lightning (Remastered)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '1985-10-27' WHERE artist = 'Celtic Frost' AND "name" = 'To Mega Therion';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '1986-09-19' WHERE artist = 'Megadeth' AND "name" = 'Peace Sells... But Who''s Buying?';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1986-04' WHERE artist = 'Kreator' AND "name" = 'Pleasure To Kill';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1989-04-17' WHERE artist = 'Annihilator' AND "name" = 'Alice in Hell';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2008-03-25' WHERE artist = 'Cavalera Conspiracy' AND "name" = 'Inflikted';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2016-01-22' WHERE artist = 'Megadeth' AND "name" = 'Dystopia';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1998' WHERE artist = 'Slayer' AND "name" = 'Reign In Blood (Expanded)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2005-07-12' WHERE artist = 'The All-American Rejects' AND "name" = 'Move Along';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2012-04-13' WHERE artist = 'Train' AND "name" = 'California 37';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '1972' WHERE artist = 'David Bowie' AND "name" = 'Space Oddity';
UPDATE "public"."Album" SET "numberOfTracks" = 19, "date" = '2005-09-27' WHERE artist = 'Blind Melon' AND "name" = 'Best Of Blind Melon';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2011-06-27' WHERE artist = 'Queen' AND "name" = 'Jazz (2011 Remaster)';
UPDATE "public"."Album" SET "numberOfTracks" = 22, "date" = '2015-03-27' WHERE artist = 'Nightwish' AND "name" = 'Endless Forms Most Beautiful (Deluxe Version)';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2004-09-28' WHERE artist = 'Marilyn Manson' AND "name" = 'Lest We Forget (The Best Of)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2003-09-09' WHERE artist = 'From Autumn To Ashes' AND "name" = 'The Fiction We Live';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2005' WHERE artist = 'Bullet for My Valentine' AND "name" = 'The Poison Digipak';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2007-03-05' WHERE artist = 'Emmure' AND "name" = 'Goodbye To The Gallows';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2006-06-12' WHERE artist = '36 Crazyfists' AND "name" = 'Rest Inside The Flames';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2018-11-09' WHERE artist = 'Architects' AND "name" = 'Holy Hell';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2011-06-21' WHERE artist = 'August Burns Red' AND "name" = 'Leveler';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bring Me the Horizon' AND "name" = 'There Is a Hell Believe Me I''ve Seen It, There Is a Heaven Let''s Keep It a Secret';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2004-03-16' WHERE artist = '36 Crazyfists' AND "name" = 'A Snow Capped Romance';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2004-05-11' WHERE artist = 'Killswitch Engage' AND "name" = 'The End of Heartache';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2004-06-01' WHERE artist = 'Parkway Drive' AND "name" = 'Don''t Close Your Eyes';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2007-08-28' WHERE artist = 'Killswitch Engage' AND "name" = 'As Daylight Dies (Special Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2013-04-01' WHERE artist = 'Bring Me the Horizon' AND "name" = 'Sempiternal (Deluxe)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Bring Me the Horizon' AND "name" = 'Sempiternal (Deluxe Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2007-03-06' WHERE artist = 'Chimaira' AND "name" = 'Resurrection';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2020-10-22' WHERE artist = 'Bring Me the Horizon' AND "name" = 'Teardrops';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1987-10' WHERE artist = 'Engenheiros Do Hawaii' AND "name" = 'A revolta dos Dândis';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2012-01-06' WHERE artist = 'Alcest' AND "name" = 'Les voyages de l''Âme';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2007-08-08' WHERE artist = 'Alcest' AND "name" = 'Souvenirs d''un autre Monde';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2007-09-17' WHERE artist = 'A Place to Bury Strangers' AND "name" = 'A Place To Bury Strangers';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2007-09-03' WHERE artist = 'M83' AND "name" = 'Digital Shades Vol. 1';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2010-03-26' WHERE artist = 'Les Discrets' AND "name" = 'Septembre et ses dernières Pensées';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2007-02-13' WHERE artist = 'A Sunny Day In Glasgow' AND "name" = 'Scribble Mural Comic Journal';
UPDATE "public"."Album" SET "numberOfTracks" = 20, "date" = '2009-09-15' WHERE artist = 'A Sunny Day In Glasgow' AND "name" = 'Ashes Grammar';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2009-03-03' WHERE artist = 'Jimi Hendrix' AND "name" = 'Music From The Motion Picture Watchmen';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2014-12-23' WHERE artist = 'The Voidz' AND "name" = 'Tyranny';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2008-03-21' WHERE artist = 'Panic! at the Disco' AND "name" = 'Pretty Odd';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2017-05-19' WHERE artist = '(Sandy) Alex G' AND "name" = 'Rocket';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2002-11' WHERE artist = 'Flёur' AND "name" = 'Прикосновение';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1998-05-05' WHERE artist = 'Tori Amos' AND "name" = 'From The Choir Girl Hotel';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2014-08-25' WHERE artist = 'Aurora' AND "name" = 'Awakening';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Emilie Autumn' AND "name" = 'Opheliac Disc 1';
UPDATE "public"."Album" SET "numberOfTracks" = 28, "date" = '1990' WHERE artist = 'The Beach Boys' AND "name" = 'Smiley Smile/Wild Honey';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2005-02-08' WHERE artist = 'Andrew Bird' AND "name" = 'Andrew Bird & the Mysterious Production of Eggs';
UPDATE "public"."Album" SET "numberOfTracks" = 39, "date" = '2016-11-18' WHERE artist = 'Tori Amos' AND "name" = 'Boys For Pele (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2007' WHERE artist = 'Flёur' AND "name" = 'Флёрография';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2012-01-30' WHERE artist = 'Pepe Deluxé' AND "name" = 'Queen Of The Wave';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2018-10-05' WHERE artist = 'Hellogoodbye' AND "name" = 'S''only Natural';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2019-11-12' WHERE artist = 'Weyes Blood' AND "name" = 'Rough Trade Session';
UPDATE "public"."Album" SET "numberOfTracks" = 3, "date" = '2008-04-14' WHERE artist = 'The Last Shadow Puppets' AND "name" = 'The Age of the Understatement EP';
UPDATE "public"."Album" SET "numberOfTracks" = 30, "date" = '2003-06-10' WHERE artist = 'The Beach Boys' AND "name" = 'Sounds of Summer';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2019-04-05' WHERE artist = 'BLACKPINK' AND "name" = 'KILL THIS LOVE';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2019-03-04' WHERE artist = 'TOMORROW X TOGETHER' AND "name" = 'The Dream Chapter: STAR';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2019-12-09' WHERE artist = 'STRAY KIDS' AND "name" = 'Clé : Levanter';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2019-12-23' WHERE artist = 'Red Velvet' AND "name" = '‘The ReVe Festival’ Finale';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2013-09-11' WHERE artist = 'BTS' AND "name" = 'O!Rul8,2?';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2015-11-30' WHERE artist = 'BTS' AND "name" = 'The Most Beautiful Moment In Life Pt.2';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2020-06-17' WHERE artist = 'STRAY KIDS' AND "name" = 'GO Live';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2017-07-18' WHERE artist = 'Exo' AND "name" = 'The War - The 4th Album';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2017-06-22' WHERE artist = 'BLACKPINK' AND "name" = 'As If It''s Your Last';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2020-10-02' WHERE artist = 'BLACKPINK' AND "name" = 'The Album';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2018-07-09' WHERE artist = 'TWICE' AND "name" = 'SUMMER NIGHTS';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2014-02-27' WHERE artist = '2NE1' AND "name" = 'Crush';
UPDATE "public"."Album" SET "numberOfTracks" = 1, "date" = '2018-11-03' WHERE artist = 'K/DA' AND "name" = 'POP/STARS';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2016-12-12' WHERE artist = 'Bigbang' AND "name" = 'Made';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2020-02-05' WHERE artist = 'Loona' AND "name" = '[#]';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '2020-11-06' WHERE artist = 'K/DA' AND "name" = 'ALL OUT';
UPDATE "public"."Album" SET "numberOfTracks" = 2, "date" = '2019-02-12' WHERE artist = 'Itzy' AND "name" = 'IT''Z DIFFERENT';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2020-02-18' WHERE artist = 'Dreamcatcher' AND "name" = '1st Album [Dystopia : The Tree of Language]';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2019-03-25' WHERE artist = 'STRAY KIDS' AND "name" = 'Clé 1 : MIROH';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2018-09-04' WHERE artist = 'SunMi' AND "name" = 'Warning';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2018-08-20' WHERE artist = 'Loona' AND "name" = '[+ +]';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Pantera' AND "name" = 'Official Live : 101 Proof';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2007-03-19' WHERE artist = 'Enter Shikari' AND "name" = 'Take To The Skies';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2011-06-14' WHERE artist = 'Of Mice & Men' AND "name" = 'The Flood';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2012-07-17' WHERE artist = 'Pierce The Veil' AND "name" = 'Collide With the Sky';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2010-06-22' WHERE artist = 'Pierce The Veil' AND "name" = 'Selfish Machines';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2007-06-26' WHERE artist = 'Pierce The Veil' AND "name" = 'A Flair for the Dramatic';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2011-05-10' WHERE artist = 'Sleeping with Sirens' AND "name" = 'Let''s Cheers to This';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2010-03-23' WHERE artist = 'Sleeping with Sirens' AND "name" = 'With Ears to See and Eyes to Hear';
UPDATE "public"."Album" SET "numberOfTracks" = 13, "date" = '2006-03-13' WHERE artist = 'Fightstar' AND "name" = 'Grand Unification';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2007-04-10' WHERE artist = 'From Autumn To Ashes' AND "name" = 'Holding A Wolf By The Ears';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2019-06-24' WHERE artist = 'Mach-Hommy' AND "name" = 'Wap Konn Jòj!';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2018-04-18' WHERE artist = 'DJ Okawari' AND "name" = 'Restore';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'The Roots' AND "name" = 'How I Got Over (Explicit)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2017-04-07' WHERE artist = 'Joey Bada$$' AND "name" = 'ALL-AMERIKKKAN BADA$$';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2020-07-22' WHERE artist = 'Boldy James' AND "name" = 'Manger on McNichols';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2019-11-01' WHERE artist = 'Earl Sweatshirt' AND "name" = 'Feet of Clay';
UPDATE "public"."Album" SET "numberOfTracks" = 15, "date" = '2013-07-08' WHERE artist = 'EarthGang' AND "name" = 'Shallow Graves For Toys';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2020-05-29' WHERE artist = 'Freddie Gibbs & The Alchemist' AND "name" = 'Alfredo';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2019-03-01' WHERE artist = 'Little Simz' AND "name" = 'Grey Area';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2014-09-13' WHERE artist = 'Kill Bill: The Rapper' AND "name" = 'RAMONA';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2015-02-24' WHERE artist = 'BADBADNOTGOOD & Ghostface Killah' AND "name" = 'Sour Soul';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2018-02-23' WHERE artist = 'EarthGang' AND "name" = 'Royalty';
UPDATE "public"."Album" SET "numberOfTracks" = 16, "date" = '2021' WHERE artist = 'Mach-Hommy' AND "name" = 'Pray For Haiti';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2009-03-24' WHERE artist = 'MF DOOM' AND "name" = 'Born Like This';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2015-09-18' WHERE artist = 'Mac Miller' AND "name" = 'GO:OD AM';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '2014-03-18' WHERE artist = 'Freddie Gibbs' AND "name" = 'Piñata';
UPDATE "public"."Album" SET "numberOfTracks" = 14, "date" = '2021-03-26' WHERE artist = 'Armand Hammer' AND "name" = 'Haram';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2017-03-10' WHERE artist = 'Jid' AND "name" = 'The Never Story';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2018-09-14' WHERE artist = 'NoName' AND "name" = 'Room 25';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2016-07-31' WHERE artist = 'NoName' AND "name" = 'Telefone';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2018-04-05' WHERE artist = 'Saba' AND "name" = 'care for me';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2001-12' WHERE artist = 'The Shroud' AND "name" = 'In the Garden';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1993-07-26' WHERE artist = 'Агата Кристи' AND "name" = 'Позорная Звезда';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2000-08-23' WHERE artist = 'Malice Mizer' AND "name" = 'Bara No Seidou';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sex Gang Children' AND "name" = 'Execution and Elegance the Ant';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2006-06-06' WHERE artist = 'Depeche Mode' AND "name" = 'Violator (Remastered)';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2004-11-11' WHERE artist = 'Within Temptation' AND "name" = 'The Silent Force';
UPDATE "public"."Album" SET "numberOfTracks" = 18, "date" = '2003' WHERE artist = 'The 69 Eyes' AND "name" = 'Framed in Blood';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '1997-03-10' WHERE artist = 'Агата Кристи' AND "name" = 'Ураган';
UPDATE "public"."Album" SET "numberOfTracks" = 17, "date" = '1986' WHERE artist = 'Bauhaus' AND "name" = 'Bauhaus - 1979-1983 Volume Two';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2005' WHERE artist = 'Depeche Mode' AND "name" = 'Playing The Angel (Deluxe)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Depeche Mode' AND "name" = 'The Best of Depeche Mode, Vol. 1 (Deluxe)';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Depeche Mode' AND "name" = 'Speak And Spell (Deluxe)';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2020-08-28' WHERE artist = 'Katy Perry' AND "name" = 'Smile';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2004-10-19' WHERE artist = 'Jimmy Eat World' AND "name" = 'Futures';
UPDATE "public"."Album" SET "numberOfTracks" = 12, "date" = '2015-09-11' WHERE artist = 'Slayer' AND "name" = 'Repentless';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2008-05-30' WHERE artist = 'Opeth' AND "name" = 'Watershed (Special Edition)';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2019-08-30' WHERE artist = 'Tool' AND "name" = 'Fear Inoculum';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2007-08-29' WHERE artist = 'Amorphis' AND "name" = 'Silent Waters';
UPDATE "public"."Album" SET "numberOfTracks" = 5, "date" = '1996-06-24' WHERE artist = 'Opeth' AND "name" = 'Morningrise';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2016-09-30' WHERE artist = 'Opeth' AND "name" = 'Sorceress';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '1997-06-14' WHERE artist = 'Sigur Rós' AND "name" = 'Von';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Godspeed You! Black Emperor' AND "name" = 'F#a#infinity';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2005-02-22' WHERE artist = 'Red Sparowes' AND "name" = 'At The Soundless Dawn';
UPDATE "public"."Album" SET "numberOfTracks" = 7, "date" = '2006-06-06' WHERE artist = 'This Will Destroy You' AND "name" = 'Young Mountain';
UPDATE "public"."Album" SET "numberOfTracks" = 4, "date" = '2007-01-23' WHERE artist = 'Yndi Halda' AND "name" = 'Enjoy Eternal Bliss';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sigur Rós' AND "name" = 'Takk';
UPDATE "public"."Album" SET "numberOfTracks" = 6, "date" = '2006-09-27' WHERE artist = 'If These Trees Could Talk' AND "name" = 'If These Trees Could Talk';
UPDATE "public"."Album" SET "hidden" = true WHERE artist = 'Sigur Rós' AND "name" = 'Med Sud I Eyrum Vid Spilum Endalaust';
UPDATE "public"."Album" SET "numberOfTracks" = 8, "date" = '2001-10-08' WHERE artist = 'A Silver Mt. Zion' AND "name" = 'Born Into Trouble as the Sparks Fly Upward';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2008-06-20' WHERE artist = 'Sigur Rós' AND "name" = 'Með suð í eyrum við spilum endalaust';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2005-02-04' WHERE artist = 'God Is An Astronaut' AND "name" = 'All Is Violent, All Is Bright';
UPDATE "public"."Album" SET "numberOfTracks" = 11, "date" = '2002' WHERE artist = 'God Is An Astronaut' AND "name" = 'The End of the Beginning';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2007-04-05' WHERE artist = 'God Is An Astronaut' AND "name" = 'Far From Refuge';
UPDATE "public"."Album" SET "numberOfTracks" = 10, "date" = '2008-11-01' WHERE artist = 'God Is An Astronaut' AND "name" = 'God Is An Astronaut';
UPDATE "public"."Album" SET "numberOfTracks" = 9, "date" = '2010-05-17' WHERE artist = 'God Is An Astronaut' AND "name" = 'Age of the Fifth Sun';
